### ISSUE TITLE
Forbidden attribute names would be nice

### ISSUE THREAD

**Issue by CHarkerRhodes** [igraph/rigraph#100]
As a way of avoiding typos, it would be nice if attribute names like "weights" were forbidden and  generated an error message. Because if I type for example E(g)$weights, I almost certainly mean E(g)$weight.  

It is a particular problem because many functions have an optional argument "weights" making it hard to remember when to use the singular and when to use the plural.

For example, the function "betweenness" has an optional argument "weights" (plural) the default for which is the weight (singular) edge attribute.

Harker

C. Harker Rhodes, MD, PhD
Professor of Pathology and Neurology (Retired)
Geisel School of Medicine at Dartmouth

Senior Scientist [C]; National Institute of Mental Health
Human Brain Collection Core
10 Center Drive, Rm. 4N306, Bethesda, MD
Phone: 603-443-3360
E-mail: CHarkerRhodes@gmail.com

**Comment by gaborcsardi** [comment]
Good idea. I am thinking about the following: collect all graph/vertex/edge attribute names that igraph treats specially, and give a warning each time a user sets an attribute that is one edit distance from them. 

It would be possible to turn this behavior off via a configuration setting.

**Comment by ntamas** [comment]
Not planned in the near future. We can reconsider if there is significant demand for this.
