### ISSUE TITLE
Expression array/RNAseq igraph users group?

### ISSUE THREAD

**Issue by CHarkerRhodes** [igraph/rigraph#101]
Are there application-specific igraph user groups?  Specifically, is there a group of individuals using igraph for the analysis of gene expression array data and/or RNAseq data?

I'm sure there are many of us using igraph for this purpose and it would be nice to have some conventions about variable names and so forth.  The immediate acute need is a convention that E(g)$weight is to be used as a similarity measure, not a distance measure and a set of functions that implement that. 

As a temporary fix we might set up a library of wrapper functions named "Gene_<name>" where <name> is an existing igraph function like "betweenness". And perhaps a few functions with some simpler names which do nothing more than call those functions because the igraph function names are already so long.

But this should be done by the entire community of us using graph-theoretical approaches to the analysis of expression array/RNAseq data, not by each of us individually on an ad hoc basis.

It would also be nice to meet face-to-face (in Boston) to discuss problems of mutual interest. For example, there are problems unique to expression array and RNAseq data from brain cortex. To address them I need a node-based Girvan–Newman clustering function and I'm not to proud to use someone else's code if it's already been written.

Harker

C. Harker Rhodes, MD, PhD
Professor of Pathology and Neurology (Retired)
Geisel School of Medicine at Dartmouth

Senior Scientist [C]; National Institute of Mental Health
Human Brain Collection Core
10 Center Drive, Rm. 4N306, Bethesda, MD
Phone: 603-443-3360
E-mail: CHarkerRhodes@gmail.com

**Comment by CHarkerRhodes** [comment]
Edit original comment:
As a temporary fix we might set up a library of wrapper functions named "Gene_NAME" where NAME is an existing igraph function like "betweenness". And perhaps a few functions with some simpler names which do nothing more than call those functions because the igraph function names are already so long.

**Comment by gaborcsardi** [comment]
This issue tracker might not be the best forum for this. 

I am pretty sure that there are no such user groups. AFAIK there are no igraph use groups, either, igraph is a small niche, I guess.

I am not sure why you would not want to use other people's code, this is what open source is about after all. 

Anyway, I will close this here now, as GitHub issues are really about things we need to fix in igraph, or feature requests at least. Feel free to open another issue if you have specific questions or suggestions.
