### ISSUE TITLE
Signature mismatches in C code

### ISSUE THREAD

**Issue by jeroen** [igraph/rigraph#1016]
When we compile the R package with emscripten, the linker complains about signature mismatches:

```
wasm-ld: warning: function signature mismatch: igraphdseupd_
>>> defined as (i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32) -> i32 in core/linalg/arpack.o
>>> defined as (i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32) -> void in vendor/arpack/dseupd.o

wasm-ld: warning: function signature mismatch: igraphdsortr_
>>> defined as (i32, i32, i32, i32, i32) -> i32 in core/linalg/arpack.o
>>> defined as (i32, i32, i32, i32, i32, i32) -> void in vendor/arpack/dsortr.o

wasm-ld: error: function signature mismatch: realloc
>>> defined as (i32, i32) -> i32 in core/cliques/cliquer/cliquer_graph.o
>>> defined as (i32, i64) -> i32 in vendor/arpack/dgetv0.o
em++: error: '/opt/emsdk/upstream/bin/wasm-ld @/tmp/emscripten_x30scq31.rsp.utf-8' failed (returned 1)
make: *** [/opt/R/4.3.0/lib/R/share/make/shlib.mk:10: igraph.so] Error 1
ERROR: compilation failed for package 'igraph'
```

**Comment by szhorvat** [comment]
@krlmlr @Antonov548 Make sure `HAVE_GFORTRAN` is defined when compiling with the Fortran version of ARPACK.  See https://github.com/igraph/igraph/blob/master/src/linalg/arpack_internal.h#L129 Hopefully this will be sufficient.

**Comment by ntamas** [comment]
Szabolcs beat me to it; the reason for the error is that there are two different calling conventions when crossing the line from C to Fortran. One of them is preferred by `gfortran` and it uses an extra "size" argument for strings. The other one applies to `f2c`-converted code and it does not use an extra "size" argument. You need to use te `HAVE_GFORTRAN` switch to choose between the two.

**Comment by georgestagg** [comment]
Adding the extra Fortran hidden size arguments should fix the first two errors.

IIUC, the error with `realloc` is due to webR's patched version of the LLVM Clang compiler. I plan to investigate things more after Christmas, and with luck a new version of our patches to LLVM and `libFortranRuntime.a` should fix the issue.

**Comment by szhorvat** [comment]
@georgestagg Are you compiling the `main` branch or 1.6.0?  I'm not sure if this helps: https://github.com/igraph/igraph/commit/68c66b2922281e4dd5a749ee933208418b51a42d

**Comment by krlmlr** [comment]
CC @Antonov548 -- running igraph in webR.

Please work from the main branch, the CRAN version uses an old version of the igraph C core. Releasing igraph 2.0.0 in January.
