### ISSUE TITLE
Investigate behavior change in `hrg_tree()`

### ISSUE THREAD

**Issue by krlmlr** [igraph/rigraph#1047]
Old attributes?

https://github.com/igraph/rigraph/pull/1038#issuecomment-1872490707

**Comment by szhorvat** [comment]
I wrote here about what to pay attention to when replacing deprecated functions:

https://github.com/igraph/rigraph/issues/1006#issuecomment-1864931159

**Comment by szhorvat** [comment]
I looked at this again. What needs to be done is to take the `probability` output of `igraph_from_hrg_dendrogram()` and add it as a vertex attribute called `probability`.

**Comment by szhorvat** [comment]
This now return a list with fields `$graph` and `$prob`. Instead, it should return just the graph, with `$prob` added as the `probability` vertex attribute. This will restore compatibility with 1.6.0.
