### ISSUE TITLE
bug? layout.fruchterman.reingold

### ISSUE THREAD

**Issue by nktkee** [igraph/rigraph#105]
I'm a bit of a newbie, please forgive anything naive. Ive been using igraph 0.7.0 successfully for about a year to plot force directed graphs using layout.fruchterman.reingold. As initial input to the force directed graphing, this has previously been able to take starting coordinates for the nodes in multiple dimensions, but seem to only take 2 dimensions since the upgrade to 1.0.0 (https://github.com/igraph/igraph/blob/master/src/layout_fr.c, line 371). I have no idea how to fix this, any help would be greatly appreciated.

**Comment by gaborcsardi** [comment]
That's the 2d version. The 3d version takes a matrix with 3 columns: https://github.com/igraph/igraph/blob/b215195214abb8355121a8430c86df04e1f00eae/src/layout_fr.c#L493

**Comment by nktkee** [comment]
thanks for the quick reply, much appreciated. Perhaps Ive misunderstood things here,

> ################# reproducible example:
> library(igraph)
> set.seed(12345)
> adj.mat <- matrix(runif(20*20, min=0, max=10), ncol=20)
> g<-graph.adjacency(adj.mat, mode = "directed", weighted=TRUE, diag=FALSE)
> 
> ################# plot the graph, specifying no starting coordinates - all good
> plot.igraph(g,
+             layout = layout_with_fr(g, coords = NULL, grid = "nogrid", weights=E(g)$weight),
+             vertex.size=4,
+             vertex.shape="circle",
+             vertex.label=NA,
+             edge.color="grey",
+             edge.width=(E(g)$weight))
> 
> ################# plot the graph, specifying 2D starting coordinates - all good
> starting.coord <- matrix(runif(20*2, min=0, max=10), ncol=2)
> plot.igraph(g,
+             layout = layout_with_fr(g, coords = starting.coord, grid = "nogrid", weights=E(g)$weight),
+             vertex.size=4,
+             vertex.shape="circle",
+             vertex.label=NA,
+             edge.color="grey",
+             edge.width=(E(g)$weight))
> 
> ################# plot the graph, specifying 3D starting coordinates - error
> starting.coord <- matrix(runif(20*3, min=0, max=10), ncol=3)
> plot.igraph(g,
+             layout = layout_with_fr(g, coords = starting.coord, grid = "nogrid", weights=E(g)$weight),
+             vertex.size=4,
+             vertex.shape="circle",
+             vertex.label=NA,
+             edge.color="grey",
+             edge.width=(E(g)$weight))
Error in .Call("R_igraph_layout_fruchterman_reingold", graph, coords,  : 
  At layout_fr.c:371 : Invalid start position matrix size in Fruchterman-Reingold layout, Invalid value
> 

i need to specify the same starting coordinates to reproduce the same graph but colored with different information. in the past ive been able to specify up to 5D starting coords, but can no longer do this after the 1.0 upgrade. Id be really really thankful for any help.

**Comment by gaborcsardi** [comment]
You need to set `dim = 3`.
