### ISSUE TITLE
Do not duplicate prototypes between rinterface.c and rinterface_extra.c

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#1053]
rinterface.c and rinterface_extra.c have a lot of function prototypes literally inserted.

TODO:

 - [ ] Move these to a common header, and include that header in both files
 - [ ] Remove unused functions
 - [ ] Remove unused prototypes
 - [ ] Change `int` return types to `igraph_error_t` where necessary. See https://github.com/igraph/rigraph/pull/1051#issuecomment-1872573532

The current setup is a crash risk and increases maintenance costs.

@krlmlr @Antonov548 can either of you do this please?

**Comment by krlmlr** [comment]
Done.
