### ISSUE TITLE
graph.isomorphic.34() is non-functional

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#1065]
`graph.isomorphic.34()` is currently non-functional, as it refers to `isomorphic_34_impl` which does not exist.

`graph.isomorphic.34()` should probably just be removed as it is a special high-performance path for small graphs. It will be used automatically by `isomorphic` when appropriate.

If we don't want to remove it, then the replacement of `igraph_isomorphic_34()`, called `igraph_isomorphic_small()`, should be exposed. I do not recommend this as this function has certain expectations about its input (such as graphs being simple) which the R interface does not currently guarantee.

**Comment by szhorvat** [comment]
@krlmlr Is there a milestone that we can add 2.0-blocker issues to?

**Comment by krlmlr** [comment]
The "upgrade" milestone is more appropriate.

**Comment by szhorvat** [comment]
@krlmlr Let's please clean up the "upgrade" milestone then and trim it down to issues that are essential to fix before the release.
