### ISSUE TITLE
upgrade_graph() going crazy

### ISSUE THREAD

**Issue by shifunan** [igraph/rigraph#107]
Hi,

In my code I have updated all the naming conventions to the new version, and no igraph object is being read-in (i.e all igraph objects are created by functions from the new version), however, this does not stop the following two warnings messages from filling the screen:

This graph was created by an old(er) igraph version.
  Call upgrade_graph() on it to use with the current igraph version
  For now we convert it on the fly...

and

In parse_op_args(..., what = "a vertex", is_fun = is_igraph_vs,  ... :
  Combining vertex/edge sequences from different graphs.
This will not work in future igraph versions

Is there anyway to suppress/remove these warnings? As far as I can tell there shouldn't be anything triggering the warnings.

Thanks
Fu

**Comment by shifunan** [comment]
it seems that the issue is triggered by debug(). the issue occurs whenever i exit out of the debug console.

**Comment by gaborcsardi** [comment]
Can you create a reproducible example?

**Comment by shifunan** [comment]
Is there any way I can send you a copy of my workspace (~4mb)? I can't pinpoint anymore specifically where the error is coming from unfortunately. Thanks!

**Comment by gaborcsardi** [comment]
Well, I would appreciate if you tried to send a _minimal_ example. Thanks.

**Comment by shifunan** [comment]
I found the problem. In my workspace there was an list object with an old
igraph object as an element. The problem is gone after removing it.
