### ISSUE TITLE
Memory allocated by R_SEXP_to_hrg() is not deallocated

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#1073]
Memory allocated `R_SEXP_to_hrg()` is not deallocated anywhere. An example is the autogenerated function `R_igraph_hrg_sample`, currently:

```
SEXP R_igraph_hrg_sample(SEXP hrg) {
                                        /* Declarations */
  igraph_hrg_t c_hrg;
  igraph_t c_sample;
  SEXP sample;

  SEXP r_result;
                                        /* Convert input */
  R_SEXP_to_hrg(hrg, &c_hrg);
                                        /* Call igraph */
  IGRAPH_R_CHECK(igraph_hrg_sample(&c_hrg, &c_sample));

                                        /* Convert output */
  IGRAPH_FINALLY(igraph_destroy, &c_sample);
  PROTECT(sample=R_igraph_to_SEXP(&c_sample));
  IGRAPH_I_DESTROY(&c_sample);
  IGRAPH_FINALLY_CLEAN(1);
  r_result = sample;

  UNPROTECT(1);
  return(r_result);
}
```

`R_SEXP_to_hrg_copy()` is fine, as that can (and is) deallocated by `igraph_hrg_destroy()`.

**Comment by szhorvat** [comment]
Note that currently most HRG functions are broken.

**Comment by szhorvat** [comment]
Possible solutions:

 - Use `R_alloc()` in `R_SEXP_to_hrg()` (not trivial, since this function calls others that allocate)
 - Have a special deallocation pair for `R_SEXP_to_hrg()`.

**Comment by krlmlr** [comment]
What does "broken" mean? Can you please share a reprex?

I see the memory leak in v1.6.0 too, can you confirm? If this were the case, this issue doesn't belong in this milestone.

**Comment by szhorvat** [comment]
No, in 1.6.0 `R_SEXP_to_hrg() ` does not allocate at all.

**Comment by krlmlr** [comment]
`sample_hrg()` and `fit_hrg()` aren't used by any CRAN packages: https://github.com/search?q=org%3Acran+%2Fsample_hrg%7Cfit_hrg%2F&type=code . Are there other functions to review?

**Comment by Antonov548** [comment]
> Possible solutions:
> 
> * Use `R_alloc()` in `R_SEXP_to_hrg()` (not trivial, since this function calls others that allocate)
> * Have a special deallocation pair for `R_SEXP_to_hrg()`.

Can it be also option to use `R_SEXP_to_hrg_copy` instead? And just use `igraph_hrg_destroy`. Not sure that we have significant improvement in perfoamance with not copying one field in `hrg` structure.

**Comment by szhorvat** [comment]
Yes.
