### ISSUE TITLE
similarirty.something() functions missing formal deprecations

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#1077]
`similarity.dice()`, `similarity.jaccard()` and `similarity.invlogweighted()` are missing format deprecations, even though they are not documented and their documentation points to `similarity()`.

`similarity()` is a replacement for all of these.

CC @maelle

**Comment by maelle** [comment]
- one use case of `similarity.dice()` https://github.com/cran/linkprediction/blob/a132f7dbf5c5b8f0642b1e32382fa1f9d65457ba/R/similarity_sor.R#L11

**Comment by maelle** [comment]
- two use cases of `similarity.jaccard()` https://github.com/search?q=similarity.jaccard+user%3Acran+NOT+repo%3Acran%2Figraph0+NOT+repo%3Acran%2Figraph&type=code&ref=advsearch
