### ISSUE TITLE
why as_adj?

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#1083]
as_adj is an alias for as_adjacency_matrix. why have this short name?

**Comment by maelle** [comment]
In igraph code itself, I'd gladly remove all occurrences of `as_adj()` with `as_adjacency_matrix()` as I find it clearer. :smile_cat:

**Comment by szhorvat** [comment]
No hard opinions on the naming from me. 

I'll note that there are `as_adj_list`, `as_adj_edge_list` and `as_adjacency_matrix`. The naming of `as_adj` does not make it clear which of these it would be.

**Comment by maelle** [comment]
https://github.com/search?q=as_adj%28+language%3AR+owner%3Acran&type=code&ref=advsearch
