### ISSUE TITLE
install error on CRAN

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#1086]
https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64/igraph-00install.html

@Antonov548

**Comment by maelle** [comment]
but maybe we can ignore it :thinking:

**Comment by szhorvat** [comment]
Looks like it's their problem.

**Comment by maelle** [comment]
unless it's related to #1006

**Comment by krlmlr** [comment]
I'd say it's their problem, too. No action needed here.

**Comment by Antonov548** [comment]
I also have sometime this issue in Windows, mostly using R studio. When I reinstalling packet many times.
