### ISSUE TITLE
get.edge.ids() broken in 2.0

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#1097]
### What happens?

`get.edge.ids()` does not return the IDs of parallel edges in the same way as 1.6 did.

### To Reproduce

1.6.0:

```
> g<-make_graph(c(1,2,2,3,2,1), directed = F)
> get.edge.ids(g, c(1,2, 1,2), multi=T)
[1] 3 1
> get.edge.ids(g, c(1,2, 1,2), multi=F)
[1] 3 3
```

Current `main`:

```
> g<-make_graph(c(1,2,2,3,2,1), directed = F)
> get.edge.ids(g, c(1,2, 1,2), multi=T)
[1] 3 3
> get.edge.ids(g, c(1,2, 1,2), multi=F)
[1] 3 3
```

**Comment by szhorvat** [comment]
This happened because the function that provided this feature was removed from the C core. See changelog:

> igraph_get_eids_multi() was removed as its design was fundamentally broken; there was no way to retrieve the IDs of all edges between a specific pair of vertices without knowing in advance how many such edges there are in the graph. Use igraph_get_all_eids_between() instead.

It would have been good to deal with this at the same time when `R_igraph_get_eids()` was updated, otherwise these things get forgotten and cause bugs.

There's no quick fix here. The proper solution is to get rid of `get.edge.ids()` and provide an alternative function with a reasonable interface that allows for retrieving _all_ edges between two vertices, based on `igraph_get_all_eids_between()`.

**Comment by szhorvat** [comment]
Here's what I suggest:

 - Deprecate `get.edge.ids()`.
 - Add a multigraph check to `get.edge.ids()` and issue a warning. This reduces performance, sometimes significantly, but we do cache the result of the multigraph check, and this function would be deprecated anyway.
 - Implement a function `get_edges(s, t)` based on `igraph_get_all_eids_between()`.

CC @ntamas for input. How do you handle this in Python?

**Comment by krlmlr** [comment]
I'll deprecate, running revdepchecks now.

**Comment by ntamas** [comment]
@szhorvat `igraph_get_eids_multi()` was never exposed in Python so there was nothing to break. Deprecation and the generic plan outlined in your comment seems OK for me.

**Comment by krlmlr** [comment]
Can we start with deprecating the `multi` argument?

**Comment by szhorvat** [comment]
The multi argument is not available with 0.10

**Comment by krlmlr** [comment]
I'd hard-deprecate so that using this argument gives an error.

**Comment by szhorvat** [comment]
That makes sense
