### ISSUE TITLE
Remove deprecated and non-functional `membership` parameter from `modularity_matrix`

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#1106]
`modularity_matrix()` has a `membership` parameter which currently uses old-style deprecation, and has never been functional. This should be removed.

There should be no concern about breaking other packages. If anyone uses this parameter, it is a misuse / misunderstanding.

https://github.com/igraph/rigraph/blob/5f4c239e6f7391bfcbc62c9bf2e5b8816ece1a6f/R/community.R#L718-L720

CC @maelle

**Comment by maelle** [comment]
#1498 -- let's first get it into the lifecycle system

**Comment by maelle** [comment]
I'm going to close this. As it's in the lifecycle system now, when we increase deprecation levels it'll be included.
