### ISSUE TITLE
get_k_shortest_paths_impl is missing docs

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#1116]
@szhorvat what are the "..." in get_k_shortest_paths_impl)?

I get this warning

```r
❯ checking Rd \usage sections ... WARNING
  Undocumented arguments in documentation object 'k_shortest_paths'
    ‘...’
  
  Functions with \usage entries need to have the appropriate \alias
  entries, and all their arguments documented.
  The \usage entries must correspond to syntactically valid R code.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.
```

**Comment by szhorvat** [comment]
The intention here was to enforce parameters following `...` to be specified by name. The discussion is in #1045 and the comments linked from there. @krlmlr can say more here, as I'm not very familiar with R the language.

**Comment by maelle** [comment]
Fixed by https://github.com/igraph/rigraph/commit/6a8a0b89c7c9e0869cbc528799820907b7232c5a
