### ISSUE TITLE
Fix installation if libraries are missing

### ISSUE THREAD

**Issue by krlmlr** [igraph/rigraph#1126]
**What is the feature or improvement you would like to see?**

We're declaring libraries as optional, can we add detection and fallback code to `configure` to actually live by it?

https://github.com/igraph/rigraph/blob/bf64f6a7cd97e83c0622f37c4107d8c81194d6ec/DESCRIPTION#L73-L74

If all dependencies are optional, installation should work on any system regarding of system libraries. If not, we need to document it.

**Use cases for the feature**

Users keep reporting installation failures when installing from source. This is something I'd really like to see in the the upcoming release.

**Comment by krlmlr** [comment]
Nice!

Can we compile a small `.c` file that includes `<glpk.h>` to check?

**Comment by krlmlr** [comment]
Computed names in Make: https://www.gnu.org/software/make/manual/html_node/Computed-Names.html

**Comment by Antonov548** [comment]
> Computed names in Make: https://www.gnu.org/software/make/manual/html_node/Computed-Names.html

Not sure how it can be useful for managing different files with sources. Can we somehow avoid additional logic of generation `Makevars` from `Makevars.in`?
