### ISSUE TITLE
Cannot plot trees in mode “in”

### ISSUE THREAD

**Issue by alumbreras** [igraph/rigraph#113]
The tree layout (igraph  1.0.1) doesn't work properly when trees are "in" instead of "out". For instance, these trees are properly plotted if no layout is used:

```
library(igraph)

# Create tree graph. Vertex 1 is root.
tree <- graph.empty(15)
tree <- tree + path(5,4,3,2,1)
tree <- tree + path(8,7,6,5)
tree <- tree + path(15,14,13,12,11,10,9,5)

# make_tree is new in igraph 1.0
tree.in <- make_tree(20, 3, mode="in")
tree.out <- make_tree(20, 3, mode="out")

par(mfrow=c(1,3))

### No layout
plot(tree, 
     vertex.label=NA, vertex.size=6, edge.arrow.size=0.1)
title("tree")

plot(tree.in, 
     vertex.label=NA, vertex.size=6, edge.arrow.size=0.1)
title("tree.in")

plot(tree.out, 
     vertex.label=NA, vertex.size=6, edge.arrow.size=0.1)
title("tree.out")
```

[![trees](http://i.stack.imgur.com/EhQJT.png)](http://i.stack.imgur.com/EhQJT.png)
However, if the tree Reingold-Tilford layout is called, then it can only plot the `tree.out`

```
### Tree layout
plot(tree, 
     vertex.label=NA, vertex.size=6, edge.arrow.size=0.1, 
     layout=layout.reingold.tilford(tree, mode="in"))
title("tree")

plot(tree.in, 
     vertex.label=NA, vertex.size=6, edge.arrow.size=0.1, 
     layout=layout_as_tree(tree.in, mode="in"))
title("tree.in")

plot(tree.out, 
     vertex.label=NA, vertex.size=6, edge.arrow.size=0.1, 
     layout=layout_as_tree(tree.out, mode="out"))
title("tree.out")
```

[![enter image description here](http://i.stack.imgur.com/EbwZn.png)](http://i.stack.imgur.com/EbwZn.png)

For the first two, the error is:

> Error in match.arg(arg = arg, choices = choices, several.ok =
> several.ok) :    'arg' should be one of “out”

**Comment by kforner** [comment]
I thinks this is due to a bug in the signature of layout_as_tree:
the signature of the mode argument should be **mode = c("out", "all", "in")** instead of **mode = "out"**
