### ISSUE TITLE
Review changes to get.incidence.dense()

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#1133]
I am not sure yet what is meant by this item

**Comment by maelle** [comment]
@krlmlr still not sure what this means (from #840) compare C changes to R changes?

**Comment by krlmlr** [comment]
The changes are here: https://github.com/igraph/rigraph/pull/840/files#diff-23e9c7af8ad164f1a343d1640ea8f5688065392d83aa9fb3337856acb65668e0R707-R719

**Comment by krlmlr** [comment]
We need to check if these are tested, if not, add tests and compare if the result is the same as with igraph 1.6.0.

**Comment by maelle** [comment]
https://app.codecov.io/gh/igraph/rigraph/blob/main/R%2Fconversion.R

**Comment by krlmlr** [comment]
From #1071.
