### ISSUE TITLE
Check that scalars are scalars during conversion

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#1141]
(i.e. do not try to index into a zero-length vector with REAL(vec)[0]) — waiting on https://github.com/igraph/rigraph/pull/1068

**Comment by szhorvat** [comment]
This was done in tandem with bounds checking for scalar. Same comments apply as in https://github.com/igraph/rigraph/issues/1140#issuecomment-1903793888

Auto-generated part was done in https://github.com/igraph/rigraph/pull/1051, manually written code still needs checks using `R_check_int_scalar()`, `R_check_real_scalar()`, `R_check_bool_scalar()`

**Comment by maelle** [comment]
Ok, then I'll check the box in #840 and close this. Thank you!
