### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#1142]
From #840 

Make sure that error codes are checked and handled in all manually written and all auto-generated code. This is essential now that the error handler must return. Previously the error handler would just longjmp(), so there is likely quite a bit of sloppiness about this in the current code, which can potentially lead to crashes. Warning, the test suite won't catch these issues!

**Comment by krlmlr** [comment]
From #1071.

**Comment by maelle** [comment]
Duplicate of #1056
