### ISSUE TITLE
Unexpected results by graph.lattice

### ISSUE THREAD

**Issue by Holzhauer** [igraph/rigraph#115]
The following behaviour of graph.lattice in igraph 1.0.1 seems to be a bug:

``` R
g <- igraph::graph.lattice(dim = 2, length = sqrt(2000))
igraph::vcount(g)
# gives 2044

g <- igraph::graph.lattice(dim = 2, length = ceiling(sqrt(2000)))
igraph::vcount(g)
# gives 2025
```

It is right that 'length' expects an integer, but however I rather expect an error message than the experienced behaviour for the first version.

**Comment by szhorvat** [comment]
@ntamas Is there any reason why you compare to `floor` but then use `round`? Why not compare to `round` and use `round`?

**Comment by ntamas** [comment]
No particular reason but it shouldn't matter, should it? If `floor(x) == x`, then X is integer so it does not matter which one I use. If `floor(x) != x`, then `round(x)` correctly rounds to the nearest integer, which is what I wanted.

**Comment by szhorvat** [comment]
> No particular reason but it shouldn't matter, should it?

No, it shouldn't, I was just wondering if I missed anything.
