### ISSUE TITLE
Create hierarchical communities with function "create.communities"

### ISSUE THREAD

**Issue by Boresal** [igraph/rigraph#116]
I am trying to create a hierarchical community detection algorithm that outputs an igraph.community object. However, the resulting community is not considered hierarchical by the function is.hierarchical (as I need).

A short-cut to solve this is using "walktrap", "edge betweenness", "fast greedy" to (fakely) define the algorithm used. However, this is not a very clean solution, since I will like the text shown when the community is printer to show the real name of the algorithm.

Is there an easy way to solve this?

Many thanks for your work!

**Comment by ntamas** [comment]
Communities are considered hierarchical if there is a `merges` attribute on the community object:

```
is_hierarchical <- function(communities) {
  ! is.null(communities$merges)
}
```

So I guess you'd need to provide a merge matrix in the object that you create and then it will work, i.e. something like:

```
> make_clusters(g, algorithm="My awesome algorithm", merges=...)
```
