### ISSUE TITLE
Better solution for `HAVE_GFORTRAN`

### ISSUE THREAD

**Issue by krlmlr** [igraph/rigraph#1161]
https://github.com/igraph/rigraph/pull/1160/commits/35fa3f23f566e637445246652f503329f9189066#diff-b12534ddaa2fc5d241629c3649f0682b7d327d944508e5b8363c397efeb2d043R10

Do we want/need this on Windows?

**Comment by szhorvat** [comment]
`HAVE_GFORTRAN` should _always_ be defined when compiling the R interface. gcc/gfortran are used on Windows as well. 

If/when you look into linking to an external ARPACK, this should be revisited.

Related: #1016

**Comment by maelle** [comment]
@Antonov548
