### ISSUE TITLE
does the Matrix package now have a support for character sparse matrix

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#1169]
In the docs of `as_adjacency_matrix()`I see

> The reason for the difference is that the `Matrix` package does not support character sparse matrices yet.

Making a note of this in case this changes/changed?

**Comment by szhorvat** [comment]
I don't think we'll support character matrices in C (unless there is a very very convincing reason), so if this is implemented in R, it will need to be a pure-R implementation that is compatible with the C one for numbers.
