### ISSUE TITLE
2.0.1 build error: `random.c: error: '__uint128_t' undeclared (first use in this function); did you mean '__uint32_t'?`

### ISSUE THREAD

**Issue by barracuda156** [igraph/rigraph#1172]
### What happens?

```
/opt/local/bin/gcc-mp-13 -I"/opt/local/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -DUSING_R -I. -Ivendor -Ivendor/cigraph/src -Ivendor/cigraph/include -Ivendor/cigraph/vendor -I"/opt/local/include/libxml2" -DNDEBUG -DNTIMER -DNPRINT -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL= -DPRPACK_IGRAPH_SUPPORT -DHAVE_GFORTRAN=1 -D_GNU_SOURCE=1 -I'/opt/local/Library/Frameworks/R.framework/Versions/4.3/Resources/library/cpp11/include' -isystem/opt/local/include/LegacySupport -I/opt/local/include    -fPIC  -pipe -Os -arch ppc  -c vendor/cigraph/src/random/random.c -o vendor/cigraph/src/random/random.o
vendor/cigraph/src/random/random.c: In function 'igraph_i_rng_get_uint64_bounded':
vendor/cigraph/src/random/random.c:507:5: error: unknown type name '__uint128_t'; did you mean '__uint32_t'?
  507 |     __uint128_t m;
      |     ^~~~~~~~~~~
      |     __uint32_t
vendor/cigraph/src/random/random.c:510:14: error: '__uint128_t' undeclared (first use in this function); did you mean '__uint32_t'?
  510 |         m = (__uint128_t)(x) * (__uint128_t)(range);
      |              ^~~~~~~~~~~
      |              __uint32_t
vendor/cigraph/src/random/random.c:510:14: note: each undeclared identifier is reported only once for each function it appears in
vendor/cigraph/src/random/random.c:513:14: warning: right shift count >= width of type [-Wshift-count-overflow]
  513 |     return m >> 64;
      |              ^~
make: *** [vendor/cigraph/src/random/random.o] Error 1
```

### To Reproduce

Try building it for `ppc`.

**Comment by barracuda156** [comment]
I guess, a check is required whether a platform support uint128: https://github.com/openssl/openssl/issues/14804

@szhorvat FYI.

**Comment by szhorvat** [comment]
How does this line even get compiled if `HAVE___UINT128_T` is not defined? Notice that it is guarded by that macro.

**Comment by szhorvat** [comment]
@barracuda156 Please comment this line in `src/vendor/config.h`:

```
#define HAVE___UINT128_T 1
```

Does it work now?

**Comment by szhorvat** [comment]
@krlmlr This is not a PPC issue. It's an issue with both 32-bit systems as well as any compiler with does not support GCC's non-standard `__uint128_t` type.

Fixing this requires a proper check for whether the `__uint128_t` type exists, and defining `HAVE___UINT128_T` accordingly.

On 32-bit platforms, not defining `HAVE___UINT128_T` has no consequence.

On 64-bit platforms, not defining `HAVE___UINT128_T` would reduce performance.

**Comment by barracuda156** [comment]
@szhorvat Let me try changing the macro.

By the way, long double is supported on `ppc`, but it is not IEEE type, it is IBM type (composed of two doubled, like on AIX).

**Comment by barracuda156** [comment]
@szhorvat @krlmlr Yes, removing `HAVE___UINT128_T` fixes the issue.

P. S. I guess, `config.h` it is supposed to be generated by a configure script. If it is not, there should be done alternative way to fix it for 32-bit platforms.

**Comment by szhorvat** [comment]
For now, please patch it in MacPorts for PPC and 32-bit _only_.

**Comment by barracuda156** [comment]
@szhorvat Obviously, for 32-bit, but shouldn’t this apply to all 32-bit archs rather than just `ppc`?

**Comment by szhorvat** [comment]
Yes, all 32-bit arches.

**Comment by Antonov548** [comment]
@szhorvat Can we try to compile simple `.c` file in configure wich will check if `__uint128_t` is available? 
I think this only way to make it work without introducing autoconf, which will do exactly the same under the hood.

**Comment by szhorvat** [comment]
I don't know a better way than what you are proposing. I never tried to do this without the help of CMake or autoconf.

I'm guessing a source file with just `__uint128_t x;` should be enough for as long as we compile without linking (`gcc -c`).

**Comment by szhorvat** [comment]
Is using the configure script good enough though? Isn't Windows one of the more likely platforms to compile R as 32-bit? Then we don't have a configure script.

**Comment by szhorvat** [comment]
@Antonov548 I searched some more and it seems there's a macro we might be able to use: `#ifdef __SIZEOF_INT128__`. Now sure how foolproof is, but seems to work fine for very old GCC and Clang versions according to https://godbolt.org/  How about just use this, to also handle Windows?

**Comment by Antonov548** [comment]
> @Antonov548 I searched some more and it seems there's a macro we might be able to use: `#ifdef __SIZEOF_INT128__`. Now sure how foolproof is, but seems to work fine for very old GCC and Clang versions according to https://godbolt.org/ How about just use this, to also handle Windows?

Would you suggest to use it for both platforms? In general I like it. I also will try to check it.

**Comment by szhorvat** [comment]
It's not really documented, at least I couldn't find anything. I got this tip from ChatGPT (after about 5 completely wrong suggestions it gave me). It's fine with GCC 4.7, and as I recall we require at least GCC 4.8. It's also fine with Clang 3.3, which is _probably_ also too old.

The advantage of this solution is that it would also handle 32-bit Windows.

The disadvantage is that if people use an uncommon compiler (e.g. Intel), it might not work.

**Comment by szhorvat** [comment]
Maybe we could use the following for a bit of additional safety:

```
#if defined(__GNUC__) && defined(__SIZEOF_INT128__)
```

There are several compilers that claim GCC compatibility and define the `__GNUC__` macro, such as Clang and Intel.

**Comment by szhorvat** [comment]
@barracuda156 Can you check if your old PPC system has `__SIZEOF_INT128__` defined without the inclusion of any headers?

**Comment by barracuda156** [comment]
> It's not really documented, at least I couldn't find anything. I got this tip from ChatGPT (after about 5 completely wrong suggestions it gave me). It's fine with GCC 4.7, and as I recall we require at least GCC 4.8. It's also fine with Clang 3.3, which is _probably_ also too old.

It works with the current GCC too, right? No point to care about < 4.7.

**Comment by barracuda156** [comment]
> @barracuda156 Can you check if your old PPC system has `__SIZEOF_INT128__` defined without the inclusion of any headers?

@szhorvat Will do once back to some PowerPC machine later today.

**Comment by szhorvat** [comment]
@barracuda156 Please re-open this if you still see the issue on the `main` branch. I think it's fixed now.

**Comment by barracuda156** [comment]
@szhorvat Will try today. (Sorry for a delay, I got stuck with Go on i386 earlier.)

**Comment by barracuda156** [comment]
@szhorvat I finally got to this. Yes, `R-igraph` from 048ea090baa3bcbdcf97765090f4dbb55eeee7fd builds fine for me on `ppc` with no patches from my side. Provided I used the right commit, we should be good.
