### ISSUE TITLE
Go back to autogenerating all code

### ISSUE THREAD

**Issue by krlmlr** [igraph/rigraph#1176]
I have allowed drift to speed up the 2.0.0 release. We need to recover from that to be functional again.

Each deviation from autogenerated code in `aaa-auto.R` is there for a reason.

**Comment by maelle** [comment]
goal: edit the Stimulus stuff until running it creates the current R code

**Comment by maelle** [comment]
```
docker run --rm -ti --platform linux/amd64 -v $(pwd):/root/workspace ghcr.io/cynkra/rig-ubuntu-igraph:main make -f Makefile-cigraph -B R/aaa-auto.R
```

**Comment by maelle** [comment]
maybe add ignore as in #1044

**Comment by szhorvat** [comment]
Drift is fixed right now.

**Comment by maelle** [comment]
Re-opening to pick up #1044 at some point

**Comment by krlmlr** [comment]
We're good here now.
