### ISSUE TITLE
Unable to update to version 2.0

### ISSUE THREAD

**Issue by gherrarte** [igraph/rigraph#1183]
I have been trying to upgrade Igraph to its newest version, but I get this message:
ERROR: compilation failed for package ‘igraph’

Now all other libraries that have Igraph as a dependency are not working either. For example, tidygraph and Networkd3 are broken. I have tried to compile from source and I get the same result. 

I have tried to upgrade using Fedora 39 and also Debian Bookworm with the same results.  Any ideas?

**Comment by gherrarte** [comment]
I have reinstall glpk-devel gmp-devel libxml2-devel.  I have also reinstall gcc gcc-c++ gcc-gfortran and the same issue persist.

**Comment by szhorvat** [comment]
FWIW I tested this with a Fedora 40 Docker image earlier, and compilation succeeded. What specific Fedora version do you have and where did you obtain R? Did you restart R after installing the required packages?

**Comment by szhorvat** [comment]
Never mind, I see the versions in the build log above.

**Comment by szhorvat** [comment]
I just tested it on Fedora 39, and did not see problems. Are we doing something differently @gherrarte ?

```
docker run -it fedora:39 bash
```

```
yum install gcc gcc-c++ gcc-gfortran glpk-devel gmp-devel libxml2-devel R
```

Then I started `R` and used `install.packages('igraph')`.

Compilation succeeded and the library works.

**Comment by gherrarte** [comment]
Hi Szhorvat, I was able to run the installation, following your instructions, in Debian Bookworm and was succesful.  But, for Fedora 39 the issue persist. I will look into libxml2 to see if I have something wrong set up for my own environment.  I will let you know.

**Comment by szhorvat** [comment]
@gherrarte Do you use Anaconda? If yes, be sure to deactivate all conda environments before compiling igraph. Can you upload the _complete_ build log somewhere and link to it?

**Comment by gherrarte** [comment]
@szhorvat Ok.  I will try this solution.  Yes.  I also use Anaconda.

**Comment by szhorvat** [comment]
So, to be clear, run `conda deactivate` before starting R, use R from the command line, and try again. Let us know if it worked.

**Comment by gherrarte** [comment]
@szhorvat Yes. I worked.  Thank you very much.
