### ISSUE TITLE
I am not in the sudoers file ,how to use apt install libglpk-dev libgmp-dev libxml2-dev

### ISSUE THREAD

**Issue by xinguo1236** [igraph/rigraph#1187]
I am not in the sudoers file ,how to use apt install libglpk-dev libgmp-dev libxml2-dev

Thanks a lot.

**Comment by szhorvat** [comment]
We would like the reserve the issue tracker for bug reports and feature requests. When you opened an issue, there was a link to the support forum. Please use the forum for support requests.
