### ISSUE TITLE
Run doc examples with sanitizer

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#1195]
Can we run the doc examples with sanitizer checks? It has the potential to reveal invalid memory accesses and memory leaks. In fact, there are such memory leaks at the moment, see https://github.com/igraph/rigraph/pull/1173#issuecomment-1925481007

**Comment by Antonov548** [comment]
@szhorvat I have reviewed types conversion. Seems you covered all wrong conversions. At least I didn't find with manual search other types that have memory leaks. I think we can try to add examples to CI. 

I just not sure what is right way to run only examples for locally installed igraph.

@maelle May you suggest some solution for running examples? 
```R
library(igraph)
functions_list <- ls("package:igraph")
for (func in functions_list) {
  example(func)
}
```

Or can we just use `R CMD check` which will run only examples?

**Comment by szhorvat** [comment]
@Antonov548 Something I wasn't sure about is cases like this:

https://github.com/igraph/rigraph/blob/7c0540e46006840f73fdf4b4ff3da83e58f42ffa/tools/stimulus/types-RC.yaml#L154-L173

Does the `INOUT` part need its own `OUTCONV`?

**Comment by Antonov548** [comment]
> INOUT

This is I also get confusen. But seems stimulus use `OUT` conversion, even if it's `INOUT` and `INOUT` for `OUTCONV` is not exists. For example `igraph_layout_drl` which has `INOUT MATRIX res`, and `MATRIX` hasn't `OUTCONV` for `INOUT`.

So, it should works fine.

**Comment by maelle** [comment]
@Antonov548 sorry seeing this only now. `devtools::run_examples(run_donttest = TRUE, run_dontrun = TRUE, fresh = TRUE)`!

**Comment by Antonov548** [comment]
> @Antonov548 sorry seeing this only now. `devtools::run_examples(run_donttest = TRUE, run_dontrun = TRUE, fresh = TRUE)`!

I see the ` *** caught segfault ***` when trying to run examples with this command. I was trying to find which exactly example produce it, but without success.

Do you also have this issue?

**Comment by szhorvat** [comment]
Do you get at least an ASan stack trace?

**Comment by Antonov548** [comment]
> Do you get at least an ASan stack trace?

I didn't try with ASan yet. Need to setup it locally after refresh of my pc.

**Comment by krlmlr** [comment]
Need to find a good way to run all examples from the installed package for ASAN.

**Comment by krlmlr** [comment]
`devtools::run_examples()` uses `pkgload::load_all()`, we had problems with this in the past with ASan.

**Comment by maelle** [comment]
Maybe using `tools::Rd2ex()` on all Rd files
