### ISSUE TITLE
Memory leaks when converting data to/from C

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#1199]
#1196
https://github.com/igraph/rigraph/pull/1173#issuecomment-1925481007

@szhorvat I'm opening an issue so we can close this once we're sure everything has been covered.

**Comment by szhorvat** [comment]
Some of this was done in #1196, but it needs to be verified that nothing is left

**Comment by szhorvat** [comment]
#1195 will help with testing that we covered everything already.
