### ISSUE TITLE
Improve libxml2 detection

### ISSUE THREAD

**Issue by krlmlr** [igraph/rigraph#1217]
https://github.com/igraph/rigraph/pull/1197#issuecomment-1928275316

- [x] Rename `xml2_include_paths` variable to `xml2_cflags`
- [x] Also use linker flags by `xml2-config` or `pkg-config` instead of hard-coding them

**Comment by szhorvat** [comment]
I checked both boxes here, as they're done. But there's one more thing: if libxml2 is not found, it'd be nice to just disable GraphML support instead of failing to build.

**Comment by maelle** [comment]
> just disable GraphML support

What should then happen if the user tries using the related functionality?

I wonder whether other R packages also have this sort of "partial installation".

**Comment by szhorvat** [comment]
There will be a nice and clear error message explaining that this functionality is not available. This is all already implemented, so nothing needs to be done in R code. The C sources simply need to be compiled with the appropriate macros (un)defined.
