### ISSUE TITLE
Communicability

### ISSUE THREAD

**Issue by Pablo1990** [igraph/rigraph#122]
Hey guys!

I've done some code for the communicability angle and distance measures. (Estrado, E. and Hatano, N. (2008) Communicability in complex networks. Physical Review E: Statistical, Nonlinear, and Soft Matter Physics, 77 (3). 036111. ISSN 1063-651X, Linear Algebra and its Applications 06/2012; 436(11):4317–4328. DOI:10.1016/j.laa.2012.01.017, Communicability Angle and the Spatial Efficiency of Networks). And I was wondering weather or not I could integrate it on your code. 
It's a basic code, 10 lines per function, 2 functions.

Cheers,
Pablo

**Comment by gaborcsardi** [comment]
Hi! Thanks for the offer. The thing is, igraph is already huge, so I think it is better to create a package for your code.

Thanks again!
