### ISSUE TITLE
`vertices(1, 2, foo = 3)` no longer works

### ISSUE THREAD

**Issue by krlmlr** [igraph/rigraph#1231]
### What happens?

Recycling of attributes is broken since igraph 2.0.0 .

Downstream: https://github.com/se-sic/coronet/pull/250

## CRAN

``` r
options(conflicts.policy = list(warn = FALSE))
library(igraph)

g <-
  make_empty_graph(1) +
  vertices("a", "b", foo = 5)
#> Error in add_vertices(e1, la, attr = e2): At rinterface_extra.c:78 : Expecting a scalar integer but received a vector of length 2. Invalid value

V(g)$foo
#> Error in eval(expr, envir, enclos): object 'g' not found
```

<sup>Created on 2024-02-09 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

## 1.6.0

``` r
options(conflicts.policy = list(warn = FALSE))
library(igraph)

g <-
  make_empty_graph(1) +
  vertices("a", "b", foo = 5)

V(g)$foo
#> [1] NA  5  5
```

<sup>Created on 2024-02-09 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by maelle** [comment]
Do you expect the bug to be in C or R, if you have any idea?

**Comment by maelle** [comment]
the error message (not the error) comes from https://github.com/igraph/rigraph/commit/b98dc71a1d8127fac9f19c604b684a5a63447b82

**Comment by maelle** [comment]
https://github.com/igraph/rigraph/commit/bf3a283b9eef75741b6eda3a3ec5d3450b68eeb8

**Comment by maelle** [comment]
There is

```c
SEXP R_igraph_add_vertices(SEXP graph, SEXP pnv) {

  igraph_integer_t nv;
  igraph_t g;
  SEXP result;

  R_check_int_scalar(pnv);
```

but the second argument of `R_igraph_add_vertices` cannot be a integer scalar I suppose, as each vertice is 2 numbers (my understanding = I have read the intro vignette at last :wink:).

**Comment by maelle** [comment]
or is it an argument order thing :thinking:

**Comment by maelle** [comment]
in `operators.R`

```r
dput(e2)
list(name = structure(c("a", "b"), names = c("", "")), foo = 5)
```
