### ISSUE TITLE
Error installing igraph on Debian 8

### ISSUE THREAD

**Issue by blaquans** [igraph/rigraph#125]
I've tried  to install  igraph on R using install.packages(). I've the following error : 

    /usr/share/R/share/make/shlib.mk:6: recipe for target 'igraph.so' failed
    make: *** [igraph.so] Error 1
    ERROR: compilation failed for package ‘igraph’
    * removing ‘/home/debian/R/x86_64-pc-linux-gnu-library/3.2/igraph’
    Warning in install.packages :
    installation of package ‘igraph’ had non-zero exit status

Do you have any explanation ? 

    > R.version
                   _                           
     platform       x86_64-pc-linux-gnu         
     arch           x86_64                      
     os             linux-gnu                   
     system         x86_64, linux-gnu           
     status                                     
     major          3                           
     minor          2.2                         
     year           2015                        
     month          08                          
    day            14                          
    svn rev        69053                       
    language       R                           
    version.string R version 3.2.2 (2015-08-14)
    nickname       Fire Safety

**Comment by gaborcsardi** [comment]
This does not contain the actual error message from the compilation. Do you have more output?

**Comment by blaquans** [comment]
Ok, this my [gist](https://gist.github.com/blaquans/3a11a3902b0d443ef090) with the whole output

**Comment by gaborcsardi** [comment]
I think you need the liblapack-dev and libblas-dev Debian packages.

**Comment by jimhester** [comment]
@blaquans you can install the `r-cran-igraph` debian package to install a precompiled version on debian.
```
apt-get install r-cran-igraph
```
If for whatever reason you still want to compile it yourself you can install the build dependencies with
```
apt-get build-dep r-cran-igraph
```

**Comment by blaquans** [comment]
The first one works but not the second one. I don't find any source for r-cran-igraph.

**Comment by blaquans** [comment]
@gaborcsardi ok, your solution is the good one. 

So the solution is :

    # apt-get install liblapack-dev
    # apt-get install libblas-dev

And then in R/RStudio

    > install.packages("igraph")
    > devtools::install_github("jimhester/lintr")

**Comment by kinzaR** [comment]
@gaborcsardi , 
I had a similar error, and your solution worked for me also :)
Thank you @pachevalier  to share the details :+1: 

My error : 
`/usr/bin/ld: cannot find -llapack
/usr/bin/ld: cannot find -lblas
/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status`
