### ISSUE TITLE
`igraph_are_adjacent()`

### ISSUE THREAD

**Issue by krlmlr** [igraph/rigraph#1253]
https://github.com/igraph/igraph/pull/2486

**Comment by szhorvat** [comment]
This is a good opportunity to move the `are_adjacent()` R function to auto-generation. This is in fact the quickest fix.

**Comment by szhorvat** [comment]
Suggested doc fix:

```
#' @return A logical scalar, `TRUE` is a `(v1, v2)` exists in the
#'   graph.
```

Change to:

```
#' @return A logical scalar, `TRUE` if edge `(v1, v2)` exists in the
#'   graph.
```
