### ISSUE TITLE
I encountered this error during network analysis; what could be the cause? How should I resolve it?

### ISSUE THREAD

**Issue by gwfs521** [igraph/rigraph#1255]
V(g)$modularity<-membership(cluster_fast_greedy(g,))
Error in cluster_fast_greedy(g, modularity = FALSE) : 
  At vendor/cigraph/src/community/fast_modularity.c:658 : Weights must not be NaN. Invalid value

**Comment by szhorvat** [comment]
Precisely what the error states. The graph contains edge weights with NaN or NA values, which are forbidden. In the future please use the forum for support questions. https://igraph.discourse.group/ We'd like to reserve the issue tracker for bug reports and feature requests.
