### ISSUE TITLE
install bot to lock closed issues?

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#1258]

**Comment by szhorvat** [comment]
Do we really need to do this? Sometimes commenting on old issues is useful. There's the annoyance of people using the issue tracker instead of the forum for support, but that won't be solved by locking closed issues.

**Comment by szhorvat** [comment]
Is it possible to do this in a way that the lock won't apply to us? Perhaps just have unlock rights for everyone within the team, and agree to be disciplined and not unlock without a good reason?

**Comment by maelle** [comment]
@szhorvat according to https://docs.github.com/en/communities/moderating-comments-and-conversations/locking-conversations

> While a conversation is locked, only [people with write access](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization) and [repository owners and collaborators](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-personal-account-settings/permission-levels-for-a-personal-account-repository#collaborator-access-for-a-repository-owned-by-a-personal-account) can add, hide, and delete comments. Reactions and votes in a locked conversation are disabled for all users.

So we'd be good?

**Comment by maelle** [comment]
If we decide to go forward with the locking idea:

- I've seen https://github.com/dessant/lock-threads used in github.com/rstudio/rmarkdown, so would choose that unless someone has another recommendation.
- What should we choose as "number of days of inactivity before a closed issue is locked"? Same number for PRs?
