### ISSUE TITLE
C/igraph version is not set before compiling

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#1259]
### What happens?

The C/igraph version is not set before compiling. See `igraph_version.h`, which contains `"@PACKAGE_VERSION@"`. This then leaks through in some contexts, for example when writing GML files.

### To Reproduce

```r
write_graph(make_graph(c(1,2)), "foo.gml", format="gml")
```

The resulting file will contain:

```
Creator "igraph version @PACKAGE_VERSION@ Tue Feb 20 11:20:57 2024"
```

**Comment by maelle** [comment]
@Antonov548 could you please have a look?

**Comment by Antonov548** [comment]
> @Antonov548 could you please have a look?

Yes, I will

**Comment by szhorvat** [comment]
You might find that fixing this is not simple, as the version is normally extracted from git tags. The script that updates the C core could be changed to write commit hash into the version field, or similar ... but that's maybe too much trouble?

For writing GMP specifically, it is possible to pass your own Creator string instead of using the default. You could pass in the R/igraph version, or just a fixed string, whatever you like.

For getting the `igraph_version()` C function working properly: this is not really critical.

Is there anything else affected? I'm not sure. Maybe not.
