### ISSUE TITLE
no visible global function definition for `.from`

### ISSUE THREAD

**Issue by mbojan** [igraph/rigraph#126]
I wrote a function in a package that uses expressions like `E(g)[ .from(i) ]` to manipulate edge attributes based on properties of adjacent nodes. When put in a package, `R CMD check` complains:

```
ssi: no visible global function definition for ‘.from’
```

How to get around that?

**Comment by mkhezr** [comment]
I noticed the same issue with other "special" edge indexing functions: 'inc' and 'to'. @mbojan Did you find a workaround? @gaborcsardi is there any news on this issue? or any advice on how to use (not to use) these special functions? Thank you!

**Comment by mkhezr** [comment]
I found a workaround. Add a call to globalVariables(c("from", "inc", "to")) somwehere in your package source files. globalVariables tells the check tool that the specified names shoudl be regarded as globally defined. see ?globalVariables

**Comment by mbojan** [comment]
@mkhezr yes, `utils::globalVariables`. I don't think there is any other sensible workaround at this moment. See also https://stackoverflow.com/questions/9439256/how-can-i-handle-r-cmd-check-no-visible-binding-for-global-variable-notes-when
