### ISSUE TITLE
WARNING on oldrel windows

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#1266]
https://www.r-project.org/nosvn/R.check/r-oldrel-windows-x86_64/igraph-00check.html (via https://cran.r-project.org/web/checks/check_results_igraph.html)

@Antonov548 does this sound familiar?

**Comment by Antonov548** [comment]
This is related to https://github.com/igraph/rigraph/pull/1180

We decided to postpone it. Seems no good solution to resolve this warnings.
If they still should be fixed it also should be fixed in C/igraph.

**Comment by szhorvat** [comment]
We discussed this in chat. Since CRAN did not complain, this issue should be closed. The warnings are the result of a bug in the old MinGW compiler, which CRAN seems to be aware of.

**Comment by maelle** [comment]
Thanks, sorry for missing this!
