### ISSUE TITLE
igraph error

### ISSUE THREAD

**Issue by bebejhun** [igraph/rigraph#1271]
### What happens?

I downloaded Seurat and I found this errors and it keeps removing the packages in the file directory. I think there is a problem downloading igraph. Is there any solution to solve this problem? Thank you

In file included from vendor/cigraph/src/community/optimal_modularity.c:32:0:
vendor/cigraph/src/internal/glpk_support.h:39:10: fatal error: glpk.h: No such file or directory
 #include <glpk.h>
          ^~~~~~~~
compilation terminated.
/usr/lib/R/etc/Makeconf:168: recipe for target 'vendor/cigraph/src/community/optimal_modularity.o' failed
make: *** [vendor/cigraph/src/community/optimal_modularity.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/home/iamgojasper/R/x86_64-pc-linux-gnu-library/4.2/igraph’
Warning in install.packages :
  installation of package ‘igraph’ had non-zero exit status
ERROR: dependency ‘igraph’ is not available for package ‘leiden’
* removing ‘/home/iamgojasper/R/x86_64-pc-linux-gnu-library/4.2/leiden’
Warning in install.packages :
  installation of package ‘leiden’ had non-zero exit status
ERROR: dependencies ‘igraph’, ‘leiden’ are not available for package ‘Seurat’
* removing ‘/home/iamgojasper/R/x86_64-pc-linux-gnu-library/4.2/Seurat’
Warning in install.packages :
  installation of package ‘Seurat’ had non-zero exit status

**Comment by szhorvat** [comment]
Installation instructions are on the website, please follow them carefully and if you still have questions, as on the forum, not in the issue tracker.

https://r.igraph.org/
