### ISSUE TITLE
**On Ubuntu** igraph install problem:vendor/cigraph/src/internal/glpk_support.h:39:10: fatal error: glpk.h: No such file or directory

### ISSUE THREAD

**Issue by Lighter-k** [igraph/rigraph#1285]
**On Ubuntu**

install libglpk-de

ie 
`sudo apt-get update`
`sudo apt-get -y install libglpk-dev`

_Originally posted by @mdeea in https://github.com/igraph/rigraph/issues/490#issuecomment-1915695897_

but how to deal the problem that im not root user

**Comment by szhorvat** [comment]
Please use the forum for support questions.
