### ISSUE TITLE
error

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#1289]
Related to #1286 (@Antonov548) I extracted all examples in an Rmd file to knit it and see what fails.

I get

```r
Error in `sample_degseq()`:
! At vendor/cigraph/src/games/degree_sequence_vl/gengraph_mr-connected.cpp:150 : Cannot realize the given degree sequence as an undirected, simple graph. Invalid value
Backtrace:
 1. igraph::sample_degseq(degs, method = "vl")
```

for 

```r
### Name: sample_degseq
### Title: Generate random graphs with a given degree sequence
### Aliases: sample_degseq degseq
### Keywords: graphs

### ** Examples


## The simple generator
g <- sample_degseq(rep(2, 100))
degree(g)
is_simple(g) # sometimes TRUE, but can be FALSE
g2 <- sample_degseq(1:10, 10:1)
degree(g2, mode = "out")
degree(g2, mode = "in")

## The vl generator
g3 <- sample_degseq(rep(2, 100), method = "vl")
degree(g3)
is_simple(g3) # always TRUE

## Exponential degree distribution
## Note, that we correct the degree sequence if its sum is odd
degs <- sample(1:100, 100, replace = TRUE, prob = exp(-0.5 * (1:100)))
if (sum(degs) %% 2 != 0) {
  degs[1] <- degs[1] + 1
}
g4 <- sample_degseq(degs, method = "vl")
all(degree(g4) == degs)

## Power-law degree distribution
## Note, that we correct the degree sequence if its sum is odd
degs <- sample(1:100, 100, replace = TRUE, prob = (1:100)^-2)
if (sum(degs) %% 2 != 0) {
  degs[1] <- degs[1] + 1
}
g5 <- sample_degseq(degs, method = "vl")
all(degree(g5) == degs)



```

but running this code directly, or with reprex... does NOT lead to any error. Maybe due to some randomness?

**Comment by szhorvat** [comment]
> Maybe due to some randomness?

Yes.

There's no guarantee that randomly picked integers will form a graphical degree sequence (i.e. that there's a graph with these degrees).

**Comment by maelle** [comment]
should we set the seed for this example then?

**Comment by szhorvat** [comment]
yes

**Comment by Antonov548** [comment]
I also wondering what is the issue in gihub actions and should we somehow install something to docker image to make it works?
```bash
Error in .External2(C_X11, d$display, d$width, d$height, d$pointsize,  : 
  unable to start device X11cairo
Calls: source -> withVisible -> eval -> eval -> eval -> eval -> x11
In addition: Warning message:
In x11(width = 10, height = 5) :
  unable to open connection to X11 display ''
```

**Comment by maelle** [comment]
let me try finding a seed that works

**Comment by maelle** [comment]
this might require making the example dependent on installing withr, or adding more boiler plate to preserve the seed.

**Comment by szhorvat** [comment]
> this might require making the example dependent on installing withr, or adding more boiler plate to preserve the seed.

Alternatively, you can keep generating degree sequences until `is_graphical` returns true. We can make it so that the probability of getting a good sequence is high (but it's next to impossible to make it _guaranteed_).

I'm not sure if R has a one-liner for this? In the Mathematica interface of igraph I even have a helper function for rejection sampling, i.e. for trying and retrying until a condition is satisfied.

**Comment by maelle** [comment]
@Antonov548 is your issue a distinct issue?

**Comment by maelle** [comment]
I feel the example would be simpler to read if we simply preserved the seed.

**Comment by maelle** [comment]
Ok, let's tackle this in #1300

**Comment by clpippel** [comment]
# Nice example to include.
degs <- c(3, 1, 1, 1)
g <- sample_degseq(degs, method = "vl")
# Warning message:
# In sample_degseq(degs, method = "vl") :
#   At vendor/cigraph/src/games/degree_sequence_vl/gengraph_graph_molloy_hash.cpp:400 : Cannot shuffle graph, maybe it is the only realization of its degree sequence?

**Comment by clpippel** [comment]
```
# Example of non existing degree sequence,
# and how to ignore.
degs <- c(3, 1, 1, 1)
tryCatch(
  expr    = g <- sample_degseq(degs, method = "vl"),
  warning = function(cond) print(paste("Ignore: ", conditionMessage(cond)))
)
warnings() # no warnings
```

**Comment by clpippel** [comment]
```
# Example of warning "Cannot shuffle graph",
# and how to ignore all warnings.
degs <- c(3, 1, 1, 1)
tryCatch(
  expr    = g <- sample_degseq(degs, method = "vl"),
  warning = function(cond) print(paste("Ignore: ", conditionMessage(cond)))
)
warnings() # no warnings
```
