### ISSUE TITLE
warning in graph_from_adjacency_matrix() example

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#1290]
``` r
library("igraph")
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union
nzs <- function(x) sort(x[x != 0])
adjm <- matrix(runif(100), 10)
adjm[adjm < 0.5] <- 0
g3 <- graph_from_adjacency_matrix((adjm + t(adjm)) / 2,
  weighted = TRUE,
  mode = "undirected"
)

g4 <- graph_from_adjacency_matrix(adjm, weighted = TRUE, mode = "max")
all(nzs(pmax(adjm, t(adjm))[upper.tri(adjm)]) == sort(E(g4)$weight))
#> Warning in nzs(pmax(adjm, t(adjm))[upper.tri(adjm)]) == sort(E(g4)$weight):
#> longer object length is not a multiple of shorter object length
#> [1] FALSE
```

<sup>Created on 2024-03-11 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by maelle** [comment]
this happens several times in that same Rd file.

**Comment by clpippel** [comment]
Maelle, Is there a compelling reason why this error would not occur?

**Comment by maelle** [comment]
I think it'd be better if the example didn't show a warning, now I need to think about how to achieve this.

**Comment by clpippel** [comment]
This error was already present Version 0.7.1, Package ‘igraph’, July 2, 2014.
I think this requires a redesign. Or a clarification by the author.

**Comment by clpippel** [comment]
Note that function d0() in
''' 
g9 <- graph_from_adjacency_matrix(adjm, weighted = TRUE, mode = "plus", diag = FALSE)
d0 <- function(x) {
  diag(x) <- 0
}
'''
Is wrong. It must end with return(x). Otherwise it will always return TRUE.

**Comment by clpippel** [comment]
The solution is to add diag=TRUE in upper.tri() and lower.tri() in the code. This will eliminate the warnings.
