### ISSUE TITLE
R: hide unexported functions

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/rigraph#13]
_From @gaborcsardi on October 7, 2013 16:26_

To avoid name clashes with other packages. See http://cran.us.r-project.org/doc/manuals/r-devel/R-exts.html#Controlling-visibility

Essentially, we need to add 

```
PKG_CFLAGS=$(C_VISIBILITY)
PKG_FFLAGS=$(F77_VISIBILITY)
```

to `Makevars`, and then prefix each entry point with `attribute_visible`, e.g (from the docs):

```
void attribute_visible R_init_stats(DllInfo *dll)
...
```

_Copied from original issue: igraph/igraph#525_

**Comment by ntamas** [comment]
I'm trying to address this in cfc46d9

**Comment by szhorvat** [comment]
Doesn't every function that is directly called by R need to be made visible as well? I.e., the visibility spec needs to be added by stimulus?

**Comment by ntamas** [comment]
No, only the init function needs to be visible. The remaining functions are all referred to by the `CallEntries` table that you can find in `init.c` (also mostly autogenerated). You only need to get a handle on `R_init_igraph()` and call it; the function will register everything else.

**Comment by szhorvat** [comment]
This is not working properly on macOS. The output of `nm -gU igraph.so` contains all symbols.

**Comment by ntamas** [comment]
This is because the R toolchain does not support it yet on Windows or macOS; see [here](https://cran.microsoft.com/doc/manuals/r-devel/R-exts.html#Controlling-visibility):

> Header R_ext/Visibility.h has some definitions for controlling the visibility of entry points. These are only effective when ‘HAVE_VISIBILITY_ATTRIBUTE’ is defined – this is checked when R is configured and recorded in header Rconfig.h (included by R_ext/Visibility.h). It is often defined on modern Unix-alikes with a recent compiler [159](https://cran.microsoft.com/doc/manuals/r-devel/R-exts.html#FOOT159), but not supported on macOS nor Windows.

**Comment by szhorvat** [comment]
For reference, here is [`Visibility.h`](https://github.com/wch/r-source/blob/trunk/src/include/R_ext/Visibility.h).

It's strange that they state that it is not supported on macOS because these attributes definitely do work there and we do use them in the C core (granted, CMake checks for them, but they must have been working for quite a long time on macOS now). What we do in the C core is build with `-fvisibility=hidden` and then selectively unhide symbols using `__attribute__ ((visibility ("default")))`

**Comment by szhorvat** [comment]
I checked my local `Rconfig.h` and it does not define `HAVE_VISIBILITY_ATTRIBUTE`. If R doesn't support this properly, I think we don't need to bother either, and this can be closed.

**Comment by ntamas** [comment]
We've done what we could so if R gains support for this on macOS, it will automatically start working in igraph.
