### ISSUE TITLE
In BFS the restricted set is 0 indexed instead of 1 indexed

### ISSUE THREAD

**Issue by Lucaweihs** [igraph/rigraph#133]
Lets consider the simple graph 1 -> 2 -> 3:

```
g = graph.edgelist(matrix(c(1,2,2,3), ncol=2, byrow=T))
```

Then if we want to do a BFS, starting at 1, but restricting to the nodes 1 and 2 we should be able to do it with the command:

```
graph.bfs(g, 1, restricted = c(1,2), unreachable=F)
```

but this returns an ordering of NA, NA, NA. Changing it to 

```
graph.bfs(g, 1, restricted = c(0,1), unreachable=F)
```

produces the correct order 1,2. This seems to be a one line change at https://github.com/igraph/rigraph/blob/dev/R/structural.properties.R#L2113 .

**Comment by gaborcsardi** [comment]
Would you like to submit a pull request? Maybe with a test case? Thanks.
