### ISSUE TITLE
Remove of `scale` parameter of `eigen_centrality()`

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#1353]
In C/igraph 1.0, the `scale` parameter of `eigen_centrality()` will be removed and the function will always behave as if `scale=TRUE` were used. Details are at https://github.com/igraph/igraph/issues/2446

This issue is to start preparing for this change on the R side, probably by deprecating the `scale` parameter.

Note that no real functionality is lost: `scale=FALSE` doesn't guarantee anything about any kind of scaling/normalization, while `scale=TRUE` uses a specific normalization. People should never have relied on `scale=FALSE`, so warning those who do soon is a good thing.

CC @maelle

**Comment by maelle** [comment]
@szhorvat do you agree that we should

- message if the argument is present and TRUE
- already error if it is present and FALSE since it seems really problematic to think `scale=FALSE` does something?
