### ISSUE TITLE
Protection issues

### ISSUE THREAD

**Issue by krlmlr** [igraph/rigraph#1359]
### What happens, and what did you expect instead?

See <https://raw.githubusercontent.com/kalibera/cran-checks/master/rchk/results/igraph.out>, these seem legit.

### To reproduce

Run checks with https://github.com/kalibera/rchk/ .

### System information

Linux

**Comment by krlmlr** [comment]
@Antonov548: are we in a better state here now?

**Comment by Antonov548** [comment]
Yes, in better state. PR is attached. I have failed to check it locally in docker container. Container just stoped without any errors. Maybe I just creating tarball not in the right way.

I will give it a try today once again.
