### ISSUE TITLE
Review `rinterface_extra.c` for memory management issues introduced during the 0.10 upgrade

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#1361]
The 0.10 upgrade introduced some memory management issues. `rinterface_extra.c` should be searched for these. Details and tips on how to do this effectively are in  https://github.com/igraph/rigraph/pull/1356#issuecomment-2098274706

Add any issues found to the following TODO list:

 - [ ] #1356
 - [x] #1362

**Comment by maelle** [comment]
@Antonov548 can this be closed?

**Comment by maelle** [comment]
@Antonov548 friendly reminder :smile_cat:

**Comment by Antonov548** [comment]
> @Antonov548 friendly reminder 😸

@maelle Sorry, I missed this notification on github. It's a bit hard to manually check `rinterface_extra.c` but I had quick look of functions and I think we can close this issue and maybe trust our sanitizer in CI.

**Comment by maelle** [comment]
thank you! no worries!
