### ISSUE TITLE
setting "betweenness = T" results in integer overflow for large graphs

### ISSUE THREAD

**Issue by ntamas** [igraph/rigraph#139]
_From @rkarpienko on January 21, 2016 13:14_

thanks for igraph and support! :)

> sessionInfo()
> R version 3.2.2 Patched (2015-09-10 r69352)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Debian GNU/Linux 8 (jessie)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] igraph_1.0.1

loaded via a namespace (and not attached):
[1] magrittr_1.5

_Copied from original issue: igraph/igraph#914_

**Comment by ntamas** [comment]
@rkarpienko Please provide more context; a small, reproducible example that shows the exact problem would be great. Or at least please specify where/how you set `betweenness=T` (i.e. which function you are trying to call).

**Comment by rkarpienko** [comment]
sorry, my bad, was in a hurry.
i meant to write setting "normalized=T" when computing betweenness results in an integer overflow for large graphs.

> somegraph <- sample_gnm(100000, 10, directed = FALSE, loops = FALSE)
> somegraph
IGRAPH U--- 100000 10 -- Erdos renyi (gnm) graph
+ attr: name (g/c), type (g/c), loops (g/l), m (g/n)
+ edges:
 [1]  7500--27496 51560--61384 60532--65832 57809--69422 77893--78205 20440--79237 47242--87115 63824--95100 30922--96525 92876--97096
> betweenness(somegraph, v = 1, normalized = TRUE)
[1] NA
Warning message:
In vc * vc : NAs produced by integer overflow

all the best,
radek

**Comment by ntamas** [comment]
Yes, that seems like a bug in the R part of `betweenness` where we do the normalization, and probably there's a better way of doing this by rearranging the multiplications and divisions in the normalization formula. I'm not the maintainer of the R interface so summon @gaborcsardi .

**Comment by szhorvat** [comment]
Betweenness normalization will eventually be moved to the C core, https://github.com/igraph/igraph/issues/1797
