### ISSUE TITLE
Network Data Validation

### ISSUE THREAD

**Issue by redsofa** [igraph/rigraph#141]
My question relates to validation of network data.
## Context : 

We have built something that looks like networkD3 (https://christophergandrud.github.io/networkD3/). It uses htmlwidgets to bridge R and JavaScript. What it adds is the ability to group nodes by nodeGroup and you can navigate the network by double-clicking on a parent node to see its children, and keep clicking  down the hierarchy. You can also filter by node, link weights etc...

We use iGraph to calculate some network statistics and pass that along to the D3 visualization for display....

Here is what defining a network looks like :

testNodes <- data.frame(nodeId, name, nodeValue, nodeGroup, nodeWeight, nodeParent)
testLinks <- data.frame(source, target, linkValue, linkGroup, linkWeight, nodeParent)

Here's what using igraph for getting network statistics  looks like:

&#35;iGraph graph
grph <- graph.data.frame(d=testLinks, directed=TRUE, vertices=testNodes)
stats <- getNetworkStatsPerNodeGroup(nodeGroupNames, grph)

Here's what launching our D3 visualization looks like : 

&#35; graph is a list of nodes and links that gets passed into the vfnetwork function
graph <- list(nodes = testNodes, links = testLinks)

&#35;Launch the visualization
plot <- vfnetwork(data=graph, options=opts)

My question is around validating the network data prior to passing it on to D3.

Prior to launching the D3 visualization, I would like to ensure that : 
- Node IDs are not duplicated in my node list
- In the node list, when a node is in a nodeGroup make sure the group exists in the node group definitions
- Link node IDs (in link data) are all in the node definitions
- Parent/child node IDs (in link data) are all in node definitions
- etc

Is there a validation library or set of validation functions in iGraph that I can use to start implementing these kinds of checks ?

**Comment by ntamas** [comment]
There are no such functions as far as I know.
