### ISSUE TITLE
Reading from GraphML quietly drops edges 

### ISSUE THREAD

**Issue by JJ** [igraph/rigraph#1428]
### What happens, and what did you expect instead?

[This graphml file](https://github.com/JJ/venice-city-networks/blob/main/code/data/venice.short.graphml) has been shortened to include only edges that manifest the problem; unfortunately, I couldn't track all nodes that are used by those edges, so it's not minimal.

This program uses that data file:

```R
library(igraph)
library(xml2)


venice.graph <- as.undirected( read_graph("venice.short.graphml",format="graphml") )
venice.graph.xml <- read_xml("venice.short.graphml")
edges.original <- xml_find_all(venice.graph.xml,".//d1:edge")

print(length(E(venice.graph)$name)) # 14
print(length(edges.original))               # 18
```
It's not entirely clear which ones are dropped and why. Assuming they are processed in the same order, `E(venice.graph)[5]$name` returns "", while the fifth element in the original graph is

```XML
    <edge source="764403528" target="27178184" id="1875">
      <data key="d0">166489461</data>
      <data key="d1">yes</data>
      <data key="d2">Ponte di Rialto</data>
      <data key="d3">footway</data>
      <data key="d4">False</data>
      <data key="d5">True</data>
      <data key="d6">9.935</data>
    </edge>
````

`d2`  key is translated as `name`, so it would look like it's dropped. The only issue about this one is that its `id`  is out of order.  It might be that it's processing it in `id` order, in which case it would make sense that the edge is this one:

```xml
   <edge source="27178422" target="223527689" id="4">
      <data key="d0">23243893</data>
      <data key="d3">pedestrian</data>
      <data key="d4">False</data>
      <data key="d5">True</data>
      <data key="d6">7.084</data>
    </edge>
```

The ones that have been dropped seem to be those with "Ponte di Rialto". Two of them have a d9 == ' building passage` I don't know if that gives a clue.

### To reproduce

Read the linked file as above, check the number of edges. The script above together with the downloaded file should be able to reproduce that.

### System information

R version 4.4.1.
igraph 2.0.3.

**Comment by szhorvat** [comment]
There are 18 `<edge>` tags in this file, and all of them are read.

```
> g<-read_graph('~/Downloads/venice.short.graphml','graphml')
> ecount(g)
[1] 18
```

You converted the graph to undirected using `as.undirected`, using the default `mode='collapse'`, which merged reciprocal connections, leaving only 14.

Since it was due to the use of `as.undirected`, I'm closing this now. Let me know if you still think that something's wrong.

**Comment by JJ** [comment]
Absolutely not. Thanks a lot, and sorry for the inconvenience.
