### ISSUE TITLE
Export `.from` etc. with behavior similar to `dplyr::across()`

### ISSUE THREAD

**Issue by krlmlr** [igraph/rigraph#1435]
and link to help pages.

Motivation:

https://github.com/maelle/simcausal/blob/b8dcf741e9388e48f1220b335add26fb073f93a1/R/simcausal.r#L422-L423

``` r
dplyr::across()
#> Error in `dplyr::across()`:
#> ! Must only be used inside data-masking verbs like `mutate()`,
#>   `filter()`, and `group_by()`.
igraph::.from()
#> Error: '.from' is not an exported object from 'namespace:igraph'
```

<sup>Created on 2024-07-18 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by szhorvat** [comment]
Have a look at https://github.com/igraph/rigraph/issues/541
