### ISSUE TITLE
TODOs in tests

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#1455]
One comment per test file, I'll ask for help once the list is done.

**Comment by maelle** [comment]
For test-arpack I'd need help or pointers to similar tests in the C core / Python interface

https://github.com/igraph/rigraph/blob/0931fa1698d8b832342a627dae9ad6ef0d66017d/tests/testthat/test-arpack.R#L98

**Comment by maelle** [comment]
I think the one below can be removed because there is a [test with subset of attributes](https://github.com/igraph/rigraph/blob/0931fa1698d8b832342a627dae9ad6ef0d66017d/tests/testthat/test-attributes.R#L110)

https://github.com/igraph/rigraph/blob/0931fa1698d8b832342a627dae9ad6ef0d66017d/tests/testthat/test-attributes.R#L66

**Comment by maelle** [comment]
I'll need a test case for 

https://github.com/igraph/rigraph/blob/0931fa1698d8b832342a627dae9ad6ef0d66017d/tests/testthat/test-closeness.R#L25

**Comment by maelle** [comment]
I'll need a test case for

https://github.com/igraph/rigraph/blob/087f84d43afc2b17c32a4eb5ae5d8b7fbcb4ca37/tests/testthat/test-scan.R#L107-L108

**Comment by szhorvat** [comment]
> # TODO: Hub and authority scores make little sense for undirected graphs

If the graph is connected, you can verify that HITS and eigenvector centrality return the same result. That would be a good test.

**Comment by maelle** [comment]
For the one below I will simply use the code from the example

https://github.com/igraph/rigraph/blob/087f84d43afc2b17c32a4eb5ae5d8b7fbcb4ca37/tests/testthat/test-iterators.R#L10

**Comment by maelle** [comment]
@szhorvat but for hits didn't we already improve the tests that use the `hits_scores()` function? If they aren't good enough yet could you please open an issue?

**Comment by maelle** [comment]
For the comment below I do not know what else to test and how

https://github.com/igraph/rigraph/blob/087f84d43afc2b17c32a4eb5ae5d8b7fbcb4ca37/tests/testthat/test-largest.cliques.R#L5

**Comment by maelle** [comment]
How:

https://github.com/igraph/rigraph/blob/087f84d43afc2b17c32a4eb5ae5d8b7fbcb4ca37/tests/testthat/test-largest.independent.vertex.sets.R#L14

**Comment by maelle** [comment]
also how:

https://github.com/igraph/rigraph/blob/087f84d43afc2b17c32a4eb5ae5d8b7fbcb4ca37/tests/testthat/test-minimal.st.separators.R#L7

**Comment by maelle** [comment]
I wonder what the expectation is supposed to be in:

https://github.com/igraph/rigraph/blob/087f84d43afc2b17c32a4eb5ae5d8b7fbcb4ca37/tests/testthat/test-get.all.shortest.paths.R#L48-L51

**Comment by maelle** [comment]
@szhorvat I am done looking for the TODOs in the test files, and for many of them I'll need some guidance, but there is no hurry.

**Comment by szhorvat** [comment]
> How:
> 
> https://github.com/igraph/rigraph/blob/087f84d43afc2b17c32a4eb5ae5d8b7fbcb4ca37/tests/testthat/test-largest.independent.vertex.sets.R#L14

Same comment as before. We can check that they are all the same size, but I don't think it's even feasible to check that they are largest/maximum. Checking that they are maximal should be feasible, but still some work. I'd leave it for now.

**Comment by szhorvat** [comment]
> also how:
> 
> https://github.com/igraph/rigraph/blob/087f84d43afc2b17c32a4eb5ae5d8b7fbcb4ca37/tests/testthat/test-minimal.st.separators.R#L7

You can check that a separator is minimal by:

 - Remove each vertex in turn and check that it is no longer a separator (`is_separator`)

**Comment by szhorvat** [comment]
> I wonder what the expectation is supposed to be in:
> 
> https://github.com/igraph/rigraph/blob/087f84d43afc2b17c32a4eb5ae5d8b7fbcb4ca37/tests/testthat/test-get.all.shortest.paths.R#L48-L51

No clue what this is. I suggest removal.

**Comment by maelle** [comment]
Thank you!

Done in https://github.com/igraph/rigraph/commit/132362fdee722ed8019ef55b29789d81f2c2caad
