### ISSUE TITLE
how to document graph_()?

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#1479]
it seems a bit different from `make_()` and `sample_()` but close. Any pointer @szhorvat?

**Comment by maelle** [comment]
Thank you!

**Comment by maelle** [comment]
https://github.com/search?q=lang%3Ar+graph_%28+NOT+repo%3Aigraph%2Frigraph+NOT+repo%3Afchauvel%2Ftrio&type=code

**Comment by maelle** [comment]
https://github.com/search?q=lang%3Ar+graph_%28+owner%3Acran&type=code

**Comment by krlmlr** [comment]
Only used by OptimalDesign?

**Comment by maelle** [comment]
yes!

**Comment by maelle** [comment]
should I email OptimalDesign maintainers telling them we might deprecate `graph_()`?

**Comment by krlmlr** [comment]
Yeah, let's start with a soft-deprecation.
