### ISSUE TITLE
cluster_spinglass crashes R when implementation='neg'

### ISSUE THREAD

**Issue by ntamas** [igraph/rigraph#151]
_From @brooksambrose on April 25, 2016 23:58_

Any command using the "negative" implementation of the spinglass community detection crashes R in RStudio, e.g. `cluster_spinglass(make_ring(10),implementation='neg')`.

I'm running:

`R version 3.2.4 (2016-03-10) -- "Very Secure Dishes"  
Platform: x86_64-apple-darwin13.4.0 (64-bit)`

_Copied from original issue: igraph/igraph#943_

**Comment by ntamas** [comment]
For the record: it does not happen if the `weights=...` argument is also specified, so this works:

```
> cluster_spinglass(make_ring(10), weights=1:10, implementation="neg")
```

Most likely the R interface fails to check whether there are any weights specified by the user; it should simply fall back to the default implementation if there are no weights.

**Comment by szhorvat** [comment]
If an unweighted graph is not allowed, that should probably be documented for the C core.  [Currently it isn't](http://igraph.org/c/doc/igraph-Community.html#igraph_community_spinglass) (or I didn't find it) and the `weights` parameter is explicitly allowed to be `NULL` according to the docs:

>  `weights` The vector giving the edge weights, it may be `NULL`, **in which case all edges are weighted equally**. Edge weights should be positive, altough this is not tested.

Are you sure this shouldn't be a C core bug?

**Comment by ntamas** [comment]
Gotcha, correct, I could reproduce it with the C core as well. Stay tuned.

**Comment by ntamas** [comment]
Fixed in https://github.com/igraph/igraph/commit/43f0f847047c73a958e8122271f862771b98b4e7
