### ISSUE TITLE
CRAN Fortran warning: Obsolescent feature: Old-style character length at (1)

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#1533]
Continuing from https://github.com/igraph/igraph/issues/551#issuecomment-2378114968

```
gfortran-14 -fvisibility=hidden -fpic  -g -O2 -mtune=native -Wall -pedantic  -c vendor/arpack/dmout.f -o vendor/arpack/dmout.o
vendor/arpack/dmout.f:34:19:

   34 |       CHARACTER*80       LINE
      |                   1
Warning: Obsolescent feature: Old-style character length at (1)
```

**Comment by szhorvat** [comment]
@krlmlr First, let me clarify that R/igraph bundles the original Fortran sources of ARPACK. These are not in C/igraph, only in R/igraph. Other high-profile projects do the same, for example SciPy.

> Do we patch in-place, or try to upstream?

There is no upstream, and I don't think changing these sources is a good idea.

As far as I can tell, this happens because Fedora's gfortran assumes a newer Fortran standard, which triggers this warning. It's merely a warning, not an error, and it is not reasonable for CRAN to require a change.

IMO, if they won't relent, the right approach here is to specify Fortran 90 as the standard, not to patch the source code.

**Comment by szhorvat** [comment]
> There is no upstream

To further clarify this, there's a fork, ARPACK-NG, _but_: (1) It is sufficiently divergent that IMO it is not a good idea to try to vendor their sources, (2) It still uses an older standard so this wouldn't be fixed.

ARPACK-NG is reasonable to use as an external dependency to link to, but we should not _require_ that, as it makes compilation difficult for many people.

**Comment by szhorvat** [comment]
Some more investigation:

 - Triggered by `-pedantic` (apparently added by CRAN)
 - Still warns with `-std=legacy` or `-std=f95`
 - Seems like `CHARACTER(LEN=80)` instead of `CHARACTER*80` is a safe fix.

I'll open a PR

**Comment by szhorvat** [comment]
For future reference, I looked for issues using

```
rg -i '^[^c].*character\\*[0-9]'
```

I'm going with `character foo*80` instead of the `len=` version. It's all old-style code anyway. Ref: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52101

**Comment by krlmlr** [comment]
I found https://github.com/opencollab/arpack-ng and https://bitbucket.org/chaoyang2013/arpack/src/master/ . SciPy seems to use arpack-ng.

I don't have a strong opinion here, but essentially we are maintaining our own fork of arpack now.

**Comment by szhorvat** [comment]
> SciPy seems to use arpack-ng.

That wasn't the case when I last checked. This must be new.

Well, I guess it's worth a try. Be sure to use 3.9.1, as 3.9.0 is buggy. All the parallel MPI stuff can be dropped.

**Comment by szhorvat** [comment]
I looked at arpack-ng a bit more. I think it's feasible to vendor their sources, but it'll not be little work. We also need to prefix all arpack functions with `igraph` to avoid conflict with an external arpack that could be loaded into the same R process.
