### ISSUE TITLE
`as.undirected()` does not retain `edge.attr.comb = `

### ISSUE THREAD

**Issue by jhollway** [igraph/rigraph#1535]
### What happens, and what did you expect instead?

The soft deprecated `as.undirected()` does not retain the `edge.attr.comb = ` argument that it previously had.

### To reproduce

In igraph >v2.1.0, `as.undirected(graph, edge.attr.comb = "first")`

**Comment by szhorvat** [comment]
Just noting that I'd consider this a pretty serious issue, the fix to which ought to be released ASAP.

**Comment by maelle** [comment]
I am so sorry, thanks so much for catching this @jhollway!

@krlmlr PR coming in a few minutes once I've been able to run `document()` :smile_cat:
