### ISSUE TITLE
Error installing Igraph on mac

### ISSUE THREAD

**Issue by anudeepchimakurthi** [igraph/rigraph#158]
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [CHOLMOD/Check/cholmod_check.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/usr/local/lib/R/3.3/site-library/igraph’
Warning in install.packages :
  installation of package ‘igraph’ had non-zero exit status

**Comment by gaborcsardi** [comment]
You'll need to provide more details, so that we can reproduce this.
