### ISSUE TITLE
assortativity() with missing data

### ISSUE THREAD

**Issue by jebrug** [igraph/rigraph#1585]
In empirical data, there are usually missing values, i.e., cells in the data.frame with vertex value NA. Could assortativity() be programmed to produce output even with some missing vertex values, and a warning about their number of occurrence?

**Comment by szhorvat** [comment]
igraph won't support missing values beyond storing them. Calculations with them won't be supported. The reasons for this are:

 - igraph is a multi-language package and not all languages support `NA`.
 - More importantly, it is unclear how missing values should even be treated when calculating various network measures. There are multiple possible interpretations, and no one-size-fits approach. Defining and implementing some of these approaches is a research-level problem.

Thus, you need to decide yourself how you want to handle these cases. Do you just want to drop these values? Then you could delete the corresponding vertices and compute assortativity afterwards.  Or, given that assortativity is just correlation, you can use R's `cov()`, which has 5 different methods to handle missing value—another decision to be made.

**Comment by jebrug** [comment]
Thanks for your reply!
