### ISSUE TITLE
Error with gclust.app and gclust.rsvt

### ISSUE THREAD

**Issue by wjmaddox** [igraph/rigraph#162]
Gclust.app and gclust.rsvt do not work with either lists of igraph objects or igraph objects. 

This issue seems to be due to faulty matrix multiplication at the beginning of the source code for these functions.

``` r
library("igraph")

test.graph <- make_graph("Zachary")
class(test.graph)
#"igraph"

gclust.app(test.graph, r=3)
#Error in colSums(Xorigin) : 
#'x' must be an array of at least two dimensions

gclust.app(list(test.graph), r=3)
#Error in Xorigin %*% solve(diag(colSums(Xorigin))) : 
#  non-conformable arguments

gclust.rsvt(test.graph, r=3)
#Error in colSums(Xorigin) : 
#  'x' must be an array of at least two dimensions

gclust.rsvt(list(test.graph), r=3)
#Error in Xorigin %*% solve(diag(colSums(Xorigin))) : 
#  non-conformable arguments
```

Additionally, in neither function are there any examples in the documentation.

**Comment by szhorvat** [comment]
It seems these functions were removed in 126176a287b58d94db18b840aecffe53f1164537 for 1.2.0, closing.
