### ISSUE TITLE
config.status: creating src/config.h error

### ISSUE THREAD

**Issue by saramelvin** [igraph/rigraph#163]
I'm trying to install the igraph library but I keep getting errors.

I tried install.packages("igraph"), install.packages("igraph", type = "source"), and install.packages("igraph", type = "source", repos = "http://cran.case.edu" ) where all of them have output errors are as follows:

config.status: creating src/config.h
libs
Error in if (nzchar(SHLIB_LIBADD)) SHLIB_LIBADD else character() : 
  argument is of length zero
removing ‘/usr/local/lib/R/site-library/igraph’
restoring previous ‘/usr/local/lib/R/site-library/igraph’
Warning in install.packages :
  installation of package ‘igraph’ had non-zero exit status

The downloaded source packages are in
    ‘/private/var/folders/mg/jzr9rnlj14jf96jx_cywh0mw0000gn/T/RtmpiHVrm3/downloaded_packages’

---

I can't even install the devtools because of a similar error.
## Error 1

installing _source_ package ‘mime’ ...
package ‘mime’ successfully unpacked and MD5 sums checked libs
Error in if (nzchar(SHLIB_LIBADD)) SHLIB_LIBADD else character() : 
  argument is of length zero
removing ‘/usr/local/lib/R/site-library/mime’
Warning in install.packages :
  installation of package ‘mime’ had non-zero exit status
## Error 2

installing _source_ package ‘curl’ ...
package ‘curl’ successfully unpacked and MD5 sums checked
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-lcurl
libs
Error in if (nzchar(SHLIB_LIBADD)) SHLIB_LIBADD else character() : 
  argument is of length zero
- removing ‘/usr/local/lib/R/site-library/curl’
## Error 3

Using PKG_LIBS=-L/usr/local/opt/openssl/lib -lssl -lcrypto
libs
Error in if (nzchar(SHLIB_LIBADD)) SHLIB_LIBADD else character() : 
  argument is of length zero
removing ‘/usr/local/lib/R/site-library/openssl’
## Error 4

installing _source_ package ‘jsonlite’ ...
package ‘jsonlite’ successfully unpacked and MD5 sums checked
libs
Error in if (nzchar(SHLIB_LIBADD)) SHLIB_LIBADD else character() : 
  argument is of length zero
removing ‘/usr/local/lib/R/site-library/jsonlite’
Warning in install.packages :
  installation of package ‘jsonlite’ had non-zero exit status
## Error 5

config.status: creating src/Makevars
libs
Error in if (nzchar(SHLIB_LIBADD)) SHLIB_LIBADD else character() : 
  argument is of length zero
removing ‘/usr/local/lib/R/site-library/git2r’
## Error 6

`rigraph ...$ make`
make: **\* No rule to make target `cigraph/interfaces/functions.def', needed by`R/auto.R'.  Stop.
## ????

What is this error and how do I fix this?

**Comment by mbojan** [comment]
Seems like something is fundamentally non-standard with your setup... Not really specific to igraph.
