### ISSUE TITLE
cannot compile rigraph on a w8 64-bit machine

### ISSUE THREAD

**Issue by emilBeBri** [igraph/rigraph#165]
Hi,

I can install "gaborcsardi/pkgconfig"  just fine, but "igraph/rigraph" doesn't work. I need it because I'm using an experimental package that requires this version of igraph. I get the following error:

```
compilation terminated.
make: *** [foreign-graphml.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.1/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-33~1.1/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="igraph.dll" SHLIB_LIBADD='$(FLIBS)' WIN=64 TCLBIN=64 ' havde status 2
ERROR: compilation failed for package 'igraph'
* removing 'C:/Users/emil/Documents/R/win-library/3.3/igraph'
Error: Command failed (1)
```

NOTE! the line "Warning: running command" in the code is translated by myself, since this was in my OS language which is danish.  I think it is an accurate translation, but the wording _might_ be slightly different.

I'm on a 64-bit Windows. I also have Lubuntu 16.04 installed on the same machine, and there I don't have any problems with the install. I need to use the package on a windows machine, unfortunately.

I also asked this question on stack.exchange:
http://stackoverflow.com/questions/39100821/cant-compile-beta-version-of-igraph-from-github

**Comment by ntamas** [comment]
More than five years have passed since this issue has been posted and the compilation now seems to work fine even from the Github master, so closing this. Feel free to reopen if the issue persists.
