### ISSUE TITLE
$ operator 

### ISSUE THREAD

**Issue by ttriche** [igraph/rigraph#168]
I wrote a one-liner to add $ support for igraph.  Is this reasonable?

```
`$.igraph` <- function(x, i, ...) induced_subgraph(x, ego(x, 1, i)[[i]])
```

If so I have a PR ready: https://github.com/igraph/rigraph/pull/167

**Comment by mbojan** [comment]
Is this reasonable? `$` is used to access graph attributes.

**Comment by gaborcsardi** [comment]
Yes, I am afraid that we `already` use `$` for something else. If you want an operator for `ego` you need to choose another one, or create your own via `%ego%`.

**Comment by ttriche** [comment]
Oh, that works.  Maybe something like %neighbors% instead?



--t

**Comment by ttriche** [comment]
Alright I updated my pull request to call it %around%, i.e. around.igraph(g, v) == g %around% v. 

%ego% didn't seem like the best choice because the ego() function doesn't return a graph.

**Comment by mbojan** [comment]
How is it different from `make_ego_graph`?

Moreover, and this is just an opinion of a long-time user:

I do not like such use of binary operators in R too much. That is, creating an operator, say `%operator%`, such that it only makes sense to call  `x %operator% y`, but not `y %operator% x` for specific `x` and `y`. Why not just write a function `operator()`. If you really want just the "sequential" syntax, you could call it with **magrittr** pipe, provided that `operator()` accepts igraph object as the first argument, i.e.:

```r
graph %>% operator(i)
```

Thats about the same amount of characters that you need to type-in.

**Comment by ttriche** [comment]
of course most of the time that's exactly how an operator is implemented,
e.g.

```
around.igraph <- function(x, i) induced_subgraph(x, ego(x, 1, i)[[i]])
```
```
"%around%" <- function(x, y) around.igraph(x, y)
```

I've only been using R since around 2005, not from the beginning, but this
is a pretty pervasive pattern.  x %>% around(y) is pretty similar to x
%around% y, the latter is just syntactic sugar.


--t

On Wed, Sep 14, 2016 at 5:39 AM, Michał Bojanowski <notifications@github.com
