### ISSUE TITLE
Dynamic node size masks arrows plot.igraph

### ISSUE THREAD

**Issue by aterhorst** [igraph/rigraph#169]
There is no default clip to edge of variable/dynamic vertex in directed graph. 

`cols` <- colorRampPalette(c("light green", "yellow","orange","red","lightblue","violet","pink", "aquamarine"))(7)
plot(explicit.knowledge.net, edge.arrow.size = 2, 
     vertex.color = cols[node_attrib], 
     vertex.size = V(G)$degree,
     vertex.label.cex = 4, 
     vertex.label = V(G)$label,
     edge.color = "black",
     layout = save_layout)
title("Network", cex.main = 10)`

**Comment by mbojan** [comment]
I can't reproduce it using `igraphdata::karate` network. Also, you are using different object for plotting (`explicit.knowledge.net`) and attributes (`G`). Is that intentional?

**Comment by aterhorst** [comment]
Thanks for the prompt response Michel. I forgot to replace the one instance of (explicit.knowledge.net<http://explicit.knowledge.net>) with (G). Apologies for this typo error.

V(G)$Degree returns an integer value. I am encountering this error when resizing node size using attributes with floating point values e.g. V(G)$constraint. iGraph has a function that computes Burt's constraint measure. The result is a floating point number between 0 and 1.

I resize nodes as thus: vertex_size = 1 / V(G)$constraint * 10. Perhaps this is why I am encountering difficulties? I will try vertex_size = as.int(1 / V(G)$constraint * 10)).  Will report back.

Apologies for not be more specific about what I am doing.



Sent from my iPad

On 16 Sep 2016, at 9:42 PM, Micha? Bojanowski <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't reproduce it using igraphdata::karate network. Also, you are using different object for plotting (explicit.knowledge.net<http://explicit.knowledge.net>) and attributes (G). Is that intentional?

-

**Comment by aterhorst** [comment]
Tried as.integer trick. Did not work :-(

**Comment by mbojan** [comment]
Vertex size AFAIK does not have to be an integer.

**Comment by aterhorst** [comment]
Thanks. I specified a too small arrow size for my plot device.  What is visible on one device disappears on another. One has to adjust scaling according to device used, it seems. Thanks for responding to my request for help. I am enjoying iGraph immensely.  I have been playing around with ggnet/ggnetwork but neither has cracked the arrow clipping to vertex shape edge problem as well as iGraph manages to do.
