### ISSUE TITLE
Catching warning thrown by `topological.sort()` a cyclic graph causes core dump

### ISSUE THREAD

**Issue by ngr-t** [igraph/rigraph#178]
Dear igraph maintainers,
I tried to catch warning `topological.sort()` throws when a cyclic graph is passed to it by `tryCatch()`, but it caused core dump.

Code to reproduce:
```R
library(igraph)

# This has a cycle
adjacency_with_cycle <- matrix(c(
  0,1,0,
  1,0,0,
  0,1,0), 3, 3)
g_with_cycle <- graph_from_adjacency_matrix(adjacency_with_cycle)


# This doesn't
adjacency_without_cycle <- matrix(c(
  0,1,0,
  0,0,0,
  0,1,0), 3, 3)
g_without_cycle <- graph_from_adjacency_matrix(adjacency_without_cycle)

# Code below moves
## Only warns on the graph with cycle.
topological.sort(g_with_cycle)

## No problem on the acyclic graph.
topological.sort(g_without_cycle)

## Call in tryCatch, but no warning
tryCatch({
  topological.sort(g_without_cycle)
  },
  warning = function (w) stop())

# Code with the problem
# Core dumped when catching warning
tryCatch({
  topological.sort(g_with_cycle)
  },
  warning = function (w) stop())
```
The error happens also on using `options(warn=2)` to turn the warning into an error.

This happens on both dev version and stable release. And I tried each on both Windows and Linux.

**Comment by gaborcsardi** [comment]
Thanks! Yes, unfortunately the igraph cleanup is messed up, and it fails every time you catch a warning (or maybe even on error).

I'll try to fix this soon.

**Comment by gaborcsardi** [comment]
As a workaround, you can just check the result of `topological.sort`, instread of catching the warning. If it is shorter than the number of vertices, then the graph is not a DAG.

**Comment by ngr-t** [comment]
Thank you for rapid response!
I do check the length of result for the present.

**Comment by szhorvat** [comment]
Just noting that in the latest C core (to become 0.9) passing in a graph that is not acyclic results in an error, not a warning. This won't make it into the next release of the R interface (as that will be based off 0.8).
