### ISSUE TITLE
graph.difference does not work properly with self loops

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/rigraph#18]
_From @rupea on March 12, 2014 19:19_

 In R (igraph_0.6.6), when calling graph.difference(g1,g2) if g1 has a self loop that is not present in g2, the self loop is added twice to the resulting graph. 

_Copied from original issue: igraph/igraph#597_

**Comment by gaborcsardi** [comment]
It is still happening in `0.7.0`:

```
g <- graph.ring(10) + edge(1,1)
g
# IGRAPH U--- 10 11 -- Ring graph
# + attr: name (g/c), mutual (g/x), circular (g/x)
g2 <- graph.ring(5)
str(g-g2)
# IGRAPH U--- 10 8 -- Ring graph
# + attr: name (g/c), mutual (g/x), circular (g/x)
# + edges:
# [1] 1--10 1-- 1 1-- 1 5-- 6 6-- 7 7-- 8 8-- 9 9--10
```

**Comment by clpippel** [comment]
It is still happening in ‘1.2.5’.

**Comment by ntamas** [comment]
Still exists in 1.2.6.

**Comment by szhorvat** [comment]
Seems to be fine in 1.3.0, but I can't find when/how this was fixed. Any recollection @ntamas?

**Comment by ntamas** [comment]
I think this was fixed simply by updating the C core. I remember this way buggy in the C core as well.
