### ISSUE TITLE
arrow.mode (and other edge-plotting properties) don't do anything

### ISSUE THREAD

**Issue by Lcarey** [igraph/rigraph#185]
Hi, 
I've tried both 1.0.1 (CRAN) and igraph_1.1.0  (github) , and I can't change the plotting behaviour for edges. I'd to not show arrows, but I still get arrows on edges w/the following code : 

mygraph <- graph_from_edgelist(  rbind(c(1,2) , c(2,3) ) )
plot(mygraph , arrow.mode='-')

(following instructions here: http://igraph.org/r/doc/plot.common.html )

-Lucas

sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.12.4 (Sierra)

**Comment by gaborcsardi** [comment]
From the website that you cite:

> Parameters for vertices start with prefix ‘vertex.’, parameters for edges have prefix ‘edge.’, and global parameters have no prefix. Eg. the color of the vertices can be given via argument vertex.color, whereas edge.color sets the color of the edges. layout gives the layout of the graphs.

So, you'll need `edge.arrow.mode`.
