### ISSUE TITLE
dominator_tree() does not return -1 for root

### ISSUE THREAD

**Issue by ntamas** [igraph/rigraph#186]
_From @nick-ulle on April 17, 2017 21:22_

Contrary to the documentation, the `dom` field of the output from `dominator_tree()` does not include a -1 as the immediate dominator of the root vertex.

Including a sentinel value for the root (or treating the root as its own immediate dominator) is useful because otherwise the indexes of `dom` will be off by one compared to the vertices of the original graph.

Minimal example:
```r
g = make_empty_graph() + vertices("A", "B", "C")
g = g + edges(c("B", "A", "B", "C"))

dom = dominator_tree(g, "B")$dom
# Now the immediate dominator for "C" (index 3 in g) is at index 2
```
It would be even better if `dom` retained the names of the vertices.

_Copied from original issue: igraph/igraph#985_

**Comment by szhorvat** [comment]
It seems that this function now returns vertex names, but the docs need to be updated.

**Comment by ntamas** [comment]
The output is still problematic; the internal dominator tree function probably returns the correct numeric vector in `$dom` now (it comes directly from the C core), but then it is piped through `create_vs()`, which does not know what to do with the -1 value that indicates the original root so it leaves it out.

**Comment by szhorvat** [comment]
It's not the only C function that uses -1 or NaN to represent non-valid vertex IDs. I think BFS/DFS do it as well, and `get_shortest_paths()` use it its predecessors vector. It was discussed here as well: https://github.com/igraph/igraph/issues/1880

**Comment by ntamas** [comment]
Yes, that's why the `predecessors` vector is typed as `VECTOR_INT` in `functions.yaml` and not as a `VERTEXSET`. Unfortunately the typing for the `dom` output argument `dominator_tree()` is wrong; it is typed as a `VERTEXSET` so the generated function tries to translate. We probably need to fix this in `functions.yaml`.

**Comment by szhorvat** [comment]
This is a somewhat related complaint about inconsistent representations of vertex sequences: https://github.com/igraph/rigraph/issues/188 

But indeed, when we represent a tree through a predecessor list (a common situation) the current vertex sequence object does not seem to be sufficient. This affects so many functions that I'm not sure messing with it for 1.3.1 is a good idea.

**Comment by ntamas** [comment]
Well, the current result is downright incorrect so I'd consider this as a bugfix for `dominator_tree`. I'm not sure how many other places are affected, but if we change the type of the `dom` argument in `functions.yaml`, that should be a local change that does not trickle down to any other places in the library.

**Comment by szhorvat** [comment]
> Yes, that's why the `predecessors` vector is typed as `VECTOR_INT` in `functions.yaml` and not as a `VERTEXSET`. Unfortunately

It is still somehow converted into a vertex sequence object, try this:

```
> set.seed(1234)
> g <- sample_gnm(10,20)
> shortest_paths(g,1,predecessors = T)$predecessors
+ 10/10 vertices, from 08d95cf:
 [1] 1 1 1 1 7 4 2 2 2 1
```

The predecessor vector here contains not -1 for the root, but the same value as the vertex's ID. That's not a very nice choice IMO and I would not want to go forward with the C core returning this. It is also inconsistent with other uses where trees are returned in a predecessor representation.

**Comment by ntamas** [comment]
We might need a separate abstract type in `types.yaml` for vectors that aim to represent a tree. `VERTEX_INDEX` (which I use for vectors that contain vertex indices from 0.10 onwards) is not suitable because we need to treat -1 specially: when converting a `VERTEX_INDEX` vector in R, we need to add 1 (because R is 1-based), but we cannot do that for -1. Well, actually, we could, but here's the problem:

```
> names <- LETTERS[1:5]
> names[c(1, 2, 0, 3)]
[1] "A" "B" "C"
```

R silently ignores zero in an index vector. For -1 we at least get an error, although not quite intuitive:

```
> names[c(1, 2, -1, 3)]
Error in names[c(1, 2, -1, 3)] :
  only 0's may be mixed with negative subscripts
```

What's even worse is this one:

```
> names[-1]
[1] "B" "C" "D" "E"
```

which holds because `-1` means "return everything except the first one". The correct solution in R-land is this:

```
> names[c(1,2,NA,3)]
[1] "A" "B" NA  "C"
```

so, when converting a tree representation in R, we need to replace `-1` with `NA` first to make the result work nice with indexing into a name vector.

**Comment by ntamas** [comment]
> The predecessor vector here contains not -1 for the root, but the same value as the vertex's ID. That's not a very nice choice IMO

I think this was done exactly because of the R interface where we can safely convert such a vector into an `igraph.vs` object while we cannot do so if we have -1 or NaN or anything fancy in the vector. I know that this is a misuse of `igraph.vs` because the predecessors vector is still not a vertex _sequence_ or _selector_; however, since this requires changes in the C core and probably cause breakage for people using igraph from R, we cannot fix this earlier than R-igraph 2.x

Anyway, let's get it sorted out in the C layer such that all tree-like representations are consistent, and then we can follow up in R when the time comes.

**Comment by szhorvat** [comment]
`bfs()` in R is basically broken, and mostly unusable for solving real problems. I can be convinced otherwise once someone shows be how to implement a Strahler number calculation with it ;-) I spent a couple of hours trying to do that for [this SO question](https://stackoverflow.com/q/70257375/695132), but failed. 

This is why I doubt that making big changes to `bfs()` will cause trouble downstream. Is anyone actually using this function successfully?

**Comment by ntamas** [comment]
Well, I don't know what Strahler numbers are so I wouldn't attempt an implementation, but if your only problem is that the predecessors vector contains a "loop edge" for the root, you can fix that easily with:

```
v <- as.vector(shortest_paths(...)$predecessors)
v[v == 1:vcount(g)] <- NA
```

It could be that there are deeper problems with `bfs()`, but then these should be fixed separately. `tidygraph` happens to wrap `bfs` from igraph in its own `bfs_` functions so there's definitely some value in it in its current form to the community and we should not take it lightly to change what it returns.

**Comment by szhorvat** [comment]
As I recall, the biggest problem was that NA breaks everything: most operations on the vertex sequence fail as soon as they see a NA, to the point that I can't even include an `is.na` check. Let's discuss this in chat.

**Comment by ntamas** [comment]
An escape hatch is to set `igraph_options(return.vs.es=FALSE)` and then you would get ordinary R vectors in the results instead of `igraph.vs` objects, and then you can do whatever you want with it.

To be honest I don't really like the idea of having global options that tweak the behaviour of a package, but it's likely here to stay as this is also something that people tend to use.
