### ISSUE TITLE
calculate weighted degree distributions

### ISSUE THREAD

**Issue by rafapereirabr** [igraph/rigraph#189]
The `igraph` library is a great contribution to network analysis in R. However, it does not have a function to calculate weighted degree distributions. This has been mentioned in a [question in SO](http://stackoverflow.com/questions/8344565/how-do-i-calculate-weighted-degree-distributions-with-igraph-in-r) and the author of the questions has proposed a simple modification to `degree.distribution` function to create an equivalent function that takes into account the weight of the edges: 

```
graph.strength.distribution <- function (graph, cumulative = FALSE, ...)
{
  if (!is.igraph(graph)) {
    stop("Not a graph object")
  }
  # graph.strength() instead of degree()
  cs <- graph.strength(graph, ...)
  hi <- hist(cs, -1:max(cs), plot = FALSE)$density
  if (!cumulative) {
    res <- hi
  }
  else {
    res <- rev(cumsum(rev(hi)))
  }
  res
}
```

It would be a good idea to incorporate this function in the next version of the `igraph` package.

**Comment by szhorvat** [comment]
I would vote against including this feature.

Even the case for `degree_distribution()` is weak, as it is only a thin wrapper for `hist()`, which is easy enough to use directly. The best binning for degrees depends on the graph. Many real-world networks have a heavy-tail degree distribution, which means that logarithmic binning works best. Thus, in most practical use cases it will be necessary to adjust the binning anyway, which makes a `strength_distribution` function not much more convenient than a combination of `strength` and `hist`.

One argument for including `degree_distribution()` as a convenience function is that it is a fairly common use case to want to use integer binning for small graphs or for graphs with small degrees (e.g. certain kinds of spatial networks). This is exactly what `degree_distribution()` does: it ensures integer binning.

Unlike for degrees, integer binning (as in the example code above) makes no sense for strength values.

@ntamas @vtraag Opinions? Agree to close?

**Comment by ntamas** [comment]
I agree with @szhorvat; however, if someone could propose a sort-of semi-automatic method for selecting appropriate bin sizes in weighted networks that has some scientific basis (maybe references), we could reconsider and implement that method in `strength_distribution()`.

**Comment by szhorvat** [comment]
`hist` already has various automatic methods implemented. See string or function values to `breaks`. I am not sure if there is anything specific to networks, or any reasoning for doing this differently for networks vs other datasets.

What's commonly needed in a network science context is logarithmic binning. A simple way is to just take the logarithm of the data. Another more sophisticated way is to increase bin sizes according to a log rule. This latter could be implemented through an option.
