### ISSUE TITLE
graph.dfs and graph.bfs in R package pass 0-based index to callback function

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/rigraph#19]
_From @djhshih on March 22, 2014 1:28_

In the R interface, graph.dfs and graph.bfs seem to be passing 0-based indices to the callback function instead of 1-based indices.
The results returned by the function uses 1-based indexing.

> library(igraph)
> sessionInfo()
R version 3.0.2 (2013-09-25)
Platform: x86_64-unknown-linux-gnu (64-bit)
...
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base  
other attached packages:
[1] igraph_0.7.0

> f <- function(graph, data, extra) print(data); 
> g <- graph.tree(10);
> tmp <- graph.dfs(g, root=1, "out", in.callback=f);
 vid dist 
   0    0
 vid dist
   1    1
 vid dist
   3    2
 vid dist
   7    3
 vid dist
   8    3
 vid dist
   4    2
 vid dist 
   9    3 
 vid dist 
   2    1 
 vid dist 
   5    2 
 vid dist
   6    2

> tmp
...
$order
 [1]  1  2  4  8  9  5 10  3  6  7
...

_Copied from original issue: igraph/igraph#601_

**Comment by gaborcsardi** [comment]
Thanks. Yes, I know, because the callbacks are called from C which uses 0-based indexing. We could always add one to the results, but this would make the callbacks much slower. Although maybe they are already slow, so it does not matter much. 

In any case, this should be either fixed, or at least documented. Thanks!

**Comment by ntamas** [comment]
The example above crashes my R session now:

```
> f <- function(graph, data, extra) print(data)
> g <- graph.tree(10)
> tmp <- graph.dfs(g, root=1, "out", in.callback=f)
 vid dist
   0    0
Error in graph.dfs(g, root = 1, "out", in.callback = f) :
  LOGICAL() can only be applied to a 'logical', not a 'double'

 *** caught segfault ***
address 0x0, cause 'unknown'

Traceback:
 1: .Call(C_R_igraph_finalizer)
 2: graph.dfs(g, root = 1, "out", in.callback = f)
```

**Comment by ntamas** [comment]
This seems to work correctly now; this is the output of the example from the documentation of `graph.dfs`:

```
> f.in <- function(graph, data, extra) {
+        cat("in:", paste(collapse=", ", data), "\n")
+        FALSE
+      }
>      f.out <- function(graph, data, extra) {
+        cat("out:", paste(collapse=", ", data), "\n")
+        FALSE
+      }
>      tmp <- dfs(make_tree(10), root=1, "out",
+                       in.callback=f.in, out.callback=f.out)
in: 1, 0
in: 2, 1
in: 4, 2
in: 8, 3
out: 8, 2
in: 9, 3
out: 9, 2
out: 4, 1
in: 5, 2
in: 10, 3
out: 10, 2
out: 5, 1
out: 2, 0
in: 3, 1
in: 6, 2
out: 6, 1
in: 7, 2
out: 7, 1
out: 3, 0
out: 1, -1
```
