### ISSUE TITLE
When will the next CRAN igraph be released?

### ISSUE THREAD

**Issue by XiaomoWu** [igraph/rigraph#190]
I'm not sure if this the right place to ask this question, but the last CRAN igraph was nearly two years ago and I noticed there have been some changes in its GitHub development version. I love igraph and believe it's in healthy condition, however, for a new R user who's looking for his social network analysis tools, a package which hasn't been updated for two years may cause him to think this package is "dead".

**Comment by gaborcsardi** [comment]
It was.
