### ISSUE TITLE
arpack hangs on current CRAN windows builds

### ISSUE THREAD

**Issue by mvanins** [igraph/rigraph#192]
There's an issue with the current [r-devel](https://cran.r-project.org/bin/windows/contrib/3.5/igraph_1.0.1.zip) (3.5) and [r-release](https://cran.r-project.org/bin/windows/contrib/3.4/igraph_1.0.1.zip) (3.4) windows builds of the package.

The arpack function hangs on both the 64-bit 3.4 and 3.5 builds, but works fine on the [oldrel ](https://cran.r-project.org/bin/windows/contrib/3.3/igraph_1.0.1.zip) (3.3) build. All work in a 32-bit environment.

> sessionInfo()
R version 3.4.0 Patched (2017-05-10 r72669)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

**Comment by gdkrmr** [comment]
i can confirm that

to reproduce (taken from the diffusionMap::diffuse example), the following code works under Linux, but crashes R on Windows R 3.4.0
I tried to rebuild igraph on Windows, but ran into some issues with missing libraries.

```R
library(diffusionMap)
library(Matrix)
library(igraph)

n=2000
t=runif(n)^.7*10
al=.15;bet=.5;
x1=bet*exp(al*t)*cos(t)+rnorm(n,0,.1)
y1=bet*exp(al*t)*sin(t)+rnorm(n,0,.1)
plot(x1,y1,pch=20,main="Noisy spiral")
D = dist(cbind(x1,y1))

eps.val = epsilonCompute(D)
neigen = 10
t = 0
maxdim = 50
delta=10^-5

start = proc.time()[3]
D = as.matrix(D)
n = dim(D)[1]
K = exp(-D^2/(eps.val))
v = sqrt(apply(K, 1, sum))
A = K/(v %*% t(v))
ind = which(A > delta, arr.ind = TRUE)
Asp = Matrix::sparseMatrix(i = ind[, 1], j = ind[, 2], x = A[ind], 
                   dims = c(n, n))
f = function(x, A = NULL) {
  as.matrix(A %*% x)
}
cat("Performing eigendecomposition\n")
if (is.null(neigen)) {
  neff = min(maxdim + 1, n)
} else {
  neff = min(neigen + 1, n)
}

decomp = igraph::arpack(
  f, extra = Asp, sym = TRUE, 
  options = list(
    which = "LA", nev = neff, 
    n = n, ncv = max(min(c(n, 4 * neff)))
  )
)
```

**Comment by gaborcsardi** [comment]
Try the `igraph_1.1.0.zip` file from here: https://github.com/igraph/rigraph/releases/tag/v1.1.0

**Comment by gaborcsardi** [comment]
I think this should be fixed by the new version on CRAN, 1.1.2.

**Comment by mvanins** [comment]
Confirmed that this is fixed in both the latest [release](https://cran.r-project.org/bin/windows/contrib/3.4/igraph_1.1.2.zip) version on CRAN and the 1.1.0 compiled linked above.

**Comment by gaborcsardi** [comment]
@mvanins Thanks!
