### ISSUE TITLE
eigen_centrality{igraph} crashes R

### ISSUE THREAD

**Issue by rafapereirabr** [igraph/rigraph#195]
Question opened in SO: [http://stackoverflow.com/questions/44085452/eigen-centralityigraph-crashes-r](http://stackoverflow.com/questions/44085452/eigen-centralityigraph-crashes-r) :

I am trying to use the eigen_centrality{igraph} to calculate the Eigenvector Centrality scores of the nodes in a network. Every time I run the command, though, Rstudio crashes. I've also tried this in plain R but it crashes as well.

I am using Windows 10. I've already tried reinstalling the library without success.
```
library(igraph)

# sample graph
  g <- sample_gnp(10, 2/10); E(g)$weight <- runif(ecount(g))

# get eigen centrality
  eigen <- eigen_centrality(g, directed = T, weights = E(g)$weight, scale = T)
```

It also crashes when I use the example provided in the library documentation
```
# Generate some test data
  g <- make_ring(10, directed=FALSE)

# Compute eigenvector centrality scores
  eigen_centrality(g)
```

**Comment by jtfeld** [comment]
I'm certainly not an authority on the technical issues here, but wanted to chime in to say that I'm experiencing the same problem (R v 3.4.0, Windows 10, igraph v 1.0.1).  Other measures of centrality work just fine, but eigen_centrality() crashes R.  

I thought it might be helpful to note that cluster_leading_eigen() similarly crashes R, while other methods of community detection do not do so.  This also crashes even when using the example from the library documentation:

`g <- make_full_graph(5) %du% make_full_graph(5) %du% make_full_graph(5)
g <- add_edges(g, c(1,6, 1,11, 6, 11))
lec <- cluster_leading_eigen(g)
lec`

Perhaps these issues are connected?

**Comment by basiliomp** [comment]
Hi there!

Here another user affected by the same issue. I am running R on Windows10 as well. This behaviour seems to affect several functions from the igraph package (eigen_centrality , pagerank, and authority.score for sure). As @rafapereirabr , I tried uninstalling the package and setting it up in a fresh install without success. 
This faulty behaviour was present in both R x64 3.4.0 and R i386 3.4.0.

Regards,
Basilio.

**Comment by gaborcsardi** [comment]
Try the `igraph_1.1.0.zip` file from here: https://github.com/igraph/rigraph/releases/tag/v1.1.0

**Comment by gaborcsardi** [comment]
This is fixed by the new version, 1.1.2.

**Comment by rafapereirabr** [comment]
thank you, @gaborcsardi !

**Comment by theclue** [comment]
I know this is supposed to be fixed, but i'm still suffering the bug on macOS, v1.2.1

to reproduce:

`igraph::eigen_centrality(igraph::make_ring(10, directed=FALSE))`

My [env setup](https://gist.github.com/theclue/c5c9a479e239058321973d9ec2fe7787)

**Comment by TwlyY29** [comment]
I am still suffering the bug as well using @theclue's example and igraph v.1.2.4 under Linux...
