### ISSUE TITLE
CRAN build fails on solaris

### ISSUE THREAD

**Issue by ntamas** [igraph/rigraph#208]
_From @wlandau-lilly on July 20, 2017 13:52_

Some [CRAN checks for igraph](https://cran.r-project.org/web/checks/check_results_igraph.html) are failing. Specifically, v1.1.1 does not install on the Solaris server, which is [breaking the checks for drake](https://cran.r-project.org/web/checks/check_results_drake.html) and other packages.

_Copied from original issue: igraph/igraph#1017_

**Comment by gaborcsardi** [comment]
If you use Solaris, then maybe you can help us fix it?

**Comment by wlandau-lilly** [comment]
I will try. Time permitting, I would like to spin up a VM and dive in.

**Comment by wlandau-lilly** [comment]
I cannot guarantee anything, however. I have never actually used Solaris, and this will be my first time digging into `igraph` internals.

**Comment by wlandau-lilly** [comment]
Thanks @gaborcsardi for 74beb96b5fd20b93dd3b4141915b7682ed019464. I saw the checks point to `func=va_arg(ap, void (*)(void));`, but my C is already a little rusty, and I do not yet have access to Solaris.

**Comment by gaborcsardi** [comment]
No worries, I submitted it to CRAN, hopefully it'll be ok.

**Comment by wlandau-lilly** [comment]
Confirmed: only one NOTE on CRAN for Solaris. The CRAN checks for my own stuff pass now. Thanks again!
