### ISSUE TITLE
Can't compile with rtools / Instructions for source incomplete

### ISSUE THREAD

**Issue by 00joshi** [igraph/rigraph#210]
Given the error in igraph 1.0.1 with eigen-centrality, I tried installing the 1.1.1 from source on Windows 10 (when is the windows binary supposed to be released?). The approach failed with a missing dependence on libxml2.

rtools does not include libxml2 - where do I get that from?

**Comment by gaborcsardi** [comment]
> when is the windows binary supposed to be released?

On CRAN? I don't know, that's not up to me.

> where do I get that from?

https://www.google.com/search?q=libxml2+windows
