### ISSUE TITLE
Build failure related to uuid/gen_uuid.c - Due to changes to net/if.h?

### ISSUE THREAD

**Issue by rohan-shah** [igraph/rigraph#212]
Compilation of r/igraph on the travis build system has started failing for me. I get the following error:

uuid/gen_uuid.c: In function ‘get_node_id’:
uuid/gen_uuid.c:152:15: error: storage size of ‘ifr’ isn’t known
  struct ifreq ifr, *ifrp;
               ^
uuid/gen_uuid.c:153:16: error: storage size of ‘ifc’ isn’t known
  struct ifconf ifc;

I suspect this is due to changes to the header <net/if.h>. In this case it seems to no longer define `struct ifreq`. A possible cause is this change: https://github.com/torvalds/linux/commit/4a91cb61bb995e5571098188092e296192309c77.

I wish I could give more details about system version, etc, but I don't have a local system to reproduce it on.

**Comment by rohan-shah** [comment]
I eventually "fixed" this by changing linux versions on travis....no idea what the underlying problem was.

**Comment by Anna-qwerty** [comment]
Hope this helps...
After many attempts, I could install igraph by editing ~/.R/Makevars with this only line:
`CFLAGS=-std=gnu11`
I installed igraph on Microsoft R 3.5.0 installed on a Centos 7 cluster.
