### ISSUE TITLE
installation of igraph returns "non-zero exit status"

### ISSUE THREAD

**Issue by ADENIRANADEBIYI** [igraph/rigraph#217]
I was trying to install igraph as a dependent of some other packages that I need. However, I am getting error messages 
"ERROR: compilation failed for package ‘igraph’"
Warning in install.packages :
  installation of package ‘igraph’ had non-zero exit status

Please kindly assist in solving this issue. 

I tried to used suggestions I saw online for previous versions, but it doesn't seem to be working.

Thanks

**Comment by CosBa** [comment]
Same here

**Comment by gaborcsardi** [comment]
This is not specific enough to be able to diagnose the problem.
