### ISSUE TITLE
can't install igraph

### ISSUE THREAD

**Issue by Noah89** [igraph/rigraph#225]
Dear Sir
I am trying to install igraph package on my linux but I can't since the package is not available for for R version 3.0.2.
** Warning message:
package ‘http://cran.r-project.org/src/contrib/Archive/igraph/igraph_1.0.1.tar.gz’ is not available (for R version 3.0.2)

What is the possible solution in this case?
Many thanks in advance

**Comment by alexperrone** [comment]
Try updating R, the latest version is much newer than what you have.
