### ISSUE TITLE
object ‘.innei’ is not exported by 'namespace:igraph'

### ISSUE THREAD

**Issue by ntamas** [igraph/rigraph#229]
_From @mkhezr on September 26, 2017 20:21_

Hello!

I'm developing an R package which depends on igraph.  but R CMD check shows the following:

Warning messages:
1: object ‘.innei’ is not exported by 'namespace:igraph' 
2: object ‘.outnei’ is not exported by 'namespace:igraph'

Is there a workaround to get check to pass clean? Why aren't these special vertex indexing functions exported?

Thanks

_Copied from original issue: igraph/igraph#1033_

**Comment by maelle** [comment]
@ntamas is this still valid?

**Comment by ntamas** [comment]
I think this is not relevant any more.
