### ISSUE TITLE
supplied colour as hex constant

### ISSUE THREAD

**Issue by pm321** [igraph/rigraph#235]
V(graph)$color will not accept colors as hex constants  (from RcolorBrewer); only numeric or character colors. It would be great if hex constants were accepted. 

Current work around by finding best fit color name thanks to https://stackoverflow.com/questions/18408333/find-color-names-for-colors-close-to-colorbrewer-palette

**Comment by gaborcsardi** [comment]
I am not sure what you mean, 
```r
❯ library(igraph)
❯ g <- make_ring(10)
❯ V(g)$color <- "#ff0000"
❯ plot(g)
```
works as expected. I.e. the vertices are red.

**Comment by pm321** [comment]
Sorry, I think I may have made a mistake in setting up a color vector
