### ISSUE TITLE
Strange behavior of modularity_matrix() with weighted networks

### ISSUE THREAD

**Issue by jpalowitch** [igraph/rigraph#238]
Hi, I'm wasn't 100% sure I wasn't doing something incorrectly, so I posted on SO first:

https://stackoverflow.com/questions/47131113/what-is-the-correct-way-to-set-up-a-modularity-matrix-call-for-a-weighted-grap

Let me know if you'd like me to compose an issue. Thanks!

**Comment by szhorvat** [comment]
SO post is deleted, closing.
