### ISSUE TITLE
Providing resolution parameters for the Louvain and other community detection algorithm

### ISSUE THREAD

**Issue by Xiaojieqiu** [igraph/rigraph#239]
Dear igraph team,

it will be very useful for the cluster_louvain (as well as for other community detection algorithms, including cluster_walktrap, cluster_spinglass, cluster_leading_eigen, cluster_edge_betweenness, cluster_fast_greedy, cluster_label_prop) to provide support for a resolution parameter. For example, this java implementation for louvain clustering as well as for a few other algorithms provide this support: 
http://www.ludowaltman.nl/slm/

**Comment by lazappi** [comment]
Not sure if it would be useful for implementing this but there is a C++ port of the Java implementation including the resolution parameter in the Seurat package https://github.com/satijalab/seurat/blob/master/src/ModularityOptimizer.cpp.

**Comment by SamGG** [comment]
Dear igraph developers,
I really think that resolution_parameter is useful. Such a development should be centralized into igraph package in order to avoid the spreading of code.
Best.

**Comment by vtraag** [comment]
A resolution parameter is implemented in the [upcoming implementation of the Leiden algorithm](https://github.com/igraph/rigraph/issues/346). It might be possible to introduce it in some algorithms, such as the Louvain algorithm, but for some other algorithms this may be more challenging.

**Comment by SamGG** [comment]
Thanks for your answer. I hope to see it soon. I have just seen somebody having introduced the resolution in the louvain code of igraph a few years ago, but I can't find back the reference. For Louvain, it seems quite simple, but I clearly don't know for other algorithms.
Thanks for working at making Leiden algorithm available to the igraph community, and I hope the rigraph one too.
Best.

**Comment by SamGG** [comment]
The link in case
https://github.com/jmonlong/Hippocamplus/blob/config/R/rigraph_gammalouvain/community.c

**Comment by vtraag** [comment]
@SamGG , great, thanks for the link! @jmonlong your contribution would be welcome as a pull request to the igraph project! It seems you already have implemented using the resolution value, by making a PR, it would become available to everybody using igraph.

**Comment by jmonlong** [comment]
Sure, I'll try to make one then. I remember having some trouble testing and compiling in some machines but I can definitely draft a first PR. I think I had added the resolution only for the Louvain algorithm though.

**Comment by SamGG** [comment]
@jmonlong That will be a great contribution! Thanks for looking at it. The R 4.0 development environment eases many steps in my little experience.
@vtraag Thanks for inviting Jean.

**Comment by szhorvat** [comment]
@jmonlong Great to hear!

Just to be clear, this should be contributed to https://github.com/igraph/igraph/ (the C core), not to https://github.com/igraph/rigraph/

**Comment by jmonlong** [comment]
I think I have this ready (working locally). As noted above I PRed the igraph part. Should I then just wait until it's merged there before creating a PR for the rigraph side?

**Comment by SamGG** [comment]
Great! Bravo!

**Comment by jmonlong** [comment]
Now that the PR is merged on the igraph side, I understand we have to wait for some updates of igraph/rigraph before making a PR here. 

It should be ready to PR in my rigraph fork at https://github.com/jmonlong/rigraph (although the submodule is pointing at the dev branch of igraph for now). 

Here is an archive of the package with those changes, in case someone needs it in the meantime: [igraph_1.2.5.louvain_resolution.tar.gz](https://github.com/igraph/rigraph/files/4713676/igraph_1.2.5.louvain_resolution.tar.gz)

Please poke me if I don't realize that everything is ready for the rigraph PR.

**Comment by SamGG** [comment]
Thanks a lot for this quick implementation!
I will try this on my Windows setup, but not sure how easy it would be.

**Comment by LTLA** [comment]
I'm a bit late to the party, but this looks interesting. Is there still an intent to PR the necessary changes into **rigraph**?

**Comment by ntamas** [comment]
@vtraag has merged a few outstanding PRs recently into igraph/rigraph; let's see what he says once he is back from holidays.

**Comment by jmonlong** [comment]
The corresponding igraph PR was merged in the *develop* branch of igraph. My understanding was that we have to wait for the next minor update of igraph (0.9.0) first. Then something about updating the C core of rigraph, then a PR for this on rigraph? 

https://github.com/igraph/igraph/pull/1386#issuecomment-633294568

Although I'm a bit confused because there have been new minor releases (but 0.8.x) of igraph since then.

**Comment by vtraag** [comment]
@jmonlong, your understanding is correct, we first have to make a new 0.9.0 release of `igraph` and then update the `rigraph` interface. 

Regarding versioning, we are trying to stick some development version of semantic versioning. That is, any patch release should be API backwards compatible (with possible additional functionality), while any new minor release will be API incompatible. Hence, 0.9.0 will present some bigger changes in the API (and a revamped build system), while any 0.8.x release is API backwards compatible with an earlier 0.8.y version.

Right now, the first priority is to make a new release of `rigraph` that uses the 0.8.x series of the `igraph` C core.

**Comment by szhorvat** [comment]
This is implemented for 1.3, closing.
