### ISSUE TITLE
Error in as_graphnel(g) : could not find function "as_graphnel"

### ISSUE THREAD

**Issue by mobadawy-sp** [igraph/rigraph#243]
Hi...I encountered the following error trying to run the first example from online igraph docs, here: http://igraph.org/r/doc/as_graphnel.html

Here's the code, running on OSX Sierra, R v3.4.2, igraph version 1.1.2 installed from CRAN.

`require(igraph)
g <- make_ring(10)
V(g)$name <- letters[1:10]
GNEL <- as_graphnel(g)

Error in as_graphnel(g) : could not find function "as_graphnel"
` 
I received the same error when I tried to use the "graph_from_graphnel" function as well.

Any idea what is going on here?
Thanks.

**Comment by mobadawy-sp** [comment]
FYI: I installed the github version, which is version 1.1.0, and the issue no longer observed. So it's only the CRAN version so far, version 1.1.2.

**Comment by rmflight** [comment]
There is a typo in the export directive of the latest version, there is a pull request to fix (was two actually), but I'm assuming @gaborcsardi has other stuff keeping him busy.
