### ISSUE TITLE
Error when trying to install igraph package in R 3.4.2.

### ISSUE THREAD

**Issue by jakobgerstenlauer** [igraph/rigraph#244]
Using R version 3.4.2 on ubuntu, I get the following error message when trying to install igraph in the R console:

foreign-graphml.c: In function ‘igraph_write_graph_graphml’:

foreign-graphml.c:1408:46: error: expected ‘)’ before ‘GRAPHML_NAMESPACE_URI’
   ret=fprintf(outstream, "<graphml xmlns=\"" GRAPHML_NAMESPACE_URI "\"\n");
                                              ^
foreign-graphml.c:1412:59: error: expected ‘)’ before ‘GRAPHML_NAMESPACE_URI’
   ret=fprintf(outstream, "         xsi:schemaLocation=\"" GRAPHML_NAMESPACE_URI "\n");
                                                           ^
foreign-graphml.c:1414:38: error: expected ‘)’ before ‘GRAPHML_NAMESPACE_URI’
   ret=fprintf(outstream, "         " GRAPHML_NAMESPACE_URI "/1.0/graphml.xsd\">\n");
                                      ^
make: *** [foreign-graphml.o] Error 1
ERROR: compilation failed for package ‘igraph’
Warning message:
In install.packages("igraph") :
  installation of package ‘igraph’ had non-zero exit status

**Comment by vkehayas** [comment]
I just faced this problem. You need to run this command:  

`sudo apt-get install libxml2-dev`

**Comment by daf** [comment]
@vkehayas this works for me, thank you!

**Comment by biosas** [comment]
Same problem with Centos 7.4, R version 3.4.2 (2017-09-28)

Solution as above (Thank you vkehayas!) with minor variation:

yum install libxml2-devel

**Comment by ntamas** [comment]
It has been almost three years since the last comment and we are at igraph 1.2.6 now so closing this issue. Feel free to reopen if the problem still exists.
