### ISSUE TITLE
[Question] Reverse function of As_long_data_frame

### ISSUE THREAD

**Issue by happyshows** [igraph/rigraph#245]
Hi,

I'd like to do some manipulation in data frame and convert it back to graph.

I have been using As_long_data_frame to convert the graph to data frame but the node attributes like name, will become from_name & to_name as edge attribute after using graph.data.frame.

Am I using the wrong function to convert data frame back to graph?

**Comment by ntamas** [comment]
Closing this issue as it is a support question; it is better suited for https://igraph.discourse.group
