### ISSUE TITLE
demo(): "hrg" Example is broken - cannot download karate-club dataset from internet 

### ISSUE THREAD

**Issue by knbknb** [igraph/rigraph#247]
When I try to run the demo "hrg                       Hierarchical random graphs" I get this, see below:
I think the error-message is self-explanatory (''Couldn't resolve host name'')

```
demo(package = "igraph", "hrg")


	demo(hrg)
	---- ~~~

Type  <Return>	 to start : 

R> pause <- function() {}

R> ### Download the Zachary Karate Club network from Nexus
R> 
R> karate <- nexus.get("karate")
Error in load(rdata, envir = env) : 
  cannot open the connection to 'http://nexus.igraph.org/api/dataset?id=karate&format=R-igraph'
In addition: Warning message:
In load(rdata, envir = env) :
  URL 'http://nexus.igraph.org/api/dataset?id=karate&format=R-igraph': status was 'Couldn't resolve host name'
```
This error  is puzzling because another demo-example (community detection) loads the karate dataset from the local host (from the igraphdata package?)

my setup:

```
Package: igraph
Version: 1.1.2
Packaged: 2017-07-20 21:33:52 UTC; gaborcsardi
Repository: CRAN
Date/Publication: 2017-07-21 11:39:40 UTC
Built: R 3.4.1; x86_64-pc-linux-gnu; 2017-08-02 08:58:43 UTC; unix
```

**Comment by igordot** [comment]
I am running into a similar issue:
```
> igraph::nexus.info("miserables")
Error in readLines(f) : 
  cannot open the connection to 'http://nexus.igraph.org/api/dataset_info?format=text&id=miserables'
In addition: Warning message:
In readLines(f) :
  URL 'http://nexus.igraph.org/api/dataset_info?format=text&id=miserables': status was 'Couldn't resolve host name'
```

**Comment by MMJansen** [comment]
Have you found a solution? I have the same issue: 
_> g <- nexus.get("miserables")
Warning in load(rdata, envir = env) :
  InternetOpenUrl failed: 'De naam of het adres van de server kan niet worden omgezet'
Error in load(rdata, envir = env) : cannot open the connection_

**Comment by ntamas** [comment]
The Nexus graph repository is not available any more and the `hrg` example was updated in c9011ece9d75ac04a315dff2bf618d5c4c2075b4 so it does not need Nexus any more. As for the "Les Miserables" dataset, I'm afraid you'll have to download it from some other source (Google probably reveals lots of potential data sources).

**Comment by ntamas** [comment]
Also, the `nexus_...()` functions are now removed in 86e0a58a

**Comment by szhorvat** [comment]
Can we add the data to the `igraphdata` package?

**Comment by ntamas** [comment]
In theory we could, not sure how much time it would take to get through CRAN review, though.

Also, note that the Les Miserables dataset is most likely referred to by other packages on CRAN as an example ([see here](https://rdrr.io/search?q=nexus.get)); I don't remember if it was cited ever in igraph's docs. This is not the case for the karate club network; that was referred to in `demo/hrg.R`, but this demo has recently been updated to use `make_graph("zachary")` instead, otherwise it would have never passed CRAN review.
