### ISSUE TITLE
Error with knn

### ISSUE THREAD

**Issue by SantiFilippo** [igraph/rigraph#249]
Dear all, I am trying to compute average nearest neighbour degree and average nearest neighbour strength, using the following code:

**fdi.graph.2003 <- graph_from_data_frame(fdi.edge.2003, directed = T, vertices = fdi.attr.2003)**
**ANND <- knn(fdi.graph.2003)**

 However, R returns the following error message 

Error in knn(fdi.graph.2003) : 
  At structural_properties.c:5889 : Average nearest neighbor degree Works only with simple graphs, Invalid value

Do you have any explanation to solve this issue? I tried to compute it from a simple binary edgelist too (the original trial has been done on a weighted network with plenty of edge attributes) but it is not working too.

**Comment by ahbon123** [comment]
I have met same issue, did you solve it?
