### ISSUE TITLE
Imported functions causing unnecessary issues

### ISSUE THREAD

**Issue by oganm** [igraph/rigraph#252]
igraph package imports many functions in its namespace. This can cause seemingly benign changes in the global environment to cause errors in igraph. I came here from this [SO question](https://stackoverflow.com/questions/27004167/coloring-vertexes-according-to-their-centrality/27004937#27004937) where my suggestion of assigning a variable `palette` causes an error in the usage of igraph.

Cases like this can be easily avoided if `palette` or similar imported functions were replaced with `grDevices::palette` or equivalent. Is there a relevant design decision behind this or would you be ok if someone added explicit function calls in a pull request?

**Comment by gaborcsardi** [comment]
I think this has been fixed. If you think this is still a problem, please reopen this issues and include some code the demonstrates the problem. Thanks.
