### ISSUE TITLE
add function for information centrality

### ISSUE THREAD

**Issue by TomKellyGenetics** [igraph/rigraph#256]
I've prepared a function to implement network efficiency and information centrality on igraph objects. See the following repository for this function with the accompanying unit tests and documentation: https://github.com/TomKellyGenetics/info.centrality

I've wrapped this function in it's own package but would prefer to add it to the "rigraph" package if feasible. If there is interest in doing so I can add this function to a fork of the dev branch and submit a pull request. In this case I will rename the function to "info_centrality" for consistency with other centrality functions.

**Comment by gaborcsardi** [comment]
Thanks, I think it is better to keep it in your package. Then you don't depend on us.

**Comment by mbojan** [comment]
@TomKellyGenetics , if you want to merge it into some other package you might ask David Schoch if he'd be interested in putting it in his https://schochastics.github.io/netrankr/index.html . It's all about centrality indices.

**Comment by TomKellyGenetics** [comment]
Thank you for considering it. It may be easier to keep it in a self-contained package but I'll look into whether it would fit with similar functions.
