### ISSUE TITLE
Is there any way to add igraph_random_edge_walk() implementation in rigraph?

### ISSUE THREAD

**Issue by joycewang914** [igraph/rigraph#261]
I noticed that igraph_random_edge_walk() was recently implemented in igraph.
Can you please also implement it in R igraph? Thanks!

Joyce

**Comment by szhorvat** [comment]
This function is exposed in the development version, which will become 1.3.0.

```
> random_edge_walk(make_ring(6), 1, 10)
+ 10/6 edges from f605bc8:
 [1] 1--2 1--2 1--6 5--6 4--5 3--4 2--3 1--2 1--2 2--3
```

You can install it per the instructions if you have the R development tools. https://github.com/igraph/rigraph/#installation
