### ISSUE TITLE
Formal Definition for igraph object

### ISSUE THREAD

**Issue by harrydgnt** [igraph/rigraph#266]
Hello 

I am trying to make a class that includes igraph object, but it seems like igraph in R lacks the formal definition for igraph object. 

I initialize my class as: 

```
> require("SingleCellExperiment")
> require("igraph")
> setClass("expression_network",
  + slots = list(normalized_data = "matrix",
  + net_graph = "igraph"),
  + contains = c("SingleCellExperiment"))
```
and I get this warning message: 

`
Warning message:
undefined slot classes in definition of "expression_network": net_graph(class "igraph")`

And when I make my class object from the "SingleCellExperiment" class, I get this error:

```
> new("expression_network", sce_object)
Error in validObject(.Object) :
  invalid class “expression_network” object: undefined class for slot "net_graph" ("igraph")
```

The "net_graph" object is going to be updated/added downstream so the igraph object slot needs to be there. 

Temporary get-around I use now is this: 

```
> setOldClass("igraph")
> dummy <- new("expression_network", sce_object, net_graph = erdos.renyi.game(1, 1))
>
```

and this can successfully generate my "expression_network" object but it would be better to do it in more explicit way, without making a dummy igraph object. 

Thank you for the help.

Harry

**Comment by harrydgnt** [comment]
If I do not make a dummy igraph object after setOldClass(), I get this error:

```
> setOldClass("igraph")
> dummy <- new("expression_network", sce_object)
Error in validObject(.Object) :
  invalid class “expression_network” object: invalid object for slot "net_graph" in class "expression_network": got class "NULL", should be or extend class "igraph"
```

**Comment by mbojan** [comment]
Well, this is not so much an igraph problem, which is written using S3 system, but the way you handle S3 objects in your S4 code. I think you need to specify the prototype when calling `setOldClass`, i.e. the following works for me:

```r
library(methods)


setClass(
  "SingleCellExperiment",
  slots= c(
    x = "numeric"
  )
  )

setOldClass("igraph", igraph::make_empty_graph())

setClass(
  "bar",
  slots = c(g="igraph"),
  contains="SingleCellExperiment"
)


new("SingleCellExperiment")
new("bar")
o <- new("SingleCellExperiment", x=1)
new("bar", o)
```
