### ISSUE TITLE
Please tag all releases

### ISSUE THREAD

**Issue by QuLogic** [igraph/rigraph#267]
There's currently only one tag, but there have been other releases made to CRAN since then.

PS, the URL on CRAN points to igraph/igraph but should probably point to igraph/rigraph?

**Comment by QuLogic** [comment]
I cannot seem to find a commit that corresponds to 1.2.1, though the NEWS seems to match 1.2.0, maybe?

**Comment by ntamas** [comment]
Releases are now tagged from 1.2.0 onwards. I have fixed the issue tracker link in the CRAN description file; the new link should go live with igraph 1.2.7 (coming soon).
