### ISSUE TITLE
Build against external igraph

### ISSUE THREAD

**Issue by QuLogic** [igraph/rigraph#268]
You can build python-igraph against an external/system copy of igraph, but there seems to be no option for it in this R version.

I can almost write a patch with an option to `Makevars.in` to do so, but there are a couple things that hinder it a bit:
1. All the sources get dropped directly in `src`, which is not a problem, but does make it a little hard to remove the extra files. It would be a bit nicer if they were all put in a single subdirectory.
2. The linked igraph commit does not seem to be a released version, which would generally be the one that was packaged. It would be nice if non-tagged versions were avoided.

**Comment by gaborcsardi** [comment]
This is not possible currently, as the sources are compiled with different flags for the R package.  See the  `USING_R` flag.

**Comment by QuLogic** [comment]
OK, good point; I had a look through those, and I _think_ most of them are benign:
1. All functions using printf are commented because R warns about it in shared libraries, but this shouldn't matter for an external dependency. Since they're all commented, the R code could never have called them and the one that _is_ called from C is avoided by `igraph_set_progress_handler`.
2. `igraph_error` has an `abort` but that should have already been avoided by calling `igraph_set_error_handler`.
3. The RNG seems to be linked to R. I'm not totally sure of the benefits/costs for this one are.
4. One `IGRAPH_ERROR` is replaced by `REprintf` in `src/community.c`; I'm not sure why this one call is special?

**Comment by gaborcsardi** [comment]
Before we go into the details here, what is the benefit of linking to an external lib?

**Comment by QuLogic** [comment]
Sorry, I should have provided more context earlier. I am trying to create a package for Fedora of igraph. We already have an igraph package (of the C library) and two python-igraph packages (for 2 and 3) which link against it. It is no longer a hard requirement, but I would _like_ it if the R package also linked against the common C library to minimize duplication. If things are super-entangled that would be impossible, but it does not appear to be the case here.

**Comment by gaborcsardi** [comment]
The releases of the C lib and the R package are not synchronized, sadly. So I am afraid that you would have complications from this setup.

**Comment by QuLogic** [comment]
So long as the C lib followed something like semver and the R version only used releases, then it would remain workable. However, for the time being, I have decided to keep the bundled igraph, and only unbundle arpack and uuid. But it would still be nice to be able to do this in the future.

One of the other reasons I was hoping to use system igraph is that I was seeing some test failures on Fedora Rawhide (but not older versions) and I had hoped the igraph maintainer had already fixed it there. But since the bundled igraph is newer than any releases, I guess that's fairly unlikely. I will open a separate bug report for this.

**Comment by gaborcsardi** [comment]
> So long as the C lib followed something like semver and the R version only used releases

That would make sense indeed, but it is not the case. The R version uses  unreleased  C versions. Currently the C lib and the R packages should be considered as  different product. (With a lot of shared code  of course, but still.)

**Comment by ntamas** [comment]
Building against an external igraph is still discouraged, especially now that the C core has advanced to version 0.10 with full 64-bit support and the R interface is not adapted yet for the new branch of the C core. I'd say that building against an external igraph is not planned in the near future, but feel free to comment further on this issue if you think that this should be changed.

**Comment by theAeon** [comment]
Commenting further as r-igraph 2.0 has finally caught up with the 64 bit c-core!
