### ISSUE TITLE
Test failure on Fedora Rawhide

### ISSUE THREAD

**Issue by QuLogic** [igraph/rigraph#270]
When building on Fedora Rawhide, I am seeing a test failure (from `R CMD check`) with Kamada-Kawai:
```
  1. Failure: Kamada-Kawai layout generator works (@test_layout.kk.R#25) ---------
  sum(l) not equal to -86.1405864709501.
  1/1 mismatches
  [1] -84.8 - -86.1 == 1.32

  testthat results ============================================================
  OK: 3306 SKIPPED: 2 FAILED: 1
  1. Failure: Kamada-Kawai layout generator works (@test_layout.kk.R#25) 
```
It works correctly on Fedora 28 or 27. I have enabled GMP and GLPK. Some possibly relevant version information:

Fedora Rawhide:
* R-core-3.4.4-1.fc29.x86_64
* gmp-6.1.2-7.fc28.x86_64
* glpk-4.61-4.fc28.x86_64
* gcc-8.0.1-0.23.fc29.x86_64
* gcc-gfortran-8.0.1-0.23.fc29.x86_64

Fedora 28:
* R-core-3.4.4-1.fc28.x86_64
* gmp-6.1.2-7.fc28.x86_64
* glpk-4.61-4.fc28.x86_64
* gcc-8.0.1-0.20.fc28.x86_64
* gcc-gfortran-8.0.1-0.20.fc28.x86_64

These versions don't seem to have changed very much, so let me know if there are any other things you might need to look into.

**Comment by gaborcsardi** [comment]
Can you look  at the output? Probably a numerical issue, and we just need to  increase the tolerance.

**Comment by QuLogic** [comment]
Sorry, I meant to include that originally; I've edited the first post to put that in.

**Comment by QuLogic** [comment]
On other architectures (ppc64, ppc64le, aarch64, s390x), _other_ tests fail:
```
Last 13 lines of output:
  
  2. Failure:  (@test_layout.fr.R#24) --------------------------------------------
  sum(l) not equal to 941.4724.
  1/1 mismatches
  [1] 1079 - 941 == 138

  Loading required package: digest
  testthat results ============================================================
  OK: 3302 SKIPPED: 2 FAILED: 2
  1. Failure:  (@test_layout.fr.R#15) 
  2. Failure:  (@test_layout.fr.R#24) 
```
and on armv7hl, a third test fails:
```
  3. Failure: SIR works (@test_sir.R#15) -------------------------------------
  digest(res) not equal to "b73a8ad03b832b3543f2f03d07330398".
  1/1 mismatches
  x[1]: "bc42d0cbe0bb3321e83979c0432f9cea"
  y[1]: "b73a8ad03b832b3543f2f03d07330398"

  testthat results ============================================================
  OK: 3301 SKIPPED: 2 FAILED: 3
  1. Failure:  (@test_layout.fr.R#13) 
  2. Failure:  (@test_layout.fr.R#22) 
  3. Failure: SIR works (@test_sir.R#15) 
```
You can view the Rawhide build logs [here](https://koji.fedoraproject.org/koji/taskinfo?taskID=26741464).

**Comment by QuLogic** [comment]
Thoughts?

**Comment by QuLogic** [comment]
Ping?

**Comment by gaborcsardi** [comment]
These are because of differences in the RNG. These  tests should be  removed.

**Comment by QuLogic** [comment]
Should I do that downstream only, or are you planning to do so here as well?
