### ISSUE TITLE
Shortest path with penalty for different edge ids.

### ISSUE THREAD

**Issue by FilipeamTeixeira** [igraph/rigraph#272]
I'm trying to get the shortest paths of a graph but based on its edge ids. So having the following graph:

```
library(igraph)

set.seed(45)
g <- erdos.renyi.game(25, 1/10, directed = TRUE)
E(g)$id <- sample(1:3, length(E(g)), replace = TRUE)
```

The `shortest_paths(g, 1, V(g))` function finds all the shortest paths from node 1 to all the other nodes. However, I would like to calculate this, not just by following the geodesic distance, but a mix between the geodesic distance, and the minimum of edge id changes. For example if this would be a train network, and the edge ids would represent trains. I would like to calculate how to get from node A to all the other nodes using the shortest path, but while changing the least amount of time of trains.

**Comment by szhorvat** [comment]
This is a bit too vague for a feature request, so I will close it now. For further discussion, please use the forum https://igraph.discourse.group/
