### ISSUE TITLE
At optimal_modularity.c:85 : GLPK is not available, Unimplemented function call

### ISSUE THREAD

**Issue by willnotburn** [igraph/rigraph#273]
I've been using `optimal.community` to detect clusters for about two years now. It looks like the new command for this has become `cluster_optimal` at some point. Regardless of which one is called, I now get the error in the title of this issue. 

This started happening within the last two weeks. I really lack the programming skills to correctly diagnose what's causing this. I am running High Sierra 10.13.4 and install OS updates as soon as they come out. BUT I also tried running the R code on my university's computing cluster, and it gave me the same error.

1. Could it be that `igraph` has re-worked the `cluster_optimal` command recently?

2. How can I install an earlier version of the `igraph` R package to test this/have it work again?

**Comment by gaborcsardi** [comment]
Unfortunately that function is not supported by the CRAN build any more, because CRAN made me remove the embedded GLPK library from igraph, and they do not provide a GLPK  library on their macOS machine.

I'll ask them to install GLPK. Alternatively, I can distribute another build somewhere else....

**Comment by willnotburn** [comment]
Thanks for a quick reply!

I need the `optimal.community` function to work to replicate results that are part of an already written manuscript. If you could please make a version of `igraph` available that will do this. And also, which R version would I need to install to work with the older `igraph` build?

**Comment by hokkaido** [comment]
@willnotburn It looks like GLPK was removed with version 1.2.1: https://cran.r-project.org/web/packages/igraph/news.html

**Comment by dirediredocks** [comment]
Hi, is there a workaround/alternative for the `cluster_optimal` function in the current `igraph` build? Thanks!

**Comment by gaborcsardi** [comment]
You need to compile the package for yourself. Unfortunately CRAN macOS does not have GLPK.

**Comment by rachitkinger** [comment]
Faced the same problem. Installing it from github worked for me.

**Comment by mokawi** [comment]
> You need to compile the package for yourself

Which package? `rglpk`? I installed the github version of `igraph` (`devtools::install_github("igraph/rigraph")`), but I'm still getting the same error.

**Comment by gaborcsardi** [comment]
> Which package? rglpk? I installed the github version of igraph (devtools::install_github("igraph/rigraph")), but I'm still getting the same error.

No, igraph. But before you install it from source, you need to install the libglpk-dev (or something similar) Debian package.

**Comment by mokawi** [comment]
This seems to work with R 3.6 (I ended up running my script on another computer), but not R 3.5. This is good enough for my own use.

**Comment by ZxyChopcat** [comment]
Hi,
I had the same problem and could not solve it.
My R version is 3.6.1.I installed igraph by "remotes::install_github("igraph/rigraph@master")" because "devtools::install_github("igraph/rigraph")"did not work for me with the error "Error: Failed to install 'unknown package' from GitHub:  HTTP error 404.  Not Found".
I also installed Rglpk before installing igraph.But I still get the error"At optimal_modularity.c:85 : GLPK is not available, Unimplemented function call".Do you have any idea?I don't know how to compile igraph  with GLPK support.

**Comment by gaborcsardi** [comment]
> Do you have any idea?I don't know how to compile igraph with GLPK support.

It depends on your OS.

**Comment by ZxyChopcat** [comment]
> > Do you have any idea?I don't know how to compile igraph with GLPK support.
> 
> It depends on your OS.

I'm using ubuntu 18.04.5.

**Comment by gaborcsardi** [comment]
Then you need to `apt-get install libglpk-dev` before you install igraph

**Comment by ZxyChopcat** [comment]
> Then you need to `apt-get install libglpk-dev` before you install igraph

Thanks for your reply.But I've installed libglpk-dev (4.65-1) before installing igraph(1.2.5) and still get the error.

**Comment by gaborcsardi** [comment]
Right, you need `libgmp-dev` as well it seems.

**Comment by ZxyChopcat** [comment]
> Right, you need `libgmp-dev` as well it seems.
It said libgmp-dev is already the newest version(2:6.1.2+dfsg-2).Are there any other components that need to be installed？

**Comment by vtraag** [comment]
@ZxyChopcat, could you perhaps output the full output you get when installing using `remotes::install_github("igraph/rigraph@master")`? I just tested it locally on machine (Ubuntu 20.04) and that does link correctly to `GLPK`. I did have to install `libgfortran4` for R 3.6, it wouldn't install without it, perhaps you might need the same?

**Comment by fusaroli** [comment]
I am on Mac OS (Catalina), R 4.03. I tried compiling the github version (remotes::install_github("igraph/rigraph@master")), but I still get the GLPK error when trying to use optimal.community. How do I install GLPK on the mac?

**Comment by vtraag** [comment]
@fusaroli, I think you can install it using homebrew: `brew install glpk`. I believe it is also available from MacPorts.

**Comment by szhorvat** [comment]
MacPorts: `sudo port install glpk`. However, with MacPorts you either need to tell R to use MacPorts's own compiler, or you need to add the compiler option `-I/opt/local/include`

The contents of my `.R/Makevars` is the following (for MacPorts, with both `clang-10` and `gcc10` installed):

```
CC=/opt/local/bin/clang-mp-10
CXX=/opt/local/bin/clang++-mp-10
FC=/opt/local/bin/gfortran-mp-10
F77=/opt/local/bin/gfortran-mp-10
FLIBS=-L/opt/local/lib/gcc10 -lgfortran -lquadmath -lm
```

**Comment by szhorvat** [comment]
Be aware that `optimal.community` is going to be extremely slow and non-interruptible (i.e. you'll have to kill your R session to stop it).

**Comment by ZxyChopcat** [comment]
> @ZxyChopcat, could you perhaps output the full output you get when installing using `remotes::install_github("igraph/rigraph@master")`? I just tested it locally on machine (Ubuntu 20.04) and that does link correctly to `GLPK`. I did have to install `libgfortran4` for R 3.6, it wouldn't install without it, perhaps you might need the same?

Thank you for your help!My output is so long that I put it here:
[https://github.com/ZxyChopcat/output/blame/main/README.md](url)
Also I installed `libgfortran4` and still get the error.

**Comment by vtraag** [comment]
From the logs it looks like it did compile correctly and links to `GPLK`. Are you sure you don't have any other versions of `igraph` installed somehow that are picked up when you load the library? That is, are you sure that you removed all previous installations?

**Comment by achubaty** [comment]
@gaborcsardi Any suggestions / best practices for package authors checking whether the version of `igraph` was compiled with GLPK support on a given system (e.g., CRAN machines)?

I have been checking whether `Sys.which("glpsol") == ""` to see if GLPK is installed and then wrapping potentially problematic `igraph` functions in `try`, but is there a better way to check for this (e.g., something like `capabilities()`) that allows me to check once and not rely on code failing?

**Comment by angelovaag** [comment]
I have this problem on macOSX (Catalina). Following the instructions here, I have managed to install GLPK on the OS (and it works from command line), then installed Rglpk successfully and also reinstalled igraph (from source), but I still get the error "At optimal_modularity.c:85 : GLPK is not available, Unimplemented function call". From **Sys.which("glpsol") == ""** I still get False (hence, GLPK is still not available). Is there a more streamlined/step-by-step explanation as to what to install and in what order, specifically for MAC users, to get GLPK to work with R properly? I must have just missed a crucial step somewhere.

**Comment by achubaty** [comment]
@angelovaag if `Sys.which("glpsol")` return an actual path to the minary (i.e., it's not an empty character string) then GLPK is installed. Did you install GLPK using `brew` or something else? When installing `igraph` did you see the following messages?

```
checking glpk.h usability... yes
checking glpk.h presence... yes
checking for glpk.h... yes
```

**Comment by angelovaag** [comment]
@achubaty Thank you for the quick response. 
Sys.which("glpsol") returns to me: 
                 glpsol 
"/usr/local/bin/glpsol"

**Comment by gaborcsardi** [comment]
igraph needs to link to the GLPK library, at build time. It does not matter if you have the `glpsol` or other command line tools available.

**Comment by angelovaag** [comment]
@gaborcsardi, thank you for the clarification. I have reinstalled igraph but it does not seem to be detecting GLPK. Is there a way to force it to link or at least look for it during installation? I have tried also installed  "igraph/rigraph@master" and although it does give me the lines @achubaty suggested, I still get the "GLPK is not available" error when I try to use igraph

**Comment by angelovaag** [comment]
Update: Thank you both! igraph finally worked after I reinstalled Rglpk as well!

**Comment by irudnyts** [comment]
Hi everyone, 

I have macOS Mojave 10.14.6 and R 4.0.2. I've tried to reinstall everything, but still get 

```
x At optimal_modularity.c:85 : GLPK is not available, Unimplemented function call
```

Here what I have done: 

1. Install GLPK: `brew install glpk`
2. Install `gcc` (I could not install `remotes::install_github("igraph/rigraph@master")` without it): `brew install gcc`
3. My `~/.R/Makevars` looks as follows: 

```
VER=-10
CC=gcc$(VER)
CXX=g++$(VER)
CFLAGS=-mtune=native -g -O2 -Wall -pedantic -Wconversion
CXXFLAGS=-mtune=native -g -O2 -Wall -pedantic -Wconversion
FLIBS=-L/usr/local/Cellar/gcc/10.2.0_4/lib/gcc/10
```

4. I have also installed `arpack`: `brew install arpack`
5. Reinstalled `{Rglpk}` by `install.packages("Rglpk")`
I tested this package via examples of `Rglpk::Rglpk_solve_LP` and it can locate GLPK
6. Reinstalled `{igraph}` by `remotes::install_github("igraph/rigraph@master", force = TRUE)`

When installing `{igraph}`, it could not locate GLPK: 

```
checking for libxml/parser.h... yes
checking for __gmpz_add in -lgmp... no
checking for glp_read_mps in -lglpk... no
```

@gaborcsardi Is there any place in code I can hardcode the location of the GLPK? 

Best,
Iegor

**Comment by gaborcsardi** [comment]
igraph does not use Rglpk. If you use brew it needs 
```
brew install gmp glpk
```

Btw. if you use the CRAN installer of R, then you don't need to compile packages from source. You can also install it from brew:
```
brew install --cask r
```

**Comment by irudnyts** [comment]
@gaborcsardi, thanks for your fast reply! 

Both (`gmp` and `glpk`) are installed. 

> You need to compile the package for yourself. Unfortunately CRAN macOS does not have GLPK.

I thought that this message assumes to compile the package ourself. Am I missing something?

**Comment by irudnyts** [comment]
Oh yeah, I think you were talking about GLPK rather than `{igraph}`.

**Comment by gaborcsardi** [comment]
> I thought that this message assumes to compile the package ourself. Am I missing something?

I think that message is obsolete and CRAN igraph builds have GLPK now.

**Comment by ntamas** [comment]
> Is there any place in code I can hardcode the location of the GLPK?

I think you could simply add the appropriate folder to the library path in `CFLAGS` and `CXXFLAGS`, e.g. something like: `CFLAGS=-mtune=native -g -O2 -Wall -pedantic -Wconversion -L/usr/local/lib` if GLPK is in `/usr/local/lib` (this is where it is symlinked on my machine when I install it with `brew install glpk`.

**Comment by gaborcsardi** [comment]
> I think you could simply add the appropriate folder to the library path in ...

I don't think R will look at these.

OTOH, you don't need to set anything at all, R / igraph finds the libs if you install them with brew, I think. It did for me.

**Comment by mcas-git** [comment]
I am trying to install `igraph` from github on a macOS machine to address specifically this problem.
Prior to install `igraph`, I installed via homebrew `glpk`, `gmp`, `libxml2` and `gcc` - following the various comments. 
I also unset an reset my environmental variables using  

`Sys.unsetenv("GITHUB_PAT")`
`Sys.setenv(GLPK_HOME = "$(MINGW_PREFIX)")`

I still cannot install `igraph` using (even with the forcing option)

`devtools::install_github("igraph/rigraph@master")`

Is there anything else I am missing?

**Comment by szhorvat** [comment]
Explicitly set the compiler that R uses. Use a full path. See my comment above and adapt it to your setup: https://github.com/igraph/rigraph/issues/273#issuecomment-746813891

**Comment by szhorvat** [comment]
> As the error I get is the following, how should i set my .R/Makevars?

You should set it to use the compilers you actually have installed. Don't copy paths from the internet. Check where _your_ compiler is installed on _your_ system and use the correct paths.

> ld: warning: directory not found for option '-L/usr/local/gfortran/lib'

It tells you that this directory does not exist. Did you check if it does?

**Comment by willnotburn** [comment]
Hello everyone! OP here, over three years later. I actually have this problem every time I get a new computer and/or update my OS - and it just happened again! And it's resolved!

I am now running Big Sur (11.5.1) and R 4.1.0. Each time the solution varies in the details, but here's a step-by-step roadmap to how I usually get through it.

Much thanks to @angelovaag @gaborcsardi @achubaty for the components of this workflow.

For MacOS

0. Conda works better than Homebrew.

1. Install compilers with conda
`conda install clang_osx-64`
`conda install clangxx_osx-64`
`conda install gfortran_osx-64`

2. Install GLPK with conda
`conda install -c conda-forge glpk`

3. Add glpk installtion to PATH
`sudo nano /etc/paths` # yes, sudo nano. `export` has not worked for me
add `/opt/miniconda3/bin/` to the top of the file

4. Install Rglpk in R
`install.packages("Rglpk")`

5. Install igraph from source
devtools::install_github("igraph/rigraph@master")

6. Re-install Rglpk (I don't know why, but I had to)
`install.packages("Rglpk")`

I am a total amateur, and I'm sure some steps here are a poke in the dark, but this list has gotten me there on a few MacOS systems.

**Comment by ShixiangWang** [comment]
For CentOS

```sh
yum install glpk glpk-devel
```

Fix my problem.

**Comment by szhorvat** [comment]
CRAN builds now support GLPK (correct, @ntamas?)

**Comment by ntamas** [comment]
CRAN builds with GLPK; also, when building from source, `SystemRequirements` states that you need GLPK, so I think this should be okay.
