### ISSUE TITLE
R is killed when edge betweenness is computed on a zero matrix

### ISSUE THREAD

**Issue by leifeld** [igraph/rigraph#277]
library("igraph")
    packageVersion("igraph")
> [1] ‘1.1.0’

    m <- matrix(0, nrow = 10, ncol = 10)
    g <- graph.adjacency(m, mode = "undirected", weighted = NULL)
    eb <- cluster_edge_betweenness(g, directed = FALSE)

> free(): invalid pointer
> Aborted (core dumped)

**Comment by DarioS** [comment]
It does not happen if using version 1.2.1. The simple solution is to upgrade the software.
