### ISSUE TITLE
Conflicting Deprecation for subgraph.edges and subgraph

### ISSUE THREAD

**Issue by DarioS** [igraph/rigraph#278]
In the documentation, `subgraph.edges` is planned to be renamed

> This function will be renamed to `subgraph` in the next major version of igraph.

to a function which is deprecated and soon-to-be defunct.

> ... it is deprecated and will be removed in the next major version of igraph.

Is the documentation trying to suggest that both of them will be replaced by `induced_subgraph` ?

**Comment by gaborcsardi** [comment]
No, the docs are wrong.
