### ISSUE TITLE
Compile error - missing libsystem_containermanager.dylib?

### ISSUE THREAD

**Issue by smartinsightsfromdata** [igraph/rigraph#284]
I have just installed latest R version 3.5.1 with homebrew on OSX.

I try to install igraph official version from source or the latest version from github.

I get 

```
ld: file not found: /usr/lib/system/libsystem_containermanager.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [igraph.so] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/usr/local/lib/R/3.5/site-library/igraph’
* restoring previous ‘/usr/local/lib/R/3.5/site-library/igraph’
Installation failed: Command failed (1)
```

As the compile report exceed github max message length, I posted it at this gist: https://gist.github.com/smartinsightsfromdata/560d743cdf24719c70b21fa8f8d5d923

**Comment by gaborcsardi** [comment]
This looks like homebrew and some unusual setup (ccache, etc.) so unfortunately you are on your own.

**Comment by bretonics** [comment]
@smartinsightsfromdata, I have the same error for another package. Did you figure this out?

**Comment by bretonics** [comment]
@aittomaki, I ended up testing it from CRAN source and it worked so I wonder if it is a homebrew source issue.

**Comment by aittomaki** [comment]
I managed to solve this for me. @bretonics It was indeed an Apple/homebrew configuration issue. Homebrew installed Command Line Tools on first installation, and after that I had installed Xcode. This had resulted in a clash in versions and libraries.

I fixed it by changing the default command line tools to the ones supplied with Xcode by running:

`sudo xcode-select -switch <path/to/>Xcode.app`

(as documented in this [Apple Technical Note](https://developer.apple.com/library/archive/technotes/tn2339/_index.html#//apple_ref/doc/uid/DTS40014588-CH1-HOW_CAN_I_UNINSTALL_THE_COMMAND_LINE_TOOLS_))
