### ISSUE TITLE
cluster_walktrap Fails Community Detection if Metadata not in Result

### ISSUE THREAD

**Issue by DarioS** [igraph/rigraph#289]
Using the example in the documentation of `cluster_walktrap`, but setting the inclusion of all of the metadata to FALSE, causes `-Inf` communities to be reported.

```
> cluster_walktrap(g, merges = FALSE, modularity = FALSE, membership = FALSE)
IGRAPH clustering walktrap, groups: -Inf, mod: NA
+ groups:
  list()
Warning message:
In max(membership(x)) : no non-missing arguments to max; returning -Inf
```

It seems that `merges` and `modularity` are mandatory, so it's unclear why they are user options.

```
> cluster_walktrap(g, merges = FALSE, modularity = TRUE, membership = TRUE)
Error in cluster_walktrap(g, merges = FALSE, modularity = TRUE, membership = TRUE) : 
  At walktrap.cpp:138 : Cannot calculate membership without modularity or merges, Invalid value
```

From the documentation, it seems that these settings only affect the exclusion of the metadata in the end result object, so I didn't expect changing them to affect the community detection processing.

**Comment by szhorvat** [comment]
This causes a crash in 1.3.0:

```
cluster_walktrap(make_ring(10), merges = FALSE, modularity = FALSE, membership = FALSE)
```

**Comment by ntamas** [comment]
More details:

```
> cluster_walktrap(make_ring(10), merges=F)
Error in cluster_walktrap(make_ring(10), merges = F) :
  At core/community/walktrap/walktrap.cpp:141 : Cannot calculate membership without modularity or merges, Invalid value
> cluster_walktrap(make_ring(10), merges=F, modularity=F)
Error in cluster_walktrap(make_ring(10), merges = F, modularity = F) :
  At core/community/walktrap/walktrap.cpp:141 : Cannot calculate membership without modularity or merges, Invalid value
> cluster_walktrap(make_ring(10), merges=F, membership=F)
IGRAPH clustering walktrap, groups: -Inf, mod: 0
+ groups:
  list()
Warning message:
In max(membership(x)) : no non-missing arguments to max; returning -Inf
```

and this one also crashes:

```
> cluster_walktrap(make_ring(10), modularity=F, membership=F)
```

**Comment by ntamas** [comment]
This is actually a bug in the C core; the C core (at least in `master`) does not tolerate the case of `modularity=NULL` and `membership=NULL`. I'm working on fixing this.

**Comment by ntamas** [comment]
C core fixed in https://github.com/igraph/igraph/commit/a5234255f314f8a8e5d7f10038d2c5012735ca3a

**Comment by ntamas** [comment]
Going back to the original issue: yes, it seems like `membership` and `merges` are both needed in order to arrive at a meaningful result. In theory, `merges` would be enough, but igraph needs to know where to cut the dendrogram in order to arrive at a partition with maximal modularity, so it needs to calculate the modularity and the membership vector anyway. The arguments do not seem to make much sense, but we need to keep them for backward compatibility purposes. I'll just make it so that setting them to `FALSE` will set the corresponding item in the returned partition to `NULL` to preserve compatibility.
