### ISSUE TITLE
igraph error: /usr/bin/ld: cannot find -lgfortran

### ISSUE THREAD

**Issue by liyq601** [igraph/rigraph#294]
When I installed igraph, I met an error like below(R 3.4.2):

/usr/bin/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
make: *** [igraph.so] Error 1
ERROR: compilation failed for package ‘igraph’`

I don't know how to fix it. Could you help me? Thanks

**Comment by amin-kaveh** [comment]
In the terminal run:
`ld -lgfortran --verbos`

then you will see that the OS can not open `/usr/lib/libgfortran.so`
`attempt to open //usr/lib/libgfortran.so failed`

Then try to find the complete name and the address of the `.so` file. For me it is `/usr/lib/x86_64-linux-gnu/libgfortran.so.3`. And finally, make the link:

`sudo ln -s /usr/lib/x86_64-linux-gnu/libgfortran.so.3 /usr/lib/libgfortran.so`

Now, you should be able to install igraph on R.

Cheers,

**Comment by LaurentBerder** [comment]
Is there any solution for when you're not an admin and can't use `sudo`?

**Comment by ntamas** [comment]
Which platform are you on, how did you install R and which igraph version are you using? (If you are on Linux, please also state which Linux distribution and how did you install R). In theory, if you have the "official" R and you installed igraph from CRAN, it should work out of the box no matter where `libgfortran.so` is.

**Comment by LaurentBerder** [comment]
I'm running on CentOS Linux release 7.9.2009.
R version 4.0.5 was installed by admin.
I try installing igraph from CRAN in a renv project, but keep running into that `cannot find -lgfortran` error.

The craziest thing is that I managed to install igraph in another renv project...

**Comment by ntamas** [comment]
Do you have a `Makevars` file for R somewhere in the search path (e.g., `~/.R/Makevars`) that could interfere with the compilation process? Also, please post the last few (20-30) lines of the compilation log so I can get a bit more context about the error.

**Comment by LaurentBerder** [comment]
You're fast to react!
I actually got it to get installed after many tries. However, since I've been sloppily trying lots of different approaches, I wouldn't be able to tell you which one has worked...

**Comment by ntamas** [comment]
That's a pity :( However, I'm glad that it all worked out in the end!
