### ISSUE TITLE
Issues with make_bipartite_graph

### ISSUE THREAD

**Issue by bommert** [igraph/rigraph#296]
Based on igraph/igraph#1110, I encounterd new problems.

```
library(igraph)
types = c(0, 1, 1, 1)

eds = c("1", "2", "1", "3", "1", "4")
make_bipartite_graph(edges = eds, types = types)
```

works fine. However, if I do some renaming of the vertices, problems arise:

```
eds = c("1", "2", "1", "3", "1", "5")
make_bipartite_graph(edges = eds, types = types)
```
gives
```
Error in make_bipartite_graph(edges = eds, types = types) : 
  At bipartite.c:512 : Invalid (negative) vertex id, Invalid vertex id
```
and
```
eds = c("A", "B", "A", "C", "A", "D")
make_bipartite_graph(edges = eds, types = types)
```
causes my R session to end with the message
*R Session Aborted
R encountered a fatal error.
The session was terminated.*

I am using R 3.5.0 with R Studio on Windows 10.

I don't get any warnings for possibly wrong input or similar.

**Comment by szhorvat** [comment]
The problem here is that unlike `make_graph`, `make_bipartite_graph` does not actually handle string vertex names. It only works with numerical vertex IDs. This contradicts the documentation and should be fixed. This should be an easy fix, as some code only needs to be coped from `make_graph`.

The error message is confusing here. I will fix that in the C core.

**Comment by ntamas** [comment]
One possible problem here is that it's unclear how the `types` vector should be handled if the user provides vertex names. The user cannot reasonably predict the order of vertices in the graph when using names, but the `types` vector needs the vertex order.

One possibility would be to enforce `types` to be a _named_ vector, but then we need to ensure that all the names that appear in the edge list are also provided in `types`.

**Comment by szhorvat** [comment]
In that case perhaps do not accept a non-numerical edge vector?

**Comment by ntamas** [comment]
Fixed above; we now accept names if the `types` vector is named.
