### ISSUE TITLE
Can not install igraph 

### ISSUE THREAD

**Issue by Lily-WL** [igraph/rigraph#302]
Dear Developer,
The igraph can not be installed on my server because of the error:

> libiconv.so.2:: cannot open shared object file: No such file or directory

But I can find this file in my server.
> ./usr/local/lib/libiconv.so.2
> ./opt/anaconda2/pkgs/libiconv-1.15-h470a237_3/lib/libiconv.so.2
> ./opt/anaconda2/lib/libiconv.so.2

My R is installed by "yum" on a Centos7 OS. Can you help to figure out the problems?  THX.

**Comment by ntamas** [comment]
Please post the full output of running `install.packages("igraph")` in R. It is unclear where the error message is coming from exactly, i.e. whether it comes from the installation process or somewhere else.

**Comment by Lily-WL** [comment]
Thank you for your reply.

I will put the last part of the output.

> installing to /usr/lib64/R/library/igraph/libs
> ** R
> ** demo
> ** inst
> ** byte-compile and prepare package for lazy loading
> ** help
> *** installing help indices
>   converting help for package ‘igraph’
>     finding HTML links ... 好了
>     E                                       html  
>     V                                       html  
>     aaa-igraph-package                      html  
>     add_edges                               html  
>     add_layout_                             html  
>     add_vertices                            html  
>     adjacent_vertices                       html  
>     all_simple_paths                        html  
>     alpha_centrality                        html  
>     are_adjacent                            html  
>     arpack                                  html  
>     articulation_points                     html  
>     as.directed                             html  
>     as.igraph                               html  
>     as_adj_list                             html  
>     as_adjacency_matrix                     html  
>     as_edgelist                             html  
>     as_graphnel                             html  
>     as_ids                                  html  
>     as_incidence_matrix                     html  
>     as_long_data_frame                      html  
>     as_membership                           html  
>     assortativity                           html  
>     authority_score                         html  
>     automorphisms                           html  
>     betweenness                             html  
>     bfs                                     html  
>     biconnected_components                  html  
>     bipartite_mapping                       html  
>     bipartite_projection                    html  
>     c.igraph.es                             html  
>     c.igraph.vs                             html  
>     canonical_permutation                   html  
>     categorical_pal                         html  
>     centr_betw                              html  
>     centr_betw_tmax                         html  
>     centr_clo                               html  
>     centr_clo_tmax                          html  
>     centr_degree                            html  
>     centr_degree_tmax                       html  
>     centr_eigen                             html  
>     centr_eigen_tmax                        html  
>     centralize                              html  
>     cliques                                 html  
>     closeness                               html  
>     cluster_edge_betweenness                html  
>     cluster_fast_greedy                     html  
>     cluster_infomap                         html  
>     cluster_label_prop                      html  
>     cluster_leading_eigen                   html  
> Rd warning: /tmp/Rtmp3yDo6J/R.INSTALL3b9e188d129d/igraph/man/cluster_leading_eigen.Rd:113: file link ‘as.dendrogram’ in package ‘stats’ does not exist and so has been treated as a topic
>     cluster_louvain                         html  
>     cluster_optimal                         html  
>     cluster_spinglass                       html  
>     cluster_walktrap                        html  
>     cocitation                              html  
>     cohesive_blocks                         html  
>     communities                             html  
>     compare                                 html  
>     complementer                            html  
>     component_wise                          html  
>     components                              html  
>     compose                                 html  
>     consensus_tree                          html  
>     console                                 html  
>     constraint                              html  
>     contract                                html  
>     convex_hull                             html  
>     coreness                                html  
>     count_isomorphisms                      html  
>     count_motifs                            html  
>     count_subgraph_isomorphisms             html  
>     count_triangles                         html  
>     curve_multiple                          html  
>     decompose                               html  
>     degree                                  html  
>     delete_edge_attr                        html  
>     delete_edges                            html  
>     delete_graph_attr                       html  
>     delete_vertex_attr                      html  
>     delete_vertices                         html  
>     dfs                                     html  
>     diameter                                html  
>     difference                              html  
>     difference.igraph                       html  
>     difference.igraph.es                    html  
>     difference.igraph.vs                    html  
>     dim_select                              html  
>     disjoint_union                          html  
>     distances                               html  
>     diverging_pal                           html  
>     diversity                               html  
>     dominator_tree                          html  
>     dyad_census                             html  
>     each_edge                               html  
>     eccentricity                            html  
>     edge                                    html  
>     edge_attr-set                           html  
>     edge_attr                               html  
>     edge_attr_names                         html  
>     edge_connectivity                       html  
>     edge_density                            html  
>     ego                                     html  
>     eigen_centrality                        html  
>     embed_adjacency_matrix                  html  
>     embed_laplacian_matrix                  html  
>     ends                                    html  
>     erdos.renyi.game                        html  
>     fit_hrg                                 html  
>     fit_power_law                           html  
>     get.edge.ids                            html  
>     girth                                   html  
>     gorder                                  html  
>     graph_                                  html  
>     graph_attr-set                          html  
>     graph_attr                              html  
>     graph_attr_names                        html  
>     graph_from_adj_list                     html  
>     graph_from_adjacency_matrix             html  
>     graph_from_atlas                        html  
>     graph_from_data_frame                   html  
>     graph_from_edgelist                     html  
>     graph_from_graphdb                      html  
>     graph_from_graphnel                     html  
>     graph_from_incidence_matrix             html  
>     graph_from_isomorphism_class            html  
>     graph_from_lcf                          html  
>     graph_from_literal                      html  
>     graph_id                                html  
>     graph_version                           html  
>     graphlet_basis                          html  
>     groups                                  html  
>     gsize                                   html  
>     head_of                                 html  
>     head_print                              html  
>     hrg-methods                             html  
>     hrg                                     html  
>     hrg_tree                                html  
>     hub_score                               html  
>     identical_graphs                        html  
>     igraph-attribute-combination            html  
>     igraph-dollar                           html  
>     igraph-es-attributes                    html  
>     igraph-es-indexing                      html  
>     igraph-es-indexing2                     html  
>     igraph-minus                            html  
>     igraph-vs-attributes                    html  
>     igraph-vs-indexing                      html  
>     igraph-vs-indexing2                     html  
>     igraph_demo                             html  
>     igraph_options                          html  
>     igraph_test                             html  
>     igraph_version                          html  
>     incident                                html  
>     incident_edges                          html  
>     indent_print                            html  
>     intersection                            html  
>     intersection.igraph                     html  
>     intersection.igraph.es                  html  
>     intersection.igraph.vs                  html  
>     is_chordal                              html  
>     is_dag                                  html  
>     is_degseq                               html  
>     is_directed                             html  
>     is_graphical                            html  
>     is_igraph                               html  
>     is_min_separator                        html  
>     is_named                                html  
>     is_printer_callback                     html  
>     is_separator                            html  
>     is_weighted                             html  
>     isomorphic                              html  
>     isomorphism_class                       html  
>     isomorphisms                            html  
>     ivs                                     html  
>     keeping_degseq                          html  
>     knn                                     html  
>     laplacian_matrix                        html  
>     layout.deprecated                       html  
>     layout.fruchterman.reingold.grid        html  
>     layout.spring                           html  
>     layout.svd                              html  
>     layout_                                 html  
>     layout_as_bipartite                     html  
>     layout_as_star                          html  
>     layout_as_tree                          html  
>     layout_in_circle                        html  
>     layout_nicely                           html  
>     layout_on_grid                          html  
>     layout_on_sphere                        html  
>     layout_randomly                         html  
>     layout_with_dh                          html  
>     layout_with_drl                         html  
>     layout_with_fr                          html  
>     layout_with_gem                         html  
>     layout_with_graphopt                    html  
>     layout_with_kk                          html  
>     layout_with_lgl                         html  
>     layout_with_mds                         html  
>     layout_with_sugiyama                    html  
>     local_scan                              html  
>     make_                                   html  
>     make_bipartite_graph                    html  
>     make_chordal_ring                       html  
>     make_clusters                           html  
>     make_de_bruijn_graph                    html  
>     make_empty_graph                        html  
>     make_full_bipartite_graph               html  
>     make_full_citation_graph                html  
>     make_full_graph                         html  
>     make_graph                              html  
>     make_kautz_graph                        html  
>     make_lattice                            html  
>     make_line_graph                         html  
>     make_ring                               html  
>     make_star                               html  
>     make_tree                               html  
>     match_vertices                          html  
>     matching                                html  
>     max_cardinality                         html  
>     max_flow                                html  
>     merge_coords                            html  
>     min_cut                                 html  
>     min_separators                          html  
>     min_st_separators                       html  
>     modularity.igraph                       html  
>     motifs                                  html  
>     mst                                     html  
>     neighbors                               html  
>     nexus                                   html  
>     norm_coords                             html  
>     normalize                               html  
>     page_rank                               html  
>     path                                    html  
>     permute                                 html  
>     pipe                                    html  
>     plot.common                             html  
> Rd warning: /tmp/Rtmp3yDo6J/R.INSTALL3b9e188d129d/igraph/man/plot.common.Rd:184: file link ‘tkfont.create’ in package ‘tcltk’ does not exist and so has been treated as a topic
> Rd warning: /tmp/Rtmp3yDo6J/R.INSTALL3b9e188d129d/igraph/man/plot.common.Rd:186: file link ‘tkfont.create’ in package ‘tcltk’ does not exist and so has been treated as a topic
> Rd warning: /tmp/Rtmp3yDo6J/R.INSTALL3b9e188d129d/igraph/man/plot.common.Rd:217: file link ‘tkfont.create’ in package ‘tcltk’ does not exist and so has been treated as a topic
>     plot.igraph                             html  
>     plot.sir                                html  
>     plot_dendrogram.communities             html  
>     plot_dendrogram.igraphHRG               html  
>     plus-.igraph                            html  
>     power_centrality                        html  
>     predict_edges                           html  
>     print.igraph                            html  
>     print.igraph.es                         html  
>     print.igraph.vs                         html  
>     print.igraphHRG                         html  
>     print.igraphHRGConsensus                html  
>     printer_callback                        html  
>     printr                                  html  
>     r_pal                                   html  
>     radius                                  html  
>     random_walk                             html  
>     read_graph                              html  
>     reciprocity                             html  
>     rep.igraph                              html  
>     rev.igraph.es                           html  
>     rev.igraph.vs                           html  
>     rewire                                  html  
>     rglplot                                 html  
>     running_mean                            html  
>     sample_                                 html  
>     sample_bipartite                        html  
>     sample_correlated_gnp                   html  
>     sample_correlated_gnp_pair              html  
>     sample_degseq                           html  
>     sample_dirichlet                        html  
>     sample_dot_product                      html  
>     sample_fitness                          html  
>     sample_fitness_pl                       html  
>     sample_forestfire                       html  
>     sample_gnm                              html  
>     sample_gnp                              html  
>     sample_grg                              html  
>     sample_growing                          html  
>     sample_hierarchical_sbm                 html  
>     sample_hrg                              html  
>     sample_islands                          html  
>     sample_k_regular                        html  
>     sample_last_cit                         html  
>     sample_motifs                           html  
>     sample_pa                               html  
>     sample_pa_age                           html  
>     sample_pref                             html  
>     sample_sbm                              html  
>     sample_seq                              html  
>     sample_smallworld                       html  
>     sample_sphere_surface                   html  
>     sample_sphere_volume                    html  
>     sample_traits_callaway                  html  
>     scan_stat                               html  
>     scg-method                              html  
>     scg                                     html  
>     scg_eps                                 html  
>     scg_group                               html  
>     scg_semi_proj                           html  
>     sequential_pal                          html  
>     set_edge_attr                           html  
>     set_graph_attr                          html  
>     set_vertex_attr                         html  
>     shapes                                  html  
>     similarity                              html  
>     simplified                              html  
>     simplify                                html  
>     sir                                     html  
>     spectrum                                html  
>     split_join_distance                     html  
>     srand                                   html  
>     st_cuts                                 html  
>     st_min_cuts                             html  
>     stochastic_matrix                       html  
>     strength                                html  
>     sub-.igraph                             html  
>     sub-sub-.igraph                         html  
>     subcomponent                            html  
>     subgraph                                html  
>     subgraph_centrality                     html  
>     subgraph_isomorphic                     html  
>     subgraph_isomorphisms                   html  
>     tail_of                                 html  
>     tkigraph                                html  
>     tkplot                                  html  
>     topo_sort                               html  
>     transitivity                            html  
>     triad_census                            html  
>     unfold_tree                             html  
>     union                                   html  
>     union.igraph                            html  
>     union.igraph.es                         html  
>     union.igraph.vs                         html  
>     unique.igraph.es                        html  
>     unique.igraph.vs                        html  
>     upgrade_graph                           html  
>     vertex                                  html  
>     vertex.shape.pie                        html  
>     vertex_attr-set                         html  
>     vertex_attr                             html  
>     vertex_attr_names                       html  
>     vertex_connectivity                     html  
>     which_multiple                          html  
>     which_mutual                            html  
>     with_edge_                              html  
>     with_graph_                             html  
>     with_igraph_opt                         html  
>     with_vertex_                            html  
>     without_attr                            html  
>     without_loops                           html  
>     without_multiples                       html  
>     write_graph                             html  
> ** building package indices
> ** testing if installed package can be loaded
> Error: package or namespace load failed for ‘igraph’ in dyn.load(file, DLLpath = DLLpath, ...):
>  无法载入共享目标对象‘/usr/lib64/R/library/igraph/libs/igraph.so’：:
>   libiconv.so.2: 无法打开共享对象文件: 没有那个文件或目录
> 错误: 载入失败
> 停止执行
> ERROR: loading failed
> * removing ‘/usr/lib64/R/library/igraph’
> 
> 下载的程序包在
> 	‘/tmp/RtmpW4k2q2/downloaded_packages’里
> 更新'.Library'里的HTML程序包列表
> Making 'packages.html' ... 做完了。
> Warning message:
> In install.packages("igraph") : 安装程序包‘igraph’时退出狀態的值不是0

**Comment by ntamas** [comment]
Are you using CentOS or Redhat Linux? You need to install the libiconv package manually on these machines as it is not part of the standard installation but igraph needs it.

**Comment by Lily-WL** [comment]
The library file was in my folders, but just not in the default path （in the /usr/local/lib）. So I tried to add the path. Seems it worked. The command is as follows.

> echo "/usr/local/lib" >> /etc/ld.so.conf
> ldconfig

**Comment by ntamas** [comment]
Closing it as resolved then; feel free to reopen if needed.
