### ISSUE TITLE
igraph:::write.graph.dot() uses "name" instead of "label"

### ISSUE THREAD

**Issue by kenahoo** [igraph/rigraph#309]
Not sure whether "name" is an older version of "label" in the GraphViz spec, or what.  I don't see "name" listed at https://www.graphviz.org/doc/info/attrs.html .

In any case, when I did `igraph::write_graph(g, 'deps.dot', format = 'dot')`, I got a file that starts like this:

```
/* Created by igraph 1.2.2 */
digraph {
  0 [
    name=LoadFX
  ];
  1 [
    name=assertthat
  ];
  2 [
    name=crayon
  ];
  3 [
    name=mime
  ];
  ...
```

After doing `dot deps.dot -Tpdf > deps.pdf`, there were no labels shown on the nodes, only the numeric IDs.  

I bulk changed all the labels by doing `perl -pi -e 's/name=/label=/g' deps.dot`, and then when I build the PDF, the labels are shown as desired.

**Comment by ntamas** [comment]
Just stumbled upon this issue while cleaning up the issue tracker. For future reference: igraph uses the `name` vertex attribute in R to store a string identifier for each vertex. When you save the graph in GraphViz format, igraph simply writes the value of each vertex attribute (except the ones storing complex R objects) into the output file. If you want to use `label` in the output file, create a `label` vertex attribute in igraph first:

```
V(g)$label <- V(g)$name
```
