### ISSUE TITLE
installation failed for package clusterProfiler

### ISSUE THREAD

**Issue by songh-ss** [igraph/rigraph#311]
HI， all！ I can' t install clusterProfiler! 
There is my R version:

R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.1 LTS

How to solve these problems?  Please HELP! THANKS
Warning messages:
1: In install.packages(pkgs = doing, lib = lib, repos = repos, ...) :
  installation of package ‘units’ had non-zero exit status
2: In install.packages(pkgs = doing, lib = lib, repos = repos, ...) :
  installation of package ‘ggforce’ had non-zero exit status
3: In install.packages(pkgs = doing, lib = lib, repos = repos, ...) :
  installation of package ‘ggraph’ had non-zero exit status
4: In install.packages(pkgs = doing, lib = lib, repos = repos, ...) :
  installation of package ‘enrichplot’ had non-zero exit status
5: In install.packages(pkgs = doing, lib = lib, repos = repos, ...) :
  installation of package ‘clusterProfiler’ had non-zero exit status

**Comment by gaborcsardi** [comment]
This is a repository for igraph, which apparently does not have much to do with your  problems.
