### ISSUE TITLE
Installation failed: Does not appear to be an R package (no DESCRIPTION)

### ISSUE THREAD

**Issue by olyerickson** [igraph/rigraph#316]
When attempting to install either the main and dev versions of `igraph` this morning I see:

```
> devtools::install_git("https://github.com/igraph/rigraph.git")
Downloading git repo https://github.com/igraph/rigraph.git
Installation failed: Does not appear to be an R package (no DESCRIPTION)
```

**Comment by prehensilecode** [comment]
The proper invocation is:
```
devtools::install_github("igraph/rigraph")
```
It's correct in the README.md, seen at the main github page for this project.

**Comment by krlmlr** [comment]
This no longer works due to changes in the devtools package, https://github.com/igraph/rigraph/issues/384.

**Comment by vtraag** [comment]
Installation should be done using `remotes:install_github("igraph/rigraph@master")`. To be clear, the code in the `master` branch is automatically generated based on the code in the `dev` branch. I have clarified this in the documentation in f8298b0b8f925ca0893548f28c5b53610d620785.

**Comment by mtaghizadehbioinf** [comment]
The comment form vtraag was useful. thanks vtraag.
