### ISSUE TITLE
layout_with_mds

### ISSUE THREAD

**Issue by TiagoVentura** [igraph/rigraph#320]
Hi all, 

I have been trying to estimate a layout_with_mds in a large network, with 160.000 nodes. I am running on problems related to  memory space,  of course because of  the distance matrix, and when I try to chop the data, I run into issues of not being able to estimate the models with a non-square matrix. I understand the question is not exactly related to the package, but do you have any suggestion on how to deal with this while keep using the function layout_with_mds. 

Thank you so very much.

**Comment by szhorvat** [comment]
If the question is still relevant, please re-post on the forum, https://igraph.discourse.group/
