### ISSUE TITLE
induced.subgraph() inherits the layout of its parent

### ISSUE THREAD

**Issue by ghost** [igraph/rigraph#330]
This code works correctly:

```
rm(list=ls())
library(igraph)

nodes <- read.csv("./coauthorship_nodes.csv", header=TRUE, as.is=T, encoding="UTF-8", stringsAsFactors=FALSE)

links <- read.csv("./coauthorship_links.csv", header=T, as.is=T, encoding="UTF-8", stringsAsFactors=FALSE)

net <- graph_from_data_frame(d=links, vertices=nodes, directed=F)
net <- simplify(net)

# Layout for the VCs
net$layout <- layout_with_fr(net)

# Giant component
netclust = clusters(net)
gcc = V(net)$name[netclust$membership==which.max(netclust$csize)]
gccnet = induced.subgraph(net, gcc, impl = "create_from_scratch")
gccnet$layout <- layout_with_kk
plot(gccnet)
```

![gcc](https://user-images.githubusercontent.com/1469713/55078034-7387aa80-5099-11e9-9ccd-6390c215fb27.png)

But if you comment line 18:
`gccnet$layout <- layout_with_kk`

The plot will be now meesed up:

![gcc_bugged](https://user-images.githubusercontent.com/1469713/55078074-8a2e0180-5099-11e9-9182-42e0ac79fb98.png)

I think that `induced.subgraph()` somehow inherits the layout from the parent. but I am not sure

**Comment by mbojan** [comment]
@raffam `graph$layout` can be two things:

1. precomputed 2-column matrix of vertex coordinates
2. a function called on igraph object returning a matrix of coordinates such as (1)

In both cases it is preserved by `induced.subgraph()`. As such the behavior is consistent with the documentation. On the other hand it may be argued that while preserving `graph$layout` makes sense in case (2) it might not make sense in case (1).

**Comment by szhorvat** [comment]
This behaviour comes from the C core, and cannot be changed there.

A possible fix on the R side would be to verify what the `layout` attribute is, and handle it accordingly (probably subset the coordinates). Ultimately, IMO coordinates should be stored as a vertex attribute, not a graph attribute.

**Comment by ntamas** [comment]
Actually, you can store the coordinates as vertex attributes; the exact algorithm is documented in `layout_nicely`, which is the default layout of the graph when no layout is passed to `plot()`:

> ‘layout_nicely’ tries to choose an appropriate layout function for the supplied graph, and uses that to generate the layout. The current implementation works like this:
> 1. If the graph has a graph attribute called ‘layout’, then this is used. If this attribute is an R function, then it is called, with the graph and any other extra arguments.
> 2. Otherwise, if the graph has vertex attributes called ‘x’ and ‘y’, then these are used as coordinates. If the graph has an additional ‘z’ vertex attribute, that is also used.
> 3. Otherwise, if the graph is connected and has less than 1000 vertices, the Fruchterman-Reingold layout is used, by calling ‘layout_with_fr’.
> 4. Otherwise the DrL layout is used, ‘layout_with_drl’ is called.

So, if you use the `layout` attribute and store a matrix in it, you need to ensure that the matrix is updated accordingly when taking a subset of the graph. We could in theory special-case this attribute in `induced.subgraph()`, but there are other operations that update the vertex set of the graph and introducing a special code path to handle the `layout` attribute in all these places does not seem like a good idea to me.

I'd simply refrain from supplying the `layout` graph attribute with a matrix. If a matrix is to be used, this matrix should be stored in the `x` and `y` vertex attributes instead.

I'm closing this for the time being but feel free to reopen if you disagree.
