### ISSUE TITLE
failed to install igraph

### ISSUE THREAD

**Issue by xiwa2006** [igraph/rigraph#335]
I tried to install.packages("igraph") and got below errors. 

installing to /home/xwang/R/x86_64-pc-linux-gnu-library/3.4/igraph/libs
** R
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘igraph’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/xwang/R/x86_64-pc-linux-gnu-library/3.4/igraph/libs/igraph.so':
  libgfortran.so.4: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/xwang/R/x86_64-pc-linux-gnu-library/3.4/igraph’
The downloaded source packages are in
	‘/tmp/RtmpyOUq7X/downloaded_packages’
Warning message:
In install.packages("igraph") :
  installation of package ‘igraph’ had non-zero exit status

My environment is as below.
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /opt/sw/R/3.4.4/lib/R/lib/libRblas.so
LAPACK: /opt/sw/R/3.4.4/lib/R/lib/libRlapack.so

**Comment by harryprince** [comment]
@xiwa2006
it is your `fortran` problem on your system.

**Comment by matteodelucchi** [comment]
same issue as #275

**Comment by 960801** [comment]
I have a similar issue on my ubuntu 20.04 with R version 4.1.0 and I get the error below:

Error: package or namespace load failed for ‘igraph’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/eric/R/x86_64-pc-linux-gnu-library/4.1/00LOCK-igraph/00new/igraph/libs/igraph.so':
  libmkl_rt.so: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/eric/R/x86_64-pc-linux-gnu-library/4.1/igraph’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpVqyzxf/file58a6db5e9bc/igraph_1.2.6.9118.tar.gz’ had non-zero exit status

one solution suggested creating  "~/.R/Makevar"  and setting:
CC = clang
CXX = clang++
this doesn't seem to work or I'm doing something wrong.
is there a way of handling this error?
Thanks in advance

**Comment by ntamas** [comment]
Try installing the `libmkl-rt` package; this is the one that contains `libmkl_rt.so`: https://packages.ubuntu.com/search?searchon=contents&keywords=libmkl_rt&mode=filename&suite=hirsute&arch=any

**Comment by 960801** [comment]
> Try installing the `libmkl-rt` package; this is the one that contains `libmkl_rt.so`: https://packages.ubuntu.com/search?searchon=contents&keywords=libmkl_rt&mode=filename&suite=hirsute&arch=any

This worked perfectly. Thank you very much.

This is where I found the package (if anyone comes across the same problem):
https://www.ubuntuupdates.org/package/core/hirsute/multiverse/base/libmkl-rt

**Comment by FloHu** [comment]
Update: I solved it, see my answer here: https://github.com/igraph/rigraph/issues/275#issuecomment-947940126
