### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by tikboaHIT** [igraph/rigraph#340]
Hey all, super new to this, so go easy! I am getting this error, which I have no idea what it is.

make: *** [AMD/Source/amd.o] Error 1
ERROR: compilation failed for package ‘igraph’

so, Any one help me?
thanks

**Comment by gaborcsardi** [comment]
You need a fortran compiler.

**Comment by gaborcsardi** [comment]
Also, why did you remove the `make: gfortran-4.8: No such file or directory` line? Is that not the error message any more?
