### ISSUE TITLE
Inconsistency between `mean_distance` and averaging `distances` result for directed graph

### ISSUE THREAD

**Issue by vkehayas** [igraph/rigraph#341]
I have observed what appears to me an inconsistency between using `mean_distance` and
taking the average of the output from `distances` for an example
directed graph (in the attached), where two of the nodes have no incoming connections.

``` r
library(igraph)
```

    ## 
    ## Attaching package: 'igraph'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     decompose, spectrum

    ## The following object is masked from 'package:base':
    ## 
    ##     union

``` r
g = readRDS("g.rds")

A = as.array(get.adjacency(g))

dim(A)
```

    ## [1] 213 213

``` r
sum(A[, 83] == 0)
```

    ## [1] 213

``` r
sum(A[83, ] == 0)
```

    ## [1] 212

Since this example node has no incoming connections in this directed
graph, I would expect that when I use function `distances` I would only
get `Inf` at the corresponding column. This is indeed what I get using
the Brain Connectivity Toolbox (version 2019\_03\_03) in MATLAB.

``` octave
% after importing A
D = distance_bin(A);
```

As a result, when I next calculate the mean shortest distance

``` r
d = distances(g)
diag(d) = NA_real_
mean(d, na.rm = TRUE)
```

    ## [1] 1.904376

I get a result different than when using `mean_distance`

``` r
mean_distance(g)
```

    ## [1] 1.920916

Using MATLAB’s toolbox I get the same result as this last operation when
averaging the shortest distance matrix (after replacing the diagonal and
`Inf`s with `NaN`).

[g.zip](https://github.com/igraph/rigraph/files/3232968/g.zip)

**Comment by vkehayas** [comment]
Here is a translation of the MATLAB function `distance_bin` from the BCT toolbox in R that gives the expected results:

```r
CalculateDistance = function(A) {
  
  A = (A != 0) * 1
  
  l = 1
  Lpath = A
  D = A
  
  Idx = TRUE
  while (any(Idx)) {
    l = l + 1
    Lpath = Lpath %*% A
    Idx = (Lpath != 0) & (D == 0)
    D[Idx] = l
  }
  
  D[!D] = Inf
  diag(D) = 0
  
  return(D)
  
}
```

**Comment by szhorvat** [comment]
I am not very experienced with the R interface of igraph (or R), but it appears that `distances(g)` ignores edge directions. Use `distances(g, mode = 'out')` and it'll be fine.

```R
dm <- distances(g)
diag(dm) <- NA
dm[sapply(dm, is.infinite)] <- NA
mean(dm, na.rm = T)
```

The output is `1.920916`
