### ISSUE TITLE
Add new method to degree.sequence.game

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#343]
I am relaying a request communicated to me offline.

Please update `degree.sequence.game` in R with the new method (configuration model) added to the C core.

https://github.com/igraph/igraph/blob/master/src/games.c#L1409

It's called `IGRAPH_DEGSEQ_SIMPLE_NO_MULTIPLE_UNIFORM` in the C core, but this name is not ideal. This method samples simple graphs uniformly.  What's confusing in the naming is that "simple" refers to a "simple method" and not to simple graphs. 

It would also be good to update the R documentation with the new information I added to the description of the C function (probabilities of graphs depending on edge and self-loop multiplicities, see `IGRAPH_DEGSEQ_SIMPLE`).

**Comment by ntamas** [comment]
`sample_degseq()` now accepts `simple.no.multiple.uniform` as a possible value for the `method` parameter.
