### ISSUE TITLE
R: graph colouring

### ISSUE THREAD

**Issue by ugroempi** [igraph/rigraph#345]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [ ] This issue is for the C core of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

Dear igraph team,

I would really like graph colouring in the R version of igraph, which does not seem to have the heuristic `vertex_coloring_greedy` function that is referenced in issue igraph/igraph#1090. Of course, it would be even better to have an exact implementation.

I am so far using the `cluster_spinglass` function with negative weights, `spins` equal to the number of colors, `implementation="neg"` and `gamma.minus=0` (as suggested in the documentation of argument `gamma.minus`). The outcome is random, and it often but not always gives me groups of suitable colors; unfortunately, it also gives me a grouping, if colouring in the requested number of colors is not possible. 

Thus, if the greedy function improves on any of that, I would love to see it also in igraph on R.

Best, Ulrike

**Comment by szhorvat** [comment]
I just wanted to note that [the Mathematica interface of igraph](http://szhorvat.net/mathematica/IGraphM) includes also an _exact_ (and very competitive) graph colouring algorithm.  This is currently implemented in Mathematica and it is based on a SAT encoding of the problem.

Of course, it would be nice to include this in the base igraph C library directly someday, but it takes some work and would require shipping a SAT solver with igraph (which may not be a big burden as tiny, single header C++ SAT solvers are available).

**Comment by ugroempi** [comment]
Thanks for the pointer. However, including functionality from Mathematica in an R package is not really an option ...

**Comment by ntamas** [comment]
FYI, the `dev` branch now includes `greedy_vertex_coloring`, which is a lightweight wrapper around `igraph_vertex_coloring_greedy()` in the C library.

**Comment by szhorvat** [comment]
> FYI, the `dev` branch now includes `greedy_vertex_coloring`

This is now released in 1.3.0, so closing.

**Comment by ugroempi** [comment]
Thank you!
