### ISSUE TITLE
Can't install igraph in R 3.4.3

### ISSUE THREAD

**Issue by gholl0** [igraph/rigraph#347]
I'm trying to install a package called phangorn and it requires igraph to install but igraph is constantly failing. Here is a small portion of the errors I get:

CHOLMOD/Check/cholmod_check.c:86:9: error: 'cholmod_common {aka struct cholmod_common_struct}' has no member named 'print_function'
  (Common->print_function) (format, arg) ; \
         ^
CHOLMOD/Check/cholmod_check.c:93:24: note: in expansion of macro 'PR'
 #define P4(format,arg) PR(4,format,arg)
                        ^~
CHOLMOD/Check/cholmod_check.c:2205:5: note: in expansion of macro 'P4'
     P4 ("%s", "\n") ;
     ^~
And then:

In install.packages("igraph", repos = "http://cran.r-project.org") :
  installation of package ‘igraph’ had non-zero exit status

I've tried some fixes from other people who have had this issue but none of them worked. Any suggestions?

**Comment by DevGra** [comment]
I had the same problem. They say it's the fortran compiler. I will try to install again!
https://cygwin.com/install.html
