### ISSUE TITLE
how to make the output higher resolution

### ISSUE THREAD

**Issue by lijing28101** [igraph/rigraph#350]
Hi, I used igraph to make a network plot, but the resolution is low when I export the plot, especially for the label on the plot. Is there a good way to make the plot clear?
![cluster112net](https://user-images.githubusercontent.com/22349573/66594037-d6d0ba00-eb5d-11e9-9b4b-71a716cde671.jpeg)

**Comment by mbojan** [comment]
Suggestions:

- Increase the resolution of the device, say: `png(width=1000, height=1000)`
- Switch to a sans serif font for vertex labels using `vertex.label.family="sans"` argument to `plot.igraph()`
- Consider using different colors...
