### ISSUE TITLE
Modularity and louvain_cluster to accept signed networks and resolution parameter?

### ISSUE THREAD

**Issue by coelhocao** [igraph/rigraph#356]
Hi,

Current calculation of `modularity` and `modularity_matrix` are not correct for signed networks.
I know a few articles that present alternatives to the Newman(2004) definition.
[Traag & Bruggeman 2009](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.80.036115)
[Gomez et al 2009](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.80.016114) 
[Kaplan & Forrest (2008)](http://scholar.google.ca/scholar_url?url=https://arxiv.org/pdf/0801.3290&hl=en&sa=X&scisig=AAGBfm0AaXENsBpPN7rH-i1UFxSlmRpJ4w&nossl=1&oi=scholarr) 
and the best definition for neuroscience [Rubinov & Sporns (2011)](https://www.sciencedirect.com/science/article/abs/pii/S105381191100348X)

All of them are but little tweeks in the equation from Newman 2004. Any chance to include any of these options so as to accommodate signed networks? I am trying to code the last one, but I know most coding behind igraph is sourced in C.
Also, some of them include the resolution parameter as something to be tuned, which is also something super useful for multiscale community detection. 

Same thing applies for `cluster_louvain` algorithm. Would it be possible to make this function accept signed networks and be tuned by a resolution parameter??

**Comment by vtraag** [comment]
The implementation of Jeroen and me ([2009](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.80.036115)) has been implemented under
https://igraph.org/r/doc/cluster_spinglass.html, you have to choose `implementation="neg"`. It is not the fasted algorithm however. If you are willing to switch to Python (but still using `igraph`), you can use the [`leidenalg`](https://github.com/vtraag/leidenalg) package, which is not only suitable for community detection in signed networks, but in multiplex networks more generally.

**Comment by coelhocao** [comment]
Hi @vtraag, 

Thanks for the reply. I realized later that the `clust_spinglass()` function does accept signed networks. That is super!
I ran it on my data and got very close results to those I found using `cluster_louvain()`. However, I do need to deal with multi-scale communities, and `cluster_spinglass()` doesn't deal with that. There is a gamma and a gamma.minus parameters there, but they are not the resolution parameter (often referred to as gamma).
I looked at your `leidenalg` package and it seems awesome. But I can't switch everything I have in R to Python now.

**Comment by vtraag** [comment]
It is possible you get similar results to `cluster_louvain`. I'm not sure though why you say that `gamma` and `gamma.minus` are not the resolution parameters? They correspond to `gamma^+` and `gamma^-` in Eq. (10) in our paper. So you should be able to look at communities at different scales/resolutions.

**Comment by coelhocao** [comment]
My apologies. I replied after a single test of the function and badly reading the description in the manual. Indeed, they're parameter resolutions.
This function is pretty awesome. Thanks a lot, @vtraag

**Comment by szhorvat** [comment]
Closing since `leiden` is now exposed in R/igraph.

**Comment by vtraag** [comment]
Just noting here that the `leiden` implementation in `igraph` itself does not work for multiplex networks in general. One would still need to use the package [`leidenalg`](https://github.com/vtraag/leidenalg) for a multiplex approach. If one is using CPM however, the `leiden` implementation in `igraph` will actually be identical to a multiplex implementation, since the two resolution parameters `gamma^+` and `gamma^-` are degenerate, and simply correspond to an overall resolution parameter of `gamma = gamma^+ - gamma^-`.

The issue can remain closed though.

**Comment by szhorvat** [comment]
See also #239.
