### ISSUE TITLE
Cannot install igraph with Rtools (config.h not found)

### ISSUE THREAD

**Issue by cslycord** [igraph/rigraph#357]
I've uninstalled and reinstalled Rtools (version 3.5) and keep getting the same error and this is when running r as an administrator. igraph_blas_internal.h tries to use config.h which doesn't appear to exist.

I receive the following output:

`c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-36~1.1/include" -DNDEBUG -I/include/libxml2 -I/include -DLIBXML_STATIC -DUSING_R -DHAVE_FMEMOPEN=0 -DHAVE_OPEN_MEMSTREAM=0 -DHAVE_RINTF -DWin32 -DHAVE_LIBXML -Wall -DPACKAGE_VERSION=\"1.2.4\" -DHAVE_FMIN=1 -DHAVE_LOG2=1 -DHAVE_SNPRINTF -Ics -I/include -DHAVE_GLPK=1 -Iplfit -Iprpack -DIGRAPH_THREAD_LOCAL= -DPRPACK_IGRAPH_SUPPORT -I. -Iinclude -ICHOLMOD/Include -IAMD/Include -ICOLAMD/Include -ISuiteSparse_config -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -I/include      -DINTERNAL_ARPACK -I. -I/include -DHAVE_GFORTRAN   -O3 -Wall  -std=gnu99 -mtune=generic -c CHOLMOD/Supernodal/cholmod_super_numeric.c -o CHOLMOD/Supernodal/cholmod_super_numeric.o
In file included from CHOLMOD/Supernodal/cholmod_super_numeric.c:63:0:
./igraph_blas_internal.h:33:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
make: *** [C:/PROGRA~1/R/R-36~1.1/etc/i386/Makeconf:208: CHOLMOD/Supernodal/cholmod_super_numeric.o] Error 1
ERROR: compilation failed for package 'igraph'
* removing 'C:/Program Files/R/R-3.6.1/library/igraph'
* restoring previous 'C:/Program Files/R/R-3.6.1/library/igraph'`

**Comment by grandtiger** [comment]
I got exactly the same error with both R-3.6.1 and latest R-Testing using Rtools4.0. 

Please refer to issue: https://github.com/r-windows/checks/issues/87 for details.

**Comment by vtraag** [comment]
@grandtiger, it should now be possible to build the latest version of `igraph` using Rtools4.0 on Windows using `remotes::install_github("igraph/rigraph@master")`. Make sure that you also install the dependencies using
```
pacman -Sy mingw-w64-{i686,x86_64}-glpk mingw-w64-{i686,x86_64}-libxml2 mingw-w64-{i686,x86_64}-gmp
```
I am now closing this issue, assuming that most Windows users will either use R>=4.0, or install from CRAN.

**Comment by pagarwal14** [comment]
Hi,
I have a need to work with the older version and am getting the same error.  Is there a way to fix this issue.  Thanks.
