### ISSUE TITLE
as.undirected with collapse problems

### ISSUE THREAD

**Issue by topl0305** [igraph/rigraph#358]
> igraph.version()
[1] "1.2.4"

I have a directed graph:
```
> E(test)
+ 7/7 edges from 66aec76:
[1] 1->2 2->1 1->3 3->1 1->4 4->1 1->4
> E(test)$weight
[1] 0.2127543 0.4225179 0.4309004 0.7738692 0.4018366 0.7604413 0.3113901
```
And create an undirected one with collapse:
`> test_u = as.undirected(test, "collapse")`

And get the next result:
```
> E(test_u)
+ 3/3 edges from ef1f2dc:
[1] 1--2 1--3 1--4
> E(test_u)$weight
[1] 1.037109 1.204770 1.071831
```
And here is the problem. Edge 1--2 has weight 1.03 instead of 0.64. It looks like the weight of  first edge 1--4 (from possible 2) is added to this edge's weight.

**Comment by szhorvat** [comment]
This works correctly in the 1.3 dev version, closing.

```
g<-graph_from_literal(1-+2, 2-+1, 1-+3, 3-+1, 1-+4, 4-+1, 1-+4, simplify = F)
E(g)$weight <- c(0.2127543, 0.4225179, 0.4309004, 0.7738692, 0.4018366, 0.7604413, 0.3113901)
```

```
> g2<-as.undirected(g, mode='collapse')
> E(g2)
+ 3/3 edges from f2194e8 (vertex names):
[1] 1--2 1--3 1--4
> E(g2)$weight
[1] 0.6352722 1.2047696 1.4736680
```

It was fixed in C/igraph 0.9.5: https://github.com/igraph/igraph/releases/tag/0.9.5
