### ISSUE TITLE
gfortran 10: rank mismatch

### ISSUE THREAD

**Issue by Enchufa2** [igraph/rigraph#363]
The internal LAPACK version fails to compile with the following error (this is for R-igraph):

```
...
gfortran -m64 -fno-optimize-sibling-calls  -fpic  -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection --no-optimize-sibling-calls  -c dgetv0.f -o dgetv0.o
f951: Warning: '-Werror=' argument '-Werror=format-security' is not valid for Fortran
dgetv0.f:404:38:

  367 |           call igraphdvout (logfil, 1, rnorm0, ndigit,
      |                                       2
......
  404 |          call igraphdvout (logfil, n, resid, ndigit,
      |                                      1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
make: *** [/usr/lib64/R/etc/Makeconf:191: dgetv0.o] Error 1
```

- Complete log: https://copr-be.cloud.fedoraproject.org/results/iucar/cran/fedora-rawhide-x86_64/01194885-R-CRAN-igraph/builder-live.log.gz
- Info about the specific change in gcc 10: https://gcc.gnu.org/gcc-10/porting_to.html#argument-mismatch

**Comment by Enchufa2** [comment]
Ok, I found it: https://github.com/igraph/rigraph/blob/dev/tools/arpack/dgetv0.f

**Comment by daissi** [comment]
Same bug was reported on Debian side: [#957739](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957739)

**Comment by Enchufa2** [comment]
There seems to be a fix for this (https://github.com/igraph/rigraph/commit/35cd06b1d61d0ae5b40bdf9c7069ce2a1a2e20e5), but I'm not sure whether this has been rolled out to CRAN already. @gaborcsardi ?

**Comment by gaborcsardi** [comment]
It has indeed. You can also suppress these with a compiler flag I believe.

**Comment by Enchufa2** [comment]
Yes, I was temporarily suppressing these on Fedora, but I was waiting for this issue to remove that flag. I confirm that the latest release [builds correctly in rawhide without the flag](https://download.copr.fedorainfracloud.org/results/iucar/cran/fedora-rawhide-x86_64/01342278-R-CRAN-igraph/builder-live.log.gz), so closing this. Thanks!

**Comment by PrashantPaunipagar** [comment]
@Enchufa2 can you please help me out with this error i don't understand it:
fortran -c -O3 -mtune=native -fPIC   -I/Software/amber14-20210312T102927Z-001/amber14/include -I/Software/amber14-20210312T102927Z-001/amber14/include   -o dgetv0.o dgetv0.f
dgetv0.f:404:38:

  367 |           call igraphdvout (logfil, 1, rnorm0, ndigit,
      |                                       2
......
  404 |          call igraphdvout (logfil, n, resid, ndigit,
      |                                      1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
make[2]: *** [Makefile:7: dgetv0.o] Error 1
make[2]: Leaving directory '/Software/amber14-20210312T102927Z-001/amber14/AmberTools/src/arpack'
make[1]: *** [Makefile:19: serial] Error 2
make[1]: Leaving directory '/Software/amber14-20210312T102927Z-001/amber14/AmberTools/src'
make: *** [Makefile:7: install] Error 2

**Comment by Enchufa2** [comment]
Just update arpack.

**Comment by PrashantPaunipagar** [comment]
and how to update this?

**Comment by Enchufa2** [comment]
I see you are compiling a software called Amber. Please, refer to the [communication channels](https://ambermd.org/MailingLists.php) set by the authors of that software to ask for help with this.
