### ISSUE TITLE
Running make using multiple jobs fails

### ISSUE THREAD

**Issue by vtraag** [igraph/rigraph#366]
When running `make` in order to build the source tarball `igraph_[VERSION].tar.gz`, it pre-compiles the YACC and LEX files. The rules that are used to compile it are not compatible with using multiple jobs (using `-j`). This is presumably due to the fact that building those files use the same temporary files:
https://github.com/igraph/rigraph/blob/5e7a689afde1864c2f36b2a7825db24f2f89b22b/Makefile#L45-L52
This does not seem to be a problem when building C `igraph`, which can be built using parallel jobs. The resulting `automake` build rule is somewhat different than what seems to be required here:
```Makefile
.l.c:
	$(AM_V_LEX)$(am__skiplex) $(SHELL) $(YLWRAP) $< $(LEX_OUTPUT_ROOT).c $@ -- $(LEXCOMPILE)

.y.c:
	$(AM_V_YACC)$(am__skipyacc) $(SHELL) $(YLWRAP) $< y.tab.c $@ y.tab.h `echo $@ | $(am__yacc_c2h)` y.output $*.output -- $(YACCCOMPILE)
```
I'm not immediately sure how to translate this to the more simpler `Makefile` that is used to build the source tarball for R `igraph`. If the `Makefile` remains incompatible with parallel builds, we should at least make sure to document it somewhere.

**Comment by QuLogic** [comment]
In Make, `$*` is the stem, i.e., the part that matches `%` in the rule. This can be used to generate temporary file names that are specific to each input.

**Comment by vtraag** [comment]
The `$(YLWRAP)` script uses a temporary directory to copy the resulting `y.tab.c` and `y.tab.h` to the intended destination/name. Something similar should be done in this `Makefile` in order to support parallel builds.

**Comment by QuLogic** [comment]
I would not consider this actually fixed.

**Comment by vtraag** [comment]
> I would not consider this actually fixed.

The original complaint was that it failed, it now no longer fails. Surely it can be made more efficient, but the `make` is only used when bootstrapping the build from the GitHub repository, and takes relatively little time. The compilation of the source code itself takes substantially more time, and parallel building is correctly supported there. So as far as I'm concerned we can consider this fixed.

Having said that, if you have an improvement over simply forcing a non-parallel build @QuLogic, that would of course be welcome!
