### ISSUE TITLE
cannot install igraph

### ISSUE THREAD

**Issue by vronizor** [igraph/rigraph#367]
Hello,

I am running R Studio on macOS Catalina 10.15.3. I get this error when trying to install igraph. Any idea what is going wrong?

```
** libs
gfortran  -fPIC  -Wall -g -O2  -c AMD/Source/amd.f -o AMD/Source/amd.o
make: gfortran: No such file or directory
make: *** [AMD/Source/amd.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/Users/vinceth/Library/R/3.6/library/igraph’
Warning in install.packages :
  installation of package ‘igraph’ had non-zero exit status
```

Thanks

**Comment by gaborcsardi** [comment]
Do you really want to install the source package?

**Comment by vronizor** [comment]
I was just running `install.package("igraph")` when this happened. Isn't this the normal procedure to install a package?

Anyway I found the solution, I simply installed gfortran through homebrew (`brew cask install gfortran`) and then relaunched the install package command in R studio.
