### ISSUE TITLE
Details of laplacian_matrix() is not clear

### ISSUE THREAD

**Issue by myildir3** [igraph/rigraph#370]
Hello,

I think there is a typo in the details of  `laplacian_matrix()` function. "...the degree of vertex i if
if i==j, -1 if i!=j ...". I think first "if" should be 1. Also, could you explain `d[i]` a little bit clearer? 

Thank you,

**Comment by szhorvat** [comment]
The typo is that `if if` should be `if`.

`d[i]` denotes the [degree](https://en.wikipedia.org/wiki/Degree_(graph_theory)) of vertex `i`.

Put simply, the Laplacian matrix of an undirected graph is the same as the negative adjacency matrix, except that it has the degrees on the diagonal. This ensures that each row/column sums to zero.
