### ISSUE TITLE
Help for drawing a similar graph in rigraph

### ISSUE THREAD

**Issue by pmp55** [igraph/rigraph#371]
I was wondering how to draw a network diagram with cluster like this in rigraph.   
![topicrelationgraph](https://user-images.githubusercontent.com/10841327/74634647-3fc8de00-519f-11ea-9f47-8168f8a7010b.jpg)

Any code snippets or hints are really appreciated!

**Comment by szhorvat** [comment]
For support questions, please use the forum at https://igraph.discourse.group/
