### ISSUE TITLE
Error installing the igraph package for Seurat

### ISSUE THREAD

**Issue by Osterhhase** [igraph/rigraph#377]
Hey guys,
I'm trying to install Seurat to use the tutorials with following functions:

install.packages('BiocManager')
BiocManager::install('multtest')
install.packages('Seurat')
library(Seurat)

The following Error occurs for the last part - library(Seurat):

library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
there is no package called ‘igraph'

After this I tried to install the igraph package (install.packages("igraph")) and this error occurred:

ERROR: compilation failed for package ‘igraph’

removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/igraph’
Warning in install.packages :
installation of package ‘igraph’ had non-zero exit status
The downloaded source packages are in
‘/private/var/folders/lw/zpnnptf933z40_3f31v_fnb40000gn/T/RtmpGNAmb6/downloaded_packages’

I would really appreciate your help!!
Thanks a lot :)

**Comment by kzuza** [comment]
Same problem here. 
Have you managed to find any solution? 
Would appreciate if you can share.
Thank you.

**Comment by vtraag** [comment]
Could you please report the exact steps that you take and the full output you get while installing the `igraph` package? Please limit it to installing `igraph` only. What OS are you on? You seem to be on macOS @Osterhhase, are you also on macOS @kzuza? There are binary packages for macOS available from [CRAN](https://cran.r-project.org/web/packages/igraph/index.html) so there should not even be any need to compile it on macOS.

**Comment by kzuza** [comment]
I am using Windows. 
Error occured while calling library(Seurat) 
> library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘igraph’
> install.packages("igraph")
Installing package into ‘C:/Users/kzuza/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
  There is a binary version available but the source version is later:
        binary source needs_compilation
igraph 1.2.4.2  1.2.5              TRUE

When choosing not to compile from the source the installation is successful. 
 Sorry for the issue.

**Comment by vtraag** [comment]
@kzuza, thanks, it seems that the `igraph` binaries for Windows are indeed outdated for `r-devel` and `r-release` (R 3.6), only version 1.2.4.2 is provided, while `igraph` binaries are provided for `r-oldrel` (R 3.5) for version 1.2.5. @gaborcsardi , will Windows binaries for version 1.2.5 for more recent R versions follow?

**Comment by pat-s** [comment]
> will Windows binaries for version 1.2.5 for more recent R versions follow?

Binaries for all OS are automatically build by CRAN - it just takes some days after the CRAN release.
