### ISSUE TITLE
BFS and DFS have issues with using father/pred/succ with disconnected components

### ISSUE THREAD

**Issue by melmasri** [igraph/rigraph#381]
I am using `bfs` or `dfs` to count the number of nodes in each disconnected component of a forest. The problem is that the succ/pred or father do not display the NA's correctly.

Here is an example of a forest of 4 components, two independent nods (1,2), node 9, and 14 are connected, and the rest is a single tree. Hence, when looking at `father`, we should have 4 NA, representing the 4 independent components, which is correct. However, the locations of those NA's are wrong. The correct `father` should be `NA NA NA  X X X X X X X X X  X  X NA X`, where `X` is some number!, the same logic applies to `pred` and `succ`!. Also the `father`, `pred`, and `succ` numbers shown below are confusing, I am not sure what they represent.

```r
library(igraph)
forest = make_empty_graph(16, directed = FALSE)
ed = c(3,13,4,5,5,11,6,13,6,16,7,13,8,13,9,14,10,11,11,12,12,15,15,16)
forest = add_edges(forest, ed)
plot(forest)

bfs(forest, 1, unreachable = TRUE, neimode = 'total', order = TRUE, 
succ = TRUE, father =TRUE, pred = TRUE)
$root
[1] 1

$neimode
[1] "all"

$order
+ 16/16 vertices, from a082f62:
 [1]  1  2  3 13  6  7  8 16 15 12 11  5 10  4  9 14

$rank
NULL

$father
+ 16/16 vertices, from a082f62:
 [1] NA NA NA  5 11 13 13 13 NA 11 12 15  3  9 16  6

$pred
+ 16/16 vertices, from a082f62:
 [1] NA NA NA 10 11 13  6  7 NA  5 12 15  3  9 16  8

$succ
+ 16/16 vertices, from a082f62:
 [1] NA NA 13 NA 10  7  8 16 14  4  5 11  6 NA 12 15

$dist
NULL

````

**Comment by clpippel** [comment]
The doc is rather sparse. In [igraph Reference Manual, Chapter 14. Graph visitors](https://igraph.org/c/doc/igraph-Visitors.html) we read:

> If not all vertices can be reached from the supplied root vertex,  then additional root vertices will be used, in the order of their vertex ids.

In the example above: root=c(1, 2, 3, 9). So you could aspect NA in $father at index 1, 2, 3, 9 as we can see
