### ISSUE TITLE
Weird behaviour of the Kamada Kawai layout

### ISSUE THREAD

**Issue by pollicipes** [igraph/rigraph#383]
Dear Gabor,

I'm using Kamada Kawai for layout and its showing a strange behaviour. When I plot the layout with my full data the output plot is very strange:
![image](https://user-images.githubusercontent.com/35963280/77775154-73bfda80-704c-11ea-9d9f-29adf346d188.png)

But, if I just remove one **any** single point, say the last node in my data frame, which has only one edge out of the 1,823 in total, the output comes as expected:
![image](https://user-images.githubusercontent.com/35963280/77775266-a073f200-704c-11ea-9a4d-17572daf257a.png)

How can a single, poorly connected node, influence the layout in this way? Have no clue about whats happening. Would appreciate any tip to solve it! 

Importantly, must say that I have been using this same code to generate layouts with dozens of other datasets, which worked as expected. This behaviour happens only with this instance of the data.

Thanks in advance!
P

I am attaching the data frame and the reproducible code:

Read this dataframe into an object:
[test_data_frame.txt](https://github.com/igraph/rigraph/files/4394589/test_data_frame.txt)

Code to reproduce the situation:

```
library(igraph)
dft=read.table(file="test_data_frame.txt")
colnames(dft)=c("id1","id2","weight")
ngw=graph.data.frame(dft)
xy<-layout_(ngw,with_kk(weights=dft$weight,dim=2),igraph::normalize())
x=xy[,1]
y=xy[,2]
plot(x,y, pch=16, cex=0.6, main="weird behaviour")

# NOW WE REMOVE, FOR EXAMPLE, THE LAST NODE WITH THE id=284
dim(dft) # note we have 1,823 nodes 
dft=dft[dft$id1 != 284,]
dft=dft[dft$id2 != 284,]
# JUST ONE LESS NODE, WHICH HAS ONLY A SINGLE EDGE WITH ONE ANOTHER NODE 
dim(dft)

# AND NOW LOOKS AS EXPECTED
ngw=graph.data.frame(dft) # read again the new dataframe
xy<-layout_(ngw,with_kk(weights=dft$weight,dim=2),igraph::normalize())
x=xy[,1]
y=xy[,2]
plot(x,y, pch=16, cex=0.6, main="Expected")
```

**Comment by szhorvat** [comment]
This could be related: https://github.com/igraph/igraph/issues/963
