### ISSUE TITLE
README lists wrong dev instructions

### ISSUE THREAD

**Issue by pat-s** [igraph/rigraph#384]
Because it suggests to install the dev version from master - however this installs v1.1.0 instead of the current dev version (which apparently lives in the "dev" branch).

However installing this one errors

``` r
remotes::install_github("igraph/rigraph@dev")
#> Using github PAT from envvar GITHUB_PAT
#> Error: Failed to install 'unknown package' from GitHub:
#>   HTTP error 404.
#>   Not Found
#> 
#>   Did you spell the repo owner (`igraph`) and repo name (`rigraph`) correctly?
#>   - If spelling is correct, check that you have the required permissions to access the repo.
```

<sup>Created on 2020-03-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by davemcg** [comment]
Does anyone know how to work-around this issue? Can't figure out how to get the "dev" branch.

**Comment by vtraag** [comment]
Installation should be done using `remotes:install_github("igraph/rigraph@master")`. To be clear, the code in the `master` branch is automatically generated based on the code in the `dev` branch. I have clarified this in the documentation in f8298b0b8f925ca0893548f28c5b53610d620785.
