### ISSUE TITLE
error when installed igraph r package 

### ISSUE THREAD

**Issue by huijfeng** [igraph/rigraph#385]
* installing *source* package ‘igraph’ ...
** package ‘igraph’ successfully unpacked and MD5 sums checked
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/RtmpbLWSDp/R.INSTALL23aa4554d392/igraph':
configure: error: C compiler cannot create executables
See `config.log' for more details
ERROR: configuration failed for package ‘igraph’
* removing ‘/R-3.4.4/library/igraph’

The downloaded source packages are in
        ‘/tmp/RtmpGiL3tl/downloaded_packages’
Warning message:
In install.packages("igraph", verbose = T, keep_outputs = T) :
  installation of package ‘igraph’ had non-zero exit status

**Comment by gaborcsardi** [comment]
You need a C compiler to install igraph from a source package. If you are on Windows or macOS, then usually binary packages are available from CRAN.
