### ISSUE TITLE
The installation of igraph package failed on AIX7.2 with error: 'struct ifreq' has no member named 'ifr_hwaddr' 

### ISSUE THREAD

**Issue by bergen288** [igraph/rigraph#396]
I am trying to install R packages (R base is 3.6.1) on AIX7.2 server with no internet access. My installation with igraph package failed with the following error.
```r
uuid/gen_uuid.c: In function 'get_node_id':
uuid/gen_uuid.c:193:30: error: 'struct ifreq' has no member named 'ifr_hwaddr'; did you mean 'ifr_name'?
   a = (unsigned char *) &ifr.ifr_hwaddr.sa_data;
                              ^~~~~~~~~~
                              ifr_name
make: 1254-004 The error code from the last command is 1.
Stop.
```
There is a "Pull request" to address the same issue on SmartOS/Solaris servers.  I modified igraph/src/uuid/gen_uuid.c from "__sun__" to "__aix__"
```r
Old line 190:     #if defined(SIOCGIFHWADDR) 
New line 190:     #if defined(SIOCGIFHWADDR) && (!defined(__aix__))
```
Unfortunately, it failed with the same error.  Can someone please help me to address this issue?

**Comment by gaborcsardi** [comment]
Well, without access to AIX, it is hard to help, but if you figure it out, we'll be happy to merge a PR.

**Comment by bergen288** [comment]
Do you have any hint and/or direction?

**Comment by gaborcsardi** [comment]
Seems like you need `_AIX`. https://sourceforge.net/p/predef/wiki/OperatingSystems/

**Comment by bergen288** [comment]
Great.  The following line works in igraph/src/uuid/gen_uuid.c.  It is installed successfully.
```r
line 190:  #if defined(SIOCGIFHWADDR) && (!defined(_AIX))
```

**Comment by szhorvat** [comment]
@bergen288 If it's not too much trouble for you, could you do a test of the igraph C core on this somewhat exotic platform?

Instructions:

```
git clone https://github.com/igraph/igraph.git
cd igraph
./bootstrap.sh
./configure
make
make check
```

It'll tell you if any tests failed.

**Comment by bergen288** [comment]
Sorry, my AIX7.2 server doesn't have internet access as mentioned in my 1st post.

**Comment by vtraag** [comment]
Should we perhaps not keep this issue open until is is fixed by replacing the line to be

```C
#if defined(SIOCGIFHWADDR) && (!defined(__sun__)) && (!defined(_AIX))
```
similar to what was suggested in PR #128?
