### ISSUE TITLE
Vertical slider of R console disappears (W10, Rgui)

### ISSUE THREAD

**Issue by clpippel** [igraph/rigraph#400]
The following code deletes the vertical slider in the R console window, making the beginning of the output inaccessible.
```
# R_bug_vertical_slider_lost.r
# vertical scroll bar slider disappears, or
# beginning of the output is not reacheble by the scroll slider

# Run RGui.exe
# copy this source to clipboard
# type Ctrl-L to clear the console and Ctrl-V to run the program in the R console

if (!require(igraph)) q() 
sessionInfo()

g <- make_ring(600, directed=TRUE) + make_tree(100, 1, mode = "out")
g
SCC <- components(g, mode=c("strong"))

data.frame(groups(SCC))                     # vertical scrol bar slider lost
```
![no-slider](https://user-images.githubusercontent.com/9609214/86388077-6d1cb100-bc94-11ea-8a7f-f8f665aa083c.jpg)

**sessionInfo**
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=Dutch_Netherlands.1252  LC_CTYPE=Dutch_Netherlands.1252   
[3] LC_MONETARY=Dutch_Netherlands.1252 LC_NUMERIC=C                      
[5] LC_TIME=Dutch_Netherlands.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.2

**Comment by gaborcsardi** [comment]
Why do you think that this is an igraph issue? igraph certainly does not do anything with any scrollbars.

**Comment by clpippel** [comment]
> 
> 
> Why do you think that this is an igraph issue? igraph certainly does not do anything with any scrollbars.

Because it occurred when using an igraph function (groups). But indeed, I think it is a problem with printing a datraframe. I will move this issue to the appropriate place, R-issues I suppose.
