### ISSUE TITLE
graph.empty(n=NULL)  results in undefined vcount(g)

### ISSUE THREAD

**Issue by clpippel** [igraph/rigraph#404]
L.S.

I happen to run into the following (simplified) R-code:

```
# allocate graph.empty with undefined vcount
library(igraph)
g <- graph.empty(n=NULL, directed=TRUE)
print(vcount(g))  # <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

sessionInfo()
```
The result is a graph with an uninitialized number of vertices, instead of as expected zero.

(screenshot included)

![igraph-graph empty-vcount-nok](https://user-images.githubusercontent.com/9609214/88077513-a5b8f780-cb7b-11ea-9fb4-6c4525bbbb71.jpg)
 0.

**Comment by gaborcsardi** [comment]
I am not sure why you'd expect that `NULL` is the same as `0`, it is not. You want an empty graph, that's `n = 0`.

**Comment by clpippel** [comment]
> 
> 
> I am not sure why you'd expect that `NULL` is the same as `0`, it is not. You want an empty graph, that's `n = 0`.

I expect NULL is NULL. In my original program NULL was actual a variable erroneously set to NULL (not NA). 

`g <- graph.empty(n=npls, directed=TRUE) `

What I did expect (or hoped for) was at least an error message for example:
`At type_indexededgelist.c:117 : cannot create empty graph, Invalid value n=NULL`

With no warning it took me some time to sort out what went wrong.

**Comment by clpippel** [comment]
`make_graph(NULL)`

gives warnings:

```
Error in (function (edges, n = max(edges), directed = TRUE)  : 
  At type_indexededgelist.c:117 : cannot create empty graph with negative number of vertices, Invalid value
In addition: Warning message:
In max(edges) : no non-missing arguments to max; returning -Inf
```

**Comment by ntamas** [comment]
I have recently patched `make_graph()` to accept `NULL` as an argument without warnings and produce an empty graph (see [this commit](https://github.com/igraph/rigraph/commit/3233a86848b383049ad8c6a004512811def9ad98)).

`g <- graph.empty(NULL)` also works now after applying [this commit](https://github.com/igraph/rigraph/commit/6453014f)).

These will be part of the upcoming patch release.
