### ISSUE TITLE
How to install earlier version of igraph

### ISSUE THREAD

**Issue by Lin936** [igraph/rigraph#409]
Hi,
I want to install seqtime package however there might be a version conflict between igraph and the current R version. I have no idea how to install earlier version of igraph. 
Can somebody teach me how to do it? 
Thanks for your help

Lin

**Comment by gaborcsardi** [comment]
The list of versions: https://github.com/cran/igraph/commits or https://cran.r-project.org/src/contrib/Archive/igraph/ and you can use `remotes::install_version()`.
