### ISSUE TITLE
Docker install cannot open shared object file

### ISSUE THREAD

**Issue by GrayAlex49** [igraph/rigraph#418]
When loading igraph in a docker container I get the following error:
```
test   | Error: package or namespace load failed for ‘igraph’ in dyn.load(file, DLLpath = DLLpath, ...):
test   |  unable to load shared object '/usr/local/lib/R/site-library/igraph/libs/igraph.so':
test   |   libglpk.so.40: cannot open shared object file: No such file or directory
test   | Execution halted
```
Dockerfile
```
FROM rocker/tidyverse

RUN apt-get update && apt-get install -y build-essential

RUN R -e "install.packages('igraph', dependencies = T)"

CMD R -e "source('script/igraph.R')"
```

**Comment by gaborcsardi** [comment]
https://packages.debian.org/search?searchon=contents&keywords=libglpk.so.40&mode=path&suite=stable&arch=any

**Comment by GrayAlex49** [comment]
Thank you, I thought I tried that but I must have missed it. For anyone seeing this installing the libglpk40 package is required before installing igraph
```
FROM rocker/tidyverse

RUN apt-get update && apt-get install -y \
  build-essential \
  libglpk40

RUN R -e "install.packages('igraph', dependencies = T)"

CMD R -e "source('script/igraph.R')"
```
I think most packages fail during install and suggest libraries that may need to be added in a case like this as opposed to assuming that they are there but I could be wrong.

**Comment by gaborcsardi** [comment]
> I think most packages fail during install and suggest libraries that may need to be added in a case like this as opposed to assuming that they are there but I could be wrong.

This does not seem like an installation error, but an error when you load igraph. igraph was compiled with glpk but then you are trying to load it without glpk. Maybe you installed a binary package from RSPM or elsewhere?

**Comment by wlandau** [comment]
I am currently dealing with an instance of this issue on GitHub Actions: https://github.com/ropensci/targets/runs/2551626293?check_suite_focus=true#step:11:32. Apparently, `igraph` is looking for  `libglpk.so.36` specifically, which I cannot find when I search https://packages.debian.org.

**Comment by ntamas** [comment]
It probably doesn't help much, but `libglpk.so.36` used to be in [`libglpk36`](https://packages.ubuntu.com/search?searchon=contents&keywords=libglpk.so.36&mode=exactfilename&suite=xenial&arch=any) in Ubuntu Xenial. Apparently you are trying to install a pre-compiled binary of the `igraph` R package that used to link to `libglpk.so.36`, but the ABI of GLPK has changed and Ubuntu 20.04 includes [`libglpk.so.40` instead](https://packages.ubuntu.com/search?searchon=contents&keywords=libglpk.so&mode=filename&suite=focal&arch=any). `igraph` should be re-compiled from source to link to `libglpk.so.40`.

**Comment by wlandau** [comment]
Ah, of course. Thanks @gaborcsardi
