### ISSUE TITLE
make: *** [foreign-gml-parser.o] Error 1

### ISSUE THREAD

**Issue by dylanzhao1993** [igraph/rigraph#419]
y.tab.c: In function ‘yytnamerr’:
y.tab.c:1036:5: warning: implicit declaration of function ‘stpcpy’ [-Wimplicit-function-declaration]
y.tab.c:1036:36: error: invalid operands to binary - (have ‘int’ and ‘char *’)
src/foreign-gml-parser.y: In function ‘igraph_i_gml_make_numeric2’:
src/foreign-gml-parser.y:214:3: warning: implicit declaration of function ‘strcasecmp’ [-Wimplicit-function-declaration]
make: *** [foreign-gml-parser.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/rds/project/rjh234/rds-rjh234-cc-mrc-epid/People/Yajie/R_lib/igraph’
The downloaded source packages are in
        ‘/tmp/RtmpyDhTFv/downloaded_packages’

**Comment by dylanzhao1993** [comment]
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Scientific Linux 7.8 (Nitrogen)

Matrix products: default
BLAS:   /usr/local/software/archive/linux-scientific7-x86_64/gcc-9/r-3.6.3-4imvl66cxokjk4bec3l75kyv3twpwui3/rlib/R/lib/libRblas.so
LAPACK: /usr/local/software/archive/linux-scientific7-x86_64/gcc-9/r-3.6.3-4imvl66cxokjk4bec3l75kyv3twpwui3/rlib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] withr_2.1.2

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3    tcltk_3.6.3

**Comment by gaborcsardi** [comment]
Can you tell us what you did?

**Comment by dylanzhao1993** [comment]
I want to install "igraph" in my unix environment but it always shows this error. I will appreciate if you can help me reslove this issue.

**Comment by dylanzhao1993** [comment]
I have tried to use "install.packages()" and "devtools:install()". But both of them show the same error.

**Comment by gaborcsardi** [comment]
I am sorry, what I meant was the _actual commands_ that you were running.

**Comment by dylanzhao1993** [comment]
with_makevars(c(PKG_CFLAGS = "-std=c11"),		  
			  install.packages("igraph",lib="/rds/project/rjh234/rds-rjh234-cc-mrc-epid/People/Yajie/R_lib")
			  ,assignment = "+=")

**Comment by gaborcsardi** [comment]
Is there a reason for setting the c11 standard? igraph is not C11 but C99.

**Comment by dylanzhao1993** [comment]
with_makevars(c(PKG_CFLAGS = "-std=c99"),		  
			  install.packages("igraph",lib="/rds/project/rjh234/rds-rjh234-cc-mrc-epid/People/Yajie/R_lib")
			  ,assignment = "+=")

**Comment by dylanzhao1993** [comment]
Have tried this command but the error appeared again.

**Comment by dylanzhao1993** [comment]
y.tab.c: In function ‘yytnamerr’:
y.tab.c:1036:5: warning: implicit declaration of function ‘stpcpy’ [-Wimplicit-function-declaration]
y.tab.c:1036:36: error: invalid operands to binary - (have ‘int’ and ‘char *’)
src/foreign-gml-parser.y: In function ‘igraph_i_gml_make_numeric2’:
src/foreign-gml-parser.y:214:3: warning: implicit declaration of function ‘strcasecmp’ [-Wimplicit-function-declaration]
make: *** [foreign-gml-parser.o] Error 1

**Comment by gaborcsardi** [comment]
I cannot reproduce this, I just run this in the `sl:7` docker container:

```
docker run -ti sl:7 bash
```

```
yum install -y epel-release
yum install -y R
yum install -y libcurl-devel openssl-devel libxml2-devel glpk-devel
R -q -e 'install.packages("igraph", repos = "https://cloud.r-project.org")'
```

and it completed without any errors. (`libcurl-devel` and `openssl-devel` are probably not actually needed.)

**Comment by dylanzhao1993** [comment]
But in my linux enviroment, the error always appears.

**Comment by dylanzhao1993** [comment]
with_makevars(c(PKG_CFLAGS = "-std=gnu99"),		  
			  install.packages("igraph",lib="/rds/project/rjh234/rds-rjh234-cc-mrc-epid/People/Yajie/R_lib",repos = "https://cloud.r-project.org")
			  ,assignment = "+=")

**Comment by dylanzhao1993** [comment]
With this command, it has been installed finally. Thank you very much for your help!
