### ISSUE TITLE
Cutoff for all_simple_paths function

### ISSUE THREAD

**Issue by rossinerbe** [igraph/rigraph#421]
Hello, thank you for making this great package.

I want to use the cutoff functionality added [here](https://github.com/igraph/igraph/pull/1232/commits/652fd1b65bb7669a1c83251ea9dfa79877c2ed5c) with the all_simple_paths function. The cutoff argument does not appear to be implemented in R package yet however. 

The function appears to just pass arguments to the C code, so is there a way for me to pass the cutoff argument through as well?

**Comment by rossinerbe** [comment]
Sorry, I see it's implemented in the dev version.

**Comment by gabora** [comment]
@rossinerbe , I see the feature implemented in the dev/cran branch, but how did you install the package from there?

**Comment by szhorvat** [comment]
@gabora You can use the instructions here: https://github.com/igraph/rigraph/#installation (remotes::install) Certain development tools are needed to be able to compile the package from source.
