### ISSUE TITLE
compilation error: implicit declaration of function 'igraph_i_vector_binsearch_slice' is invalid

### ISSUE THREAD

**Issue by gabora** [igraph/rigraph#424]
Hi, 
I try to install the R-igraph from the `dev` branch following the instruction in  `CONTRIBUTNG.md`. 
At the `install()` step I get the following error:
```
community_leiden.c:428:17: error: implicit declaration of function 'igraph_i_vector_binsearch_slice' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                igraph_i_vector_binsearch_slice(&cum_trans_diff, r, &chosen_idx, 0, nb_neigh_clusters);
                ^
1 error generated.
make: *** [community_leiden.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/igraph’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/igraph’
```

I  searched for the definition of this function across the repo but could not find it. 
Could you please check if it is there?
thanks!

**Comment by vtraag** [comment]
This is already fixed in the C core (see PR https://github.com/igraph/igraph/pull/1341). We should upgrade the C core to a more recent version (0.8.3 or later). The current C core is still at version 0.8.1.

**Comment by gabora** [comment]
Dear @vtraag,
thanks a lot for the fast response! After I updated the C core to the current master, the compilation worked! 

May I suggest two small things: 
(1) updating the readme.md on the r-igraph:
it mentions that one could install the `dev` version by devtools, but actually, this isn't correct: the dev branch is not an R package and the actual code provided there installs an old version from the master branch.  If you could direct the user to the `CONTRIBUTING.md`, "Making More Involved Changes" section, that could have saved a lot of time!

(2) There is a `cigraph` submodule pointing to `cigraph @ 5886f21`, maybe that could be updated to the current master (?). or at least to a newer version. 

thanks again.

**Comment by vtraag** [comment]
> After I updated the C core to the current master, the compilation worked!

Great, good to hear it worked flawlessly!

> updating the readme.md on the r-igraph:

Yes, good point, there is already an open issues about this https://github.com/igraph/rigraph/issues/384 and a PR https://github.com/igraph/rigraph/pull/420 that addresses this by ensuring that installing from the `dev` branch works correctly.

> (2) There is a `cigraph` submodule pointing to `cigraph @ 5886f21`, maybe that could be updated to the current master (?). or at least to a newer version.

Yes, this is exactly what I meant with updating the C core to 0.8.3.
