### ISSUE TITLE
converting a neo4j graph into a graph object that igraph accepts

### ISSUE THREAD

**Issue by AprilSong0323** [igraph/rigraph#428]
Hello,

My project requires analyzing graphs stored in Neo4j. I can import a neo4j graph into R using "neo4r" package.

I am writing to ask if there is a function that I could convert a neo4j graph into a graph object that igraph accepts?

Thanks in advance

**Comment by szhorvat** [comment]
If you are still looking for a solution to this, please post the question on the support forum at https://igraph.discourse.group/
