### ISSUE TITLE
Expand graph

### ISSUE THREAD

**Issue by NeginValizadegan** [igraph/rigraph#430]
Hello,

I have about 20 pathways and am linking them to genes. However, when the number of pathways are more than 4-5, the graph really gets messy and I could not make it look better. Is there anyway to make the graph expand a bit? The package enrichplot really layout plots nicely, don't know what the underlying script is though. Can something like that be done with igraph?

**Comment by szhorvat** [comment]
We prefer to reserve the issue tracker for bugs and feature requests. If you are looking for help, please use the support forum: https://igraph.discourse.group/
