### ISSUE TITLE
make_graph(c()) should work

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#431]
I would expect `make_graph(c())` to return a null graph instead of throw an error. 

```
> make_graph(c())
Error in (function (edges, n = max(edges), directed = TRUE)  : 
  At type_indexededgelist.c:117 : cannot create empty graph with negative number of vertices, Invalid value
In addition: Warning message:
In max(edges) : no non-missing arguments to max; returning -Inf
```

I suggest using `n=max(edges,0)` instead of `n=max(edges)` in `make_graph` as well as related functions (`make_undirected_graph`, etc.)

**Comment by gaborcsardi** [comment]
I guess `make_graph(integer())` should work, but I am not sure if passing `NULL` should be interpreted as an empty edge list.

**Comment by szhorvat** [comment]
> I guess `make_graph(integer())` should work

Yes, that was really my main point.

I'm not experienced enough with R to be able to tell what the best solution is, or whether there is a reasonably easy solution. I didn't think about `NULL`.

**Comment by gaborcsardi** [comment]
>  I didn't think about NULL.

`c()` is the same as `NULL`:

```r
❯ c()
NULL
```
