### ISSUE TITLE
Status of cran branch

### ISSUE THREAD

**Issue by vtraag** [igraph/rigraph#434]
Currently all development is taking place on the `dev` branch, and the `cran` branch is now fully merged with the `dev` branch. I created tags for all specific versions (of the 1.2.x release), so that we can easily trace back specific releases. In part, this is also to support version creation based on `git` tags (part of PR https://github.com/igraph/rigraph/pull/433).

@gaborcsardi , is there any specific reason why we should keep a separate `cran` branch? If not, could we simply remove it?

**Comment by gaborcsardi** [comment]
> @gaborcsardi , is there any specific reason why we should keep a separate cran branch? If not, could we simply remove it?

I am not entirely sure why you want to remove it, but if it bothers you then go ahead.

**Comment by vtraag** [comment]
> I am not entirely sure why you want to remove it

I would like to make sure that ongoing development is done in the `dev` branch, to avoid any confusion. It took me some time to realise that the actual most recent releases were not made from the `dev` branch, but from the `cran` branch.

I just wanted to make sure that I didn't miss any specific CRAN related things for which you used the `cran` branch. I'll remove it then.

**Comment by vtraag** [comment]
@gaborcsardi , I see you just pushed a couple of things to the `cran` branch still, I will merge those in `dev`. Just so that I understand, is there any reason you made those commits to the `cran` branch instead of the `dev` branch?

**Comment by gaborcsardi** [comment]
These are commits for patch releases, IDK what is in the dev branch, so I didn't want to deal with it.

**Comment by gaborcsardi** [comment]
Having the tags on the dev branch is not great, because then the new tags do not correspond to the actual CRAN releases. Possibly.

**Comment by vtraag** [comment]
> These are commits for patch releases, IDK what is in the dev branch, so I didn't want to deal with it.

OK, clear. From that perspective, it might then be useful to keep the `cran` branch alive, for now, until we are able to make a new release from the `dev` branch.

> Having the tags on the dev branch is not great, because then the new tags do not correspond to the actual CRAN releases. Possibly.

The tags are made on the `cran` branch for commits where the version number was bumped. I assumed that those commits would correspond to the released version. Is there any other way to identify which commit corresponds to a particular release? If you do see any discrepancies, I'd be happy to correct them.

**Comment by gaborcsardi** [comment]
> The tags are made on the cran branch for commits where the version number was bumped.

Oh, all right, fine then. The GH release are not super important for the R package, it is not worth the time looking over the commits.
