### ISSUE TITLE
MacOS binary package is not available (404)

### ISSUE THREAD

**Issue by Thijss** [igraph/rigraph#439]
On  https://igraph.org/r/#downloads, the link to the MacOS binary package ([Mac OS X universal binary package](https://cran.r-project.org/bin/macosx/el-capitan/contrib/r-release/igraph_1.2.4.2.tgz)) gives a 404

**Comment by ntamas** [comment]
Thanks for the heads up! It looks like the up-to-date URL at the time of writing is https://cran.r-project.org/bin/macosx/contrib/r-release/igraph_1.2.6.tgz ; I'll fix it once I clarify with @vtraag which one the most recent version is :)

**Comment by vtraag** [comment]
The latest release is 1.2.6. I am not immediately sure if there is a direct CRAN link we can simply point to which always points to the most recent release on the igraph.org website?

**Comment by ntamas** [comment]
I don't know, but I've updated the links on the homepage.

**Comment by szhorvat** [comment]
@ntamas Why don't we just link to https://cran.r-project.org/web/packages/igraph/index.html instead of explicitly linking to the downloads?

**Comment by ntamas** [comment]
I have modified the page now to link to the CRAN page. It should be published soon.
