### ISSUE TITLE
Fix portability issue in configure

### ISSUE THREAD

**Issue by brook-milligan** [igraph/rigraph#443]
The use of == with test(1) is not portable; a single = should be used instead.  Please apply this patch.  Thanks.

--- configure.orig	2018-03-10 12:30:50.000000000 +0000
+++ configure
@@ -3499,7 +3499,7 @@ ac_compile='$CC -c $CFLAGS $CPPFLAGS con
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-if test "x$ac_cv_fc_compiler_gnu" == xyes; then
+if test "x$ac_cv_fc_compiler_gnu" = xyes; then
 
 $as_echo "#define HAVE_GFORTRAN 1" >>confdefs.h

**Comment by gaborcsardi** [comment]
`configure` is generated from `configure.ac` I believe, so we should ideally fix that. Maybe it is enough to re-generate it?

**Comment by brook-milligan** [comment]
Yes, fixing configure.ac and regenerating configure would be the best fix.  Here is the equivalent patch for configure.ac.

--- configure.ac.orig	2020-10-06 08:59:00.000000000 +0000
+++ configure.ac
@@ -21,7 +21,7 @@ AC_PROG_CC
 
 # Fortran compiler, we need to check if it is the GNU compiler
 AC_PROG_FC
-if test "x$ac_cv_fc_compiler_gnu" == xyes; then
+if test "x$ac_cv_fc_compiler_gnu" = xyes; then
   AC_DEFINE([HAVE_GFORTRAN], [1], [Define to 1 if using the GNU fortran compiler])
 fi
