### ISSUE TITLE
Test failure on ARM64 and x86_64（v1.2.6）

### ISSUE THREAD

**Issue by fubingting** [igraph/rigraph#447]
When Rscript testthat.R on ARM64,The test fails and the following error occurs:
══ Failed tests ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
── Error (test_graph.adjacency.R:164:3): graph.adjacenct empty graph bug is fixed ───────────────────────────
Error: incorrect number of dimensions
Backtrace:
    █
 1. └─igraph::graph_from_adjacency_matrix(A, mode = "undirected") test_graph.adjacency.R:164:2
 2.   └─igraph:::graph.adjacency.sparse(...)
 3.     ├─el[el[, 3] != 0, ]
 4.     ├─base::`[.table`(el, el[, 3] != 0, )
 5.     ├─base::NextMethod()
 6.     ├─el[, 3]
 7.     ├─base::`[.table`(el, , 3)
 8.     └─base::NextMethod()
── Failure (test_layout.fr.R:12:3):  ───────────────────────────────────────────
||... is not TRUE

`actual`:   FALSE
`expected`: TRUE
── Failure (test_layout.fr.R:21:3):  ───────────────────────────────────────────
||... is not TRUE

`actual`:   FALSE
`expected`: TRUE

[ FAIL 3 | WARN 0 | SKIP 4 | PASS 3302 ]
Error: Test failures

**Comment by vtraag** [comment]
@fubingting, this error is now solved in 7f9a897a5d039c5ab05aeacae6966ee1dd4b54fc and dfcf5c3e7c8ea6015e82ffcfdbad1dbe03ccf883, you should be able to install it using `remotes::install_github("igraph/rigraph@master")`.

**Comment by fubingting** [comment]
> @fubingting, this error is now solved in [7f9a897](https://github.com/igraph/rigraph/commit/7f9a897a5d039c5ab05aeacae6966ee1dd4b54fc) and [dfcf5c3](https://github.com/igraph/rigraph/commit/dfcf5c3e7c8ea6015e82ffcfdbad1dbe03ccf883), you should be able to install it using `remotes::install_github("igraph/rigraph@master")`.

@vtraag When will the official version be released?

**Comment by fubingting** [comment]
> > @fubingting, this error is now solved in [7f9a897](https://github.com/igraph/rigraph/commit/7f9a897a5d039c5ab05aeacae6966ee1dd4b54fc) and [dfcf5c3](https://github.com/igraph/rigraph/commit/dfcf5c3e7c8ea6015e82ffcfdbad1dbe03ccf883), you should be able to install it using `remotes::install_github("igraph/rigraph@master")`.
> 
> @vtraag When will the official version be released?

When I install it using remotes::install_github("igraph/rigraph@master"),It seems that the error about test_layout.fr.R has not been solved,The test fails and the following error occurs:
══ Failed tests ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
── Failure (test_layout.fr.R:12:3):  ───────────────────────────────────────────
||... is not TRUE

`actual`:   FALSE
`expected`: TRUE
── Failure (test_layout.fr.R:20:3):  ───────────────────────────────────────────
||... is not TRUE

`actual`:   FALSE
`expected`: TRUE

[ FAIL 2 | WARN 0 | SKIP 4 | PASS 3309 ]
Error: Test failures

**Comment by vtraag** [comment]
@fubingting , thanks for testing! Sorry, I failed to realise there were two (or well, three, technically) errors that your reported initially.

I had not observed the errors in `test_layout.fr.R` before. Could you perhaps provide some more details? The title changes suggested that you observed these errors initially on ARM64 only, but later also on x86_64. What architecture do the test fail for the latest version? Are you using a linux distro on ARM64, or macOS?

> @vtraag When will the official version be released?

This is difficult to say. I have to clean up a number of things, but hopefully not longer than a few weeks at most.

**Comment by fubingting** [comment]
> @fubingting , thanks for testing! Sorry, I failed to realise there were two (or well, three, technically) errors that your reported initially.
> 
> I had not observed the errors in `test_layout.fr.R` before. Could you perhaps provide some more details? The title changes suggested that you observed these errors initially on ARM64 only, but later also on x86_64. What architecture do the test fail for the latest version? Are you using a linux distro on ARM64, or macOS?
> 
> > @vtraag When will the official version be released?
> 
> This is difficult to say. I have to clean up a number of things, but hopefully not longer than a few weeks at most.

I tested it on arm64 and x86_64 machines,uname -a:
**Linux CentOS8 4.18.0-240.10.1.el8_3.aarch64
Linux localhost.localdomain 4.18.0-240.el8.x86_64** 

When I print the test to test_layout.fr.R, the test results are as follows:

**sum(l)1: 10.79904
sum(l)2: 1079.41**
══ Skipped tests ══════════════════════════════════════════════
● empty test (1)
● No graph package (1)
● On CRAN (2)

══ Failed tests ═══════════════════════════════════════════════
── Failure (test_layout.fr.R:13:3):  ───────────────────────────────────────────
||... is not TRUE

`actual`:   FALSE
`expected`: TRUE
── Failure (test_layout.fr.R:22:3):  ───────────────────────────────────────────
||... is not TRUE

`actual`:   FALSE
`expected`: TRUE

[ FAIL 2 | WARN 0 | SKIP 4 | PASS 3309 ]
Error: Test failures
Execution halted
