### ISSUE TITLE
Partial argument match

### ISSUE THREAD

**Issue by mgirlich** [igraph/rigraph#449]
There are a couple of partial argument matches in the package (e.g. in `plot.igraph()`). Would be great if these could be fixed. To find the partial matches it is useful to use the option `warnPartialMatchArgs = TRUE` for the tests.

**Comment by ntamas** [comment]
I think most of the partial arg matches are now sorted out; I haven't seen these warnings for quite a while now. I'm closing this issue but keep an eye open and fix any similar warnings if they pop up.
