### ISSUE TITLE
ggplot plotting engine

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/rigraph#45]
_From @gaborcsardi on October 16, 2014 23:6_

To look at:
http://is-r.tumblr.com/post/38459242505/beautiful-network-diagrams-with-ggplot2
http://chrischizinski.github.io/rstats/2014/04/04/igraph-ggplotll/
http://sumtxt.wordpress.com/2011/07/02/visualizing-networks-with-ggplot2-in-r/

Maybe in a separate package? It is high time to split things up.

_Copied from original issue: igraph/igraph#735_

**Comment by briatte** [comment]
Having just stumbled upon this suggestion, I'd like to reference some code I wrote to plot networks with `ggplot2`: https://briatte.github.io/ggnet/

![](https://github.com/briatte/ggnet/raw/master/demo.png)

Right now, the code uses the `network` and `sna` packages. However, there are lots of namespace conflicts between these two packages and `igraph`. If `igraph` is more resilient to these issues, I might consider rewriting the code to use `igraph` instead.

**Comment by thomasp85** [comment]
Also, [ggraph](https://github.com/thomasp85/ggraph) :-)

**Comment by briatte** [comment]
Wow, old thread!

Three approaches to network viz with ggplot2 are documented here:

- https://journal.r-project.org/archive/2017/RJ-2017-023/index.html
- https://github.com/sctyner/ggnet-paper

The three approaches:

- https://github.com/sctyner/geomnet
- https://github.com/briatte/ggnet
- https://github.com/briatte/ggnetwork

… but in my view, ggraph is a far superior approach:

- https://github.com/thomasp85/ggraph

**Comment by ntamas** [comment]
Given the state of `ggraph`, I think we can safely close this as there is no need to implement this in igraph itself. Feel free to reopen if needed.
