### ISSUE TITLE
Adding new functions from C, auto-generating init.c

### ISSUE THREAD

**Issue by vtraag** [igraph/rigraph#453]
Much of the R interface, and much of the R-C glue code is being automatically generated by Stimulus. However, there is one file that is not generated automatically, namely `init.c`. If there is a new function from the C core, the C code in `rinterface.c` can be automatically generated, however, the C declarations in `init.c` are never automatically generated. I think that in principle, Stimulus should also be able to automatically generate `init.c`.

Is there a particular reason this is not the case @gaborcsardi ? 

I would be happy to implement this, but I just want to make sure that I am not overlooking anything that may be causing problems with this approach.

**Comment by gaborcsardi** [comment]
> Is there a particular reason this is not the case @gaborcsardi ?

There was no `init.c` when the auto-generation was added.

**Comment by vtraag** [comment]
Thanks! OK, I will then try to add a new Stimulus script to generate this also automatically.

**Comment by gaborcsardi** [comment]
Up to you, adding them manually is also fine I guess...

**Comment by vtraag** [comment]
Yeah, sure, that's what I am doing now. But there are now still quite a bunch of new functions that still need to be added, so that the cost-benefit ratio may tip towards the choice to automate it.

**Comment by ntamas** [comment]
Working on the autogeneration of `init.c` as an experiment, but it's not as simple as it seems because some prototypes in `init.c` have matching names but the argument list is different compared to what `functions.def` would imply (because they were hand-crafted and unify multiple C functions). This will eventually come but not necessarily now.
