### ISSUE TITLE
Is it possible to get the maximum distance instead of minimum?

### ISSUE THREAD

**Issue by mostafiz67** [igraph/rigraph#458]
I have a dataset, containing the edge list and weight. The `distances` function giving me the minimum total of the weights of the edges. 

For example, from `Source: ID_1` to `Destination: ID_5`, I can visit `ID_1 - ID_2 - ID_5` (the total weight of this path sequence is 1.4). On the other hand for the same source and destination, I can visit `ID_1 - ID_3 - ID_5` (the total weight of this path sequence is 0.86876). 

Is it possible to get the `maximum` or `average` of the total weight like `1.4 or 1.13` respectively for the above example? 

Reproducible Code and Data

```
df <- read.csv("~/data.csv")
df$X <- NULL
g2 <- df

graph2 <- graph_from_data_frame(g2, directed = FALSE)
plot(graph2, vertex.label = V(graph2)$name)
mat_2 <- distances(graph2, weights=E(graph2)$weight)
```
```
structure(list(nodeA = structure(c(1L, 1L, 1L, 2L, 2L, 3L, 4L, 
5L, 3L), .Label = c("ID_1", "ID_2", "ID_3", "ID_4", "ID_8"), class = "factor"), 
    nodeB = structure(c(2L, 3L, 4L, 5L, 4L, 6L, 6L, 1L, 5L), .Label = c("ID_100", 
    "ID_2", "ID_3", "ID_4", "ID_5", "ID_7"), class = "factor"), 
    weight = c(0.5, 0.77, 0.5, 0.9, 0.44, 0.32, 0.45, 0.543, 
    0.09876)), row.names = c(NA, -9L), class = "data.frame")
```

**Comment by szhorvat** [comment]
For support questions (as opposed to bug reports or feature requests) please use the forum: https://igraph.discourse.group/

**Comment by szhorvat** [comment]
The `all_simple_paths` function can compute all simple paths (i.e. no repeating vertices or edges) between two vertices. In theory, you can compute all paths and take the maximum or average. However, usually there are a very high number of paths, so this is not feasible for anything but tiny graphs. For the very same reason, [the longest path problem](https://en.wikipedia.org/wiki/Longest_path_problem) is much harder than the shortest path one (in fact it is NP-hard).

I suggest thinking about whether this is really the best graph metric for your application.
