### ISSUE TITLE
set_vertex_attr() and vertex_attr() <- still converts factors to integers

### ISSUE THREAD

**Issue by mathlandry** [igraph/rigraph#460]
Was there any solution to this issue?

**Comment by vtraag** [comment]
Could you include a link to the prior issue you are referring to?

**Comment by vtraag** [comment]
@mathlandry , you probably refer to https://github.com/igraph/rigraph/pull/193?

**Comment by mathlandry** [comment]
Exactly! Sorry I am not used to Github very much

**Comment by mathlandry** [comment]
I saw your response on #193 and will close this issue, thank you for your time!
