### ISSUE TITLE
Why can not change attribute type?

### ISSUE THREAD

**Issue by wanglu2014** [igraph/rigraph#464]
![图片](https://user-images.githubusercontent.com/12541282/116272203-4f847f00-a7b3-11eb-9bc3-a5cf1a6e8ddf.png)
Even set as numeric, the name of nodes were still charactor.
How to change it's type?

**Comment by ntamas** [comment]
You cannot change its type; names must be strings. This is because internally each igraph vertex has a numeric ID, ranging from 1 to the number of vertices, and most igraph functions (like `degree()`) allow you to specify vertices either by their numeric IDs or by their names. If we allowed integers as names, it would be ambiguous whether something like `degree(g, v=c(2, 4))` refers to the vertices with _names_ equal to 2 and 4 or _IDs_ equal to 2 and 4.

**Comment by wanglu2014** [comment]
> 
> 
> You cannot change its type; names must be strings. This is because internally each igraph vertex has a numeric ID, ranging from 1 to the number of vertices, and most igraph functions (like `degree()`) allow you to specify vertices either by their numeric IDs or by their names. If we allowed integers as names, it would be ambiguous whether something like `degree(g, v=c(2, 4))` refers to the vertices with _names_ equal to 2 and 4 or _IDs_ equal to 2 and 4.

In fact, change edge( such as as.numeric(E(G)$weight)) attribute also failed.

**Comment by iosonofabio** [comment]
Hi @wanglu2014,

Perhaps give us a little bit more context? It'd a little hard to understand what you are trying to do here. As a general rule, each vertex has an index (integer) and a name (string), the same is true for edges too, each edge has an index (integer) and a name (string). Those types (int/str) cannot be changed, so converting stuff to numeric is probably not what you should be doing here.

**Comment by wanglu2014** [comment]
> 
> 
> Hi @wanglu2014,
> 
> Perhaps give us a little bit more context? It'd a little hard to understand what you are trying to do here. As a general rule, each vertex has an index (integer) and a name (string), the same is true for edges too, each edge has an index (integer) and a name (string). Those types (int/str) cannot be changed, so converting stuff to numeric is probably not what you should be doing here.

![图片](https://user-images.githubusercontent.com/12541282/116335144-ed566900-a808-11eb-8f8b-4819a22ec696.png)
I am trying convert charactor (such as '1') into numeric (such as 1). However, result is still charactor.

**Comment by iosonofabio** [comment]
I'm afraid that's not enough context still, a single line of code...

Anyway, something similar works just fine on my computer:
```R
> E(g)$weight <- list("4", "6", "5", "7")
> E(g)$weight <- as.numeric(E(g)$weight)
> E(g)$weight
[[1]]
[1] 4

[[2]]
[1] 6

[[3]]
[1] 5

[[4]]
[1] 7

```
