### ISSUE TITLE
Suggestion: allow users to provide a seed in the function calls

### ISSUE THREAD

**Issue by leofontenelle** [igraph/rigraph#468]
I noticed `srand()` was deprecated because CRAN doesn't allow R packages to change C's seed. That's a bummer for computational reproducibility.

The way Stan gets away with it is having a `seed = sample.int(.Machine$integer.max, 1)` argument in the relevant functions: `rsan::stan()` and `cmdstanr::sample()`, and by extension `brms::brm()`, `rstanarm::stan_glm()` and friends.

I just wanted to make sure you were aware of the possibility. I appreciate this would involve both changes to the R package and the underlying C code, and that I don't know how extensive these changes would be, or what unintended consequences such changes could bring.

Thanks for the great software!

**Comment by gaborcsardi** [comment]
Does igraph use the C library's random numbers at all?

**Comment by leofontenelle** [comment]
Hi! I was thinking something like rigraph functions such as `cluster_leiden()` passing a seed argument to C igraph functions, which would in turn call the appropriate C igraph functions to set the seed.

**Comment by ntamas** [comment]
@leofontenelle As far as I know, `igraph` in R uses R's own internal RNG instead of C, so you can use `set.seed()` for reproducible results. E.g., when generating a geometric random graph, I can do:

```R
set.seed(42)
g <- sample_grg(100, 0.2)
set.seed(42)
g2 <- sample_grg(100, 0.2)
all.equal(get.edgelist(g), get.edgelist(g2))
# [1] TRUE
```

So there is no need for a separate `seed` argument; just set R's seed and that's it.

**Comment by leofontenelle** [comment]
I'm sorry. I thought I had tried it and that it hadn't worked. My bad.
