### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/rigraph#470]
> p. 54 - Examples:
" karate <- karate add_layout_(with_fr()) set_vertex_attr("size", value = 10) " to "karate <- karate %>%   add_layout_(with_fr()) %>%  set_vertex_attr("size", value = 10)"

> p. 65 - Description:
"Cloness centrality" to "Closeness centrality".

> p. 83 - Description:
"cocitation siply" to "cocitation simply"

**Comment by ntamas** [comment]
Fixed the last two; I cannot find the first one in the source yet; it seems to be in `R/palette.R` but it looks fine there.
