### ISSUE TITLE
get.adjacency(edges=T) behaves differently with multigraphs for dense/sparse

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#473]
`get.adjacency` has an `edges` parameter, which allows returning not `1`s, but the edge IDs in the adjacency matrix. This of course makes little sense for multigraphs, as multiple edges correspond to the same matrix position, but only one edge ID can be stored.  The current behaviour of the function is not very nice:

 - There is no warning about multigraphs. 
 - The behaviour with the sparse and dense code paths is different:
   - The dense one overwrites the matrix entry with the ID of the last considered edge. This comes from `igraph_get_adjacency()` in the C core.
   - The sparse one adds up the IDs of parallel edges. This is implemented purely in R, and probably comes from how R's sparse matrix constructor handles input.

**Comment by szhorvat** [comment]
The quickest solution to the consistency issue is probably to use `use.last.ij = TRUE` in the `Matrix::sparseMatrix` constructor in the sparse case. This should prevent edge IDs from being summed up. Instead, the last one will override the previous ones.

**Comment by ntamas** [comment]
Okay, so the `edges` parameter will be gone in C-igraph 0.10 anyway, therefore I think this is what we should do:

* add a deprecation warning for `edges=TRUE` (or, in fact, for any invocation that explicitly uses the `edges` parameter)
* temporarily fix the sparse variant to `use.last.ij=TRUE` iff `edges=TRUE`

Then we can remove the `edges` parameter in R-igraph 1.4.0.
