### ISSUE TITLE
error in writing and reading graph 

### ISSUE THREAD

**Issue by spocks** [igraph/rigraph#474]
When trying to write and read a graphml file, I get error. 

```Error in norm_coords(layout, -1, 1, -1, 1) : `layout' not a matrix ```

Here is the code:
```
library(igraph)
g <- make_ring(25)
g$layout <- layout.grid(g) ##create layout
plot(g)
write_graph(g, "tmp.graphml", format ="graphml") ##write file

k <- read_graph("tmp.graphml", format ="graphml") ##read file
plot(k)
## Error in norm_coords(layout, -1, 1, -1, 1) : `layout' not a matrix
```

**Comment by ntamas** [comment]
This is expected; GraphML does not have a native matrix data type so it cannot store the `layout` attribute of the graph properly. A workaround is to store the X and Y coordinates separately as vertex attributes:

```
library(igraph)
g <- make_ring(25)
layout <- layout.grid(g)
V(g)$x <- layout[,1]
V(g)$y <- layout[,2]
write_graph(g, "tmp.graphml", format ="graphml")
```
