### ISSUE TITLE
Check for correct types in bipartite graph - prevent unwarned failure in matching

### ISSUE THREAD

**Issue by ugroempi** [igraph/rigraph#476]
**igraph** is often a great help for me. In this case, I fell for a glitch in the type handling for bipartite graphs:

The types must start with 0, because `max_bipartite_match` gives an erroneous result otherwise. However, there is no warning or error message, if one uses a type vector that starts with 1. Thus, a user who is not aware of the requirement for types, gets an unwarned wrong result (igraph 1.2.6). Example:

`el <- rbind(c(1,5), c(1,6), c(2,5), c(2,6), c(2,7), c(3,8), c(4,5))`
`G <- igraph::graph_from_edgelist(el)`
`igraph::vertex_attr(G) <- list(type = rep(1:2, each=4))`
`is.bipartite(G)        ## looks OK`
`igraph::vertex_attr(G)  ## looks OK`
`igraph::max_bipartite_match(G)`

does not find the perfect match, although there is one. Everything works fine with 

`igraph::vertex_attr(G) <- list(type = rep(0:1, each=4))`.

Best, Ulrike

**Comment by ugroempi** [comment]
I have a proposal how to fix this:

Change lines 2688 to 2690 of file structural.properties.R (in `max_bipartite_match`)

```
if (!is.null(types)) {
        types <- as.logical(types)
    }
```

into 
```

if (!is.null(types)) {
  if (!is.logical(types)){
    ut <- sort(unique(types))
    if (!length(ut) == 2) stop("graph is not bipartite (" , length(ut), " types)")
    types <- types == ut[2]
  }
}
```

Best, Ulrike

**Comment by ntamas** [comment]
I've checked how igraph handles the `types` argument in functions related to the handling of bipartite graphs. The results were mixed; `bipartite_projection()` and `layout_as_bipartite()` checked whether the `types` vector is logical (using `is.logical()`) and correctly printed a warning if it wasn't, so this would have caught the initial mistake that you made. Unfortunately, `is_matching()`, `is_max_matching()` and `max_bipartite_match()` did not do so.

For sake of consistency across igraph functions, I am now refactoring the handling of the `types` argument into a separate function, which _will_ print a warning if the `types` vector is not logical.

**Comment by ugroempi** [comment]
Thanks! 

Is it intentional that bipartite graphs with only one type are permitted (i.e., all TRUE or all FALSE)? Shouldn't these perhaps also trigger a warning?

Best, Ulrike

**Comment by ntamas** [comment]
I don't think these should trigger a warning; I consider these as "degenerate" but valid bipartite graphs where one of the partitions is empty. In my head this is similar to the case of an "ordinary" graph with no vertices, which is also permitted by igraph and does not trigger a warning.

**Comment by ugroempi** [comment]
That also makes sense to me, though I suppose that single type bipartite graphs do occur unintentionally relatively often.
