### ISSUE TITLE
Unexpected value for theoretical maximum degree centrality

### ISSUE THREAD

**Issue by pozsgaig** [igraph/rigraph#479]
I am not sure how centr_degree_tmax() calculates the theoretical maximum but it gives a different value than the n*(n-1)/2 formula. Thus, normalized degree centrality also gives different results when the centr_degree() function is used with the attribute normalized=T and when the same function is used with normalized=F and then the value is divided by the theoretical maximum degree (as in the main example).

```
g <- sample_pa(1000, m = 4)
centr_degree(g, normalized = FALSE)$centralization %>%
    `/`(centr_degree_tmax(g))
centr_degree(g, normalized = TRUE)$centralization
```

Should these two result in the same value?

**Comment by szhorvat** [comment]
Please see #369 for the explanation.

I'd like to ask you to use [the support forum](https://igraph.discourse.group/) for questions and support requests. We would like to reserve the issue tracker for bugs and feature requests. Thanks!
