### ISSUE TITLE
How to understand the contribution of edge-attributes value when multiple edges exist between two nodes?

### ISSUE THREAD

**Issue by peranti** [igraph/rigraph#483]
Hi, Thanks for your work and support through this package.

I have a question about understanding the multiple edges and edge attributes.

In my Igraph object, I have multiple edges between some of the nodes. 

```
is_simple(net_full)
# [1] TRUE
```

I have identified those instances using `which_multiple(net_full)`. Now, I would like to understand how the edge.attribute values are coming from these edges individually.

```
edge_attr(net_full, "score")[c(1898, 5892, 6556, 6746, 7443, 8267, 8564)]
# [1] 161 189 310 433 917 216 324

count_multiple(net_full)[c(1898, 5892, 6556, 6746, 7443, 8267, 8564)]
# [1] 2 2 2 2 2 2 2
```
How can I find the contribution of the `161` from these `2` edges or edge types for the edge index `1898` individually?

**Comment by szhorvat** [comment]
Hello @peranti, we would prefer to reserve the issue tracker for bugs and feature requests. Please use the forum for questions / support: https://igraph.discourse.group/  We can continue the discussion there.  Briefly, each edge has its own unique ID. The value 161 belong to edge 1898. There might be other edges between the same two vertices, but these have their own separate attribute values.
