### ISSUE TITLE
R: 0.8 pre version question

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/rigraph#49]
_From @happyshows on November 11, 2014 16:22_

Hi,

I'd like to deploy my R app on linux server needed 'get.all.simple.path' function in 0.8 pre. However I'm not able to install the igraph package on that because of the error in source tar.gz.
Is there any timeline to fix the current compilation error? Also, what's the target date to release 0.8 production version?

Thanks.

_Copied from original issue: igraph/igraph#761_

**Comment by gaborcsardi** [comment]
What error do you mean? I actually use it every day...

**Comment by gaborcsardi** [comment]
Re target date, there is no date, but most probably this year it'll happen.

**Comment by gaborcsardi** [comment]
_From @happyshows on November 11, 2014 19:41_

@gaborcsardi , I downloaded below file and try to install it on linux
R package source code	0.8.0-pre	develop	dbe0da6


Here are the last portion of error message I got from console:
foreign-graphml.c:65: warning: excess elements in struct initializer
foreign-graphml.c:65: warning: (near initialization for ‘blankEntityStruct’)
foreign-graphml.c: In function ‘igraph_read_graph_graphml’:
foreign-graphml.c:1316: error: ‘XML_PARSE_HUGE’ undeclared (first use in this function)
foreign-graphml.c:1316: error: (Each undeclared identifier is reported only once
foreign-graphml.c:1316: error: for each function it appears in.)
make: *** [foreign-graphml.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/users/xle/shiny-server/ADAP/packrat/lib/x86_64-redhat-linux-gnu/3.1.1/igraph’
* restoring previous ‘/users/xle/shiny-server/ADAP/packrat/lib/x86_64-redhat-linux-gnu/3.1.1/igraph’
Warning in install.packages :
  installation of package ‘/users/xle/shiny-server/igraph_0.7.999-247.tar.gz’ had non-zero exit status

**Comment by gaborcsardi** [comment]
You probably have an old libxml2 library.

G.

**Comment by gaborcsardi** [comment]
_From @brunoamancio on December 2, 2014 15:35_

@gaborcsardi , I also get an error when I try compiling the dev version. My error happens when compiling:

gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG     -DUSING_R -I. -Iinclude -Ics -Iglpk -Iplfit -ICHOLMOD/Include -IAMD/Include -ICOLAMD/Include -ISuiteSparse_config -g -DNDEBUG -DNPARTITION -DNTIMER -DNCAMD -DNPRINT -DPACKAGE_VERSION=\"@VERSION@\" -DINTERNAL_ARPACK -DIGRAPH_THREAD_LOCAL=/**/ -fpic  -g  -c uuid/gen_uuid.c -o uuid/gen_uuid.o
uuid/gen_uuid.c: In function ‘get_clock’:
uuid/gen_uuid.c:362:3: warning: implicit declaration of function ‘flock’ [-Wimplicit-function-declaration]
   while (flock(state_fd, LOCK_EX) < 0) {
   ^
uuid/gen_uuid.c:362:26: error: ‘LOCK_EX’ undeclared (first use in this function)
   while (flock(state_fd, LOCK_EX) < 0) {
                          ^
uuid/gen_uuid.c:362:26: note: each undeclared identifier is reported only once for each function it appears in
uuid/gen_uuid.c:434:19: error: ‘LOCK_UN’ undeclared (first use in this function)
   flock(state_fd, LOCK_UN);
                   ^
make: *** [uuid/gen_uuid.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/home/th3b0y/R/x86_64-pc-linux-gnu-library/3.1/igraph’
Warning message:
In install.packages(path_to_file, repos = NULL, type = "source",  :
  installation of package ‘/home/th3b0y/Downloads/igraph_0.7.999-280.tar.gz’ had non-zero exit status

**Comment by gaborcsardi** [comment]
This should be fixed by now, there is also a new release.

**Comment by happyshows** [comment]
@gaborcsardi  thanks Gabor. what's the relationship between latest Dev RiGraph vs the nightly build 0.8.0? which one is more comprehensive?

**Comment by gaborcsardi** [comment]
Dev on github is always latest. The nightly is out of date and I'll remove it soon, actually. It did not work the way I wanted it.
