### ISSUE TITLE
Counting multiple edges gives unexpected (wrong?) results

### ISSUE THREAD

**Issue by mbojan** [igraph/rigraph#493]
**Describe the bug**
`count_multiple()` assigns to each edge a number of edges in the same dyad. `simplify()`ing a graph with an edge attribute created with `count_multiple()` does not give the result one would expect.

**To reproduce**
This is an exegesis of the last example of `?count_multiple`:

``` r
library(igraph)
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union
g <- make_graph(~ A -- B, B -- A, A -- C, simplify = FALSE)
E(g)$weight <- count_multiple(g)
as_data_frame(g)
#>   from to weight
#> 1    A  B      2
#> 2    A  B      2
#> 3    A  C      1
as_data_frame(simplify(g))
#>   from to weight
#> 1    A  B      4
#> 2    A  C      1
```

The likely intention for the `A-B` edge in  `simplify(g)` above is to have weight of 2, not 4.

I think at least the man page deserves the clarification. It says that

> See the examples for getting rid of multiple edges while keeping their original multiplicity as an edge attribute.

The example gives a distorted info on multiplicity in that the edge counts/weights are essentially squared.

**Version information**
1.2.7

**Comment by gaborcsardi** [comment]
This is not a bug. An edge attribute called `weight` is summed up by default:
```r
❯ igraph_opt("edge.attr.comb")
$weight
[1] "sum"

$name
[1] "concat"

[[3]]
[1] "ignore"
```

You can supply an argument to override the default:
```r
❯ as_data_frame(simplify(g, edge.attr.comb=list(weight = "min")))
  from to weight
1    A  B      2
2    A  C      1
```

**Comment by ntamas** [comment]
I've fixed the docs in https://github.com/igraph/rigraph/commit/3b3ecfb0d25296ca33be787129f8673bda5d51fe; although, I wonder whether this would be simpler (but it does not show the usage of `count_multiple` so it's not appropriate in that place in the docs). The upside of the example in the docs is that it works no matter what value `igraph_opt("edge.attr.comb")` is set to:

```
g <- make_graph(~ A -- B, B -- A, A -- C, simplify = FALSE)
E(g)$weight <- 1
g <- simplify(g)
```

**Comment by mbojan** [comment]
While not technically a bug, the example deserved clarification. Thanks for the fix. I would add the one above too @ntamas , while not using `count_multiple()` it does showcase how to achieve the same goal.
