### ISSUE TITLE
dfs() and bfs() argument naming: neimode -> mode

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#495]
`dfs()` and `bfs()` have a `neimode` argument. As far as I can tell, this argument is named `mode` in most (all?) other functions. For consistency's sake, should we rename it in `dfs()`/`bfs()` as well?

**Comment by ntamas** [comment]
A tiny problem is that the output of these methods is a named list that also has a `neimode` key, and we cannot rename that easily without potentially braking revdeps. I'll rename the argument though. For the result, we can probably provide `mode` and `neimode` at the same time.

**Comment by szhorvat** [comment]
Does it matter if we break revdeps in version 2.0? We would break a bunch of stuff anyway.

**Comment by ntamas** [comment]
@gaborcsardi I plan to do it like this, I guess it's okay, right?

```
  if (!missing(neimode)) {
    warning("Argument `neimode' is deprecated; use `mode' instead")
    if (missing(mode)) {
      mode <- neimode
    }
  }
```
