### ISSUE TITLE
max_bipartite_match crashes R session when no vertex types are set

### ISSUE THREAD

**Issue by Selbosh** [igraph/rigraph#498]
**Describe the bug**
The function `max_bipartite_match` will crash the R session without warning if no `types` are specified and the graph does not have vertex types set.

**To reproduce**
```r
df <- data.frame(x = 1:5, y = letters[1:5])
library(igraph)
g <- graph_from_data_frame(df)
max_bipartite_match(g)
```

**Version information**

- igraph version 1.2.9
- R version 4.0.5
- Windows 10

**Expected behaviour**

If vertices of the graph `g` do not have a `types` property, and the `types` argument is `NULL`, the function `max_bipartite_match` should throw an informative error, rather than pressing ahead, calling the underlying C function and crashing the entire R session.

I know I'm supposed to set vertex types, but the penalty for forgetting this should be an R error, or possibly a sensible fallback behaviour, not a crash.

**Comment by szhorvat** [comment]
I am just noting that development versions of the upcoming R/igraph 1.3 can now be installed using:

```
devtools::install_github("igraph/rigraph@master")
```

You need to have the R development tools installed for this to work. It will be compiled from source. Thanks to the improvements made to igraph's C core (version 0.9.x), this is what happens now:

```
> max_bipartite_match(g)
Error in max_bipartite_match(g) : 
  At core/core/vector.pmt:484 : Assertion failed: v != NULL. This is an unexpected igraph error; please report this as a bug, along with the steps to reproduce it.
```

So, `max_bipartite_match` is still buggy, but at least it won't crash your session.
