### ISSUE TITLE
Layout functions should be deterministic

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#499]
I suggest making layout functions deterministic. They should take a `seed` argument, and use that seed for the random number generator in a local environment. ([See local seed solution](https://stackoverflow.com/a/14324316/695132)).

This makes for reproducible figures _by default_. 

We can make it so that `seed=NA` uses the old behaviour, i.e. does not create a local random environment.

**Comment by gaborcsardi** [comment]
This is an anti-pattern. Setting and resetting the random seed is up to the end user and not us.

**Comment by iosonofabio** [comment]
I'm with @gaborcsardi on this one. If the algo is stochastic the user should be made aware of it, else they might be induced to think that the algo is not dependent on a random seed at all, and get *more* suprised when they discover it after the fact.

**Comment by szhorvat** [comment]
I strongly disagree, and I think you are seeing this from a programmer's perspective, who works with code. Most users are not programmers. They are scientists who work with graphs. 

Think about usability in an interactive environment, such as a notebook. If I look at the same object two times, I expect to see the same thing.

All systems which have a long notebook tradition, such as Mathematica, Maple, SageMath, will use a visualization of the graph as its standard display form. If I evaluate `g`, the output is not something like `IGRAPH 62e821e U--- 10 13`, but an actual picture of the graph. If I evaluate it several times, to look at it several times, it is intuitive to expect the same result. In my mind, the picture of the graph is tied to its identity. If two graphs don't look the same, they are not the same. If they do look the same, I know they are the same (as in `igraph_is_same_graph()`—not the same as isomorphic).

An act of plotting is not inherently a random operation. Why should it give a different result each time? 

I feel strongly about this because it is precisely seeing beyond the typical programmer's mindset is what could distinguish igraph from the myriads of identical looking open-source graph libraries out there. I want us to innovate, and to look at usability from outside the box instead of just copying the same old like almost every other open source project does.

**Comment by iosonofabio** [comment]
TBH, I'm a scientist who (sometimes) works with graphs, not a software eng.

A lot of algorithms, including e.g. t-SNE and UMAP, give different results every time you call them. Although that sometimes leads to inconveniences (you forgot to save the layout and have to remake a bunch of paper figures), it is useful to remind myself that the exact layout is arbitrary and I shouldn't make a bug fuss about it in the paper.

**Comment by gaborcsardi** [comment]
Fixing the seed for a randomized algorithm makes total sense, it is just not up to us. If a user wants to make an analysis or an analysis step reproducible, they can fix the random seed themselves. 

In R it is pretty simple:
```
withr::with_seed(123, 
  plot(...)
)
```

If you fix the seed for a randomized algorithm, that's not the same algorithm any more, you change its performance and its (not so average any more) running time.

**Comment by mbojan** [comment]
I think that looking at different realizations of a stochastically optimized graph layout is a valuable experience. Network visualizations are not statistical charts. It is up to the user to fix the seed or save the layout for some later re-use.

**Comment by szhorvat** [comment]
@iosonofabio 

I've actually seen people believe that the Kamada-Kawai layout of R/igraph is meaningful, and trying to interpret it for publications. It produces the same result every time you run it. That's only because the starting layout is a circle, not a random arrangement. Of course, the result is strongly dependent on the starting position, it's just that the current implementation uses a fixed starting position.

Why did they believe that the Kamada-Kawai result is interpretable? Precisely because (for completely arbitrary reasons) igraph's Fruchterman-Reingold function happens to produce random output, while the Kamada-Kawai doesn't. "So there must be a meaningful difference."

If all layout produced the same results consistently, people would be less confused.

**Comment by gaborcsardi** [comment]
Interpreting a single realization of a randomized algorithm with a fixed seed seems like a very bad idea to me.

**Comment by iosonofabio** [comment]
... and yet, you'll be surprised how common it is :smirk: let's not encourage it any further...

**Comment by szhorvat** [comment]
> If a user wants to make an analysis or an analysis step reproducible, they can fix the random seed themselves.

> Interpreting a single realization of a randomized algorithm with a fixed seed seems like a very bad idea to me.

We are not talking about analysis, or randomized algorithms. We are talking about graph visualization, which, in most cases, shouldn't be "interpreted" (it can give hints, but no robust conclusions).

The current situation is precisely what led people to pick specifically Kamada-Kawai, as they believed that "that's the interpretable one".

**Comment by iosonofabio** [comment]
good point. I would be in favour of changing the KK starting point to a random one then, unless there's a specific reason?

**Comment by mbojan** [comment]
I noticed that e.g. **graphlayouts** does indeed fixes the seed internally... For example:

https://github.com/schochastics/graphlayouts/blob/084bff7968c98a74d17df00795c63cbfa457a783/R/layout_stress.R#L41-L48

I think it gives ppl false sense of "certainty".

 If **igraph** goes in that direction I would be certainly interested in having some opt-out option available (a package option perhaps).

**Comment by ntamas** [comment]
Actually, the KK layout is not that deterministic either; look what we have in the test case for different platforms:

https://github.com/igraph/rigraph/blob/master/tests/testthat/test_layout.kk.R#L14

I'd not support making layouts pre-seeded in general, but I'd probably accept a package-level option that turns on "notebook mode" when set to TRUE so that the layouts become pre-seeded. But this should be opt-in, not opt-out. Also, we should properly store and restore the RNG state around plotting calls, otherwise we would mess up the outputs of randomized function calls that might appear elsewhere in the same notebook.

**Comment by vtraag** [comment]
I agree that seeding any random algorithm, whether layout or otherwise, should be left to the user, and should not be pre-seeded.

However, there is perhaps one thing that could make sense to do, and which I think is useful in various respects: we can "standardize" layouts to some extent. That is, many layouts are rotationally invariant, and this rotation is not otherwise informative. We could for example always choose to rotate such layouts according to PCA, so that the "long" component would be the x-axis (showing most variation) and the "short" component would be the y-axis (showing less variation). Additionally, we could then mirror the x and y axis so that the most "heavy" part (i.e. containing most node positions) would always be to the left/lower end. This reduces quite a lot of the possible variation of such layouts and make them more "deterministic" in a sense, but it respects all relative distances as specified by such layouts, and should still be seeded by the user.

Of course, this is not always useful for all graph layouts, for example, for layouts of trees or DAGs, we would perhaps simply always want lines to be (mostly) horizontal or vertical.

**Comment by szhorvat** [comment]
Responding with a clearer head, after sleeping on it.

One of the main arguments for using a fixed seed (in a local environment, of course the random state must be restored afterwards) made sense in a notebook environment, when using a picture of the graph as its output format. This is the issue tracker for R/igraph, and as far as I'm aware R is rarely used from notebooks, but the same discussion is relevant for Python / Mathematica as well.

I still think that having deterministic output makes sense in a notebook, when simply evaluating a graph `g` and looking at it (no explicit plotting command), but this behaviour could be restricted to this scenario only.

The other scenario is when using a plotting command, `plot(g)`, i.e. performing an action explicitly. In this case it is more natural to let the output be random. 

**Question 1** to you all: Does it make sense to you to keep the random output for plotting commands, but use a deterministic output if auto-visualization is implemented specifically for notebook environments (as in Mathematica/Maple/Sage)?

----

I'd like to mention that I don't really find much use for repeatedly running a plotting command and looking at the various random outputs. Certainly, I do explore the variations, to find a nice layout, but if I do so, I set the seed explicitly so I can repeat the result.

**Question 2:** Do any of you make practical use of the current random behaviour (without setting explicit seeds)?

**Comment by szhorvat** [comment]
@iosonofabio:

> I would be in favour of changing the KK starting point to a random one then, unless there's a specific reason?

That makes sense to me.

I think the KK layout, its starting point, and its stopping condition, should be revisited. I find that sometimes it produces very bad results in igraph, but not in other systems, which suggests that igraph's implementation could be improved. See here: https://github.com/igraph/igraph/issues/963

**Comment by szhorvat** [comment]
@vtraag Regarding rotating the layout:

For reference, I proposed this here, as inspired by Mathematica's behaviour:

https://github.com/igraph/igraph/issues/875

I implemented it using PCA in IGraph/M, but it's not quite perfect. Mathematica does something smarter than PCA, and we should think about what other criteria we can use for nice rotation. But this is a discussion to be had in another place (e.g. the above-linked issue)

**Comment by szhorvat** [comment]
> **Question 2:** Do any of you make practical use of the current random behaviour (without setting explicit seeds)?

Another thought here: igraph's layout algorithms are not doing that well for small graphs (and neither do most open-source implementations). There is incentive to try several random layouts until finding a good one.

I am still amazed at the quality of Mathematica's built-in graph visualization. The force directed layouts almost never go wrong. This was implemented by Yifan Hu many years ago, and he has several publications on the topic. 

The lesson for me is that following the Fruchterman-Reingold publication to the letter, and using the resulting algorithm as the default, may not be the best idea. It's not surprising that the very first attempt at any tasks (first paper on this style of visualization) won't be as polished as it could be.
