### ISSUE TITLE
Visualization: Edges may end or start at the wrong position with rectangular vertices

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#501]
**Describe the bug**

With rectangular vertices, edges may end of start at the "opposite" size of the vertex

In this example, 1 -> 2 starts at the wrong place and 1 -> 4 ends at the wrong place. To see this, it is important to set the vertex colour to semi-transparent, so the edges are visible behind the vertices.

<img width="411" alt="image" src="https://user-images.githubusercontent.com/1212871/147576487-4e70f980-f1fb-4565-b41f-1fd96122ce21.png">

The bug was noted here:

https://stackoverflow.com/q/70506672/695132

**To reproduce**

Try different random seeds. It is easy to reproduce the issue, but be sure to set vertex colours to transparent.

```
set.seed(1234)
g <- erdos.renyi.game(5, 6, 'gnm', directed=T)
plot(g, 
     vertex.size=30, 
     vertex.color=rgb(0.1,0.7,0.8,0.1), 
     vertex.shape="rectangle")
```

**Version information**

1.2.10

**Comment by ucb** [comment]
I see this issue has been discovered and re-discovered by several users during the two years. Are thre any suggestions for fixes?

**Comment by ntamas** [comment]
This is an R implementation issue. Plotting is implemented separately in each of the higher-level interfaces. I am not familiar with R so I cannot offer a fix myself, but hopefully @krlmlr or @Antonov548 can chime in sooner or later. If someone figures this out in the meanwhile, PRs are welcome. There is most likely a piece of code somewhere that figures out the intersection between the rectangular outline and the edge itself and there is a bug somewhere in that code for certain combinations of angles.

**Comment by ntamas** [comment]
For those attempting to fix or at least write regression tests for it: there is another example in igraph/igraph#2455
