### ISSUE TITLE
Should say "type"

### ISSUE THREAD

**Issue by brooksambrose** [igraph/rigraph#510]
A little thing that nonetheless may cause confusion: this error message should advise the user to add a `type` not a `types` vertex attribute.

https://github.com/igraph/rigraph/blob/4b48d0e94cbf1bbc032250a3d82d2ef759bf60db/R/conversion.R#L777

**Comment by szhorvat** [comment]
In cases like this, feel free to open a PR. You can even do it through GitHub's web interface.

**Comment by ntamas** [comment]
Well, strictly speaking, the error message is correct; you need to supply the `types` argument to the _function call_  (in this particular case `as_incidence_matrix`) to specify the vertex types. Alternatively, you can use the `type` vertex attribute; igraph falls back to this vertex attribute if `types` is missing or `NULL` in the function call.

I'll try to clarify the error message a bit.
