### ISSUE TITLE
`cluster_fluid_communities` drops vertex names

### ISSUE THREAD

**Issue by VPetukhov** [igraph/rigraph#527]
**Describe the bug**
Community detection using `cluster_fluid_communities` ignores vertex names and always returns unnamed community vector. Other methods work fine

**To reproduce**
```r
g <- igraph::make_full_bipartite_graph(10, 10)
V(g)$name <- paste0("v", 1:length(V(g)))
names(membership(cluster_fluid_communities(g, 10)))
```

**Version information**
1.3.0 Github (igraph/rigraph@c4b0f81)

**Comment by ntamas** [comment]
Thanks, this will be fixed in 1.3.1
