### ISSUE TITLE
plot.igraph(..., vertex.frame.width=0) no longer works in igraph 1.3.0

### ISSUE THREAD

**Issue by hpages** [igraph/rigraph#530]
Hi,

The following code worked with previous versions of **igraph**:
```
library(igraph)
g <- make_ring(10)
plot(g, layout=layout_with_kk, vertex.frame.width=0)
```
but not with **igraph** 1.3.0:
```
plot(g, layout=layout_with_kk, vertex.frame.width=0)
# Error in symbols(x = coords[, 1], y = coords[, 2], bg = vertex.color,  : 
#   invalid value specified for graphical parameter "lwd"
```
This breaks Bioconductor package **AlphaBeta** on all platforms in [release](https://bioconductor.org/checkResults/3.14/bioc-LATEST/AlphaBeta/) and [devel](https://bioconductor.org/checkResults/3.15/bioc-LATEST/AlphaBeta/).

Best,
H.

**Comment by ntamas** [comment]
Thanks, I wonder why this was not discovered with `revdepcheck` before submission. Let me look into this real quick.

**Comment by ntamas** [comment]
In previous versions where things worked, did `vertex.frame.width=0` have _any_ effect at all or was it simply ignored? The only place where the affected part of the code changed is [this commit](https://github.com/igraph/rigraph/commit/abddfa25708108ef780ee0029f849783abc5956d), which added support for `vertex.frame.width`, so the option should have had no effect in earlier versions.

**Comment by hpages** [comment]
I'm not the author of **AlphaBeta** and I'm not familiar with its code. I installed **igraph** 1.2.11 from the CRAN package archive and setting `vertex.frame.width` to 0 or any other value seems to have no effect at all. Was `vertex.frame.width` even a valid argument in **igraph** 1.2.11?

```
library(igraph)
g <- make_ring(10)
plot(g, layout=layout_with_kk, an_invalid_argument=5e6)
```
Hmm.. seems like invalid arguments are silently ignored :disappointed: 

H.

**Comment by ntamas** [comment]
Indeed, and it has always been this way; the only change is that `vertex.frame.width` is not invalid any more, and the zero value that the package supplies to it is actually not a valid frame width.

Nevertheless, I have added support for `vertex.frame.width == 0` in 6a933482 so this should not crash the test cases any more once igraph 1.3.1 is released.

**Comment by hpages** [comment]
Thanks. Hopefully **igraph** 1.3.1 can be released to CRAN soon so the `plotPedigree()` function in **AlphaBeta** works again.

**Comment by ntamas** [comment]
I've just revdepchecks with a release candidate of igraph 1.3.1 and everything seemed fine so I'll probably submit a patch version in the next few days.
