### ISSUE TITLE
Outdated example for raster vertex shapes?

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#533]
There is an example here that uses last.fm to get a graph with artist pictures (the last one):

https://igraph.org/r/doc/shapes.html

It does not actually show the pictures. Probably the last.fm API changed? This should be fixed.

**Comment by ntamas** [comment]
I decided to remove the example; it would be too much work to re-write it completely using a different web service, and even if we did, note that there was a hardcoded API key in the example, which is not nice.

**Comment by szhorvat** [comment]
Last.fm still works, it's just that the API might have changed. But yes, there's that thing with the API key ... that basically represents our (or Gabor's) responsibility and should not be exposed to the whole world.

**Comment by ntamas** [comment]
Even if it works, I wouldn't want to follow up API changes whenever the upstream API changes...

**Comment by szhorvat** [comment]
It would be good to add an alternative example, as people are demanding similar things: https://stackoverflow.com/q/73525798/695132
