### ISSUE TITLE
How to repel labels from igraph?

### ISSUE THREAD

**Issue by levinhein** [igraph/rigraph#538]
Hello. May I ask if igraph supports ggrepel or how can I repel labels from network plots generated from igraph? Not that good at coding, hope anyone can point me to an example or resource showing how to repel network plots to show labels, if anyone have any experience with it.  

Thank you!!!

**Comment by GroteGnoom** [comment]
Hi! I don't think igraph directly supports such label repelling, so if you want you'll have to fix it manually. You can for example add an extra node to each node and connect it with some weight. Then you can layout the graph (maybe with kamada-kawai? ) and change the weights to control where all the labels end up.

We'd like to use issues for things we have to fix in the code, and keep support questions in the forum: https://igraph.discourse.group/, so I'm closing this issue 🙂
