### ISSUE TITLE
Crash in rigraph function permute()

### ISSUE THREAD

**Issue by clpippel** [igraph/rigraph#542]
**Describe the bug**
The following code makes R / rigraph crash.

**To reproduce**
~~~
# sessionInfo()
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 10 x64 (build 22000)
# R version 4.1.3 (2022-03-10)
# [1] compiler_4.1.3  magrittr_2.0.1  pkgconfig_2.0.3
# [1] igraph_1.3.1
sg <- graph_from_literal(
 4 -+1 ,  20-+1 ,  34-+1 ,  35-+1 ,  68-+1 ,  69-+1 ,  75-+1 ,  3 -+2 ,  12-+2 ,  14-+2
,65-+2 ,  2 -+3 ,  13-+3 ,  15-+3 ,  26-+3 ,  1 -+4 ,  6 -+4 ,  9 -+4 ,  27-+4 ,  40-+4
,12-+5 ,  18-+5 ,  22-+5 ,  4 -+6 ,  12-+6 ,  37-+6 ,  41-+6 ,  43-+6 ,  46-+6 ,  11-+7
,43-+7 ,  47-+7 ,  74-+7 ,  19-+9 ,  34-+9 ,  37-+9 ,  71-+9 ,  40-+10,  53-+10,  7 -+11
,25-+11,  34-+11,  2 -+12,  6 -+12,  16-+12,  17-+12,  19-+12,  14-+13,  52-+13,  68-+13
,38-+14,  70-+14,  52-+15,  73-+15,  30-+16,  41-+16,  41-+17,  67-+17,  17-+18,  69-+18
,72-+18,  50-+19,  73-+19,  75-+19,  37-+20,  23-+21,  28-+21,  67-+21,  5 -+22,  69-+22
,72-+22,  71-+23,  64-+25,  65-+26,  68-+27,  72-+27,  21-+28,  16-+30,  36-+30,  42-+30
,42-+32,  9 -+34,  48-+34,  40-+35,  44-+35,  47-+36,  61-+36,  6 -+37,  49-+37,  45-+38
,70-+38,  74-+38,  53-+39,  64-+39,  65-+39,  35-+40,  16-+41,  32-+42,  61-+42,  73-+43
,38-+44,  50-+44,  71-+44,  48-+45,  59-+47,  45-+48,  67-+48,  50-+49,  44-+50,  49-+50
,21-+53,  39-+53,  66-+56,  47-+59,  66-+60,  7 -+64,  10-+64,  39-+64,  20-+65,  25-+65
,39-+65,  60-+66,  26-+67,  48-+67,  36-+69,  38-+70,  46-+70,  44-+71,  64-+71,  27-+72
,15-+73 
)
tg <- sg %>% get.edgelist %>% .[, 2:1] %>% graph_from_edgelist(directed=TRUE) # transpose graph
permute(tg, V(tg)$name) # restore original order of vertices
~~~

If you are confident that the issue is not in the R interface but in the
C core of igraph, please add it to the main [igraph repo](https://github.com/igraph/igraph)
instead.

If you are unsure, feel free to add your issue here - we will transfer it to
the main [igraph repo](https://github.com/igraph/igraph) if the root cause is
in the C core of igraph.

**Version information**
 igraph_1.3.1

**Comment by clpippel** [comment]
You are absolutely right.
However, my program still crashes after applying your suggestion.

The above example is still OK for a demonstration for the error in permute().

**Comment by mbojan** [comment]
My code above does not crash for your data.

**Comment by clpippel** [comment]
My original graph is (much) bigger. This example has been reduced in size for practical reasons.

~~~
IGRAPH dbbd732 DNW- 613 2883 -- Gamefile tree
~~~

**Comment by clpippel** [comment]
A smaller example:
~~~
library(igraph)
# The purpose of this code is to show a crash in permute
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 10 x64 (build 22000)
# R version 4.1.3 (2022-03-10)
# [1] compiler_4.1.3  magrittr_2.0.1  pkgconfig_2.0.3
# [1] igraph_1.3.2
sg <- graph_from_literal(
 12-+5 , 18-+5 , 22-+5
,43-+7 , 47-+7 , 74-+7 , 19-+9 , 34-+9 , 37-+9, 71-+9, 40-+10, 53-+10, 7 -+11
,42-+32, 9 -+34, 48-+34, 40-+35, 44-+35, 47-+36, 61-+36, 6 -+37, 49-+37, 45-+38
)
tg <- sg %>% get.edgelist %>% .[, 2:1] %>% graph_from_edgelist(directed=TRUE) # transpose graph
rtg <- permute(tg, V(tg)$name) # crash after a few seconds
~~~

**Comment by ntamas** [comment]
Hmm, the first, original example crashes for me, but this new one doesn't. This is with R 4.2.0 on macOS, Apple M1. I'll investigate, thanks.

**Comment by ntamas** [comment]
Okay, so, first things first: `permute()` does not seem to work with names, only with indices:

```
> g <- graph_from_literal( a -+ b, b -+ c, c -+ d)
> permute(g, c("b", "c", "d", "a"))
Error in permute(g, c("b", "c", "d", "a")) :
  At core/constructors/basic_constructors.c:75 : Invalid (negative) vertex id, Invalid vertex id
In addition: Warning message:
In permute(g, c("b", "c", "d", "a")) : NAs introduced by coercion
```

The messages are cryptic, but what essentially happens inside `permute()` is that the permutation vector is piped through `as.numeric` and then you get a bunch of NAs in there.

In your case, the permutation vector happens to survive `as.numeric()` because the names can actually be cast into numbers, but at that point you are working with vertex _IDs_, not names, and IDs like 75 are incorrect (because you only have 63 vertices).

Nevertheless, the R interface shouldn't crash even when fed with invalid input so I'll fix this. If I have some more time, I'll enable the remapping of vertex names to IDs as well.

**Comment by ntamas** [comment]
Now this seems to be a Heisenbug. The original example (which crashes for me) does _not_ crash when running R via a debugger (`lldb`).

**Comment by szhorvat** [comment]
Nor with AddressSanitizer, which I tried.

**Comment by clpippel** [comment]
I have a large graph that is constantly crashing. However, I don't know how to communicate the graph.

As I mentioned before, the code is less likely to crash after a successful attempt.

**Comment by ntamas** [comment]
Does the large graph crash also when you correctly provide a _numeric_ vector as the second argument of `permute()`? The second argument of `permute()` must be an index vector such that the i-th element tells what the new index of vertex i must be.

**Comment by clpippel** [comment]
Yes it does.

I have created a small function:
~~~
# transpose directed weighted graph, reverse edges
t.graph <- function(g){
tg <- g %>% get.edgelist %>% .[, 2:1] %>% graph_from_edgelist(directed=TRUE) # transpose graph
E(tg)$weight <- E(g)$weight
return(permute(tg,  match(V(tg)$name, V(g)$name))) # restore original order of vertices
}
~~~
It crashes after t.graph(g), where g is constructed from a tournament table.

**Comment by szhorvat** [comment]
Can you save the large graph to a file and share that file?

**Comment by szhorvat** [comment]
@ntamas Can you reproduce the crash when using the command line instead of the GUI version of R, on macOS? I cannot. It only crashes with the GUI.

**Comment by ntamas** [comment]
For me it's the opposite: it does not crash with the GUI but it crashes from the command line with `Rscript`, unless I turn on debugging, in which case it doesn't crash again.

If I have some more time next week, I'll try with an R-debug Docker image in Linux (see https://github.com/wch/r-debug/blob/master/debugging-r.md )

**Comment by szhorvat** [comment]
After trying many many times, I get occasional crashes, but only with the CRAN R binary. With the debug/ASan version of R that I compiled, I could never get a crash. Now I can look at the macOS crashlogs and see what I find. It's different every time, and the crash is never in a C/igraph call. Furthermore, one time, instead of a crash, I got:

```
Error in match.call() : bytecode version is too old
```

So perhaps some memory region belonging to R gets overwritten, which then causes trouble at a later point. But if this is true, ASan _should_ catch it.

**Comment by clpippel** [comment]
Please find enclosed the result of toString(g).
[ghcrash542.txt](https://github.com/igraph/rigraph/files/8987115/ghcrash542.txt)

**Comment by szhorvat** [comment]
Could you perhaps save it using the `save` command, which would allow simply loading it on our end? The format of `toString` is not easy to convert back to a usable object.

**Comment by clpippel** [comment]
It would be nice to have fromString()  as an inverse for toString(). 

Please find enclose a zipped copy of the workspace.
[ghcrash452.zip](https://github.com/igraph/rigraph/files/8987359/ghcrash452.zip)

**Comment by clpippel** [comment]
I wonder if moving the workspace is safe. Or is it possible (for me)  to inject malicious code?

**Comment by szhorvat** [comment]
Good question, I don't know. `saveRDS`/`readRDS` is probably better as they don't save the workspace contents, just a single R object.

**Comment by szhorvat** [comment]
No, not at the moment. Doesn't crash for me on Mac.

**Comment by clpippel** [comment]
Please find a smaller example below:
```
for (i in seq(1000)){
  sg <- graph_from_literal(
   12-+5 
  ,43-+7 
  ,42-+32
  )
  tg <- sg %>% get.edgelist %>% .[, 2:1] %>% graph_from_edgelist(directed=TRUE) # transpose graph
  rtg <- permute(tg, V(tg)$name) # crash after a few seconds
}
```

**Comment by clpippel** [comment]
Consider:
```
for (i in seq(8)){
  sg <- graph_from_literal(
   3-+1 
  ,5-+2 
  ,4-+32
  )
  permute(sg, V(sg)$name) # crash after a few seconds
}
```

**Comment by szhorvat** [comment]
I added a check that verified that the permutation vector is valid, https://github.com/igraph/igraph/commit/9cea1f6453b28fc81ddab9400ef79ce04b452432 @ntamas Have a look before I port it to `develop`.

@clpippel As @ntamas said earlier, using `V(sg)$name` is not currently valid for the permutation vector. It should be a vector of integers. The above check will catch this error in future versions. Do you have any example that crashes where the input is a valid permutation vector?

**Comment by clpippel** [comment]
The transposed graph does not contain the isolates. That could be the problem.

I didn't find any problems with the graph connected.

**Comment by szhorvat** [comment]
Since we can't reliably reproduce these crashes, would you be willing to help with testing the development version? You would need to compile it from source. Are you comfortable doing this?

Here's what you need to do on Windows:

 - Make sure you have the latest R, 4.2.1
 - Install RTools 4.2: https://cran.r-project.org/bin/windows/Rtools/
 - Restart R, make sure you have the `remotes` package installed, then run `remotes::install_github("igraph/rigraph@master")`. This will install the latest development version of R/igraph.

If you could test it, it would be helpful, but if you're not comfortable compiling packages from source, that's fine too.

**Comment by ntamas** [comment]
> I added a check that verified that the permutation vector is valid, https://github.com/igraph/igraph/commit/9cea1f6453b28fc81ddab9400ef79ce04b452432 @ntamas Have a look before I port it to develop.

Thanks, this looks good and feel free to port it to `develop`!

> It should be a vector coercible to integer and within range, I think.

A word of warning: the vertex with ID = `x` (as an integer) might or might not be the same as the vector with _name_ = `"x"`. When you pass a list of _strings_ to `permute()`, the strings in there mean vertex _names_. However, `permute()` will simply coerce them to integers and at that point the vertex _names_ turn into vertex _IDs_, so you might end up with a different permutation than what you want.

For instance, consider this graph:

```
g <- make_ring(3)
Vg)$name <- c("4", "5", "6")
```

In this case, vertex with ID=1 has name `"4"`. Passing `c("5", "6", "4")` as an input to `permute()` would coerce the vector into `c(5, 6, 4)`, but none of the members in this vector are valid vertex _IDs_ in the input graph. Indeed, this is not checked in the C core of igraph and this could be a potential reason for the crash. That's what @szhorvat is attempting to fix in the C core. Until then, a quick check in R to determine whether a permutation vector is valid:

```
> perm <- c("4", "5", "6")
> all(is.finite(perm) & perm >= 1 & perm <= vcount(g))
FALSE
```

**Comment by clpippel** [comment]
I am not very comfortable compiling packages. I haven't done that for 50 years now.
I am rather confident this will solve the problem. 

One more question: is there an obvious way to find the isolates?
If yes, I would appreciate a suggestion.

**Comment by mbojan** [comment]
I downloaded the graph from https://github.com/igraph/rigraph/issues/542#issuecomment-1166626619 and

```r
library(igraph)

load("~/Desktop/ghcrash452.RData")

# Transpose
tg <- g |>
  get.edgelist() %>%
  .[, 2:1] |>
  graph_from_edgelist(directed=TRUE)
```

I could swear there was a function for graph transpose in **igraph**, but I think there isn't (perhaps an enhancement?). Indeed as noted in https://github.com/igraph/rigraph/issues/542#issuecomment-1168511934 computing the transpose using only the edge list makes sense only if the graph is connected as it ignores the isolates. 

```r
table(degree(g))["0"]
## 0 
## 12 
vcount(g) - vcount(tg) # Isolates were dropped because of the above
## [1] 12
```

I dont know C enough to dig further but I suspect the crash might be because the transposed graph is smaller than the original so there are values in `V(g)$name` (original graph) that are greater than the network size, that is:

```r
table(as.numeric(V(g)$name) <= vcount(tg))

## FALSE  TRUE 
##   12   601
```

Perhaps a simple R-level check in `permute()` in the direction of `all(permutation <= vcount(graph) &  permutation >= 1)  will do?



More generally @clpippel , a better solution is to use a (sparse) adjacency matrix:

```r
library(Matrix)
am <- as_adjacency_matrix(g, sparse = TRUE)
tg2 <- graph_from_adjacency_matrix(t(am)) # transpose the adj. mat.
vcount(g) - vcount(tg2) # OK
## 0
```

and no permutation is required:

```r
identical(V(g)$name, V(tg2)$name)
## [1] TRUE
```


<details>
<summary>Session info</summary>

      ─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────
       setting  value
       version  R version 4.2.0 (2022-04-22 ucrt)
       os       Windows 10 x64 (build 19042)
       system   x86_64, mingw32
       ui       RStudio
       language en
       collate  Polish_Poland.utf8
       ctype    Polish_Poland.utf8
       tz       Europe/Warsaw
       date     2022-06-28
       rstudio  2022.02.3+492 Prairie Trillium (desktop)
       pandoc   2.18 @ C:\\PROGRA~3\\CHOCOL~1\\bin\\pandoc.exe
      
      ─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────
       package     * version date (UTC) lib source
       cli           3.3.0   2022-04-25 [1] CRAN (R 4.2.0)
       clipboard     0.0-1   2022-06-28 [1] Github (mbojan/clipboard@69b1b7c)
       colorspace    2.0-3   2022-02-21 [1] CRAN (R 4.2.0)
       igraph      * 1.3.2   2022-06-13 [1] CRAN (R 4.2.0)
       lattice       0.20-45 2021-09-22 [3] CRAN (R 4.2.0)
       lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.2.0)
       magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.2.0)
       Matrix      * 1.4-1   2022-03-23 [3] CRAN (R 4.2.0)
       mbtools       0.3-0   2022-06-28 [1] Github (mbojan/mbtools@ed7680f)
       munsell       0.5.0   2018-06-12 [1] CRAN (R 4.2.0)
       pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.2.0)
       R6            2.5.1   2021-08-19 [1] CRAN (R 4.2.0)
       rlang         1.0.2   2022-03-04 [1] CRAN (R 4.2.0)
       scales        1.2.0   2022-04-13 [1] CRAN (R 4.2.0)
       sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.0)
      
       [1] C:/Users/mbojanowski/Documents/R/library/x86_64-w64-mingw32/4.2
       [2] C:/Program Files/R/R-4.2.0/site-library
       [3] C:/Program Files/R/R-4.2.0/library
      
      ──────────────────────────────────────────────────────────────────────────────────────────────────────────────

</details>

**Comment by szhorvat** [comment]
Filter for vertices with degree zero. Something like `which(degree(g, mode='all') == 0)`

**Comment by mbojan** [comment]
I did not notice that the @szhorvat already added the test. Apologies!

**Comment by clpippel** [comment]
@mbojan, A appreciate your suggestion, but I like a spartan approach. So I'm reluctant to import the Matrix package.

**Comment by clpippel** [comment]
@ntamas,
    A word of warning: the vertex with ID = x (as an integer) might or might not be the same as the vector with name = "x". 
This is a philosophical question indeed.  Do we need to be strict (and save) or permissive?

**Comment by clpippel** [comment]
This will do the transpose of the graph, including isolates
```
# transpose directed weighted graph, including isolates
t.graph <- function(g){
tg <- make_graph(t(get.edgelist(g, names=FALSE)[,2:1]), vcount(g)) # transpose edges
E(tg)$weight <- E(g)$weight                                                           # keep weights
if (!is.null( V(g)$name)) V(tg)$name <- V(g)$name                          # keep name
return(tg)
}
```

**Comment by clpippel** [comment]
Third attempt.
```
# transpose directed graph, including isolates
# keep edge attributes
t.graph <- function(g){
tg <- add_edges(delete_edges(g, edges=E(g)), t(get.edgelist(g, names=FALSE)[,2:1])) # transpose and revert edges
edge_attr(tg) <- edge_attr(g)                                      # save edge attributes
return(tg)
}
```

**Comment by szhorvat** [comment]
The crash was likely due to invalid indices in the permutation vector. That is now fixed in the development version. Since we cannot reproduce the crash consistently on our end, we need you (or someone else) to test the fix.

You will be able to test this easily once version 1.3.3 has been released. Alternatively, you can compile the development version ([see three-step process](https://github.com/igraph/rigraph/issues/542#issuecomment-1168558294)) and test with that.

**Comment by clpippel** [comment]
Then I think I can close this issue after a successful test on my machine.

**Comment by clpippel** [comment]
The function successfully catches the following errors:

- At core/operators/permute.c:50 : Invalid index in permutation vector. Invalid value
- At core/operators/permute.c:54 : Duplicate entry in permutation vector. Invalid value
- At core/operators/permute.c:91 : Permute vertices: invalid permutation vector size. Invalid value
