### ISSUE TITLE
No chart output in plot when plotting large graph

### ISSUE THREAD

**Issue by clpippel** [igraph/rigraph#546]
**Describe the bug**
I understand it doesn't make much sense to plot a graph with 40000*125 edges.
But I wonder why only the title is executed and there is no warning that the graph is missing.

**To reproduce**
```
# title = Players = 39999, Games = 2559872, SCC = 1
load("~\\ghbug453.RData")
library(igraph)
dev.new()
system.time(try(
plot(g, mark.groups = SCC$groups
      , layout = layout_in_circle
      , y.flip=FALSE
    )
,silent=TRUE) )
# --------------------------------
   user  system elapsed
  60.59    0.31   60.94
```
If you are confident that the issue is not in the R interface but in the
C core of igraph, please add it to the main [igraph repo](https://github.com/igraph/igraph)
instead.

If you are unsure, feel free to add your issue here - we will transfer it to
the main [igraph repo](https://github.com/igraph/igraph) if the root cause is
in the C core of igraph.

**Version information**
R version 4.1.3 (2022-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

[1] igraph_1.3.2

Unfortunately the file to upload is too big (117MB).

**Comment by ntamas** [comment]
Not sure but maybe the `try(..., silent=TRUE)` part silences any warnings / errors that R might print?

I tried this on my Mac but it's still doing something after 3 minutes so I'll wait it out and see what happens:

```
> g <- sample_gnm(n=39999, m=2559872)
> plot(g, layout=layout_in_circle)
```

**Comment by ntamas** [comment]
Okay, so after several minutes the function returned and I got a nice big gray circle, which I guess is actually 2.5 million edges. But the plot seems to have succeeded. Can you try removing the `silent=TRUE` part on your machine to see if it prints something?

**Comment by clpippel** [comment]
There is an error message with silent = FALSE!
```
> dev.new()
> system.time(try(
+ plot(g, mark.groups = SCC$groups
+       , layout = layout_in_circle
+       , y.flip=FALSE
+     )
+ ,silent=FALSE) )
Error in xspline(cl$rescoords, shape = shape, open = FALSE, col = col,  : 
  add_point - reached MAXNUMPTS (25200)
   user  system elapsed 
  61.22    0.43   61.65 
```

>

**Comment by ntamas** [comment]
Okay, this one comes from the `mark.groups` parameter. It determines the convex hull of a group first, and then draws a spline around the group with `xspline`. I guess that if the group is large, it becomes harder and harder to fit a spline around the group, and eventually it reaches a stage where R refuses to add more points to the spline.

**Comment by clpippel** [comment]
To conclude:

1. There was no warning because silent=TRUE.
2. It is not unreasonable for this file to be too big.

**Comment by ntamas** [comment]
Yes, exactly. Closing the issue.
