### ISSUE TITLE
Reverse the direction of edges and transpose

### ISSUE THREAD

**Issue by clpippel** [igraph/rigraph#547]
**What is the feature or improvement you would like to see?**

Reversing the direction of edges is basically a transpose of a directed graph.

Transpose is an elementary and important concept applicable to matrices and graphs.
Therefore it would be nice to be compatible with objects like vector, list, matrix and sparse matrix.

In addition to a new function `reverse_edges()` , let `t(g)` be the transpose of graph `g`.

It’s "syntactic sugar" but nice to have.

**Use cases for the feature**

```r
library(igraph)
library(Matrix)
g <- make_star(7); g 

v  <- c(1,2,3,4,5,6,7,8); t(v)
m  <- matrix(v, 4,2); t(m)
p  <- g[]; t(p)

tg <- t(g);                                                  # transpose "igraph" c;lass
te <- t(edges(g)                                             # transpose "igraph.edge" class
g |> t() |> t() |> identical_graphs(g) |> stopifnot()        # t∘t equals I
```

**References**

 - https://github.com/igraph/igraph/issues/1477

**Comment by szhorvat** [comment]
The request to add `t` as an alias for `reverse_edges` makes sense to me.

@mbojan As an expert user, do you see any reason why `t` shouldn't be added as an alias for `reverse_edges`? Are there any expectations from R users that `t` should return a matrix, even when passed a non-matrix input?

`reverse_eges` is a newly added function that works like this:

```
> g <- make_graph(~ a-+b, b+-c)
> g
IGRAPH 2472e57 DN-- 3 2 -- 
+ attr: name (v/c)
+ edges from 2472e57 (vertex names):
[1] a->b c->b
> reverse_edges(g) # reverse all edges
IGRAPH 523cafd DN-- 3 2 -- 
+ attr: name (v/c)
+ edges from 523cafd (vertex names):
[1] b->a b->c
> reverse_edges(g, 1) # reverse only the 1st edge
IGRAPH d41e8b1 DN-- 3 2 -- 
+ attr: name (v/c)
+ edges from d41e8b1 (vertex names):
[1] b->a c->b
```

**Comment by clpippel** [comment]
@szhorvat, A s I found out recently
```
g <- make_ring(3)
set_edge_attr(g, "weight", value = seq(3) )
edge_attr(g)
```
returns `list()`, that is, it does nothing. The reason is that objects in R are immutable.
So rather then
`> reverse_edges(g) # reverse all edges`

it should be
`> g <- reverse_edges(g) # reverse all edges`

**Comment by mbojan** [comment]
> In addition to a new function `reverse_edges()` , let `t(g)` be the transpose of graph `g`.

Good idea.

BTW: Did you test it on a digraph with isolates?

**Comment by ntamas** [comment]
Yes, and it works. I'm just adding a formal test case for it now.

**Comment by szhorvat** [comment]
The function is implemented in C and the number of vertices is passed to the constructor of the new graph: https://github.com/igraph/igraph/blob/master/src/operators/reverse.c#L81 So isolates are fine.
