### ISSUE TITLE
Setting the `layout` attribute of a graph to `layout_nicely` causes infinite recursion

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#552]
**Describe the bug**

Setting the `layout` attribute of a graph to `layout_nicely` causes infinite recursion.

**To reproduce**

```r
> g <- make_ring(4)
> g$layout <- layout_nicely
> plot(g)
Error: C stack usage  7971488 is too close to the limit
```

**Version information**

1.3.3, as well as older.

**Comment by ntamas** [comment]
should be fixed in 4d62d515
