### ISSUE TITLE
layout_as_tree occasionally drops a label if graph is not a tree

### ISSUE THREAD

**Issue by clpippel** [igraph/rigraph#559]
**Describe the bug**
 layout_as_tree occasionally drops a label if graph is not a tree.

**To reproduce**
```
# g is indeed not a tree.
# label 5 is absent.
# edge 5 (10->6) is drawn through vertex 2, 14.
# If this is drawn as a nondirected graph, this gives a deceptive impression.
library(igraph)
g <- graph_from_literal(4-+10:2:14:6, 10-+6)
E(g)$label <- seq_len(ecount(g))
g$main <- "Label 5 is missing"
g
plot(g, layout=layout_as_tree)
```

**Version information**
Which version of igraph are you using?
![lay-out-as-tree-label-missing](https://user-images.githubusercontent.com/9609214/182546890-2009acc9-0560-48c4-b434-86627662265c.jpg)

[1] igraph_1.3.4

**Comment by ntamas** [comment]
This  is most likely a "wontfix" :( The label is not missing, it just happens to be "behind" vertex 2 (labels are plotted at one third of the edge, closer to the tail of the edge). Also, checking whether an edge goes straight through other vertices is computationally costly, especially for large graphs, so it's unlikely we'll add such a check in the plotting code. You can set the edge to curved manually and then you'll see that the label is also there:

```
plot(g, layout=layout_as_tree, edge.curved=c(0,0,0,0,0.5))
```
