### ISSUE TITLE
compose() crashing when allocating memory

### ISSUE THREAD

**Issue by clpippel** [igraph/rigraph#561]
**Describe the bug**
Compose crashing when allocating memory.

**To reproduce**
```
n <- 800
g <- make_full_graph(n)
system.time(q <- compose(g, g))  # crash after 10 seconds if n = 1000

The program produces the following error:
# Error: cannot allocate vector of size 3.8 Gb
# Timing stopped at: 66.94 46.47 135.9
```
For n = 1000, however, a crash occurs after about 10 seconds.

Also crashing: make_full_graph(1E5)

**Version information**
sessionInfo()

locale:
[1] LC_COLLATE=Dutch_Netherlands.1252  LC_CTYPE=Dutch_Netherlands.1252   
[3] LC_MONETARY=Dutch_Netherlands.1252 LC_NUMERIC=C                      
[5] LC_TIME=Dutch_Netherlands.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] igraph_1.3.4

loaded via a namespace (and not attached):
[1] compiler_4.1.3  magrittr_2.0.1  rlang_1.0.4     pkgconfig_2.0.3

**System**
Processor	AMD Ryzen 7 3700X 8-Core Processor 3.60 GHz
Geïnstalleerd RAM-geheugen	16,0 GB
Type systeem	64-bits besturingssysteem, x64-processor (W11)
```

**Comment by mbojan** [comment]
I believe that's standard R behavior when trying to create an object too
big for memory. The timing is not relevant. Probably R asks for memory
several times and trips on, say, second time for 1000 but on 8th time for
800. That's not an igraph bug.

**Comment by clpippel** [comment]
I tried:

`x <- rep(pi, 1E10)`

and got:

`Error: cannot allocate vector of size 74.5 Gb`

without any problems.

**Comment by mbojan** [comment]
@clpippel I believe the behavior you report is correct. It's not a bug and this issue should be closed.

**Comment by clpippel** [comment]
@mbojan If this is as expected, the documentation should be updated to describe this behaviour.
In this situation it is immediately clear. But this can also occur deeply hidden in a program.

**Comment by mbojan** [comment]
I think it is sufficiently documented on `?Memory` and related pages. See also http://adv-r.had.co.nz/memory.html.

**Comment by clpippel** [comment]
I tried:
```
## the purpose of this program is to provoke memory errors
ll <- list()
for ( i in seq(1E10) ){
   force(print(i))
   append(ll, rep(pi, 1E9) )
}
```
[1] 1
And got:
```
Error: memory exhausted (limit reached?)
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
```

This is good. However, I don't expect the program to close without warnings.

**Comment by szhorvat** [comment]
C/igraph 0.9, which R/igraph 1.3 is based on, does not behave well when data structure sizes exceed their maximum limit. C/igraph 0.10 (not yet released) improves on this substantially, but it will take some time until these improvements can make it into R/igraph.

**Comment by clpippel** [comment]
Then I will test it when the new version is available. Together with #405.

**Comment by szhorvat** [comment]
Yes, this is of the same nature as #405. I had a look at the C code for `compose()` and I _think_ it should work fine in the new version. "Fine" here means that when maximum sizes are exceeded, an error will be issued and R will not crash.

**Comment by ntamas** [comment]
Also note that the behaviour that you will see at times of over-allocation is heavily system-dependent. For instance, Linux systems may overcommit memory allocations (i.e. pretend that it successfully managed to allocate a chunk of memory that is larger than the largest block available) in the hope that not all pages of the allocated chunk will be used in practice, and then crash the process later (without an error message) when it turns out that indeed more memory is needed than what is available.

**Comment by ntamas** [comment]
Targeting this for 2.0 (which is a long way ahead) because it will require C/igraph 0.10, which will break lots of stuff so we can only do it after a major version bump.

**Comment by szhorvat** [comment]
I took another look at the behaviour here, and I don't think we can do anything about it. As @mbojan says, the behaviour is from R. igraph itself does check for OOM errors as much as possible, but some systems will just terminate the program on OOM anyway, without giving the program the chance to try to recover.

**Comment by szhorvat** [comment]
I have to say that I don't like the design of this function. I wish it didn't create multi-edges, but instead stored the edge multiplicity in an attribute. That would work around the high memory usage.
