### ISSUE TITLE
Installing old version of igraph

### ISSUE THREAD

**Issue by Jeff87075** [igraph/rigraph#564]
I want to ask how can I install an older version of ```igraph``` specifically version ```1.2.5``` since I've tried using the following codes but it still produces an error:
```
devtools::install_version(package = "igraph", version = "1.2.5")

In file included from feedback_arc_set.c:31:
igraph_glpk_support.h:36:10: fatal error: glpk.h: No such file or directory
 #include <glpk.h>
          ^~~~~~~~
compilation terminated.
make: *** [C:/PROGRA~1/R/R-40~1.3/etc/i386/Makeconf:222: feedback_arc_set.o] Error 1
ERROR: compilation failed for package 'igraph'
* removing 'C:/Users/Jeffrey/Documents/R/win-library/4.0/igraph'
Error: Failed to install 'unknown package' from URL:
  (converted from warning) installation of package ‘C:/Users/Jeffrey/AppData/Local/Temp/Rtmp0IQDfJ/remotes43a0383c3f33/igraph’ had non-zero exit status
```
```
packageurl <- "https://cran.r-project.org/src/contrib/Archive/igraph/igraph_1.2.5.tar.gz"
install.packages(packageurl, repos=NULL, type="source")

ERROR: compilation failed for package 'igraph'
* removing 'C:/Users/Jeffrey/Documents/R/win-library/4.0/igraph'
```

**Comment by ntamas** [comment]
This seems to be about the R interface so I'm transferring the issue to the R repo.

As for the messages you get: CRAN does not keep the pre-compiled binaries of older versions of packages, so your computer is attempting to build igraph from source code. In order to do that, it would need a bunch of additional libraries, notably GLPK, which it seems to be missing. Have you installed the [appropriate version of Rtools](https://cran.r-project.org/bin/windows/Rtools/) on your machine before attempting to build binaries on Windows?

**Comment by szhorvat** [comment]
We do not recommend using old versions. Most differences between old and new releases are the result of bugfixes.

Can you explain why you want to install an old version?

P.S. In the future please use the forum for support requests. We use the issue tracker for bug reports and feature requests only.

**Comment by Jeff87075** [comment]
Apologies, if given the option I would also like to use the newest version but I am actually trying to install another package ```CellChat``` which requires an older version of ```igraph``` otherwise it couldn't be installed hence the issue

**Comment by szhorvat** [comment]
I have just installed CellChat according to the instructions in its GitHub repository: https://github.com/sqjin/CellChat It loads correctly, but I did not tests its functionality. I have the latest igraph from CRAN. I see no indication in its README or DESCRIPTION files that it would require an old version of igraph. Can you please explain why you think that it needs an old igraph?

**Comment by Jeff87075** [comment]
I followed the instructions for installation but get this error:
```
Error: (converted from warning) package 'igraph' was built under R version 4.0.5
Execution halted
ERROR: lazy loading failed for package 'CellChat'
* removing 'C:/Users/Jeffrey/Documents/R/win-library/4.0/CellChat'
Error: Failed to install 'CellChat' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Jeffrey/AppData/Local/Temp/Rtmp4A1McZ/file36e85f58779c/CellChat_1.5.0.tar.gz’ had non-zero exit status
```
And upon going through the github of the package it seems similar problem was resolved by installing an older version of ```igraph```

**Comment by ntamas** [comment]
It seems like your R is converting a warning ("package 'igraph' was built under R version 4.0.5") into an error. Which version of R are you running and can you simply turn off the conversion of warnings to errors (i.e. `options(warning=1)`)? Maybe that would resolve your problem without having to install older versions of igraph.

**Comment by szhorvat** [comment]
This may be happening because you have an older R version than what igraph was built with. The simplest solution to upgrade your R, at leas to the latest point release of the release series.
