### ISSUE TITLE
Louvain and Leiden for directed graphs

### ISSUE THREAD

**Issue by Chengwei94** [igraph/rigraph#566]
Any timeline for louvain and leiden to support directed graphs too?

**Comment by szhorvat** [comment]
Please edit this and make it into a proper feature request conforming to the [issue template](https://github.com/igraph/rigraph/blob/dev/.github/ISSUE_TEMPLATE/feature_request.md) that was shown to you when you created the issue.

**Comment by Chengwei94** [comment]
I think this belong to the main igraph repo
