### ISSUE TITLE
simplify() fails on simple graph

### ISSUE THREAD

**Issue by hclimente** [igraph/rigraph#574]
**Describe the bug**
A library I depend on calls simplify on an already simple graph (4 edges). The call fails with a C error.

**To reproduce**

Download [the edgelist](https://github.com/hclimente/gwas-tools/blob/consensus/test/data/interactions.tsv), then run:

```r
library(igraph)
library(tidyverse)

g <- read_tsv("interactions.tsv") %>%
    graph_from_data_frame(directed=F)

simplify(g)
```

I get the following error:

> Error in adjacent_vertices(x, i, mode = if (directed) "out" else "all") :
  At core/graph/iterators.c:767 : Cannot create iterator, invalid vertex ID. Invalid vertex id

**Version information**

 - R/igraph version: 1.3.4
 - R version: 4.1.3
 - Operating system: macOS and Linux (tested on this Docker image: https://hub.docker.com/r/hclimente/gwas-tools)

**Comment by ntamas** [comment]
I cannot reproduce this locally on my machine with R 4.2.1 and R/igraph 1.3.4. Can you post the output of `traceback()` after seeing the error as well as the value of `igraph_opt("edge.attr.comb")` here?

**Comment by hclimente** [comment]
Thanks for trying it out. This is the output on both my macOS and the Docker container:
```
> traceback()
6: adjacent_vertices(x, i, mode = if (directed) "out" else "all")
5: `[[.igraph`(X, i)
4: X[[i]]
3: vapply(x, is.atomic, logical(1))
2: can_simplify(.x, .type)
1: simplify(g)
> igraph_opt("edge.attr.comb")
$weight
[1] "sum"

$name
[1] "concat"

[[3]]
[1] "ignore"
```

Actually, the problem happens even with the example graph at [simplify's documentation](https://igraph.org/r/doc/simplify.html):
```r
g <- graph( c(1,2,1,2,3,3) )
```

**Comment by ntamas** [comment]
The traceback shows a function named `can_simplify()`, which does not exist in R-igraph's source code anywhere. Are you sure that the `simplify` function is not shadowed by some other function from another package? Can you try running `igraph::simplify()` instead of `simplify()` on the graph?

**Comment by hclimente** [comment]
You are absolutely right, that solves the issue. I hadn't noticed, but tidyverse's purrr exports its own `simplify` function. I am not sure why `purrr:::simplify` calls rigraph's functions internally, but obviously this is not a bug on rigraph's side.

Thank you very much for your help.

**Comment by ntamas** [comment]
Wild guess: `purrr:::simplify` probably calls the indexing operator on an igraph graph, which in turn tries to reach into the adjacency list of the graph, but the index that is passed to the indexing function is not valid. Anyhow, I'm glad that it works now.
