### ISSUE TITLE
error: "as(<dsCMatrix>, "dgCMatrix") is deprecated ... "

### ISSUE THREAD

**Issue by stefpeschel** [igraph/rigraph#582]
Hi!

After updating the `Matrix` package to v1.5-1, calling `igraph::as_adjacency_matrix()` throws the message 
`as(<dsCMatrix>, "dgCMatrix") is deprecated since Matrix 1.5-0; do as(., "generalMatrix") instead`.

`as(<dsCMatrix>, "dgCMatrix")` is called within the igraph-internal function `get.adjacency.sparse()`.

Best,
Stefanie

**Comment by szhorvat** [comment]
This is fixed in the recently released igraph 1.3.5:

```
> as_adjacency_matrix(sample_gnm(4,4))
4 x 4 sparse Matrix of class "dgCMatrix"
            
[1,] . 1 1 1
[2,] 1 . 1 .
[3,] 1 1 . .
[4,] 1 . . .
```

Please double-check that this is the version you are using, and if you still see problems, please post a minimum reproducible example.
