### ISSUE TITLE
Building igraph fails when using parallel testing

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#585]
After the recent change to enable parallel testing, building igraph fails on my machine during the `test()` command.

Steps to reproduce:

```
git clean -fdx
make
```

then in R:

```
library(devtools)
install() # succeeds
test() # fails
```

The `test()` command will re-build igraph, and this re-building appears to fail. Specifically, running the `configure` script fails with `checking whether the C compiler works... no`. Looking into what happens, it turns out that the contents of the `confdefs.h` file, included in `conftest.c` used to check if the C compiler is working, is corrupted. I see this in`config.log`:

```
| /* confdefs.h */
| AME "igraph"
| #define PACKAGE_TARNAME "igraph"
| #define PACKAGE_VERSION "1.3.5.9023"
| #define PACKAGE_NAME "igraph"
| #define PACKAGE_STRING "igraph 1.3.5.9023"
| #define PACKAGE_TARNAME "igraph"
| #define PACKAGE_BUGREPORT "ntamas@gmail.com"
| #define PACKAGE_VERSION "1.3.5.9023"
| #define PACKAGE_URL ""
| #define PACKAGE_STRING "igraph 1.3.5.9023"
| #define PACKAGE_BUGREPORT "ntamas@gmail.com"
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
```

Notice that the `#define`s are added multiple times to this file, no doubt due to the parallel runs, and some of them are cut off.

Changing `Config/testthat/parallel: true` to `false` resolves the problem.

Any tips for this @krlmlr ?

Why does `test()` rebuild igraph at all? Is this necessary, is it avoidable? It takes far longer than actually running the tests.

**Comment by krlmlr** [comment]
Thanks. A workaround is to run the following code instead, in R:

```r
library(devtools)
install() # to install in the package library, optional
load_all() # to re-build in preparation for test()
test()
```

**Comment by krlmlr** [comment]
Because `install()` already seems to be run by `make`, it seems unnecessary. This also works:

```r
library(devtools)
load_all() # to re-build in preparation for test()
test()
```

With ccache, the rebuilding doesn't take all too long.

I can't tell without looking in closer detail why `load_all()` (which is called implicitly by `test()`) needs to rebuild the package. I'm pretty sure it's solvable, though.

**Comment by szhorvat** [comment]
> ```r
> library(devtools)
> load_all() # to re-build in preparation for test()
> test()
> ```

Thank you. This does work without having to disable parallel testing.

**Comment by ntamas** [comment]
it looks like #590 will solve this.
