### ISSUE TITLE
Function dfs() returns a 0-indexed root.

### ISSUE THREAD

**Issue by clpippel** [igraph/rigraph#589]
**Describe the bug**
Function dfs() returns a 0-indexed root, unlike dfs().

**To reproduce**
```
dfs(make_ring(3), root=1)$root
[1] 0
```
**Version information**
 - R/igraph version: [1] igraph_1.3.4
 - Operating system: Windows 10 x64

**Comment by ntamas** [comment]
Thanks a lot, this will be fixed in the next patch version (see commit above).
