### ISSUE TITLE
WArning for isolates in infomap

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/rigraph#59]
> From: Nick Eubank <nickeubank@gmail.com>

> Hi All,

> Two quick things:
 - the C notes for community_infomap() say infomap can't take isolated
vertices. It might be a good idea to put that note in the python and R
documentation. I only found it after lots of trouble shooting.
 - Does "isolated vertices" mean no vertices of degree zero, or no
disconnected components?

> Thanks!

> Nick

**Comment by nickeubank** [comment]
Not actually relevant according to infomap implementor.
