### ISSUE TITLE
Function convex_hull() returns a 0-indexed hull.

### ISSUE THREAD

**Issue by clpippel** [igraph/rigraph#613]
**Describe the bug**
Function convex_hull()$resverts returns a 0-indexed hull.

**To reproduce**
```
library(igraph)
n = 10
set.seed(45)
xy <- cbind(runif(n), runif(n))
vp <- convex_hull(xy)
vp$resverts
# [1] 7 9 6 1 0
```

**Version information**
 - R/igraph version: [1] "1.3.1.9037"

**Comment by ntamas** [comment]
Thanks, fixed, will be released in the next version.
