### ISSUE TITLE
RStudio's igraph.Rproj file deleted on branch switch

### ISSUE THREAD

**Issue by dmurdoch** [igraph/rigraph#618]
**Describe the bug**

I forked `igraph/rigraph` to https://github.com/dmurdoch/rigraph and used RStudio to check out a copy into a directory called `igraph`.  It chose the `dev` branch, so I attached the main site as a remote called `upstream`, and switched to `upstream/master`.  This deleted my `igraph.Rproj` file, which causes RStudio to get confused when I close and reopen the project.

I think this happens because `igraph.Rproj` is under version control in `dev`, but it is not present in `master`.

Shouldn't it be in neither one?  Or maybe in both, if it has some non-default settings.

**Comment by krlmlr** [comment]
Thanks. I believe the medium-term goal is to lose the master branch, so that this will become a non-issue.

What's your rationale to work on the master branch locally?

**Comment by dmurdoch** [comment]
The dev branch won't build, but the master branch will.  It looks as though dev is missing some configuration stuff, because compiles fail with `igraph.h not found` sorts of errors.

**Comment by krlmlr** [comment]
Can you please try running `make` on the dev branch, and then `R CMD INSTALL .` ?

**Comment by dmurdoch** [comment]
On a clean checkout of dev that fails with these messages:

```
$ make
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
python3 -m venv .venv
.venv/bin/pip install -r tools/build-requirements.txt
Collecting stimulus
  Cloning https://github.com/igraph/stimulus (to revision 0.11.0) to /private/var/folders/d6/s97fjjxd3_9353x_lwb692100000gn/T/pip-install-wlnfb01k/stimulus_adb2bee18a2f4b6b9e25e0f8b648c0c7
  Running command git clone --filter=blob:none --quiet https://github.com/igraph/stimulus /private/var/folders/d6/s97fjjxd3_9353x_lwb692100000gn/T/pip-install-wlnfb01k/stimulus_adb2bee18a2f4b6b9e25e0f8b648c0c7
  Running command git checkout -q f6ec07c7453196b8339447557e31077c5d404fcf
  Resolved https://github.com/igraph/stimulus to commit f6ec07c7453196b8339447557e31077c5d404fcf
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting PyYAML<7.0,>=6.0
  Using cached PyYAML-6.0-cp310-cp310-macosx_10_9_x86_64.whl (197 kB)
Collecting deepmerge<0.4.0,>=0.3.0
  Using cached deepmerge-0.3.0-py2.py3-none-any.whl (7.6 kB)
Building wheels for collected packages: stimulus
  Building wheel for stimulus (pyproject.toml) ... done
  Created wheel for stimulus: filename=stimulus-0.11.0-py3-none-any.whl size=45815 sha256=7d36cda52385d66c0070361980d133140a931797d46057053b488daa5a69a7b1
  Stored in directory: /private/var/folders/d6/s97fjjxd3_9353x_lwb692100000gn/T/pip-ephem-wheel-cache-1eebw977/wheels/93/0e/78/204a85a34af7858b77d4d1660bdd44623b79b3d48d0882b261
Successfully built stimulus
Installing collected packages: PyYAML, deepmerge, stimulus
Successfully installed PyYAML-6.0 deepmerge-0.3.0 stimulus-0.11.0

[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: python3.10 -m pip install --upgrade pip
touch .venv/stamp
make: *** No rule to make target `cigraph/interfaces/functions.yaml', needed by `R/aaa-auto.R'.  Stop.

```

I ran the suggested `python3.10 ...; touch .venv/stamp` commands, but it still fails.

**Comment by dmurdoch** [comment]
I'm on macOS 12.6.2, Monterey, in case that makes a difference.

**Comment by krlmlr** [comment]
I'm not sure if submodules are checked out automatically.

**Comment by dmurdoch** [comment]
Where is it looking for that?  I do have cigraph checked out, but not in the same directory.  Should I just put it beside igraph (which is really rigraph)?

**Comment by szhorvat** [comment]
Run `git submodule update --init` and try again.

**Comment by dmurdoch** [comment]
Thanks, that works.  For future reference I'll summarize the steps.

To build `igraph` from source on the `dev` branch:

1.  Check out the dev branch locally.
2.  In a terminal, run 
```
git submodule update --init
make
```
3. Use the usual method to install the package, e.g. the Build | Install menu item in RStudio, or `R CMD INSTALL .` in 
a terminal.
