### ISSUE TITLE
Treatment of `NULL` vertex and edge sets

### ISSUE THREAD

**Issue by krlmlr** [igraph/rigraph#623]
The interpretation of `NULL` vertex and edge sets has changed in d05ac3140bde37d53365da464e23b22fe89e1b90, to support #466. This leads to failures in the causaleffect package, https://github.com/igraph/rigraph/pull/621/files#diff-bbdda7f28391ee0ec001638e5603609582124345e0d65ebd4747cc592f9bd56dR30-R38.

That package is calling `subgraph.edges(g, NULL)` at some point. Should this be an error (better, but with breaking changes), or do we want to support the current (implicit) behavior that `NULL` means empty vertex/edge set?

This potentially affects all functions that use `as.igraph.vs()` or `as.igraph.es()` .

## Current dev

``` r
g <- igraph::make_ring(10)
igraph:::as.igraph.vs(g, NULL)
#> + 10/10 vertices, from 881e524:
#>  [1]  1  2  3  4  5  6  7  8  9 10
igraph:::as.igraph.es(g, NULL)
#> + 10/10 edges from 881e524:
#>  [1] 1-- 2 2-- 3 3-- 4 4-- 5 5-- 6 6-- 7 7-- 8 8-- 9 9--10 1--10
```

<sup>Created on 2023-01-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

## CRAN version

``` r
g <- igraph::make_ring(10)
igraph:::as.igraph.vs(g, NULL)
#> numeric(0)
igraph:::as.igraph.es(g, NULL)
#> numeric(0)
```

<sup>Created on 2023-01-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by krlmlr** [comment]
I'll revert the commit in question, `as.igraph.*()` is used virtually everywhere.

**Comment by ntamas** [comment]
I'd vote to keep on supporting the current behaviour where `NULL` means the empty vertex / edge set. I guess that's yet another reason for reversal.
