### ISSUE TITLE
sample_bipartite produces graphs with densities that appear too low when using the "gnp" option

### ISSUE THREAD

**Issue by ngmaclaren** [igraph/rigraph#629]
**Describe the bug**
sample_bipartite produces graphs with densities that appear too low when using the "gnp" option. 

**To reproduce**
```
library(igraph)

ntrials <- 1000

N <- 500
prop <- 1/3
n1 <- ceiling(N*prop)
n2 <- floor(N*(1 - prop))

p <- .06
m <- (p * (N * (N - 1)))/2

## "gnm" option gives exactly the correct density
b_gnm <- replicate(ntrials, sample_bipartite(n1, n2, "gnm", m = m), simplify = FALSE)
summary(sapply(b_gnm, edge_density))

## the unipartite version gives the density expected by `p`
u_gnp <- replicate(ntrials, sample_gnp(N, p), simplify = FALSE)
summary(sapply(u_gnp, edge_density))

## "gnp" option results in densities that are too low
b_gnp <- replicate(ntrials, sample_bipartite(n1, n2, "gnp", p = p), simplify = FALSE)
summary(sapply(b_gnp, edge_density))
```

I think the difference between the density I expected (p = 0.06, above) and the resulting graph density has to do with the n1/n2 split, which you can see by running the below code (target edge density is marked with the red line):
```
library(igraph)
palette("R4")

                                        # local plotting function
histlocal <- function(dl, ...) {
    x <- unlist(lapply(dl, edge_density))

    if(max(x) < p) {
        xlim <- c(min(x), p*1.05)
    } else if(min(x) > p) {
        xlim <- c(p*.95, max(x))
    } else xlim <- range(x)

    hist(x, breaks = 20, xlim = xlim, xlab = "Edge Density", ...)
    abline(v = p, col = 2, lwd = 2)
}

ntrials <- 1000

N <- 500

p <- .06
m <- (p * (N * (N - 1)))/2

props <- c(.1, .25, .333, .5)
plotdata <- lapply(props, function(prop) {
    n1 <- ceiling(N*prop)
    n2 <- floor(N*(1 - prop))
    replicate(ntrials, sample_bipartite(n1, n2, "gnp", p = p), simplify = FALSE)
})

dev.new(width = 12, height = 12)
par(mfrow = c(2, 2))
for(i in seq_along(props)) {
    histlocal(
        plotdata[[i]],
        main = paste("n1/n2 split at", props[i])
    )
}
```

**Version information**

 - R/igraph version: 1.3.5
 - R version: 4.2.2
 - Operating system: Manjaro Linux 22.0

R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Manjaro Linux

Matrix products: default
BLAS:   /usr/lib/libopenblasp-r0.3.21.so
LAPACK: /usr/lib/liblapack.so.3.11.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] igraph_1.3.5

loaded via a namespace (and not attached):
[1] compiler_4.2.2  magrittr_2.0.3  cli_3.5.0       rlang_1.0.6    
[5] pkgconfig_2.0.3

**Comment by ntamas** [comment]
Yes, the discrepancy is caused by the n1/n2 split, but note that we never stated that `p` is the density of the generated graph. The documentation says this:

> Real scalar, connection probability for G(n,p) graphs. Should not be given for G(n,m) graphs.
> [...]
> In G(n,p) every possible edge between top and bottom vertices is realized with probability p, independently of the rest of the edges.

Basically, each possible edge between the two groups is realized with probability `p`, but this only means that the density will be `p` for unipartite graphs. For bipartite graphs, there is no such guarantee.
