### ISSUE TITLE
Upload to CRAN

### ISSUE THREAD

**Issue by zaynabhammoud** [igraph/rigraph#641]
Hi. Could you please upload the newest version of igraph to CRAN? My package mully needed to be updated since the rgl functions were deprecated. I also use rglplot from igraph which uses rgl.texts and rgl.planes. I saw that you resolved the issue on GitHub, but this version was not uploaded yet to CRAN.

**Comment by ntamas** [comment]
There is one relatively significant change that we are making in https://github.com/igraph/rigraph/pull/633 ; @krlmlr is running reverse dependency checks and we are trying to notify downstream maintainers about any possible breakages. Once that is sorted out, I guess we can make an official CRAN release.

**Comment by krlmlr** [comment]
1.4.0 is out, 1.4.1 will follow very soon.
