### ISSUE TITLE
Compilation error [ Windows OS]

### ISSUE THREAD

**Issue by happyshows** [igraph/rigraph#65]
Hi,

I encountered the below error when trying to install the rigraph package.

foreign-graphml.c:38:29: fatal error: libxml/encoding.h: No such file or directory
compilation terminated.
make: *** [foreign-graphml.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/R/R-3.1.2/etc/i386/Makeconf" -f "C:/R/R-3.1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="igraph.dll" SHLIB_LIBADD='$(FLIBS)' ' had status 2
ERROR: compilation failed for package 'igraph'
* removing 'C:/R/Lib/igraph'
* restoring previous 'C:/R/Lib/igraph'
Error: Command failed (1)

**Comment by gaborcsardi** [comment]
You need the libxml2 library. If you don't want to do this yourself, I suggest you use win-builder.r-project.org.

**Comment by happyshows** [comment]
@gaborcsardi could you share more details on how to use win-builder.r-project.org? Looks it require the DESCRIPTION file in the zip file, however this is missing in the Dev version.

**Comment by gaborcsardi** [comment]
Download the `master` branch.

**Comment by jose2007kj** [comment]
please help me to install on windows 8.......how i need to proceed
