### ISSUE TITLE
Investigate Windows binary build failure on R-universe?

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#658]
https://github.com/r-universe/igraph/actions/runs/4034644821/jobs/6946500880 via https://igraph.r-universe.dev/builds

**Comment by maelle** [comment]
exact line with the error https://github.com/r-universe/igraph/actions/runs/4034644821/jobs/6946500880#step:9:513

**Comment by szhorvat** [comment]
https://github.com/r-universe-org/help/issues/222

**Comment by maelle** [comment]
Thank you & sorry!

**Comment by maelle** [comment]
given the last comment https://github.com/r-universe-org/help/issues/222#issuecomment-1449864073, this issue can be closed I think?
