### ISSUE TITLE
console() does not work

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#664]
**Describe the bug**

`console()` does not work.

**To reproduce**

```
> console()
Error in igraph.pars.callbacks[[cn]](temp[[cn]]) : 
  LOGICAL() can only be applied to a 'logical', not a 'character'
```

**Version information**

 - R/igraph version: 1.3.5.9106
 - R version: 4.2.2
 - Operating system: macOS

**Comment by ntamas** [comment]
Fixed in 7aa2c123
