### ISSUE TITLE
`print.igraph` errors with very long vertex names.

### ISSUE THREAD

**Issue by ahmohamed** [igraph/rigraph#675]
**Describe the bug**
`print.igraph` errors when vertex names are very long

**To reproduce**
Reprex blow:

``` r
library(igraph)
#> 
#> Attaching package: 'igraph'
#> The following objects are masked from 'package:stats':
#> 
#>     decompose, spectrum
#> The following object is masked from 'package:base':
#> 
#>     union
g <- make_full_graph(50, directed=TRUE, loops=TRUE)
V(g)$name = paste("V", 1:vcount(g))
V(g)$name[[1]] = paste(sample(letters, 1000, TRUE), collapse = '')
g
#> IGRAPH 513007b DN-- 50 2500 -- Full graph
#> + attr: name (g/c), loops (g/l), name (v/c)
#> + edges from 513007b (vertex names):
#> Error in el[seq_len(no), , drop = FALSE]: subscript out of bounds

sessionInfo()
#> R version 4.2.2 (2022-10-31)
#> Platform: aarch64-apple-darwin20 (64-bit)
#> Running under: macOS Big Sur 11.4
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] igraph_1.4.0
#> 
#> loaded via a namespace (and not attached):
#>  [1] withr_2.5.0     digest_0.6.31   lifecycle_1.0.3 magrittr_2.0.3 
#>  [5] reprex_2.0.2    evaluate_0.19   highr_0.10      stringi_1.7.8  
#>  [9] rlang_1.0.6     cli_3.5.0       rstudioapi_0.14 fs_1.5.2       
#> [13] vctrs_0.5.1     rmarkdown_2.19  tools_4.2.2     stringr_1.5.0  
#> [17] glue_1.6.2      xfun_0.36       yaml_2.3.6      fastmap_1.1.0  
#> [21] compiler_4.2.2  pkgconfig_2.0.3 htmltools_0.5.4 knitr_1.41
```

<sup>Created on 2023-02-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I managed to trace the issue to `head_print_callback`. Precisely, this line:

https://github.com/igraph/rigraph/blob/fd4a242d163eab71052e5ddf5e482677338f37a8/R/printr.R#L124

A simple fix would be to replace it with `no <- can_max`. I'd suggest name truncation though if that can be considered. Happy to submit a PR with any of the solutions above.

**Version information**
Provided in the reprex

**Comment by ntamas** [comment]
Replacing `no <- len` with `no <- can_max` seems good to me as a quick fix; if you send a PR, we can squeeze it into the upcoming 1.4.1 release. Thanks a lot in advance!

If you don't have time to do this, let me know and I'll commit it myself, I just want to make sure that you get the credit for it in the commit log.

Truncation of vertex names seems to be a bigger task for me; if you feel up for it, we'll be happy to accept a PR, but let's do the quick fix first so we can get this done by 1.4.1.
