### ISSUE TITLE
Update cigraph module to resolve OpenBSD build failure

### ISSUE THREAD

**Issue by pschmied** [igraph/rigraph#68]
Hello,

You kindly merged a [pull request for the cigraph module](https://github.com/igraph/igraph/pull/816) that fixes builds on OpenBSD and other platforms where timeb.h has been removed. Because of my dev environment, I failed to notice / submit a request to bump the cigraph module reference in the rigraph package. I just noticed the rigraph build failure when doing a clean build from rigraph@master today.

Bumping the cigraph module reference to the head should resolve the problem. Oddly, I'm not sure how to issue a PR for a module link. I probably should figure that out...

Cheers,
Peter

**Comment by pschmied** [comment]
Oops, just realized that was on the @dev branch that this is a submodule. Build fails on @master branch on OpenBSD because of the timeb.h include still, but not sure how changes in @dev will get migrated to @master.

**Comment by gaborcsardi** [comment]
Yes, the problem is that the submodule reference was not updated in `rigraph`, I'll update it in a minute.
