### ISSUE TITLE
GHA: Install ape < 5.7 on oldrel-2 and older

### ISSUE THREAD

**Issue by krlmlr** [igraph/rigraph#681]
Our GitHub Actions fail becase ape 5.7 is using the new-style pipe `|>` without declaring the dependency.

https://github.com/igraph/rigraph/actions/runs/4220464943/jobs/7326819328#step:5:3333

@maelle: How can we teach pak to use older ape?

**Comment by maelle** [comment]
To me the simplest solution would be
- make a PR to https://github.com/emmanuelparadis/ape
- add a Remotes field pointing to our fork
- once it's merged (hopefully it would) point to ape dev version
- wait for ape CRAN release

How would that sound?

**Comment by maelle** [comment]
I now understand we also need the older ape version for older R.

- Why is igraph built on that R version by the way?
- ape before the use of the native pipe: https://github.com/emmanuelparadis/ape/blame/1b24647acecf5d775ac672f520001b0f58c60a91/R/rtt.R so we could add a Remotes field that'd point to that commit exactly. https://pak.r-lib.org/reference/pak_package_sources.html?q=remotes#the-remotes-field However should we add it conditionally based on the R version, so adding this step inside the R CMD check workflow?

**Comment by maelle** [comment]
For reference https://github.com/emmanuelparadis/ape/pull/68
