### ISSUE TITLE
Configure merge settings

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#682]
I'd suggest

- [Configuring commit merging for pull requests
](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-merging-for-pull-requests) to either the PR title or PR title with description,
- [Configuring commit squashing for pull requests](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests) to PR title.

This would make the commit log on the main branch more directly useful together with {fledge} (even more so when the PR titles use the conventional commits syntax).

cc @krlmlr

**Comment by ntamas** [comment]
I've changed this setting to the PR title -- let's try it and see whether it improves the workflow.

**Comment by maelle** [comment]
Thank you! These are two separate settings if I remember correctly.

**Comment by ntamas** [comment]
Yes, they are, I've changed both.
