### ISSUE TITLE
Installation error "unable to load shared object "

### ISSUE THREAD

**Issue by zhen-fu** [igraph/rigraph#686]
**Describe the bug**
Error: package or namespace load failed for ‘igraph’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/varidata/research/home/daisy.fu/R/x86_64-pc-linux-gnu-library/4.2/00LOCK-igraph/00new/igraph/libs/igraph.so':
  /varidata/research/home/daisy.fu/R/x86_64-pc-linux-gnu-library/4.2/00LOCK-igraph/00new/igraph/libs/igraph.so: undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE

**To reproduce**
Using R (v4.2.1) from command line, by typing install.packages("igraph")

**Version information**

 - R/igraph version: 1.4.0
 - R version: 4.2.1
 - Operating system: CentOS Linux 7

sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /varidata/research/software/BBC/R/build-4.2.1/lib64/R/lib/libRblas.so
LAPACK: /varidata/research/software/BBC/R/build-4.2.1/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.2.1

**Comment by szhorvat** [comment]
This is a known issue, see #670. The fix will be in 1.4.1, once that version is approved by CRAN.
