### ISSUE TITLE
when to completely remove the nexus functions, if ever?

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#694]
They don't work since https://github.com/igraph/rigraph/commit/86e0a58a04a4a599a90ad18194d2f11bdea6276f

@ntamas

**Comment by szhorvat** [comment]
Any reason not to remove in 1.5.0? This should just be put on a milestone.

**Comment by maelle** [comment]
soon time for spring cleaning in this hemisphere so perfect :grin: 

When I say remove, it'd really be removing them, not adding any badge etc. as they've been deprecated for a while. Does that sound good?

**Comment by ntamas** [comment]
Yes, that sounds good. It's been years since we shut down the backend server and I'm pretty sure that no one uses them because they are kinda useless now. It's okay to remove them without any badges or formal deprecation cycle.
