### ISSUE TITLE
Use {lifecycle} instead of zzz-deprecate.R

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#697]
- Keep "redirecting" calls, but with lifecycle syntax.
- Completely remove most functions?

Apart from [automorphism](https://github.com/igraph/rigraph/commit/1c8d344e264f0346c699ffa7697554df68817c24) and [page.rank.old](https://github.com/igraph/rigraph/commit/b93a8681762ecbe9f94b9b7501a551dfe5a4e13e#diff-861f2ed6503102e90f22cc3d1169a8a001ef4364e066977f3a88ef06b180ed6a) most deprecations seem to be from 2015.

**Comment by ntamas** [comment]
It seems to me that even though these functions are marked as deprecated "unofficially", they do not print any warnings to the user yet. `zzz-deprecate.R` seems to be a nice central place to add warnings to all the "old" dotted-style functions in the next version (say, igraph 1.5.0) so we can schedule their removal for igraph 1.6.0 or 2.0.0, whichever comes first.
