### ISSUE TITLE
modularity() crashes if 0 present

### ISSUE THREAD

**Issue by ronammar** [igraph/rigraph#70]
g <- graph(c(1,2, 1,3, 2,3, 3,7, 4,5, 4,6, 4,10, 5,6, 5,10, 6,10, 7,8, 7,9, 8,9, 8,10),
      directed=FALSE)
    communities <- c(1,1,1, 2,2,2, 3,3,3, 2)
    modularity(g, communities)  # outputs 0.497449
    
    communities <- c(0,0,0, 2,2,2, 3,3,3, 2)
    modularity(g, communities)  # crashes. Boo.

    communities <- c(1,1,1, 2,2,2, 3,3,3, 0)
    modularity(g, communities)  # crashes. Boo.

Also, R crashes without any function-specific error message. Would be nice to detect the 0's and/or output a specific error message instead of crashing.

**Comment by gaborcsardi** [comment]
Yes, it would be nice.

**Comment by gaborcsardi** [comment]
Fixed in 85e0a0328f1767528963d54864ade6dc0ea3e006.
