### ISSUE TITLE
modularity() implementation is wrong

### ISSUE THREAD

**Issue by songw01** [igraph/rigraph#71]
I just realized that "modularity()" implementation is wrong by calculating modularity from modularity matrix calculated by "mod.matrix()" function. The following is a toy example: 

####### test script
rm(list = ls())

library(igraph)

### function to calculate 
q.calculate.wrong <- function(mod.mat,membership,total.w)
{
 # mod.mat = output from mod.matrix(). implementation of Mij = Aij - kikj/2m.
 # membership = node membership vector
 # total.w = total links (or sum of edge weights)
 
 sum(sapply(split(names(membership),factor(membership)),function(i,m) sum(m[i,i],na.rm = T),m = mod.mat))/(2*total.w) 
 # this equation is wrong in two ways: 
 # - sum(m[i,i]) also sums over Mii, whose contribution should not be included in the proper definition of Q,
 # - sum(m[i,i]) is not divided by 2, whereas Mij is symmetric and sum(m[i,i]) must be divided to account for undirectedness of link. 
}

q.calculate.right <- function(mod.mat,membership,total.w)
{
 diag(mod.mat) <- 0;mod.mat <- as.matrix(mod.mat) # remove diagonal elements to avoid contribution of linking to itself in kikj term in original q
 sum(sapply(split(names(membership),factor(membership)),function(i,m) sum(m[i,i],na.rm = T)/2,m = mod.mat))/(2*total.w)
 
 ## this equation resolves all of issues above. 
}

##### undirected network example to validate toykit is working properly
x <- graph(c(1,2, 1,3, 2,3, 3,7, 4,5, 4,6, 4,10, 5,6, 5,10, 6,10, 7,8, 7,9, 8,9, 8,10),
  directed=FALSE)
  V(x)$name <- paste("v",1:vcount(x),sep = "")
membership <- c(1,1,1, 2,2,2, 3,3,3, 2);
names(membership) <- paste("v",1:vcount(x),sep = "");

mm <- mod.matrix(x,membership);rownames(mm) <- names(membership);colnames(mm) <- names(membership)
wrong.q <- q.calculate.wrong(mm,membership,ecount(x))
right.q <- q.calculate.right(mm,membership,ecount(x))
igraph.q <- modularity(x,membership)

vec <- c(wrong.q,right.q,igraph.q);names(vec) <- c("wrong.q","correct.q","igraph.q")
print(vec)

###############################################

The toy example above gives:

> print(vec)
  wrong.q correct.q  igraph.q 
0.4974490 0.3010204 0.4974490 

#################################

You can clearly see from above that output given by modularity() is wrong since its output matches modularity calculation with few misleading features. I suppose that this is a serious issue as modularity() should be one of most fundamental functions network community uses to develop their new algorithms (including myself). 

By the way, I checked "mod.matrix()" works totally fine itself. So what matters is to calculate properly normalized modularity from the matrix. 

Cheers,

**Comment by gaborcsardi** [comment]
Hi, you are doing something wrong. I don't know what, because I did not decipher your code, but something is definitely wrong. The simplest way to see the correct result is to use the matrix formulation from here: http://en.wikipedia.org/wiki/Modularity_%28networks%29#Matrix_formulation Here it is for your graph:

```r
library(igraph)
x <- graph(c(1,2, 1,3, 2,3, 3,7, 4,5, 4,6, 4,10, 5,6, 5,10, 
                     6,10, 7,8, 7,9, 8,9, 8,10), directed = FALSE)
membership <- c(1,1,1, 2,2,2, 3,3,3, 2)

S <- matrix(0, vcount(x), max(membership))
for (i in 1:vcount(x)) S[i, membership[i]] <- 1

A <- get.adjacency(x, sparse = FALSE)
B <- A - (degree(x) %*% t(degree(x))) / ecount(x) / 2

trace <- function(x) sum(diag(x))
trace(t(S) %*% B %*% S) / ecount(x) / 2
#> [1] 0.497449

> modularity(x, membership)
#> [1] 0.497449
```
