### ISSUE TITLE
why is as_phylo.igraphHRG not exported

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#713]
I'm working on an automated script for #708 and noticed this.

If the function isn't exported, the lifecycle stuff isn't so important.

**Comment by ntamas** [comment]
As far as I know this function simply adds support for igraph's `igraphHRG` objects to be used in conjunction with the `as_phylo()` generic function so you can convert them to `phylo` objects from the `ape` package. Although I'm a bit confused now because `ape` seems to use `as.phylo` and not `as_phylo`... maybe we've accidentally renamed a dotted function that we shouldn't have?

**Comment by krlmlr** [comment]
There never was an `as.phylo()` in the codebase.

We need delayed method registration to switch to `as.phylo()` because ape is only suggested, not imported.

**Comment by maelle** [comment]
But does this mean we can simply remove `asPhylo.igraphHRG()` (that was deprecated to `as_phylo.igraphHRG()` in `zzz-deprecate.R`)?

**Comment by ntamas** [comment]
Hmmm, it may mean that `as.phylo()` in igraph has fallen victim to the mass renaming of dotted methods to underscored methods in the past, and we should reverse the renaming.

**Comment by maelle** [comment]
ok, so in community.R? could that be done independently from #716? But what to do about `as_phylo.igraphHRG()` in that PR?

**Comment by krlmlr** [comment]
We should implement `as.phylo()` methods and forward our `as_phylo()` to `as.phylo()` (with a deprecation warning). I seriously doubt that anyone has implemented `as_phylo()` methods: https://github.com/search?q=org%3Acran%20as_phylo.&type=code .

**Comment by krlmlr** [comment]
For implementing an S3 method for a suggested package, drop https://github.com/r-lib/rlang/blob/main/R/standalone-s3-register.R into the package and use the functions provided there.

**Comment by krlmlr** [comment]
A separate small PR seems a good way here.
