### ISSUE TITLE
special case the lifecycle transformation of igraph.arpack.default

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#714]
since at the moment it's a list not a function

**Comment by maelle** [comment]
same for igraph.eigen.default

**Comment by maelle** [comment]
it's a bit of a challenge as if I make it a function, it's a breaking change. @krlmlr any suggestion?

**Comment by maelle** [comment]
@krlmlr any idea? I'm a bit stuck as to how to deprecate _data_.

**Comment by maelle** [comment]
I found an idea via https://stackoverflow.com/a/75192818/5489251

https://github.com/allisonhorst/palmerpenguins/pull/25

I'll draft something

**Comment by maelle** [comment]
but, actually, igraph.arpack.default isn't exported?!

**Comment by maelle** [comment]
I mean eigen_defaults isn't.

**Comment by maelle** [comment]
And since these two lists are not data, the delayedAssign idea doesn't work. :thinking:

**Comment by maelle** [comment]
maybe I'm making this more complicated than it should, although the two deprecated names were exported, they're maybe not used a lot?

**Comment by ntamas** [comment]
They are not used frequently; they represent default parameters to the underlying ARPACK eigensolver and most users won't mess around with the default settings. Nevertheless, `eigen_defaults` should be the new name that is exported and `igraph.eigen.default` is the one that should be deprecated. If `igraph.arpack.defaults` already exists as `arpack_defaults`, then the latter one should be the preferred one, similarly to `eigen_defaults`.

**Comment by krlmlr** [comment]
We can't easily make it assignable.

**Comment by krlmlr** [comment]
The tidyverse has very detailed opinions on defaults, in particular <https://design.tidyverse.org/def-user.html> (incomplete) and the sections before that.
