### ISSUE TITLE
deprecation loop

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#736]
- `graph()` is deprecated to `make_graph()`.
- `make_graph` calls `graph_from_literal()`.
- `graph_from_literal()` calls `graph_from_literal_i()` that calls `graph()`. :zany_face: 

That is a problem with the lifecycle changes in https://github.com/igraph/rigraph/pull/716

Is the best solution to remove all calls to `graph()` in the main branch, then I'll rebase my PR? 

ccc @krlmlr

**Comment by ntamas** [comment]
Yes, if `graph()` is deprecated, IMHO we should also replace all places where we use it with `make_graph()`.
