### ISSUE TITLE
R: Edge lines are waving in metafiles

### ISSUE THREAD

**Issue by ko-ichi-h** [igraph/rigraph#78]
With recent versions (0.7.1 and 0.7.0) of igraph R package, I find that edge lines are waving in saved metafiles. Please see the “before” figure of the attached image.
![igraph2](https://cloud.githubusercontent.com/assets/12220822/7836212/94f99366-04b9-11e5-89f8-aff71a2ef680.png)

It can be fixed like the “after” figure by changing the following line in the “igraph.Arrows” function.

>    if (is.logical(curved) && all(!curved)) {

I changed this line as follows to make the “after” figure.

>    if ( (is.logical(curved) && all(!curved)) || all(!curved) ) {

BTW, thank you very much for developing such a nice software!

**Comment by gaborcsardi** [comment]
Well, the real fix would be to draw straight lines instead of Bezier curves for edges with `curved=0`.
