### ISSUE TITLE
R: Custom defined function disappears

### ISSUE THREAD

**Issue by ameyahate** [igraph/rigraph#79]
I have defined a function that calculates a new centrality measure called ['Group Betweenness'](https://github.com/igraph/igraph/issues/827). I added the function to the file ```cigraph/src/centrality.h``` and declared the function in ```cigraph/include/igraph_centrality.h```.

In order to create an R interface for this function I edited the ```R/structural.properties.R``` and ```tools/stimulus/rinterface.c.in``` files.
I then built igraph and ran tests as has been suggested:
```
system("git submodule init")
system("git submodule update")
system("make")
library(devtools)
install()
build()
test()
```

I then tested the defined function ```group_betweenness()``` on an example. It works but only immediately after I have built the igraph library. As soon as I detach the igraph library and attach it again, the function disappears:
```
> group_betweenness(dfg, types=V(dfg)$types, weights=E(dfg)$weights)
0 1 2 3 4 5 
0 2 0 3 0 3 
> detach("package:igraph", unload=TRUE)
> library("igraph", lib.loc="/Library/Frameworks/R.framework/Versions/3.1/Resources/library")

Attaching package: ‘igraph’

The following objects are masked from ‘package:stats’:

    decompose, density, spectrum

The following object is masked from ‘package:base’:

    union

> group_betweenness(dfg, types=V(dfg)$types, weights=E(dfg)$weights)
Error: could not find function "group_betweenness"
```

I am not sure what the problem is. The igraph library is built in the default location: ```/Library/Frameworks/R.framework/Versions/3.1/Resources/library``` so there aren't two separate versions of the igraph library as far as I can tell. 
```
> packageVersion("igraph")
[1] ‘0.7.999’
```
I am clearly missing something simple here. Help is greatly appreciated!! Thanks.

**Comment by gaborcsardi** [comment]
You are probably loading another installation of igraph that does not have your updates.

Btw. you can't edit stuff in `cigraph`, it is a submodule, an exact copy of another git repo. You need to add your stuff to C igraph (https://github.com/igraph/igraph), and then set up your R igraph to use your C igraph.

**Comment by gaborcsardi** [comment]
I'll close this, please reopen if you have problems.
