### ISSUE TITLE
Set up a CI run with AddressSanitizer 

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#802]
There should be an AddressSanitizer-enabled CI run. This will provide some extra confidence while migrating to igraph 0.10, and it will make it much easier to debug crash bugs.

This will require building R itself with AddressSanitizer first, and caching the R installation. After this, igraph can be installed as normal, as R itself will pass the correct flags.

This is how I do this now locally: https://github.com/igraph/igraph/wiki/Using-sanitizers-to-find-bugs#rigraph

@krlmlr Can you help with this?

**Comment by krlmlr** [comment]
@Antonov548: Can you please take this on?

We can use the Docker image at https://github.com/wch/r-debug to avoid building R from scratch. We still need to install igraph dependencies in the Docker image. I propose to set up a CI/CD workflow that builds a Docker image based on `wch1/r-debug` with igraph and all dependencies installed. We would need the following things:

- [ ] A `Dockerfile` that runs `RD -q -e 'pak::pak("igraph/rigraph", dependencies = TRUE)' for all versions of `RD*` that the r-debug image provides
- [ ] CI/CD that pushes the resulting image somewhere, e.g., to a GitHub Registry or to Dockerhub
- [ ] An extension of our GitHub Actions workflow that runs on the image generated in the previous step, in a build matrix, one entry for each `RD*` version

This is a bit terse, can you work with that? Happy to clarify as needed.

**Comment by szhorvat** [comment]
Thanks @krlmlr and @Antonov548 ! This will be very useful.

**Comment by krlmlr** [comment]
For the third step, we could use a Docker action: https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action . If we do this, the first step modifies the entrypoint of the Docker image.

**Comment by krlmlr** [comment]
Everything can live in this repository.

See, e.g., https://github.com/tidyverse/tibble/tree/main/.github/workflows/check for an action that is embedded in the repo, and https://github.com/tidyverse/tibble/blob/main/.github/workflows/R-CMD-check.yaml#L72 for usage.

**Comment by krlmlr** [comment]
Done now, we'll improve as we go.
