### ISSUE TITLE
ego/neighbourhood

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#828]
Currently `neighborhood()` is deprecated in favour of `ego()`. As discussed in #827, `neighborhood()` should be un-deprecated. Both names, `ego()` and `neighborhood()`, should be equal-status non-deprecated aliases for the same function.

via https://github.com/igraph/rigraph/pull/827#issuecomment-1567332361 @szhorvat @ntamas 

Especially crucial for #716 hence my opening an issue before #827 is merged :grin:

**Comment by szhorvat** [comment]
Thanks for opening the issue. I updated the issue text a bit to show what I meant in https://github.com/igraph/rigraph/issues/801#issuecomment-1549603570
