### ISSUE TITLE
check_version() and warn_version() claim that the graph has an *older* format even when in fact it's *newer*

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#830]
`check_version()` and `warn_version()` in `versions.R` issue messages claiming that the graph format is too old whenever its format version does not match the current format version. This message is shown even if the format version is _newer_, not _older_.

This will become a problem if we bump the format version and keep the same system.

See also: https://github.com/igraph/rigraph/issues/829#issuecomment-1571586827

**Comment by ntamas** [comment]
`check_version()` does not seem to be called from anywhere so I guess we can remove that. `warn_version()` is indeed problematic.
