### ISSUE TITLE
estimate_betweenness() should be deprecated

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#844]
TODOS

- [ ] Adapt docs in igraph.
- [x] Make PRs in repos using `estimate_betweenness()` and the dotted version.
    - https://github.com/SachaEpskamp/qgraph/pull/77
    - https://github.com/thomasp85/tidygraph/pull/174
    - https://github.com/snlab-ch/migraph/pull/271
    - https://github.com/biometry/bipartite/pull/15
- [ ] Make PRs in repos using `estimate_edge_betweenness()` and the dotted version.
   - https://github.com/FMestre1/gDefrag/pull/2
   - tidygraph see above
- [ ] Make PRs in repos using `estimate_closeness()` and the dotted version.
   - migraph see above

`estimate_betweenness()` should be deprecated and should not appear in the docs. "Estimate" is a bit of a misnomer here as proper betweenness estimation takes a lot more than what this function does.  The replacement is using the `cutoff` parameter of `betweenness()`.

The same applies to `estimate_closeness()`, but that function already doesn't appear in the docs.

Do you have time for this @maelle ?

**Comment by maelle** [comment]
What about `estimate_edge_betweenness()`?

**Comment by szhorvat** [comment]
The same. All the `estimate_xyz()` functions are replaced by a new `cutoff` argument in `xyz()`. The reason is that limiting shortest paths to a cutoff distance is not nearly enough for getting a proper estimate of the result. What these functions produce is very useful, but it's not an estimate of the cutoff-less result.

I consider this very important because many people come to igraph without much experience in network analysis. They see the name "estimate" and decide to just use this function for a faster approximate calculation. That's not what they really do. Let's avoid names that create confusion.

**Comment by maelle** [comment]
Ok! We'll have to start with a simple warning though, then an error in another version of the package.

**Comment by maelle** [comment]
actually, we'll have to start with a soft deprecation because some revdeps use `estimate_betweenness()`: https://github.com/search?q=estimate_betweenness+org%3Acran&type=code

**Comment by maelle** [comment]
I'll open PRs in the corresponding repos (not the cran/ ones, which are mirrors), hopefully next week.

**Comment by maelle** [comment]
Even edge.betweenness.estimate is used in gDefrag

**Comment by maelle** [comment]
I added a TODO list in the first comment.

**Comment by maelle** [comment]
I'll resume the PR openings next week.

**Comment by maelle** [comment]
I've opened PRs in all revdeps where I could, via a GitHub search, find usage of the to-be-deprecated functions. 
#852 is ready for review.

**Comment by maelle** [comment]
All PRs in revdeps merged/integrated except https://github.com/FMestre1/gDefrag/pull/2#issuecomment-1893366387

**Comment by maelle** [comment]
even that one is merged now

**Comment by maelle** [comment]
I'll close this: since we use lifecycle for this deprecation, it'll be looked at when we increase deprecation levels anyway.
