### ISSUE TITLE
Suggest adding -lquadmath in src/Makevars.win PKG_LIBS 

### ISSUE THREAD

**Issue by LuShuYangMing** [igraph/rigraph#855]
**Describe the bug in windows 10 install**
undefined reference to 'quadmath_snprintf' 
Error in building igraph.dll

**Version information**

 - R/igraph version: .1.5.0
 - R version: 4.0.2 [microsoft R open]
 - Operating system: windows 10

**Comment by szhorvat** [comment]
This was already done in Makevars.ucrt in #778, so for consistency let's do it in Makevars.win as well.

@LuShuYangMing Note that Microsoft R Open has been unsupported for years, and its website will be shut down in less than two weeks.
