### ISSUE TITLE
Avoid etime in Fortran code

### ISSUE THREAD

**Issue by krlmlr** [igraph/rigraph#857]
From CRAN:

etime is a GNU extension, used for two purposes:

i) To find the user and system CPU times.  For their sum (which is what one usually wants) there is (from F95) a standard replacement CPU_TIME.

igraph leidenbase svd all seem to use a LAPACK-derived function SECOND which returns user CPU time.  However, current LAPACK has several versions one of which uses CPU_TIME: see INSTALL/second_INT_CPU_TIME.f

ii) to measure elapsed time.  For that there is (from F90) a standard replacement SYSTEM_CLOCK.  This is what quantreg seems to want for GTIMER, but EXTETIME seems unused.  (It is not clear to me that the timer is actually used so maybe could simply return 0.0.)

gfortran has for many years supported F95 as well as GNU extensions by default so there is no problem using F90/F95 functions.  OTOH, flang (the compiler being considered for Windows-on-ARM) does not have etime and as there are standard equivalents is unlikely ever to do so.

Please review your usage and if possible change to a standard-compliant form.

**Comment by szhorvat** [comment]
Just noting that this is not from igraph, but ARPACK. ARPACK-NG still uses ETIME.

However, at least in igraph, the SECOND function does not seem to be used at all, so it should be safe to remove entirely.

**Comment by szhorvat** [comment]
Just noting that ETIME seems to come from ARPACK, and is still used by the most recent ARPACK-NG.

**Comment by szhorvat** [comment]
These are the versions in the current LAPACK:

Using ETIME:

https://www.netlib.org/lapack/explore-html/d6/d94/second___e_x_t___e_t_i_m_e_8f_ae9f971a8b343bd2fcb85c3b16da97f10.html#ae9f971a8b343bd2fcb85c3b16da97f10

Using CPU_TIME:

https://www.netlib.org/lapack/explore-html/d8/d80/second___i_n_t___c_p_u___t_i_m_e_8f_ae9f971a8b343bd2fcb85c3b16da97f10.html#ae9f971a8b343bd2fcb85c3b16da97f10

Just returning zero all the time:

https://www.netlib.org/lapack/explore-html/d4/d99/second___n_o_n_e_8f_ae9f971a8b343bd2fcb85c3b16da97f10.html#ae9f971a8b343bd2fcb85c3b16da97f10

I'm wondering if we can just return zero as well, and whether that will influence the functionality in any way.
