### ISSUE TITLE
cannot install igraph in R

### ISSUE THREAD

**Issue by beew** [igraph/rigraph#86]
Hi, I am trying to update igraph on R and got these errors.

..-c uuid/gen_uuid.c -o uuid/gen_uuid.o
uuid/gen_uuid.c:100:5: error: conflicting types for ‘gettimeofday’
 int gettimeofday (struct timeval *tv, void *dummy)
In file included from uuid/gen_uuid.c:61:0:
/usr/include/x86_64-linux-gnu/sys/time.h:71:12: note: previous declaration of ‘gettimeofday’ was here
 extern int gettimeofday (struct timeval *__restrict __tv,
            ^
/usr/lib/R/etc/Makeconf:134: recipe for target 'uuid/gen_uuid.o' failed
make: *** [uuid/gen_uuid.o] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/usr/lib/R/library/igraph’
* restoring previous ‘/usr/lib/R/library/igraph’

The downloaded source packages are in
	‘/tmp/RtmpFDnDLe/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages(update[instlib == l, "Package"], l, contriburl = contriburl,  :
  installation of package ‘igraph’ had non-zero exit status

R 3.2.1 on Ubuntu 15.04 64 bit.
Please advise.

Thanks

**Comment by gaborcsardi** [comment]
Bug in igraph. Fixing now.

**Comment by gaborcsardi** [comment]
VErsion 1.0.1 is on CRAN now, please try it.

**Comment by beew** [comment]
It works now. Thanks for the quick response.

**Comment by ramsairaguru** [comment]
tried to install  " igraph " like this 
 install.packages("igraph", repos = "http://cran.case.edu" )

started with 
trying URL 'http://cran.case.edu/src/contrib/igraph_1.0.1.tar.gz'

but ended with this error :
make: *** [igraph.so] Error 1
ERROR: compilation failed for package ‘igraph’
* removing ‘/root/R/x86_64-redhat-linux-gnu-library/3.3/igraph’

**Comment by gaborcsardi** [comment]
@ramsairaguru This is a closed issue. Please open another one if you still have problems, and also provide a reproducible example.

**Comment by Noah89** [comment]
Dear Sir
I am trying to install igraph package on my linux but I can' and it keep giving me the following statement on terminal (bash: syntax error near unexpected token `"igraph",').
I don't know what is the problem exactly!!
Many thanks for your help.

P.S: I use the following command to install the package: install.packages("igraph")

**Comment by ChrisHIV** [comment]
@Noah89 it sounds like you are running the command `install.packages("igraph")` directly from the command line. You need to run it from inside an interactive R session, which you can start by typing `R` at the command line and hitting enter.
