### ISSUE TITLE
Consider adding git tags for old releases?

### ISSUE THREAD

**Issue by cboettig** [igraph/rigraph#87]
It would be convenient if you could add tags for releases, though hardly a real issue.   

Have to fix some issues to be compatible with 1.0 release, meanwhile it's nicer to grab the old versions on travis, e.g. I think this is 0.7.1: 07e57e0ef0250b05e14ff23c9fa2b6a0a81b2060 

(guess I could just use an `devtools::install_version()` instead, but you know, tags are nice)

**Comment by gaborcsardi** [comment]
In general I can't really fix this, sorry. Older releases of R igraph are not in the git repository in a format that can be used by `install_github`. I can tag them, but you still need to go over a custom build process, which is certainly not performed by `install_github`.

**Comment by cboettig** [comment]
Right, my bad, just realized that as well. No worries.

On Fri, Jun 26, 2015, 12:29 AM Gábor Csárdi <notifications@github.com>
wrote:

> In general I can't really fix this, sorry. Older releases of R igraph are
> not in the git repository in a format that can be used by install_github.
> I can tag them, but you still need to go over a custom build process, which
> is certainly not performed by install_github.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/igraph/rigraph/issues/87#issuecomment-115561281>.
>
-- 

http://carlboettiger.info
