### ISSUE TITLE
missing 'ape' package in plot_dendrogram function

### ISSUE THREAD

**Issue by Carol-seven** [igraph/rigraph#875]
When I use the function `plot_dendrogram`, I get the following error:
Error in loadNamespace(name) : there is no package called 'ape'.

Here is my code:
`clust_res <- igraph::fastgreedy.community(graph)`
`plot_dendrogram(clust_res, mode = "phylo")`

Previously, I was able to generate the dendrogram figure in the "phylo" style directly from igraph. However, now I need to library packgae "ape" separately.

**Comment by szhorvat** [comment]
The `ape` package must be installed (not loaded) to use `plot_dengrogram()` with `mode='phylo'`. This has always been the case, nothing has changed in this regard. Perhaps you didn't realize that you had `ape` installed last time you used this functionality?

Simply install the `ape` package and everything should work.

If you believe that something broke in recent igraph versions, please show a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates it.
