### ISSUE TITLE
sample_degseq() method parameter values should be renamed to match C core

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#876]
The allowed value for `sample_degseq`'s `method` parameter should be renamed to match the 0.10 C core. Old names can be kept for compatibility. The renaming can be done now, even before the 0.10 upgrade.

See the C docs:

https://igraph.org/c/html/latest/igraph-Generators.html#igraph_degree_sequence_game

The R docs should be updated. Feel free to copy and paste from the C docs.

Renaming should be done like so:

 - `simple` -> `configuration`
 - `simple.no.multiple` -> `fast.heur.simple`
 - `simple.no.multiple.uniform` -> `configuration.simple`
 - `vl` does not need renaming
 - when upgrading to 0.10, there will be a new method called `edge.switching.simple`.

The new names are rationalized. When they contain the word "simple", it means that they produce simple graphs (not multigraphs).

If someone will do the renaming, and deprecates the old names, I can do the doc update.

**Comment by szhorvat** [comment]
@krlmlr This would be very good to fix before a 2.0.

**Comment by krlmlr** [comment]
It's used by seven packages: https://github.com/search?q=org%3Acran%20sample_degseq&type=code .

More than zero, but also more like a "nice to have" in my book.

**Comment by szhorvat** [comment]
These names are quite misleading and have been changed a long time ago in other interfaces. I plan to reuse names like "simple" in the C core in the near future. The sooner this is fixed the better.

**Comment by krlmlr** [comment]
I don't disagree, it's just not necessary for 2.0.0. We can rename parameters without breaking other packages.

**Comment by szhorvat** [comment]
I'd like to ask to give this some priority, and to expose `edge.switching.simple` soon.
