### ISSUE TITLE
`cluster_leading_eigen()` no longer converges

### ISSUE THREAD

**Issue by krlmlr** [igraph/rigraph#879]
**Describe the bug**

`cluster_leading_eigen()` no longer converges in #840.

**To reproduce**

``` r
options(conflicts.policy = list(warn = FALSE))
library(igraph)

set.seed(20230808)
for (i in 1:100) {
  print(i)
  g <- sample_gnm(20, sample(5:40, 1))
  lec1 <- cluster_leading_eigen(g)
  lec2 <- cluster_leading_eigen(g)
  stopifnot(identical(
    as.vector(membership(lec1)),
    as.vector(membership(lec2))
  ))
}
#> [1] 1
#> [1] 2
#> [1] 3
#> [1] 4
#> [1] 5
#> [1] 6
#> [1] 7
#> [1] 8
#> Error in cluster_leading_eigen(g): At src/community/leading_eigenvector.c:564 : ARPACK did not converge, No eigenvalues to sufficient accuracy
```

<sup>Created on 2023-08-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>## CRAN

## CRAN

``` r
options(conflicts.policy = list(warn = FALSE))
.libPaths(c("cran", .libPaths()))
library(igraph)

set.seed(20230808)
for (i in 1:100) {
  # print(i)
  g <- sample_gnm(20, sample(5:40, 1))
  lec1 <- cluster_leading_eigen(g)
  lec2 <- cluster_leading_eigen(g)
  stopifnot(identical(
    as.vector(membership(lec1)),
    as.vector(membership(lec2))
  ))
}
```

<sup>Created on 2023-08-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by szhorvat** [comment]
I'll look into this, but I expect that there will always be cases where ARPACK doesn't converge and there's not much we can do about it.

See:

 - https://github.com/igraph/igraph/issues/1990
 - https://github.com/igraph/igraph/issues/1641
 - https://github.com/igraph/igraph/issues/551

ARPACK-NG generally does better than the vendored ARPACK version, but it's still not perfect. Also, in ARPACK-NG 3.9.0, there's the bug that's been an issue for igraph for a while. Upgrading R/igraph's ARPACK to ARPACK-NG 3.8 would improve the situation somewhat.

**Comment by szhorvat** [comment]
@krlmlr Can you help by exporting the offending graph to GML and attaching it?

**Comment by szhorvat** [comment]
Removing from the blocker list for 2.0 (`upgrade`) since this is not a regression and improvement may be difficult (or impossible). Re-add if you disagree.

**Comment by krlmlr** [comment]
Seems to be an ARPACK issue, and not really a regression, closing for now.
