### ISSUE TITLE
cluster_leiden() implicit seed dependancy

### ISSUE THREAD

**Issue by TimBMK** [igraph/rigraph#885]
The cluster_leiden() function can be heavily reliant on a random seed. If no seed is given, results can vary significantly between runs of the algorithm - not only in terms of community names, but especially in community sizes. This issue seemingly becomes more pronounced for larger and more complex networks.

As this dependancy is not made explicit in the documentation, it can be confusing to the user and make later reproduction of results impossible. Setting a random seed manually solves the issue. However, I believe that, in order to avoid confusion and heartache about non-reproducible results, an explicit "seed" option in the function and adjusted documentation would be very helpful.

To reproduce the issue:

```{R}
library(igraph)
library(tidyverse)

graph <- sample_forestfire(3000, 0.3, directed = F)

graph %>% 
    cluster_leiden(objective_function = "CPM", resolution_parameter = 0.2) %>% 
    membership() %>% as_tibble() %>% 
    summarise(size = n(), .by = x) %>% 
    arrange(desc(size))

graph %>% 
    cluster_leiden(objective_function = "CPM", resolution_parameter = 0.2) %>% 
    membership() %>% as_tibble() %>% 
    summarise(size = n(), .by = x) %>% 
    arrange(desc(size))
```
Note how the results vary between runs of the leiden algorithm. Additional runs make the effect more pronounced.

If we set a seed, the results become reproducible: 

```{R}
set.seed(20230817)
graph %>% 
    cluster_leiden(objective_function = "CPM", resolution_parameter = 0.2) %>% 
    membership() %>% as_tibble() %>% 
    summarise(size = n(), .by = x) %>% 
    arrange(desc(size))

set.seed(20230817)
graph %>% 
    cluster_leiden(objective_function = "CPM", resolution_parameter = 0.2) %>% 
    membership() %>% as_tibble() %>% 
    summarise(size = n(), .by = x) %>% 
    arrange(desc(size))
```

**Version information**

 - R/igraph version: 1.5.0
 - R version: 4.3.1
 - Operating system: Windows 10 x64 (build 19045)

**sessionInfo()**
```
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8    LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.utf8    

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] lubridate_1.9.2 forcats_1.0.0   stringr_1.5.0   dplyr_1.1.2     purrr_1.0.1     readr_2.1.4     tidyr_1.3.0     tibble_3.2.1   
 [9] ggplot2_3.4.2   tidyverse_2.0.0 igraph_1.5.0   

loaded via a namespace (and not attached):
 [1] vctrs_0.6.3      cli_3.6.1        rlang_1.1.1      stringi_1.7.12   generics_0.1.3   glue_1.6.2       colorspace_2.1-0 hms_1.1.3       
 [9] scales_1.2.1     fansi_1.0.4      grid_4.3.1       munsell_0.5.0    tzdb_0.4.0       lifecycle_1.0.3  compiler_4.3.1   timechange_0.2.0
[17] pkgconfig_2.0.3  rstudioapi_0.14  R6_2.5.1         tidyselect_1.2.0 utf8_1.2.3       pillar_1.9.0     magrittr_2.0.3   tools_4.3.1     
[25] withr_2.5.0      gtable_0.3.3  
```

**Comment by szhorvat** [comment]
> As this dependancy is not made explicit in the documentation, it can be confusing to the user and make later reproduction of results impossible. Setting a random seed manually solves the issue.

Be careful here. "Reproducibility" in this dogmatic sense is not useful, but dangerous.

Many of the heuristic community detection methods are stochastic in nature, which is a great benefit, as it allows you do check if your results are sane. If multiple runs of the algorithm do indeed give significantly different results, then can we say that there is a community structure in the network? _No, we cannot._

> This issue seemingly becomes more pronounced for larger and more complex networks.

This is not true. If you observe this, then your networks likely do not possess much of a community structure.

----

Unfortunately, there is a tremendous amount of misuse of community detection by empirical researchers, especially in biology. People obtain a single clustering with a single random seed, and go with that, then call it "reproducible" as the seed was fixed. Do not fall in this trap, this is _not_ a reproducible result!  First you need to check that the result is valid, for example:

 - Do you get similar clusters _regardless_ of the seed? If not, we have no basis to claim a community structure.
 - Does the value of the objective function drop in a statistically significant way if you randomize the network? (You can randomize based on the same null model as the objective function was based on, e.g. keeping degrees with modularity or full rewiring with CPM.) If it does not, then we have no basis to claim a community structure.

The result should only be considered reproducible, if it can be reproduced without reliance on very specific settings such as a particular seed.

I recommend you read this: https://arxiv.org/abs/1608.00163

----

Thus a seed parameter will not be added, as it is not necessary. It would only reinforce flawed usage patterns that typically lead to dubious results.

**Comment by TimBMK** [comment]
Thank you for the clarification. And I agree, having vastly different results in repeated runs points to problems in the network structure or problematic assumptions about the algorithm. However, I do not think that making the function results non-reproducible by default will solve any of these issues. For example, multiple runs will almost always yield slightly different results, even when the general community structure is stable. The fluctuating numerical labels assigned to the communities can be problematic when different researchers intend to hand-label the communities independently. Also, the differences in group sizes can be confusing to users. And this is the case even in the reprex above which utilizes an algorithm for network generation _specifically intended to produce community structures_. At the very least, a clear pointer to the non-deterministic nature of the algorithm or a clearer distinction between stochastic and non-stochastic community detection algorithms in the documentation would be helpful. I believe that arguing that "users should know better", rather than pointing them at potential flaws in their assumptions about the tools they are using, will lead to even more dubious results.

**Comment by TimBMK** [comment]
Yes, and again, thank you for taking the time to explain the reasoning behind your design decisions. I 100% agree with you that a) multiple runs should be done to assure stability of the results, and b) that in order to publish results that utilize a certain algorithm, the author should familiarize themselves with the algorithm and its limitations. My point was less concerning the reproducability of scientific results, but more the reliability of the tool to produce identical results on multiple runs if needed. This concerns the reproduction of results _already checked for reliability_ in order to reliably hand-label communities, reproduce results for peer-review, etc. My suggestion was to make the reliance on a random seed more explicit, and potentially offer a shortcut for a number of niche-cases where the exact reproduction of results is desired. However, I can understand your concern in terms of making the algorithm appear deterministic and, in doing so, deepening misconceptions of its nature. Thank you for taking the time for this discussion and the clarifications!
