### ISSUE TITLE
dendPlot not grouping nodes properly

### ISSUE THREAD

**Issue by pehenne12** [igraph/rigraph#891]
**Describe bug**
when running a dendogram, certain sub-sets of the data produce  graphs in which nodes are shaded by cluster but are scattered amongst each other rather than organized by cluster. I had posted about this on Stackoverlow and was told it's a bug-https://stackoverflow.com/questions/76226275/igraph-dendogram-not-arranging-vertices-by-cluster?noredirect=1#comment134436976_76226275

**To reproduce**
I can't provide the data, but here is the code:

sc <- fastgreedy.community(s3)
V(s3)$community <- membership(sc)
s_sub1 <- delete_vertices(s3, V(s3)[community != 1])
Mus_sub1s <- V(s_sub1)$majislam
sc1 <- leading.eigenvector.community(s_sub1)
plot(s_sub1, mark.groups = communities(sc1), layout = layout_with_lgl, vertex.color = Mus_sub1s, vertex.size=10, edge.arrow.size=3, edge.curved=1)
title("Remaining countries: all Muslim countries together")
dendPlot(sc1, mode = "phylo")

**Version information**
igraph 1.5.1
R 4.3.1

<html>
<body>

R version 4.3.1 (2023-06-16 ucrt) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 11 x64 (build 22621)  Matrix products: default   locale: [1] LC_COLLATE=English_United States.utf8  [2] LC_CTYPE=English_United States.utf8    [3] LC_MONETARY=English_United States.utf8 [4] LC_NUMERIC=C                           [5] LC_TIME=English_United States.utf8      time zone: America/New_York tzcode source: internal  attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   [7] base       other attached packages: [1] ape_5.7-1         estimatr_1.0.0    countrycode_1.5.0 [4] igraph_1.5.1      dplyr_1.1.2        loaded via a namespace (and not attached):  [1] digest_0.6.33    Formula_1.2-5    utf8_1.2.3       R6_2.5.1          [5] tidyselect_1.2.0 lattice_0.21-8   magrittr_2.0.3   glue_1.6.2        [9] tibble_3.2.1     parallel_4.3.1   pkgconfig_2.0.3  generics_0.1.3   [13] lifecycle_1.0.3  cli_3.6.1        fansi_1.0.4      grid_4.3.1       [17] vctrs_0.6.3      withr_2.5.0      compiler_4.3.1   tools_4.3.1      [21] nlme_3.1-162     pillar_1.9.0     Rcpp_1.0.11      rlang_1.1.1
--
 
> | >
>

</body>
</html>

**Comment by szhorvat** [comment]
In the comment I also said that a bug report was already written up ;-) #797. We will handle it once we get the time.
