### ISSUE TITLE
Could the functions eccentricity() and radius() be implemented for weighted graphs?

### ISSUE THREAD

**Issue by jskvor** [igraph/rigraph#893]
Could the functions `eccentricity()` and `radius()` be updated to support weighted graphs, similar to how `distances()` and `diameter()` do when passed the weights argument?

I know I can calculate eccentricity and radius for a weighted graph like this:
```{r}
g <- sample_pa(1000, directed = FALSE)
E(g)$weight <- runif(ecount(g))
my_eccentricity <- apply(distances(g), 1, max)
my_radius <- min(my_eccentricity)
```
However, for consistency and usability, I think it would be better if `eccentricity()` and `radius()` accepted a `weights` argument like `distances()` and `diameter()`.

**Comment by szhorvat** [comment]
Note: The relevant C functions are `igraph_eccentricity_dijkstra()` and `igraph_radius_dijkstra()`.  It makes sense to expose the closely related `igraph_graph_center()` and `igraph_graph_center_dijkstra()` as well. Some of these were added only in the recently released 0.10.7.
