### ISSUE TITLE
Add `max_ivs()` alias for `maximal_ivs()`, for consistency

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#899]
There is an inconsistency between the names `max_cliques()` and `maximal_ivs()`.  I propose adding an alias `max_ivs()` for `maximal_ivs()`. Could you do this @maelle ? _Eventually_ we can remove`maximal_ivs()`.

As a naming policy that aligns most closely with what we already have, I suggest using `max` for _maximal_ and `largest` for _maximum_.  We mostly follow this already, except for `min_separators()` and `min_st_separators()`, but those concepts are a bit tricky and this is not the right place to discuss them. Agree with this policy @krlmlr and @ntamas ?

**Comment by maelle** [comment]
Let's tackle this after #894

**Comment by maelle** [comment]
@szhorvat @ntamas @krlmlr could you please indicate which function names need to be changed (with proper deprecation) by editing the tables below

``` r
exports <- getNamespaceExports("igraph")

min <- exports[startsWith(exports, "min")]
min <- stringr::str_subset(min, "\\.", negate = TRUE)
min_df <- tibble::tibble(
  current_name = min,
  new_name = ""
)
knitr::kable(min_df)
```

| current_name      | new_name |
|:------------------|:---------|
| min_separators    |          |
| min_cut           |          |
| min_st_separators |          |

``` r

max <- exports[startsWith(exports, "max")]
max <- stringr::str_subset(max, "\\.", negate = TRUE)
max_df <- tibble::tibble(
  current_name = max,
  new_name = ""
)
knitr::kable(max_df)
```

| current_name        | new_name |
|:--------------------|:---------|
| max_cliques         |          |
| maximal_ivs         |          |
| maxcohesion         |          |
| max_cohesion        |          |
| max_flow            |          |
| max_cardinality     |          |
| max_bipartite_match |          |

<sup>Created on 2023-11-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by maelle** [comment]
Last, but not least, if this max/largest convention is adopted, where will it be documented? Is there a document with naming conventions for all igraph projects?

**Comment by szhorvat** [comment]
I think this is the last one I need to answer today. I'll do this one later. If there are any other questions I missed, please ping me again @maelle.

**Comment by maelle** [comment]
Thanks! I'll work a bit more on igraph but after that further work will probably happen next week. Thanks for your help and patience.

**Comment by maelle** [comment]
(fat fingers, sorry)

**Comment by maelle** [comment]
Related: #801

**Comment by szhorvat** [comment]
Done with the table.

**Comment by maelle** [comment]
maxcohesion will be deprecated by #716
