### ISSUE TITLE
"incidence matrix" naming should be changed to "biadjacency matrix"

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#900]
Mirroring https://github.com/igraph/igraph/issues/2326, any function names referring to an "incidence matrix" should be changed to say "biadjacency matrix".

This affects at least `as_incidence_matrix()` and `graph_from_incidence_matrix()`.

In the future, the name "incidence" matrix will be used for edge-vertex incidence matrices.

@krlmlr @maelle Up to you when you start adding aliases in preparation for a future deprecation (and eventual repurposing) of the "incidence" names.

**Comment by szhorvat** [comment]
Thanks so much for all the help so far @maelle ! If there's any issue when you pinged me but I failed to respond, please ping again. I think I looked at everything now.

**Comment by maelle** [comment]
``` r
exports <- getNamespaceExports("igraph")
grep("incidence_matrix", exports, value = TRUE)
#> [1] "from_incidence_matrix"       "as_incidence_matrix"        
#> [3] "graph_from_incidence_matrix"
```

<sup>Created on 2023-11-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by szhorvat** [comment]
Yes, all three.
