### ISSUE TITLE
Conflict with `stats`

### ISSUE THREAD

**Issue by riccardocadei** [igraph/rigraph#902]
I am developing an R package relying both on `igraph` 1.5.1 and `stats` 4.2.1. 
I am currently getting this warning because the functions `decompose` and `spectrum` are defined in both packages.

```
Warning messages:
1: replacing previous import ‘igraph::decompose’ by ‘stats::decompose’ when loading ‘NetworkCausalTree’ 
2: replacing previous import ‘igraph::spectrum’ by ‘stats::spectrum’ when loading ‘NetworkCausalTree’ 
```

Are you aware of this conflict? Should we ignore it?

Thank you in advance for your support,
Riccardo

**Comment by ntamas** [comment]
Yes, as far as I know this is a long-standing name conflict between the two packages, but neither of the two packages can do anything about it without breaking backward compatibility. I think it is safe to ignore it.

**Comment by riccardocadei** [comment]
Thank you for the prompt answer.
