### ISSUE TITLE
`identical` graph objects?

### ISSUE THREAD

**Issue by mbojan** [igraph/rigraph#91]
I used to use `identical` on igraph objects to check if they are exactly the same. The new graph representation (in igraph 1.0-1), when I look using `utils:::str.default`, looks like a list with 10 components and some hashcodes inside. These hashcodes are different for two graphs that should be identical. All this leads to things like:

```{r}
g <- graph(c(1,2, 2,3))
h <- graph(c(1,2, 2,3))
identical(g, h)
# [1] FALSE
```

Is this desired?

How to test if two igraph objects are identical?

**Comment by gaborcsardi** [comment]
It is not a hashcode, but a generated ID, so it makes sense that they are not identical. To compare them use the `identical_graphs`:

```r
g <- graph(c(1,2, 2,3))
h <- graph(c(1,2, 2,3))
identical_graphs(g, h)
#> [1] TRUE
```

**Comment by mbojan** [comment]
Thanks!
