### ISSUE TITLE
`make docs` fails

### ISSUE THREAD

**Issue by szhorvat** [igraph/rigraph#913]
**Describe the bug**

`make docs` fails

**To reproduce**

 - Clone the repo
 - `make`
 - `make docs`

```
$ make docs
tools/builddocs.sh
ℹ Updating igraph documentation
ℹ Loading igraph
Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE) : 
  must specify DLL via a “DLLInfo” object. See getLoadedDLLs()
Calls: <Anonymous> ... assignNativeRoutines -> getDLLRegisteredRoutines.DLLInfo
Execution halted
```

**Version information**

Current `main`

R 4.3.1 on macOS 13.6 arm64

**Comment by krlmlr** [comment]
We now just use `devtools::document()` .

**Comment by krlmlr** [comment]
Do we want `make docs` to work? Where is it referenced?

**Comment by szhorvat** [comment]
Well, it should either be fixed or removed. It'd be good to write up how to do these things in the wiki.

**Comment by krlmlr** [comment]
Now in #1261.
