### ISSUE TITLE
Return value of topo_sort() is not a numeric vector (in versions 1.0.x)

### ISSUE THREAD

**Issue by danielturek** [igraph/rigraph#92]
The `topo_sort()` function no longer returns a numeric vector, as it used to (version 0.7.1), and as the documentation states:

Value: A numeric vector containing vertex ids in topologically sorted order.

I found that re-casting the return value of `topo_sort()` using `as.numeric()` produces a numeric vector identical to previous versions.

Here's a simple reproducible example:

library(igraph)
graph <- graph.empty()
graph <- add.vertices(graph, 2, name = c('a', 'b'))
graph <- add.edges(graph, c(1, 2))
toposortReturn <- topological.sort(graph, mode = 'out')
print(toposortReturn)
'## + 2/2 vertices, named:
'## [1] a b
class(toposortReturn)
'## [1] "igraph.vs"

**Comment by gaborcsardi** [comment]
Thanks, I'll document it that it returns an S3 object. Actually the object is exactly the same as before, apart the S3 class, so it works in most cases, but unfortunately it breaks sometimes.

**Comment by danielturek** [comment]
Makes sense.  Thanks!
