### ISSUE TITLE
Error in xspline when plotting network communities

### ISSUE THREAD

**Issue by szymanskiburgos** [igraph/rigraph#937]
I am trying to conduct network analysis on a complex multi-scale network for IR research using the igraph package. I am using a disparity filter from the package "Backbone" to plot only the statistically significant 'backbone' of the network for a given level of alpha.

```
network <- graph_from_data_frame(d=edges, vertices=nodes, directed=T) 
network<-disparity(network, alpha = 0.05, narrative = TRUE)
deg <- igraph::degree(network, v=V(network), mode='total', loops=F, normalized = F) 
out_deg <- igraph::degree(network, v=V(network), mode='out', loops=F, normalized = F)
V(network)$degree<-deg
V(network)$outdegree<-out_deg
 ```

I am able to plot the backbone of the network itself without any problems. Vertex size and label size are based on the out-degree of the nodes while the edges are based on the network weights.

``` 
plot(network, edge.color = 'black', vertex.label.pos = '3',
     vertex.label.cex=sqrt(deg/150) * 0.5,
     vertex.label.dist=0, vertex.label.degree=0 ,
     vertex.color=region_color,
     vertex.size= log(out_deg), 
     edge.width=sqrt(E(network)$weight)/100,
     edge.arrow.size=sqrt(E(network)$weight)/100,
     mode = "fruchtermanreingold")
```

Then I perform community detection on the network backbone using the cluster_infomap algorithm. When I try to plot the network again with the community membership overlay I receive an error when running the plot function. This error says "Error in xspline(cl$rescoords, shape = shape, open = FALSE, col = col,  : 
  There must be at least three control points"

The code below that throws the error

```
ci <-cluster_infomap(network, 
                     e.weights = E(network)$weight,
                     nb.trial=50)
plot(ci, network, edge.color = 'black', vertex.label.pos = '3',
     vertex.label.cex=sqrt(deg/150) * 0.5,
     vertex.label.dist=0, vertex.label.degree=0 ,
     vertex.color=region_color,
     vertex.size= log(out_deg),
     edge.width=sqrt(E(network)$weight)/100,
     edge.arrow.size=sqrt(E(network)$weight)/100,
     mode = "fruchtermanreingold")
```

This error is difficult to identify the cause for through either the R traceback or through google searches as I could not find any instance of the error coming up for others when plotting networks. I do not understand why plotting the network without the community membership works fine, but throws an error here. For what it's worth, what comes up in the plot after the error are the community 'contours' but without the nodes and edges of the network. 

[![enter image description here][1]][1]

I can only assume there is an issue in the data structure of the 'ci' object but I am not sure. Any help in this regard is appreciated.

Please see here for a minimally, reproducible example with code and data: https://drive.google.com/drive/folders/1HoMZ2kcg08RW-HqJA18aVrHYc3faq0Qs?usp=sharing

  [1]: https://i.stack.imgur.com/2kcaf.png

**Comment by szhorvat** [comment]
Thanks for posting the issue. Let's link back to where it came from: https://stackoverflow.com/q/77390629/695132

It may take a while until someone gets the time to debug this. Until then, can you help us and make the example actually minimal? Are all 16 packages really needed? Is all the code really needed? Is the entire datafile really needed? Can you produce a _short_ example with one input graph, one community detection line, and one plotting line with minimal parameters that still shows the issue?

**Comment by szymanskiburgos** [comment]
> Thanks for posting the issue. Let's link back to where it came from: https://stackoverflow.com/q/77390629/695132
> 
> It may take a while until someone gets the time to debug this. Until then, can you help us and make the example actually minimal? Are all 16 packages really needed? Is all the code really needed? Is the entire datafile really needed? Can you produce a _short_ example with one input graph, one community detection line, and one plotting line with minimal parameters that still shows the issue?
> 
> Please follow the instructions at https://stackoverflow.com/help/minimal-reproducible-example

Thanks, I have re-uploaded the files through the link with more minimal examples.

By eliminating plot parameters I discovered that the parameter causing the error is "vertex.size= log(out_deg)." Taking the log of out_degree or degree (total) prevents the community detection plot to crash but does not cause the plot without the community overlay to crash. 

I am interested if there is any way I can use the degree to size nodes for the community overlay plot in a way that is visually appropriate.
