### ISSUE TITLE
igraph::membership documentation has repeated block in "See Also" 

### ISSUE THREAD

**Issue by suthers** [igraph/rigraph#939]
library(igraph)
?membership
scroll down ... and this is what you get 

> **See Also**
> See plot_dendrogram() for plotting community structure dendrograms.
> 
> See compare() for comparing two community structures on the same graph.
> 
> The different methods for finding communities, they all return a communities object: cluster_edge_betweenness(), cluster_fast_greedy(), cluster_label_prop(), cluster_leading_eigen(), cluster_louvain(), cluster_leiden(), cluster_optimal(), cluster_spinglass(), cluster_walktrap().
> 
> Community detection as_membership(), cluster_edge_betweenness(), cluster_fast_greedy(), cluster_fluid_communities(), cluster_infomap(), cluster_label_prop(), cluster_leading_eigen(), cluster_leiden(), cluster_louvain(), cluster_optimal(), cluster_spinglass(), cluster_walktrap(), compare(), groups(), make_clusters(), modularity.igraph(), plot_dendrogram(), split_join_distance()
> 
> Community detection as_membership(), cluster_edge_betweenness(), cluster_fast_greedy(), cluster_fluid_communities(), cluster_infomap(), cluster_label_prop(), cluster_leading_eigen(), cluster_leiden(), cluster_louvain(), cluster_optimal(), cluster_spinglass(), cluster_walktrap(), compare(), groups(), make_clusters(), modularity.igraph(), plot_dendrogram(), split_join_distance()
> 
> Community detection as_membership(), cluster_edge_betweenness(), cluster_fast_greedy(), cluster_fluid_communities(), cluster_infomap(), cluster_label_prop(), cluster_leading_eigen(), cluster_leiden(), cluster_louvain(), cluster_optimal(), cluster_spinglass(), cluster_walktrap(), compare(), groups(), make_clusters(), modularity.igraph(), plot_dendrogram(), split_join_distance()
> 
> Community detection as_membership(), cluster_edge_betweenness(), cluster_fast_greedy(), cluster_fluid_communities(), cluster_infomap(), cluster_label_prop(), cluster_leading_eigen(), cluster_leiden(), cluster_louvain(), cluster_optimal(), cluster_spinglass(), cluster_walktrap(), compare(), groups(), make_clusters(), modularity.igraph(), plot_dendrogram(), split_join_distance()
> 
> Community detection as_membership(), cluster_edge_betweenness(), cluster_fast_greedy(), cluster_fluid_communities(), cluster_infomap(), cluster_label_prop(), cluster_leading_eigen(), cluster_leiden(), cluster_louvain(), cluster_optimal(), cluster_spinglass(), cluster_walktrap(), compare(), groups(), make_clusters(), modularity.igraph(), plot_dendrogram(), split_join_distance()
> 
> Community detection as_membership(), cluster_edge_betweenness(), cluster_fast_greedy(), cluster_fluid_communities(), cluster_infomap(), cluster_label_prop(), cluster_leading_eigen(), cluster_leiden(), cluster_louvain(), cluster_optimal(), cluster_spinglass(), cluster_walktrap(), compare(), groups(), make_clusters(), modularity.igraph(), plot_dendrogram(), split_join_distance()

.... etc (it repeats)

**Comment by suthers** [comment]
Also it repeats once in modularity.igraph. And cluster_leiden has two different versions of this list (below). Might want to check all CD related documentation. -- Dan 

> Other community detection algorithms: cluster_walktrap(), cluster_spinglass(), cluster_leading_eigen(), cluster_edge_betweenness(), cluster_fast_greedy(), cluster_label_prop() cluster_louvain() cluster_fluid_communities() cluster_infomap() cluster_optimal() cluster_walktrap()
> 
> Community detection as_membership(), cluster_edge_betweenness(), cluster_fast_greedy(), cluster_fluid_communities(), cluster_infomap(), cluster_label_prop(), cluster_leading_eigen(), cluster_louvain(), cluster_optimal(), cluster_spinglass(), cluster_walktrap(), compare(), groups(), make_clusters(), membership(), modularity.igraph(), plot_dendrogram(), split_join_distance()

**Comment by maelle** [comment]
I'll have a look later this week or next week, sorry for the delay! Thanks for catching this!

**Comment by maelle** [comment]
I'll remove the duplicate `@family` tags. https://github.com/r-lib/roxygen2/issues/1530
