### ISSUE TITLE
Report about layouts

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/rigraph#94]
- overlapping edges and nodes
- how close nodes and edges are, nodes to other nodes
- number of edge crossings where they are

Output: R object with summary statistics

**Comment by gaborcsardi** [comment]
Voica:
> I took a glance on github and I would like to give a try on solving
the problem with distances between nodes. There is any global layout
function, which should I watch, on which this distances are computed?

It is not so simple. Layout just creates a two-column matrix, does not know the labels, or even how vertices will look. It is probably enough for edge crossings, but nothing else, so it is not worth going that way.

What I would do is adding some options to the actual `plot.igraph` function, to record (or just return) information about the graph and the plot. This is hard to do properly, of course, but you can give it a try if you want.

Please make sure that you read the contribution guide.

**Comment by voica** [comment]
But what kind of information? For example initially I thought to determine only if the traces of the shapes (vertices or edges) intersect, but after that I found that the intersection points or the shapes relative position would be also useful.

So, there is no function to take the trace of a vortex at whole?

**Comment by gaborcsardi** [comment]
Sizes and shapes of vertices are not in the layout. The layout is just a matrix is 0 dimensional dots. vortex == vertex I assume. What do you mean by trace?

**Comment by ntamas** [comment]
Not planned in the near future. We can reconsider if there is significant demand for this.
