### ISSUE TITLE
create_lcp() an unexpected igraph error

### ISSUE THREAD

**Issue by mthompsonecologic** [igraph/rigraph#941]
**Describe the bug**

Running create_lcp() in loop or lapply on two class SpatialPoints works for some points but not all.

**To reproduce**
```
> o1
class       : SpatialPoints 
features    : 1 
extent      : 627821.3, 627821.3, 6087539, 6087539  (xmin, xmax, ymin, ymax)
crs         : +proj=utm +zone=10 +datum=WGS84 +units=m +no_defs

> d1
class       : SpatialPoints 
features    : 1 
extent      : 627401.9, 627401.9, 6086865, 6086865  (xmin, xmax, ymin, ymax)
crs         : +proj=utm +zone=10 +datum=WGS84 +units=m +no_defs

AtoB_TRWI[i] <- create_lcp(cost_surface=DEM_DEM_TR_gctr,
                                 origin=d1,
                                 destination=o1)
```
Result:

> Error in add_edges(res, edges = t(as.matrix(el[, 1:2])), attr = weight) : 
>   At core/core/vector.pmt:1030 : Assertion failed: v->stor_begin != NULL. This is an unexpected igraph error; please report this as a bug, along with the steps to reproduce it.

**Version information**

 - R/igraph version: ...Package igraph version 1.4.1
 - R version: ...4.2.3
 - Operating system: ...Windows 10

```
> sessionInfo()
R version 4.2.3 (2023-03-15 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)
```

**Comment by szhorvat** [comment]
Can you give complete steps to reproduce the issue? Please follow the instructions here: https://stackoverflow.com/help/minimal-reproducible-example Make sure you use the latest version of igraph, not the outdated version 1.4.1.

**Comment by szhorvat** [comment]
Closing for lack of feedback. It's a pity to leave this unfixed, but there is simply not nearly enough information in this report to go on.
