### ISSUE TITLE
Get the name of the vertex in the igraph::transitivity(graph, type = "local") function in R

### ISSUE THREAD

**Issue by silasalvescosta** [igraph/rigraph#943]
When I use the degree(graph) function from the igraph package in R, the output comes up with the name of the vertex and its respective value, however, when I run the transitivity(graph, type = "local") function from the same package, the output is a list without names, I can't tell which node each value corresponds to.

I suggest that the output of the transitivity(graph, type = "local") function to be accompanied by the name of the vertices.

**Comment by szhorvat** [comment]
Here's a demo to make it clear what this is about:


```
> g <- make_graph(~ a-b-c-a-d)
> transitivity(g,'local')
[1] 0.3333333 1.0000000 1.0000000       NaN
> degree(g)
a b c d 
3 2 2 1 
> betweenness(g)
a b c d 
2 0 0 0 
> hub_score(g)
$vector
        a         b         c         d 
1.0000000 0.8546377 0.8546377 0.4608111 
```

Normally, the result vector should include names.

Is this something to fix for 1.6.0 @krlmlr ? (I.e., is it considered breaking?)
