### ISSUE TITLE
how to remove the label of the node?

### ISSUE THREAD

**Issue by liamxg** [igraph/rigraph#947]
<img width="998" alt="image" src="https://github.com/igraph/rigraph/assets/46078579/1a7996de-b683-4517-ad73-22b95b29c68b">

**Comment by szhorvat** [comment]
Please do not use the issue tracker when asking for help with using igraph. We have a forum for this purpose, and this is clearly indicated to you when you try to open an issue. https://igraph.discourse.group/

If you do post on the forum, _explain your question clearly, and in detail_, and refrain from pinging multiple people.
