### ISSUE TITLE
is.hierarchical/is_hierarchical

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#959]
I think only the first should exist?

**Comment by szhorvat** [comment]
We always go for the underscore ones, so `is_hierarchical`.

**Comment by maelle** [comment]
right but in the case of functions whose name start with "is", it's more idiomatic to use the dot.

I think there's a similar issue somewhere, but maybe it was for functions whose names start with "as" (where it's also more idiomatic to use the dot).

cc @krlmlr

**Comment by szhorvat** [comment]
That is not what we do in igraph, see `is_connected`, `is_tree`, and many many others.,

**Comment by krlmlr** [comment]
Is there a reference for `is.*()` being more idiomatic than `is_*()` ? I changed to `is_...` in all my packages and never looked back 🙃

**Comment by szhorvat** [comment]
I'd say it's also about consistency. I don't have nearly enough R expertise to decide between the two in general, but naming should be _consistent_ and _predictable_. Given the naming of the other functions, this should use `_` too (otherwise there's a whole lot of other functions to change).

**Comment by maelle** [comment]
Ok, my suggestion was wrong :grin: I was confused with as dot.

**Comment by krlmlr** [comment]
Same thing with `as.*()`, in my book...

**Comment by maelle** [comment]
I was thinking of https://github.com/igraph/rigraph/pull/763

**Comment by krlmlr** [comment]
ape 0.1 was released in 2002.

**Comment by maelle** [comment]
Then I stand corrected :innocent: :pray:

**Comment by krlmlr** [comment]
It's on the maintainer to change the name of a generic, this is a very tedious process.
