### ISSUE TITLE
problem installing igraph in R

### ISSUE THREAD

**Issue by lpantano** [igraph/rigraph#96]
Hi,

I had igraph for R-3.1, when I moved to new version (3.2.* and igraph 1.0.1) I keep getting this error:

```

** R
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/home/lpantano/soft/R-3.2.0/lib/R/library/igraph/libs/igraph.so':
  /home/lpantano/soft/R-3.2.0/lib/R/library/igraph/libs/igraph.so: undefined symbol: _gfortran_pow_r8_i4
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/lpantano/soft/R-3.2.0/lib/R/library/igraph’
* restoring previous ‘/home/lpantano/soft/R-3.2.0/lib/R/library/igraph’
```

I am in a Ubuntu14.04. I am aware that maybe is something I messed up, but if you have any idea, I will be happy to try. Feel free to close the issue if you didn't see before.

thanks for your time

**Comment by gaborcsardi** [comment]
I have no idea what you messed up, but I guess a reinstall will fix the problem.

**Comment by gaborcsardi** [comment]
Closing now, please reopen with more information if the problem persists.
