### ISSUE TITLE
document vertex_disjoint_paths() better

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#960]
It's documented together with vertex_connectivity (I'm fixing the use of alias for that) but without many details.

**Comment by szhorvat** [comment]
I'll update the C side docs for this, and then you can refer to that. I'll post an update here when done.

`vertex_connectivity()` and `vertex_disjoint_paths()` should be documented on the same page, since they are closely related.

**Comment by szhorvat** [comment]
https://github.com/igraph/igraph/commit/5f062af4c3f05b7c328fb6a91fbe14fc64aae481

Should anything be unclear, just ask.

**Comment by maelle** [comment]
To be ported to the R package after #894 is merged, because it'd touch the same lines.
