### ISSUE TITLE
Add k_shortest_paths

### ISSUE THREAD

**Issue by luukvdmeer** [igraph/rigraph#972]
**What is the feature or improvement you would like to see?**
The igraph core contains a function to compute k shortest paths with Yen's algorithm since March 2022. I noticed it has also been made available in the Python package of igraph recently. Is there any plan to make this available also in the R package?

I could try to start a PR based on the logic of the regular shortest_paths function, but have almost no experience in wrapping C code. Therefore the question if this is a planned addition already.

**Use cases for the feature**
Finding more "good" paths then only the shortest path, but without the need to compute all simple paths and subset them (which is very time consuming).

**References**
[Issue on the igraph core repo about this function](https://github.com/igraph/igraph/issues/1397) 
[Python docs for this function](https://python.igraph.org/en/stable/api/igraph.GraphBase.html#get_k_shortest_paths)

**Comment by szhorvat** [comment]
This functionality is present in version 0.10 of the C core.

Upgrading R/igraph to use 0.10 is not trivial. This is an ongoing project that has already made a lot of progress, but will still take some time to finish. Once it's done, exposing new functions will be fairly easy.
