### ISSUE TITLE
results of evcent does not match the first eigenvector the graph adjacency matrix

### ISSUE THREAD

**Issue by jszhao** [igraph/rigraph#973]
**Describe the bug**
results of evcent does not match the first eigenvector the graph adjacency matrix

**To reproduce**
```
set.seed(12345)
g2 <- sample_degseq(1:10, 10:1)
g2 <- simplify(g2)
g2.adj <- as.matrix(as_adjacency_matrix(g2))
evcent(g2, directed = TRUE, scale = FALSE)$vector
eigen(g2.adj)$vector[,1]
eigen(t(g2.adj))$vector[,1]
```

**Version information**
```
> sessionInfo()
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22631)

Matrix products: default


locale:
[1] LC_COLLATE=Chinese (Simplified)_China.utf8 
[2] LC_CTYPE=Chinese (Simplified)_China.utf8   
[3] LC_MONETARY=Chinese (Simplified)_China.utf8
[4] LC_NUMERIC=C                               
[5] LC_TIME=Chinese (Simplified)_China.utf8    

time zone: Asia/Shanghai
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] igraph_1.5.1

loaded via a namespace (and not attached):
[1] compiler_4.3.2  Matrix_1.6-2    magrittr_2.0.3  cli_3.6.1      
[5] tools_4.3.2     grid_4.3.2      rlang_1.1.2     pkgconfig_2.0.3
[9] lattice_0.22-5
```

**Comment by szhorvat** [comment]
Works fine for me. Remember that eigenvectors are unique only up to a multiplicative constant.

```
> set.seed(12345)
> g2 <- sample_degseq(1:10, 10:1)
> g2 <- simplify(g2)
> g2.adj <- as.matrix(as_adjacency_matrix(g2))
> e1<-evcent(g2, directed = TRUE, scale = FALSE)$vector
> e2<-eigen(g2.adj)$vector[,1]
> e3<-eigen(t(g2.adj))$vector[,1]
> 
> e1/e3
 [1] -1+0i -1+0i -1+0i -1+0i -1+0i -1+0i -1+0i -1+0i -1+0i -1+0i
```

**Comment by szhorvat** [comment]
Well, you did not spell out that question ...

The standard definition of eigenvector centrality for directed graphs is the _left eigenvector_, not the right eigenvector. [This is documented:](https://r.igraph.org/reference/eigen_centrality.html)

> In the directed case, the left eigenvector of the adjacency matrix is calculated. In other words, the centrality of a vertex is proportional to the sum of centralities of vertices pointing to it.

The second sentence above explains the reason. The eigenvector centrality of a vertex is determined by vertices that influence it, not by vertices that it influences. If you need the right eigenvector, reverse the graph first (`reverse_edges`).
