### ISSUE TITLE
graph.famous

### ISSUE THREAD

**Issue by maelle** [igraph/rigraph#974]
A problem I'm having in #970 is that `graph.famous()` is deprecated to `make_famous_graph()` which isn't exported.

- what should the replacing call actually be?
- How should be `graph.famous("zachary")` and `graph.famous("Levi")` (from the tests) be adapted?

**Comment by szhorvat** [comment]
`make_graph("Zachary")`

**Comment by maelle** [comment]
ok, thanks, I used that, makes sense! :pray:

**Comment by szhorvat** [comment]
I could check your commit now. So the test just checked that `make_graph` gives the same as `graph.famous`. That seems a bit pointless, I agree to just remove it.

I'm in China for a while and my internet access is limited.
