### ISSUE TITLE
Error with new current rigraph

### ISSUE THREAD

**Issue by ckluss** [igraph/rigraph#98]
Hi

thank you for the great package! With the old release something like

ml <- max(sapply(cliq, length))
sf <- function(x) sort(x)[seq_len(ml)]
reord <- do.call(order,  as.data.frame(do.call(rbind, lapply(cliq, sf))))
cliq <- cliq[reord]

works, but now I get a

Error in simple_vs_index(x, ii, na_ok) : Unknown vertex selected

I there an eas way to fix this?

Christof

**Comment by ckluss** [comment]
do not know if it is a good way, but can be fixed with

cliq2 <- lapply(cliq, as.numeric)
reord <- do.call(order,  as.data.frame(do.call(rbind, lapply(cliq2, sf))))

**Comment by gaborcsardi** [comment]
Please include a complete reproducible example that I can run. Thanks.

**Comment by ckluss** [comment]
full example on http://menugget.blogspot.de/2014/05/automated-determination-of-distribution.html

**Comment by gaborcsardi** [comment]
That seem to contain a lot of irrelevant stuff. I also get 

```
Error in parse_op_args(..., what = "a vertex", is_fun = is_igraph_vs,  : 
  Not a vertex sequence
```

instead of your error message.

**Comment by ckluss** [comment]
maybe, but with the following it will work like before (in the old igraph version)

cliq2 <- lapply(cliq, as.numeric)

reord <- do.call(order, data.frame(
    do.call(rbind, 
        lapply(cliq2 , function(x) c(sort(x), rep.int(0, ml-length(x))))
    )
))
