### ISSUE TITLE
Revdepcheck failures for igraph 2.0.0

### ISSUE THREAD

**Issue by krlmlr** [igraph/rigraph#989]
We're submitting igraph 2.0.0 to CRAN just before it closes for Christmas. The following dependent packages show failures when checking with the release candidate:

- [x] bnstruct
- [x] Canek
- [ ] countland: mail
- [ ] DiagrammeR
- [ ] dnet
- [ ] dragon: mail
- [ ] EGAnet
- [ ] ggnetwork
- [ ] inferCSN
- [x] influential
- [ ] integraph
- [ ] manynet
- [ ] migraph
- [ ] molnet: mail
- [x] NAIR
- [ ] nat
- [ ] nbTransmission
- [ ] netcom
- [ ] nosoi
- [ ] oddnet
- [ ] pcalg: mail
- [ ] phyloseqGraphTest
- [ ] rgraph6
- [ ] riverconn: mail
- [x] statGraph
- [ ] tidygraph
- [ ] VertexSort: mail

## Not terminating

- [x] dm
- [ ] SteinerNet
- [ ] ctmm
- [ ] lolog
- [ ] readsdr
- [x] robotoolbox (via dm): https://gitlab.com/dickoa/robotoolbox/-/issues

**Comment by krlmlr** [comment]
E-mailed dragon and VertexSort.

**Comment by krlmlr** [comment]
Filed an issue at https://gitlab.com/dickoa/robotoolbox/-/issues/9.

**Comment by maelle** [comment]
notes on DiagrammeR. 

the test calls 

```r
     add_islands_graph(
       n_islands = 4,
       island_size = 10,
       p = 1 / 5,
       edges_between = 1,
       set_seed = 23)
```

so the 4 is here, and should unsurprisingly be the number of strongly connected elements :thinking:

**Comment by maelle** [comment]
oh https://github.com/rich-iannone/DiagrammeR/issues/500

**Comment by krlmlr** [comment]
Submitted.
